### ISSUE TITLE
Upgrading from 3.1.0 to 3.2.2 breaks AdoStore Configuration

### ISSUE THREAD

**Issue by davidhjones** [quartznet/quartznet#1000]
**Describe the bug**

Upgaded from 3.1.0 to 3.2.2, and now my Quartz Scheduler has moved from AdoStore to RAMStore (without changing configuration)

**Version used**

3.2.2

**To Reproduce**

I simply upgraded the package from 3.1.0 to 3.2.2 -- nothing tricky to reproduce. 

**Expected behavior**

AdoStore would be used for scheduling.

**Additional context**
AppSettings (with removed connection strings):
```
"Quartz": {
    "quartz.scheduler.instanceId": "AUTO",
    "quartz.scheduler.instanceName": "iModelBridgeService.BackgroundScheduler",
    "quartz.dataSource.myDs.provider": "SqlServer",
    "quartz.dataSource.myDs.connectionString": "connectionStringHere",
    "quartz.jobStore.type": "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
    "quartz.jobStore.driverDelegateType": "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz",
    "quartz.jobStore.dataSource": "myDs",
    "quartz.jobStore.useProperties": "true",
    "quartz.jobStore.isClustered": "true",
    "quartz.serializer.type": "json"
  },
```

I do see some changelog notes (in breaking changes section), in regards to removing dependencies on SqlClient. Is this something I need to react to if using Azure SQL for the AdoStore?

**Comment by lahma** [comment]
How do you configure on code side?

**Comment by davidhjones** [comment]
```
            services.AddQuartz(q =>
                {
                q.UseMicrosoftDependencyInjectionJobFactory();
                q.UseSimpleTypeLoader();
                q.UseDefaultThreadPool(tp =>
                    {
                    tp.MaxConcurrency = 100000;
                    });
                });


            // Add our two background hosted services
            services.AddQuartzServer(options =>
                {
                // when shutting down we want jobs to complete gracefully
                options.WaitForJobsToComplete = true;
                });
```

**Comment by lahma** [comment]
I think you need to explicitly read the base configuration like here:

https://github.com/quartznet/quartznet/blob/5a3aee17eb7d4c7160af83288282233b500e207b/src/Quartz.Examples.AspNetCore/Startup.cs#L67

You could also drop the UseMSDI and SimpleTypeLoader as they are the defaults.

**Comment by davidhjones** [comment]
Ok that got me further, thanks for that. 

I did experience two issues after making that change. 

First, I got an exception (`FileNotFoundException: Could not load file or assembly 'Microsoft.Data.SqlClient`) during configuration. I fixed this by adding a dependency on the Microsoft.Data.SqlClient nuget (v2.0.1).

Second, I got an exception from Quartz while parsing the quartz.jobStore.isClustered property (`SchedulerConfigException: Could not parse property 'isClustered' into correct data type: No writable property 'IsClustered' found`). The [documentation](https://www.quartz-scheduler.net/documentation/quartz-3.x/configuration/reference.html#clustering) suggests using this name, although, I know in the past I have used `quartz.jobStore.clustered`. Reverting back to `quartz.jobStore.clustered` fixed this for me. Is this expected?

**Comment by lahma** [comment]
First one is expected, you can choose to use either System.Data or Microsoft.Data, Quartz removed the hard dependency.

Second one seems to be documentation problem. The page has link to submit s PR to fix the wrong name, seems to be referred multiple times with wrong name.

**Comment by davidhjones** [comment]
Done: https://github.com/quartznet/quartznet/pull/1001

**Comment by davidhjones** [comment]
Closing -- seems this issue is resolved. Thanks for the quick help @lahma
