### ISSUE TITLE
ServiceA executing ServiceB jobs

### ISSUE THREAD

**Issue by sergeyshaykhullin** [quartznet/quartznet#1002]
**Describe the bug**

**Test setup**:
- `Web` service
  - schedulerName=Test
  - schedulerId=Test.Web
  - `.AddQuartz`
- `Worker` service
  - schedulerName=Test
  - schedulerId=Test.Worker
  - `AddQuartz` and `AddQuartzServer`

**Test workflow**:
- `Web` has an endpoint and adding once-fire trigger with job data
- `Worker` configure a job logging job data to console

```
HTTP -> Web -> Scheduler <-> Trigger <-> Scheduler -> Service -> Log
```

**Problem**:

- `Web` also trying to execute this job, but no `AddQuartzServer` configured =/
- I can't configure `Web` schedulerName differ from `Worker`, because `Worker` scheduler will not see triggers and jobs for another scheduler

**Version used**

3.2.2

**Expected behavior**

`Web` can schedule job for `Worker` and only `Worker` executing this job

**Comment by lahma** [comment]
For a node that is only administering the database, you should configure `ZeroSizeThreadPool` into use and not start the scheduler.

**Comment by sergeyshaykhullin** [comment]
I add configuration methods for `ZeroSizeThreadPool` https://github.com/quartznet/quartznet/pull/1003
