### ISSUE TITLE
Xamarin android can't get scheduler

### ISSUE THREAD

**Issue by neyugnluan** [quartznet/quartznet#1008]
I have used this package for my xamarin.android
SQLite is used for data persistent
Version 3.2.2 of Quartznet

When I get the scheduler but throw an error as below

![image](https://user-images.githubusercontent.com/20486401/96983629-63bc9a80-154a-11eb-8852-569117cbccb0.png)

```
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
  at System.IO.Path.Combine (System.String path1, System.String path2) [0x00003] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.IO/Path.cs:102 
  at Quartz.Util.FileUtil.ResolveFile (System.String fName) [0x00042] in <533cba05bf9c43fe880ca9febfff8d19>:0 
  at Quartz.Impl.StdSchedulerFactory.InitializeProperties (Quartz.Logging.ILog logger, System.Boolean throwOnProblem) [0x00027] in <533cba05bf9c43fe880ca9febfff8d19>:0 
  at Quartz.Impl.StdSchedulerFactory.Initialize () [0x0001e] in <533cba05bf9c43fe880ca9febfff8d19>:0 
  at Quartz.Impl.StdSchedulerFactory.GetScheduler (System.Threading.CancellationToken cancellationToken) [0x00020] in <533cba05bf9c43fe880ca9febfff8d19>:0
```
For debugging package I saw that it's can't directory and throw at AppContext.BaseDirectory is null.
![image](https://user-images.githubusercontent.com/20486401/96983906-8484f000-154a-11eb-9dbe-d3c46cac13f5.png)

xamarin.android => throw error
xamarin.ios no issue

**Comment by lahma** [comment]
Seems that there's already a issue filed https://github.com/xamarin/xamarin-android/issues/3489

**Comment by neyugnluan** [comment]
hi @lahma 

Understand that this is an issue from xamarin-android as you mention
Do we have any plans to change this path?
Ex: string documentsPath = System.Environment.GetFolderPath(System.Environment.SpecialFolder.*);
Something like this.

**Comment by lahma** [comment]
Created https://github.com/quartznet/quartznet/pull/1010 to fix the issue. Basically ignoring the resolution failing in this case and just looking for `quartz.config` instead of app relative one. If you still need to resolve under such environment you can define full path with environment variable `quartz.config`. I don't have experience in Xamarin development so your mileage may vary...

**Comment by neyugnluan** [comment]
> Created #1010 to fix the issue. Basically ignoring the resolution failing in this case and just looking for `quartz.config` instead of app relative one. If you still need to resolve under such environment you can define full path with environment variable `quartz.config`. I don't have experience in Xamarin development so your mileage may vary...

Yup, absolutely what it need
Can configure under quartz.config or codebase setup path for data sources 

Thanks so much for quick responses

**Comment by lahma** [comment]
Version 3.2.3 of Quartz.NET has been released including this fix.
