### ISSUE TITLE
Autofac job factory registration fails

### ISSUE THREAD

**Issue by b3hdad** [quartznet/quartznet#1011]
**Describe the bug**

When I upgrade the following libraries, Quartz does not run my jobs:

**Version used**

- Quartz v3.2.0-->v3.2.2
- Autofac.Extras.Quartz v6.0.0-->v6.0.1

**To Reproduce**

Please see the link below, however, please ignore the error as in my case I am not seeing any errors. However, my wiring is almost identical to what is in the following page:

[Quartz Setup and Usage](https://stackoverflow.com/questions/64441224/quartz-says-cannot-instantiate-type-which-has-no-empty-constructor)

**Expected behavior**

I expected to jobs run as before upgrade.

**Comment by lahma** [comment]
Version 3.2.3 of Quartz.NET has been released including this fix.

**Comment by b3hdad** [comment]
Thank you for the quick fix. Just tested it and it works fine now.
