### ISSUE TITLE
Support for no sql DB

### ISSUE THREAD

**Issue by vivekkjain** [quartznet/quartznet#1019]
Can we extend and support No-SQl db like (Elastic, Cassandra, Mongo)

**Comment by lahma** [comment]
Would you like to offer a PR?

**Comment by lahma** [comment]
There are 3rd party solutions, here's quick search for Mongo: https://www.nuget.org/packages?q=quartz+mongodb . One seems to even be updated. I don't have resources to build all kinds of these so community might help out.
