### ISSUE TITLE
MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT missing

### ISSUE THREAD

**Issue by pantonis** [quartznet/quartznet#1021]
My job class is annotated DisallowConcurrentExecution attribute to avoid concurrence, so the same job just can run once per time (OK)
It is a CRON and runs every 1 minute (OK)
The time is 13:00:00s and the the job starts run (OK)
Now the time is 13:01:00s and the previous job didn't finish yet (OK)
As the class is annotated the next job will not start (IT IS GREAT - OK)
Now the time is 13:02:15s and the first job just finished (OK)
The job that was supposed to start at 13:02:00s is firing up at 13:02:15s

I dont want this to happen and instead this job (13:02:00s) must not run. I want the next job (13:03:00s) to run

I found out that in java quartz you can do this by using the ```MISFIRE_INSTRUCTION_RESCHEDULE_NEXT_WITH_REMAINING_COUNT``` found [here ](http://www.quartz-scheduler.org/api/2.1.7/org/quartz/SimpleTrigger.html)

I dont see this option in quartz.net.
Can you please add support for the above misfire option?

**Comment by lahma** [comment]
Seems that you've found the logic, https://stackoverflow.com/questions/64660900/quartz-net-withmisfirehandlinginstructionnextwithremainingcount-not-working-as . Please don't cross-post to different forums without informing about it.

**Comment by pantonis** [comment]
@lahma I found it but doesn't seem to be working as expected based on documentation
