### ISSUE TITLE
FileScanJob is faling after upgrading from 3.0.7 to 3.2.3

### ISSUE THREAD

**Issue by dvdwouwe** [quartznet/quartznet#1027]
We are using a derived class from JsonObjectSerializer:
```
/// <inheritdoc />
    /// <remarks>Serialize enums as string. </remarks>
    [UsedImplicitly]
    public class QuartzJsonObjectSerializer : JsonObjectSerializer
    {
        /// <inheritdoc />
        protected override JsonSerializerSettings CreateSerializerSettings()
        {
            JsonSerializerSettings serializerSettings = base.CreateSerializerSettings();
            serializerSettings.Converters.Add(new StringEnumConverter { AllowIntegerValues = false });

            return serializerSettings;
        }
    }
```

And specify this class using the property 'quartz.serializer.type'.
After upgrade I saw following exceptions passing in our logs:
```
Quartz.Core.ErrorLogger [?:?] - Job XMLSchedulingDataProcessorPlugin.XMLSchedulingDataProcessorPlugin_jobInitializer_quartz_persistent_jobs_xml threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> System.InvalidCastException: Identified object is not a DateTime.
   at Quartz.Util.StringKeyDirtyFlagMap.GetDateTime(String key)
   at Quartz.Job.FileScanJob.<Execute>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Quartz.Core.JobRunShell.<Run>d__10.MoveNext()
   --- End of inner exception stack trace --- [See nested exception: System.InvalidCastException: Identified object is not a DateTime.
   at Quartz.Util.StringKeyDirtyFlagMap.GetDateTime(String key)
   at Quartz.Job.FileScanJob.<Execute>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Quartz.Core.JobRunShell.<Run>d__10.MoveNext()]
```

After some digging the problems started with issue #843, here a line was added:

DateParseHandling = DateParseHandling.DateTimeOffset

```
protected virtual JsonSerializerSettings CreateSerializerSettings()
        {
            return new JsonSerializerSettings
            {
                Converters = new List<JsonConverter>
                {
                    new NameValueCollectionConverter(),
                    new StringKeyDirtyFlagMapConverter(),
                    new CronExpressionConverter(),
                    new CalendarConverter()
                },
                ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor,
                TypeNameHandling = TypeNameHandling.Auto,
                ContractResolver = new DefaultContractResolver
                {
                    IgnoreSerializableInterface = true
                },
                NullValueHandling = NullValueHandling.Ignore,
                DateParseHandling = DateParseHandling.DateTimeOffset
            };
        }
```

This has the effect dat inside the FileScanJob class, all DateTime properties are de-serialized as DateTimeOffset, making this code faling:
```
if (mergedJobDataMap.ContainsKey(LastModifiedTime))
{
	lastDate = mergedJobDataMap.GetDateTime(LastModifiedTime);
}
```
```
        /// <summary>
        /// Retrieve the identified <see cref="DateTime" /> value from the <see cref="JobDataMap" />.
        /// </summary>
        public virtual DateTime GetDateTime(string key)
        {
            var obj = this[key];

            try
            {
                return Convert.ToDateTime(obj, CultureInfo.InvariantCulture);
            }
            catch (Exception)
            {
                throw new InvalidCastException("Identified object is not a DateTime.");
            }
        }

```

The reason why we got an exception is that DateTimeOffset doesn't implement IConvertible, so Convert class isn't working here.

I dunno why in issue #843 this change was done, but it has a lot of implications. I saw that there are a lot of fixes afterwards in commit c2a4fd75e36d5870e27c8208a8456698898145df.

Probably the best thing is to use DateTimeOffset in FileScanJob, what do you think about it?

**Comment by dvdwouwe** [comment]
@lahma , I have created an PR for this issue and tested it locally in different repo's on our side.
It seems there are currently no unit-tests for the embedded jobs (expect for sending emails)

**Comment by lahma** [comment]
Thank you for explaining the problem in detail and also providing a valid fix!

**Comment by dvdwouwe** [comment]
@lahma , are there plans to release this bug in the near future? 

Thank you in advance,
Danny

**Comment by lahma** [comment]
Can you utilize [the MyGet feed](https://www.myget.org/F/quartznet/api/v3/index.json) for this? It has all the commits that are in master.

**Comment by dvdwouwe** [comment]
I was first a little bit confused using the [Myget feed](https://www.myget.org/F/quartznet/api/v3/index.json), I expected a 3.3.0-(preview|beta|rc-xxx), but it was 3.2.3-preview-<datetime>-<build>.

Most of the tools only display preview versions if they are semantically greater then 3.2.3.
3.2.3-preview-20201112-1630 < 3.2.3 < 3.3.0-rc001 < 3.3.0.

So, I believe that package 3.2.3-preview-20201112-1630 is the right one for me?
What does the 1630 mean?

**Comment by lahma** [comment]
Yes the versioning if a bit there somewhere because it's based on master which is usually the latest release out. So it's the version out there + something on the top. I think you've found the correct version, the last part is time as there can be multiple for same date.
