### ISSUE TITLE
支持net 5

### ISSUE THREAD

**Issue by ghd258** [quartznet/quartznet#1030]
support for net5

**Comment by lahma** [comment]
What is not working?

**Comment by dvdwouwe** [comment]
The nuget packages of Quartz are build against .Net Standard API 2.0, this is enough to work with .NET 5.

**Comment by lahma** [comment]
Closing as seems to be a non-issue.

**Comment by janissimsons** [comment]
> Closing as seems to be a non-issue.

@lahma  How is this not an issue? 
We can't update our applications to the latest .NET 5 version, because this library doesn't support it.

Just as @dvdwouwe said, quartz is built against .net standard 2.0, which does not support .NET 5.

Can you please re-open this issue and add support for .NET 5?

**Comment by lahma** [comment]
Please study [this page](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) on how .NET standard works. Quartz supports netstandard2.0 which is supported **by** .NET 5. Even the main branch's examples run on top .NET 5.

**Comment by janissimsons** [comment]
There are several .NET 5 libraries that require targeting .NET Standard 2.1, such as Entity Framework Core 5.0:
![image](https://user-images.githubusercontent.com/6424248/106573142-f0abc280-6541-11eb-912e-c8da52fd8f12.png)
https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms

That means applications can no longer target both Standard 2.0 and 2.1.
If you try to launch an app that targets Standard 2.0 and use EF Core 5, you will get a runtime error that EF Core methods are not implemented and this is only one example.

So, if I wanted to use EF Core alongside with Quartz, I would be forced to target 2.0 and use an older version of EF Core (2.1 or 3.1), which is not what we want, we have already updated everything to .NET 5 and we are targeting Standard 2.1.

Would it be possible for you to add support for .NET Standard 2.1?

Thank you

**Comment by lahma** [comment]
Please show me example project file that doesn't work.

You can target netstandard2.0, netstandard2.1, netcoreapp3.1, net5.0 while Quartz is included, netstandard20 is the **minimal required API surface**. You can read the table you linked as "Quartz will run with 2.1, 3.1 and 5.0 on their supported platform, whereas EF Core 5 requires netstandard2.1 compatible runtime, there Quartz also works".
