### ISSUE TITLE
Quartz 3.2.x won't read from appsettings.json

### ISSUE THREAD

**Issue by mrducnguyen** [quartznet/quartznet#1037]
**Describe the bug**

Configuration section `"Quartz"` is not applied

**Version used**

latest 3.2.3

**To Reproduce**

**Expected behavior**

Documentation mentioned that the section `"Quartz"` in `appsettings.json` will be applied automatically.

**Additional context**

I have read the source code and it seems that starting from release `3.2.x`, the extension method `AddQuartz` from Quartz.Extensions.DependencyInjection doesn't touch the section `"Quartz"`, it does in `3.1.0` though.

PR #878 added the feature in (for issue #877)
but this PR #978 removed it (for issue #955)

**Comment by lahma** [comment]
You need to pre-initialize from configuration section, [like in the example](https://github.com/quartznet/quartznet/blob/master/src/Quartz.Examples.AspNetCore/Startup.cs#L67).

**Comment by mrducnguyen** [comment]
Thanks for your quick response.

The release notes and the documentation gave impressions that `"Quartz"` section will be loaded automatically :)

**Comment by lahma** [comment]
Maybe we should return that behavior then if the section is there.

**Comment by lahma** [comment]
Would you like to offer a PR?

**Comment by mrducnguyen** [comment]
I had a closer look. It's not really straight forward to automatically load the config section `"Quartz"` from `appsettings.json`. It's not possible to access `IConfiguration` from `IServiceCollection`, will need to pass `IConfiguration` as parameter

The current way of doing thing, users of the library can actually configure a section of their choice for Quartz, doesn't have to be `"Quartz"`

I think I'll settle with this

``` C#
    services.Configure<QuartzOptions>(config.GetSection("Quartz"));
    services.AddQuartz();
```
