### ISSUE TITLE
Report quartz ready/live healthchecks

### ISSUE THREAD

**Issue by sergeyshaykhullin** [quartznet/quartznet#1041]
**Is your feature request related to a problem? Please describe.**
Quartz can report scheduler healthchecks, like MassTransit do for IBus

**Describe the solution you'd like**
Add healthcheck registration inside `AddQuartz`?

**Describe alternatives you've considered**
Configure healhchecks on `IServiceCollectionQuartzConfigurator`?

**Comment by lahma** [comment]
Might be more of documentation issue. If you use [Quartz.AspNetCore](https://www.nuget.org/packages/Quartz.AspNetCore) and its `AddQuartzServer` then it will add the health check. Might also be worth while to think about restructuring/making API easier to discover.

[Source for reference](https://github.com/quartznet/quartznet/blob/master/src/Quartz.AspNetCore/QuartzServiceCollectionExtensions.cs).

**Comment by sergeyshaykhullin** [comment]
Why does AddQuarts is not adding hralthckeck?

For example when i have control plane node with zero thread pool, just for scheduling, i want to check for ability to connect and use scheduler

**Comment by lahma** [comment]
The AspNetCore project is using `Microsoft.AspNetCore.Diagnostics.HealthChecks` which seems to be quite obsolete. Might make sense to add `Microsoft.Extensions.Diagnostics.HealthChecks` to hosting project and do the health check there. I don't think it's a good idea to bring health checks to core DI library as dependency as it also pulls hosting abstractions. Might get a bit bloated.

**Comment by sergeyshaykhullin** [comment]
Do you mean add `Microsoft.Extensions.Diagnostics.HealthChecks` to `Quartz.AspNetCore` is not a right way?

**Comment by lahma** [comment]
Your original question was about `AddQuartz`, which is part of DI integration, adding there would add quite a lot of dependencies. Are you using the hosting package for the scheduler your want to query for health checks?

**Comment by sergeyshaykhullin** [comment]
I am using `Quartz.AspNetCore` package

I want to add healthchecks to project with `ZeroThreadPool` and without `AddQuartzServer` -> `AddQuartzHostedService`

**Comment by lahma** [comment]
ZeroSizeThreadPool + scheduler which hasn't been started will only return unhealthy as it's not running?

**Comment by sergeyshaykhullin** [comment]
Hmmm...

I think that not started scheduler can try to connect to database or do simple operation

Main problem is that i don't know does not started Quartz scheduler with ZeroSizeThreadPool can schedule something or it is unhealthy

**Comment by lahma** [comment]
Sounds that you need database specific health check then. Quartz health check really cannot schedule jobs and triggers to validate database connectivity.

**Comment by sergeyshaykhullin** [comment]
I have database check, but does scheduler can operate on it?

I think that scheduler can periodically try to get/list job/trigger or check exists to ensure it is working?

**Comment by lahma** [comment]
Yes,  you can create such custom check if you need it.

**Comment by sergeyshaykhullin** [comment]
So this kind of check is not useful and should not be as part of quartz, right?

Workaround is write a custom check

**Comment by lahma** [comment]
Easier for you to write custom one. This kind of check needs more use case specific information than generic one would know (db required, but not running etc).
