### ISSUE TITLE
SQL Version 10.50.6220.0

### ISSUE THREAD

**Issue by mentatpsi** [quartznet/quartznet#1060]
I'm having issues running your SQL Script on SQL Version 10.50.6220.0... the command you released for the SqlServer Script relies on minimum SQL Server 2016. What requirements do you have for Quartz 3.2.3.0? The command can be modified to run for SQL Server 10.50.6220 using old syntax. But wondering what other reliance on new Syntax there might be.

**Comment by lahma** [comment]
You should be able to use the older version of the script from earlier release or from Git history, Quartz doesn't depend on the syntax, just the schema.

You probably know you're out of support with your database version anyway.
