### ISSUE TITLE
Testing quartz scheduler in xUnit

### ISSUE THREAD

**Issue by khanhna** [quartznet/quartznet#1061]
**Describe the bug**

The Scheduler not running as expected when testing with xUnit

**Version used**

v3.2.3, on .Net Core 3.1

**To Reproduce**

[xUnit test repo](https://github.com/khanhna/Masstransit.Demo.Testing)

1. Run all the test.
2. Remove the <code>Skip</code> parameter on <code>Should_Mark_Book_As_Available</code> test.
3. Run <code>Should_Mark_Book_As_Available</code> test separately.
4. Run all the test again.

**Expected behavior**

Every tests should all be pass.

**Additional context**

- This test demo using quartz scheduler integrated in Masstransit.
- The test <code>Should_Mark_Book_As_Available</code> often failed.(not always fail, just most of the times, and always passed if running separately).

**Comment by khanhna** [comment]
A temporary work around, 

Put the <code>[assembly: CollectionBehavior(DisableTestParallelization = true)]</code> for all the test to run sequentially.
Or use <code>[CollectionDefinition]</code> annotation on some specific test collection that related to Quartz, then it will run sequentially for them only.

**Comment by lahma** [comment]
With [Quartz 3.12](https://github.com/quartznet/quartznet/releases/tag/v3.12.0) the containments of schedulers should be now better aligned to DI. If there are still problems maybe need to update the repro sample to latest dependencies to show the problem.
