### ISSUE TITLE
JobRunShell silently handles OperationCanceledException which is not correct in terms of job retry handling

### ISSUE THREAD

**Issue by nazar-kuzo** [quartznet/quartznet#1064]
**Describe the bug**

JobRunShell has an ability to cancel the execution via OperationCanceledException but try/catch logic handles any OperationCanceledException being thrown in user code which is silently handled rather than generating exception and report exception to JobListeners.

**Version used**

Quartz v 3.2.3

**To Reproduce**

```
    public class TestJob : IJob
    {
        public Task Execute(IJobExecutionContext context)
        {
            throw new OperationCanceledException();
        }
    }
```

Quartz treats this Job as cancelled which is not correct since for example HttpClient.Timeout throws exact exception which is an exception in code execution rather than signal to Quartz to cancel the Job.

**Expected behavior**

Based on the code provided inside Job.Execute method, this is a user code and any exception thrown there should not be handled by Quartz, so JobListeners could log them and trigger retries.

**Additional context**
Based on JobRunShell implementation, each Job.Execute is wrapped with try/catch statement and there is a catch block which handles the OperationCanceledException

```
  // Execute the job
  try
  {
  ...
      await job.Execute(jec).ConfigureAwait(false);
  ...
  }
  catch (OperationCanceledException)
  {
      endTime = SystemTime.UtcNow();
      log.InfoFormat($"Job {jobDetail.Key} was cancelled");
  }
```
To have graceful handling of OperationCanceledException, I`m suggesting to perform check for CancellationToken (OperationCanceledException.CancellationToken) inside exception to check whether token is Quartz related (for example Scheduler signaled to cancel job) or it is user code related exception which should not be handled

**Comment by lahma** [comment]
Would you like to create a PR?

**Comment by nazar-kuzo** [comment]
@lahma 

Sure 😉
