### ISSUE TITLE
Jobs are not fired

### ISSUE THREAD

**Issue by cppmyjob** [quartznet/quartznet#1072]
Jobs are not fired in my project since 3.2.1 version (3.2.0 has not this issue). I attached a project to reproduce the issue

[Reproduce.zip](https://github.com/quartznet/quartznet/files/5789068/Reproduce.zip)

If you launch the project then HelloJob will be fired. But if you uncomment 

`<dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>`

in App.config then HelloJob  will not be fired.

I use .NetFramework 4.7.2 and I am not sure that System.ValueTuple in dependentAssembly is needed. My project has not System.ValueTuple in references and as I understand Tuples is part of NetFramework. But
1. Quartz does not fire jobs and there is not any info Why (even in logs). I.e. there is no way to understand what is wrong. I expect to see a reason in logs
2. My project (where I faced with the issue) is old project and was created with .Net framework 4.5 originally. I think System.ValueTuple was added during migrations between frameworks. I just want to say that my case is not unique and other developers will face with the same issue

**Comment by lahma** [comment]
The binding redirect is wrong as such version cannot be found. You should probably just remove all such references and bindings altogether. You can see the exception when you run your solution in debug mode with break on all exception set. These are quite hard to protect against as CLR type loading fails.

**Comment by lahma** [comment]
I've scheduled a fix for version 3.3 which removes the problematic dependency for binaries targeting .NET 4.6.1.
