### ISSUE TITLE
SchedulerContext can hold data of any type but JobDataMap  can not

### ISSUE THREAD

**Issue by reponemec** [quartznet/quartznet#1073]
Why **SchedulerContext** can hold data of any type (e.g. IFileScanListener)...

```
//This is from FileScanJob.Execute:
public virtual async Task Execute(IJobExecutionContext context)
...
SchedulerContext schedCtxt = context.Scheduler.Context;
IFileScanListener listener = (IFileScanListener) schedCtxt[listenerName];
...
```

...while **JobDataMap** can only hold data of primitive types?

**Comment by lahma** [comment]
`JobDataMap` can also hold objects?

```csharp
IJobDetail job = JobBuilder.Create<MyJob>().WithIdentity("job", "group").Build();
job.JobDataMap.Put("key", new object());
job.JobDataMap["key2"] = new object();
````

**Comment by reponemec** [comment]
> `JobDataMap` can also hold objects?
> 
> ```cs
> IJobDetail job = JobBuilder.Create<MyJob>().WithIdentity("job", "group").Build();
> job.JobDataMap.Put("key", new object());
> job.JobDataMap["key2"] = new object();
> ```

**Comment by reponemec** [comment]
Yes, technically speaking, it is possible. However Best practices say:

_"Only store primitive data types (including strings) in JobDataMap to avoid data serialization issues short and long-term."_ 
https://www.quartz-scheduler.net/documentation/best-practices.html#jobdatamap-tips.

That practice is not relevant for SchedulerContext?

**Comment by lahma** [comment]
Scheduler context is not serialized so it isn't vulnerable to object format changes. If you are using database to store data primitive types + JSON serializer is always a wise choice.
