### ISSUE TITLE
Which is a good and compatibile web UI for Quartz?

### ISSUE THREAD

**Issue by biapar** [quartznet/quartznet#1078]
Which is a good and compatibile web UI for Quartz?

**Comment by lahma** [comment]
There are currently three viable options which you can evaluate:

* [Crystal Quartz Panel](https://github.com/guryanovev/CrystalQuartz)
* [Quartzmin](https://github.com/jlucansky/Quartzmin)
* [QuartzNetWebConsole](https://github.com/mausch/QuartzNetWebConsole) (hasn't been updated for a while, might not work with 3.x at all)

Some day there might be one build-in too.
