### ISSUE TITLE
Jobs not firing after upgrade to 3.2.x (from 3.0.7) on Microsoft Server 2008 R2

### ISSUE THREAD

**Issue by DaveLaa** [quartznet/quartznet#1083]
I have a service implementation that uses Quartz.Net for several years now. All works fine and i allways tried to stay up to date with all external libraries, also with Quartz.Net.
I had some issues with version 3.1.x (unneccessary ms package installations) so i waited to version 3.2.x to upgrade.
I installed my services on several customer servers a week ago and a problem showed up that is quite unexplainable for me.

On customer servers that use for example windows server 2019 all my quarz jobs are fireing and working without problems. But I installed the same code package on a windows Server 2008 R2 of a customer and I realized that no jobs were started.

I looked into the log and there have been the normal initialization entries:

...
Scheduler meta-data: Quartz Scheduler (v3.2.3.0) 'QuartzSchedulerFactory' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.
...
QuartzScheduler      ThreadID=1: Scheduler QuartzSchedulerFactory_$_NON_CLUSTERED started.
...
QuartzSchedulerThread ThreadID=6: Batch acquisition of 1 triggers
QuartzSchedulerThread ThreadID=6: Batch acquisition of 1 triggers
QuartzSchedulerThread ThreadID=6: Batch acquisition of 1 triggers
QuartzSchedulerThread ThreadID=6: Batch acquisition of 1 triggers
...

On all other installations i also have log entries like for example:
JobRunShell          ThreadID=12: Calling Execute on job DEFAULT.JobQueueAwsJobDetail

But on the Vindows 2008 Server R2 those log entries are missing and no jobs are executed.
I tried to downgrade back to V3.0.7and now my service also runs the jobs on the old server and all works perfectly again... 

Is there something I can do about that problem or am i stuck to the old version of Quartz.Net?

**Comment by lahma** [comment]
This really would require more logs to understand the underlying problem. Only thing that I can remember that has changed related to SQL Server is probably the [parametrization of size of SQL parameters](https://github.com/quartznet/quartznet/issues/939).

**Comment by DaveLaa** [comment]
Thx for the very quick answer.
I use Quartz with Spring.Net (Spring.Quartz) and I dont have SQL-Server runing. Is there a way to activate additional logging? I tried to find something in the sources of Quarz.Net but it seems there is not more to see than DEBUG-Logs...

Localy and on working customer servers there is allways this "Batch acquisition of 1 triggers"-log line followed by a "Calling Execute on job xxx"-log line. The second line is missing on WinSvr2008R2...
But it works perfectly only by downgrading my services to V3.0.7 of Quartz. There must be something between the batch acquisition and the job execution that doesnt work any more on the old windows...

I wished I could help you more with a more detailed logging. For me it is no problem to stay on V3.0.7 for a while but I would rather update to the latest build.

**Comment by lahma** [comment]
Ah somehow I associated the 2008R2 as SQL Server, need more coffee I guess. So could it be that the job somehow hangs inside it's execute method. Can you add logging there and trace the steps that happen?

**Comment by lahma** [comment]
Might this be a DLL load problem then, [like this one](https://github.com/quartznet/quartznet/issues/1072)?

**Comment by DaveLaa** [comment]
That is also not possible as there would be a loading-execption from spring. 
And we see the log entries of Quartz that logs the startup of the library (Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally...). This log comes from inside Quartz and can only be loged if the lib is loaded and started correctly...

**Comment by lahma** [comment]
OK I think this pretty much leaves only the option to run maybe a VM with same Windows version and attaching debugger to see what is happening there.

**Comment by DaveLaa** [comment]
I found something:
Within the JobRunShell.Run there is a call to NotifyListenersBeginning which has no general exception catch-block. I placed a catch(Excepton) in and loged the exception that is thrown on WinSvr2008R2:

System.TypeLoadException: Could not load type 'System.ValueTuple`2' from assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Quartz.Core.QuartzScheduler.NotifyJobListeners(Func`2 notifyAction, IJobExecutionContext jec, JobExecutionException je)
   at Quartz.Core.QuartzScheduler.NotifyJobListenersToBeExecuted(IJobExecutionContext jec, CancellationToken cancellationToken)
   at Quartz.Core.JobRunShell.<NotifyListenersBeginning>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Quartz.Core.JobRunShell.<Run>d__10.MoveNext()

The System.ValueTuple is one of the new dependencies of Quartz.Net in Versions > V3.0.x. It seems that this lib cannot be used in WinSvr2008R2... Of course it is part of my services as it is automatically installed by NuGet with Quartz and it works on newer versions of windows server.

**Comment by lahma** [comment]
* What framework version is this?  -  System.ValueTuple should be quite compatible: https://www.nuget.org/packages/System.ValueTuple , even net4.5 is supported. 
* Are there multiple versions referenced of System.ValueTuple in your project?
* Does it help if you create explicit binding redirect to correct version?

**Comment by DaveLaa** [comment]
Sorry, forgot to mention... My services run explicitely on V4.6.1.

**Comment by DaveLaa** [comment]
Back on first deploy I had to ask the customers it to install the runtime for v4.6.1 on the server because it wasn't pre installed...

**Comment by lahma** [comment]
Well seems that if you're running Windows Server 2008 R2 SP1 you can even install NET 4.8. NET 4.7.2 is a release that handles value tasks without binding issses out of the box IIRC.

**Comment by DaveLaa** [comment]
Isn`t it possible to get rid of additional dependencies in Quartz.Net like in V3.0.7 (no dependencies for Net4.6.1)? That would be the best solution...
Or is there a way that WinSvr2008R2 can load the dll?

**Comment by lahma** [comment]
If you want to submit a PR to split the dependency from net461 and only offer it via net472 target that would be great. Seems that Windows 2008 R2 support has ended a year ago anyway...

**Comment by DaveLaa** [comment]
Yeah, I know... Thats what I have to deal with... My customers do not update their servers. I also have customers who still run oracle 11...
So I wait for a new release of Quartz.Net without dependencies (which would be great) and stay with V3.0.7 for now...

**Comment by increment-efficiency** [comment]
> Well seems that if you're running Windows Server 2008 R2 SP1 you can even install NET 4.8. NET 4.7.2 is a release that handles value tasks without binding issses out of the box IIRC.





https://vinnie-tabby5.github.io/sPbHi6GJ4A8XPFDIJIMWo4PJbwAZu2F9wHLNn5/
