### ISSUE TITLE
Unable to Create a Job Using Type

### ISSUE THREAD

**Issue by furqan5656** [quartznet/quartznet#1105]
If this is a question, please use the [discusssion feature](https://github.com/quartznet/quartznet/discussions)

ScheduleJob is not available which takes away the liberty to register many jobs dynamically is there a workaround for this so we don't necessarily needs to use reflection to invoke a generic extension method just to create a job from Type?
Task<DateTimeOffset> ScheduleJob(IJobDetail jobDetail, ITrigger trigger, CancellationToken cancellationToken = default)

**Comment by lahma** [comment]
I think this was addressed by #1090 and is available on MyGet feed already.
