### ISSUE TITLE
QuartzHostedService.StopAsync throws NullReferenceException if StartAsync hasn't been run

### ISSUE THREAD

**Issue by ArturDorochowicz** [quartznet/quartznet#1123]
**Describe the bug**

`QuartzHostedService.StopAsync` throws `NullReferenceException` if `StartAsync` has not been run.

`StartAsync` won't run if there's another hosted service that is registered earlier and throws in `StartAsync`. Exception in `StartAsync` causes Asp.Net Core to begin shutdown during which all hosted services are stopped via `StopAsync`.

IOW hosted services must not assume in `StopAsync` that `StartAsync` has been executed.

**Version used**
3.2.4

**To Reproduce**

**Expected behavior**

`QuartzHostedService.StopAsync` should check that `scheduler` is not `null`.
https://github.com/quartznet/quartznet/blob/5411524b7c05317b5b895d696e9cf17da5793321/src/Quartz.Extensions.Hosting/QuartzHostedService.cs#L23-L32

**Comment by lahma** [comment]
Thanks for the report, would you like to offer a PR to fix this issue?

**Comment by ArturDorochowicz** [comment]
Created #1124

**Comment by lahma** [comment]
Thank you!
