### ISSUE TITLE
QuartzServiceCollectionExtensions AddQuartzHostedService

### ISSUE THREAD

**Issue by mwgevans** [quartznet/quartznet#1126]
I wanted to extend the Hosted Service with some code to initialise the persistent store if it didn't already exist

Allowing
services.AddQuartzHostedService\<MyHostedService\>......
would make this trivial.

I looked at just adding the code to the main program, but that was messy! I have for now created an AddMyQuartzHostedService which uses MyQuartzHostedService. @andrewlock @lahma

**Comment by lahma** [comment]
I'm not sure if I follow. The Quartz hosted service is quite simple and you can probably create your own version if needed? The hosted service is anyway internal so you don't have access to extension points.

**Comment by mwgevans** [comment]
Yes, creating a different hosted service is simple, Currently the extension for adding a QuartzHostedService to the container only adds the internal hosted service, I wondered if it would be possible to use a Generic to allow injecting a modified hosted service? Appologies if I am not clear :(

**Comment by lahma** [comment]
Sorry but I really don't see much point in having such generic possibility. You basically just need this call in your own code:

```csharp
services.AddSingleton<IHostedService, MyHostedService>();
```

You anyway need to write your own version of the hosted service.

**Comment by lahma** [comment]
Closing as nothing much here to do.
