### ISSUE TITLE
Logging of stack trace doesn't work

### ISSUE THREAD

**Issue by MartinDemberger** [quartznet/quartznet#1133]
**Describe the bug**

There are a few logging outputs in the code which creates a Exception to get the caller stacktrace.

I found:

* DBSemaphore.ReleaseLock
* SimpleSemaphore.ObtainLock
* SimpleSemaphore.ReleaseLock

I Exception which isn't thrown doesn't have a stacktrac so the caller information isn't given.

In my case I get the following output

```log
Lock 'TRIGGER_ACCESS' attempt to return by: 2245a025-b4aa-4578-a8ac-58e727bd08c1 -- but not owner!

System.Exception: stack-trace of wrongful returner
```

**Version used**

3.2.4

**To Reproduce**

I don't know how to reproduce this because it's the information I need to reproduce it that is missing.

**Expected behavior**

The caller information is contained in the log output.

**Additional context**

The stacktrace can be obtained with `Environment.Stacktrace`

**Comment by lahma** [comment]
Thank you for your contribution!
