### ISSUE TITLE
IServiceCollectionQuartzConfigurator.ScheduleJob does not trigger job

### ISSUE THREAD

**Issue by ruwentos** [quartznet/quartznet#1134]
According to the [documentation ](https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/microsoft-di-integration.html#di-aware-job-factories) I'm using **IServiceCollectionQuartzConfigurator.ScheduleJob** like this.

`services.AddQuartz(q =>
{
    q.SchedulerId = "CutOff-time-scheduler";

    q.UseMicrosoftDependencyInjectionScopedJobFactory(options =>
    {
        options.CreateScope = true;
        options.AllowDefaultConstructor = false;
    });
    
    q.ScheduleJob<SendEventIfMarketECutOffTimePassedJob>(trigger => trigger
        .WithIdentity("daily-trigger")
        .WithCronSchedule("0/15 * * * * ?")
        .WithDescription("triggers the 'SendEventIfMarketECutOffTimePassed' job every day at ")
        .StartNow()
    );
});`

My job code looks like this:

`public class SendEventIfMarketECutOffTimePassedJob : IJob
    {
        private readonly ITopicPublisher<GenericEvent> _topicPublisher;
        private IAssetRepository _assetRepository;
        private IMarketRepository _marketRepository;
        private ICalendarRepository _calendarRepository;

        public SendEventIfMarketECutOffTimePassedJob(ITopicPublisher<GenericEvent> topicPublisher, IAssetRepository assetRepository, IMarketRepository marketRepository,
            ICalendarRepository calendarRepository)
        {
            _topicPublisher = topicPublisher;
            _assetRepository = assetRepository;
            _marketRepository = marketRepository;
            _calendarRepository = calendarRepository;
        }

        public Task Execute(IJobExecutionContext context)
        {
            var cutOffTimeEvent = new GenericEvent
            {
                Id = Guid.NewGuid(),
                SendFromObject = nameof(SendEventIfMarketECutOffTimePassedJob),
                Payload = "no payload"
            };

            if (CutOffTimePassed())
            {
                var _ = _topicPublisher
                    .SendEventAsync(cutOffTimeEvent, EventTopicNamesEnum.Market_e_cut_off_time_passed.ToString())
                    .Result;
            }
            return Task.CompletedTask;
        }

        private bool CutOffTimePassed()
        {
            return true;
        }
    }`

The job never gets triggered but should every 15 seconds.

I'm using fresh installed version:
`<PackageReference Include="Quartz" Version="3.2.4" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.2.4" />`

**Comment by lahma** [comment]
You need to either start the scheduler manually (by resolving it from services/DI in your hosted service or similar) or use the [hosting package](https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/hosted-services-integration.html) to start it automatically after configured as so:

https://github.com/quartznet/quartznet/blob/73f2e3132fdec18140986141a99d3248f2e5f972/src/Quartz.Examples.AspNetCore/Startup.cs#L224-L229
