### ISSUE TITLE
JobBuilder missing Puts

### ISSUE THREAD

**Issue by gkruszewski** [quartznet/quartznet#1141]
JobBuilder is missing `UsingJobData` methods for Guid and Char:

`UsingJobData(string key, Guid value)`

`UsingJobData(string key, char value)`

**Comment by lahma** [comment]
Would you like to offer a PR to add these features?

**Comment by elementh** [comment]
I don't mind doing it if @gkruszewski doesn't wants to ;)

**Comment by elementh** [comment]
Thanks @gkruszewski !
