### ISSUE TITLE
Update OpenTelemetry to v1 (1.0.1)

### ISSUE THREAD

**Issue by carlreid** [quartznet/quartznet#1165]
**Is your feature request related to a problem? Please describe.**
When trying to call `AddQuartzInstrumentation` and use `OpenTelemetry 1.0.1` then II hit this error:
`Reference to type 'TracerProviderBuilder' claims it is defined in 'OpenTelemetry', but it could not be found`

**Describe the solution you'd like**
Update the OpenTelemetry dependencies to the non-beta release of `1.0.1`. I believe the extensions were renamed from `TraceBuilderExtensions` to `TracerProviderBuilderExtensions`.

**Describe alternatives you've considered**
Tried calling extension method directly with `OpenTelemetry.Trace.TraceBuilderExtensions`, still no 🎲 

**Additional context**
Reach v1 release blog: https://devblogs.microsoft.com/dotnet/opentelemetry-net-reaches-v1-0/

**Comment by carlreid** [comment]
Looks like it may take some work to update as the API looks like it changed a bit since it was implemented here. There is some documentation [here](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk) to help out.  
  
Though maybe could be [inspired](https://github.com/honeycombio/opentelemetry-dotnet/blob/main/src/Honeycomb.OpenTelemetry/HoneycombExporter.cs) by other [solutions](https://github.com/newrelic/newrelic-telemetry-sdk-dotnet/blob/main/src/NewRelic.OpenTelemetry/NewRelicTraceExporter.cs) also.

**Comment by lahma** [comment]
I had a quick look when 1.0 was released and saw that it indeed isn't as simple as just updating the package. Any help with migration would of course be appreciated.

**Comment by carlreid** [comment]
Would you still want to have a separate OpenTelemetry instrumentation package? It's [recommended](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#writing-own-instrumentation-library) to just add the instrumentation directly in the library if you can. Then it seems if there's no `AddSource` called then all the tracing wouldn't happen.

That way the implementation would be more like what is described [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#instrumenting-a-libraryapplication-with-net-activity-api). I'd think it's a better option since it's based on .NET's `Activity` which is the way it's going to be going forward.

It probably also makes sense to get rid of the OpenTracing package too since it merged with OpenCensus to form the OpenTelemetry project. What do you think? I know it was basically just added to the Quartz project 🙈 

I might be able to find time to look into migrating but I would just need an idea on the direction to go in.

**Comment by trejjam** [comment]
I made tiny research about migration to v1. I will suggest moving the integration into the [opentelemetry-dotnet-contrib](https://github.com/open-telemetry/opentelemetry-dotnet-contrib) or if it's possible to the [opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet)

**Comment by lahma** [comment]
> Would you still want to have a separate OpenTelemetry instrumentation package? It's [recommended](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/trace/extending-the-sdk#writing-own-instrumentation-library) to just add the instrumentation directly in the library if you can. Then it seems if there's no `AddSource` called then all the tracing wouldn't happen.

I think the main Quartz package should be kept as having as little dependencies as possible. Some standard things like DiagnosticsSource is probably OK, but ideally no third party libraries outside MS.

> That way the implementation would be more like what is described [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#instrumenting-a-libraryapplication-with-net-activity-api). I'd think it's a better option since it's based on .NET's `Activity` which is the way it's going to be going forward.

> It probably also makes sense to get rid of the OpenTracing package too since it merged with OpenCensus to form the OpenTelemetry project. What do you think? I know it was basically just added to the Quartz project 🙈

I think it was meant to support some legacy options, can be there for now, should not be a big maintenance burden.

> I might be able to find time to look into migrating but I would just need an idea on the direction to go in.

This would be awesome, let's try to coordinate efforts (see below).

> I made tiny research about migration to v1. I will suggest moving the integration into the opentelemetry-dotnet-contrib or if it's possible to the opentelemetry-dotnet

This would also be a good option, having integrations closer to SDK would probably yield better synchronization, of course requires a stable plug-in point in Quartz to allow it to function between releases.

**Comment by carlreid** [comment]
I don't think contrib makes sense either. From what I understand, the new way is to simply add Activity tracing directly in the library and then out of the box it'll allow someone that wishes to instrument with OpenTelemetry to make use of that.

If you think of it in another way, how would you implement logging? You wouldn't defer it out to another package, you'd call ILogger and then something would listen or handle those events. That's how the Activity approach would work too, just with traces instead.

Though do let me know if I'm _completely_ wrong 😅

**Comment by maldago** [comment]
I have been following this thread as I also recently went down the path using `OpenTelemetry 1.0.1`

I spend some time reviewing the changes made to the OpenTelemtry SDK/API:
[open-telemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet)

* v `0.8.0-beta.1` - [ChangeLog.MD](https://github.com/open-telemetry/opentelemetry-dotnet/blob/7af79470d92a5f7430e10b93cd785ec60f612249/src/OpenTelemetry/CHANGELOG.md#080-beta1)
  > 0.8.0-beta.1
  >Released 2020-Nov-5
  > 
  > TracerProviderBuilder API changes Renamed AddInstrumentation to AddDiagnosticSourceInstrumentation and made internal.  Added AddInstrumentation (#1454)
  > DiagnosticSource subscription helper classes (DiagnosticSourceSubscriber, ListenerHandler,PropertyFetcher) are made internal.

* v `1.1.0-beta1`  [ChangeLog.MD] (https://github.com/open-telemetry/opentelemetry-dotnet/blob/7af79470d92a5f7430e10b93cd785ec60f612249/src/OpenTelemetry/CHANGELOG.md#110-beta1) contains [pull request 1836](https://github.com/open-telemetry/opentelemetry-dotnet/pull/1836)  removing the `ActivitySourceAdapter`.

I joined the CNCF  Slack otel-dotnet channels to see if there was any guidance on how to proceed, I came across this [conversation](https://cloud-native.slack.com/archives/C01N7PP1THC/p1619692929065400). Where the breakdown between core and contrib described as CORE = API+SDK+exporters that are required by the SDK spec (e.g. Jaeger/Zipkin); contrib = anything else. 

From those comments, it seems if you want to take advantage of the `DiagnosticSource` subscriptions helper classes, the open-telemetry-contrib is the way to go.  The contrib solutions, it contains a project `OpenTelemetry.Shared` which contains the `DiagnosticSource` subscription helper classes. A project can add those files as linked files, so it is possible to take the `Quartz.OpenTelelmetry.Instrumenation` project and with a few adjustments get it to work within the open-telemetry-contrib solution.

**Comment by lahma** [comment]
Thank you for the insights and detective work @maldago ! I don't have strong opinions and I'm fine with moving the code towards contrib project, probably handles dependency changes there better too.

**Comment by maldago** [comment]
Hi @lahma, I have taken a first glance at taking the existing solution and porting to the [open-telemetry-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) solution. I do not want to overstep but would you be interested in getting some assistance in moving this over?

**Comment by lahma** [comment]
@maldago all help is more than welcome and appreciated!

**Comment by lahma** [comment]
@maldago great work! Please create the PR to remove,  we probably need to wait for them to publish before merging 🙂

**Comment by drusellers** [comment]
@maldago did we ever get a PR for this? Looking to add OTEL to my current application.

**Comment by lahma** [comment]
@drusellers I believe [this is the integration package](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Quartz).

**Comment by lahma** [comment]
I'm closing this issue as Quartz's side integration has been marked as deprecated, please use:

https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Quartz
