### ISSUE TITLE
Scheduler Service is not picking up the schdule

### ISSUE THREAD

**Issue by MubarakPatel** [quartznet/quartznet#1169]
**Describe the bug**
We have use the version 3.0.7 in our dot net core application 
We have created a our windows scheduler service and use the Quartz in it After certain time or in access of application Scheduler Service did not run the upcomings schedules  after the windows service restart everything started working.

After
**Version used**
3.07

**To Reproduce**
Need to keep the scheduler service inactive, after the windows service restart everything started working.

 public async Task Execute(IJobExecutionContext context)
        {
            try
            {
                JobDataMap dataMap = context.JobDetail.JobDataMap;

                string jobId = dataMap.GetString("trubotJobId");
                string command = dataMap.GetString("command") ?? "";
                if (dataMap.GetString("CreatedBy") != null)
                {
                    UserCode = dataMap.GetString("CreatedBy");

                }
                        await ExecuteBotRunner(context).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                logger.LogError(ex, $"{DateTime.UtcNow} - BotRunnerJob.Execute() - Exception: {ex.Message}", UserCode);
            }
        }
        private async Task ExecuteBotRunner(IJobExecutionContext context)
        {
            JobDataMap dataMap = context.JobDetail.JobDataMap;
            string jobId = dataMap.GetString("trubotJobId");
            string scheduleId = dataMap.GetString("trubotScheduleId");
            string consoleApiUrlRunJob = dataMap.GetString("consoleApiUrlRunJob");
            if (!string.IsNullOrEmpty(consoleApiUrlRunJob))
            {
                
                HttpResponseMessage response = await new HttpClient().
                    PostAsJsonAsync(consoleApiUrlRunJob, new { jobId = jobId, scheduleId = scheduleId }).ConfigureAwait(false);

                await response.Content.ReadAsAsync<string>().ConfigureAwait(false);
            }
        }
**Expected behavior**

**Additional context**

**Comment by lahma** [comment]
* Did you get any error logs? 
* Do you have any logic in your constructor? Constructor throwing exception will prevent job from running
* Are you using persistence? Not being able to connect to database will fail Quartz's startup
* Also check out the new integration libraries that allow to use hosted services, some bug fixes available if you upgrade to latest (not related to this probably though)
