### ISSUE TITLE
CronTriggerImpl.WillFireOn returns wrong result when TimeZone is specified

### ISSUE THREAD

**Issue by odesyatnyk** [quartznet/quartznet#1187]
Hi all

Trying to cover with tests some of mine CRON expressions i ran into an issue that `WillFireOn` method of `CronTriggerImpl` returns `false` when it shouldn't

**Version used**

.NET Core 3.1, Quartz 3.3.2

**To Reproduce**

Listed CRON expression is meant to fire everyday at 5:50, 11:50, 17:50 and 23:50 (all GMT)

I have created simple example of test where you can reproduce the issue. `Assert.IsTrue` fails, when the next line `Assert.AreEqual` passes the test that in fact the same thing and both should pass.

``` c#
using NUnit.Framework;
using Quartz;
using Quartz.Impl.Triggers;
using System;

namespace TestProject
{
    public class Tests
    {
        private static readonly TimeSpan Offset = TimeZoneInfo.FindSystemTimeZoneById("GMT Standard Time").BaseUtcOffset;
        private static readonly DateTime StartDate = new DateTime(2021, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        private const string TimezoneGMT = "GMT Standard Time";

        [Test]
        public void Test_GMT_CRON()
        {
            var trigger = TriggerBuilder.Create()
                .WithIdentity("name", TriggerKey.DefaultGroup)
                .WithCronSchedule("0 50 5,11,17,23 ? * *", x =>
                {
                    x.InTimeZone(TimeZoneInfo.FindSystemTimeZoneById(TimezoneGMT));
                    x.WithMisfireHandlingInstructionDoNothing();
                })
                .StartAt(StartDate)
                .Build() as CronTriggerImpl;

            var expected = new DateTimeOffset(StartDate.AddHours(5).AddMinutes(50), Offset);

            Assert.IsTrue(trigger.WillFireOn(expected));
            Assert.AreEqual(expected, trigger.GetFireTimeAfter(StartDate));
        }
    }
}
```

**Assumption**
I think the problem is in [CronTriggerImpl.cs](https://github.com/quartznet/quartznet/blob/main/src/Quartz/Impl/Triggers/CronTriggerImpl.cs)

At the very first line of the method it overwrites value of `test` losing offset in this case, so later it is not able to compare correctly.

```c#
public bool WillFireOn(DateTimeOffset test, bool dayOnly)
{
    test = new DateTime(test.Year, test.Month, test.Day, test.Hour, test.Minute, test.Second);
    ...
}
```

**Comment by lahma** [comment]
Thanks for the detailed report and also for fixing the issue, much appreciated!

**Comment by odesyatnyk** [comment]
> Thanks for the detailed report and also for fixing the issue, much appreciated!

My pleasure! Thank you for accepting and for feedback!
