### ISSUE TITLE
Veracode Scan Show High Severity Security Threat Within Quartz Code 

### ISSUE THREAD

**Issue by harexelizaga** [quartznet/quartznet#1188]
To whom it my concern,

The company I work for utilizes Quartz and we appreciate the work you guys have done. We use Veracode to detect if any security threats exist within our code. After running a scan, Veracode detected a "high flaw" within the Quartz library. I've attached a screenshot of the  flaw and its location. The error is, "External Control of System or Configuration Setting."  [Here is a link to an in depth explanation of this weakness.](https://cwe.mitre.org/data/definitions/15.html)

![image](https://user-images.githubusercontent.com/83475882/116753942-a2248d80-a9a3-11eb-83a8-9bdbbac201f8.png)
![image](https://user-images.githubusercontent.com/83475882/116754019-c2544c80-a9a3-11eb-8a9b-d15528440290.png)

Here are some solutions we've tried:

- updated to the most recent version of the package (v3.3.2). This had no effect to the flaw. It was still giving that same error
- downgraded to see if the version matters. That didn't work as well. 

If you have any suggestions and/or concerns please do not hesitate to contact me! We can work together to solve this weakness within the Quartz library! Looking forward to hearing from you guys! Have a wonderful day! :)

**Comment by lahma** [comment]
If I understand correctly this is about Quartz setting connection string value from configuration setting. I don't see this as a big problem as it's controlled via configuration files or in-memory configuration.

**Comment by harexelizaga** [comment]
@lahma hi! Thank you for responding! I will let my team know about this!

**Comment by lahma** [comment]
Closing as not requiring actions.
