### ISSUE TITLE
AddQuartzHostedService Task Cancellation

### ISSUE THREAD

**Issue by busyscout** [quartznet/quartznet#1202]
When I add Quartz hosted service via
```csharp
services.AddQuartzHostedService(opt =>
 {
        opt.WaitForJobsToComplete = true;
});
```
and then shutdown my app how do my jobs know about app shutdown?

Say, I have a job like
```csharp
public class DummyJob : IJob
    {
        public async Task Execute(IJobExecutionContext context)
        {
            while (!context.CancellationToken.IsCancellationRequested)
            {
                await Task.Delay(TimeSpan.FromSeconds(30), context.CancellationToken);
            }
        }
    }
```
When the host is shut down I expect context.CancellationToken be cancelled. But it is not. So this job never finishes.

**Comment by lahma** [comment]
Hmm, I think you need to consider configuring for the scheduler:

`quartz.scheduler.interruptJobsOnShutdown = true`
and/or
`quartz.scheduler.interruptJobsOnShutdownWithWait = true`

See:

https://github.com/quartznet/quartznet/blob/1539d8eec323973f6a198d9b09ff32455715eccb/src/Quartz/Core/QuartzScheduler.cs#L490-L498`

**Comment by busyscout** [comment]
Thanks. It helped:
```csharp
services.AddQuartz(quartz =>
                    {
                        //...
                        quartz.SetProperty("quartz.scheduler.interruptJobsOnShutdownWithWait", "true");

                    });
```

**Comment by lahma** [comment]
I think I'll keep this open as it's a bit of trap as it's undocumented and lacks programmatic API. Glad it helped you though.

**Comment by csmorley** [comment]
Having issues with this I believe, on shutdown of the scheduler the tasks continue to run. Have added below on registration of the scheduler to the DI container:

```
var props = new NameValueCollection
{
    {"quartz.scheduler.interruptJobsOnShutdownWithWait", "true"},
};

var scheduler = AsyncContext.Run(async () => await new StdSchedulerFactory(props).GetScheduler());
```

And my shutdown code is as follows:

`await this.scheduler.Shutdown(cancellationToken);`

I have [posted in SO ](https://stackoverflow.com/questions/68153595/quartz-net-scheduler-shutdowntrue-not-killing-jobs)prior to finding this forum, any ideas much appreciated. Would be great to add this is a property in future.

**Comment by lahma** [comment]
I've exposed [some new configuration properties](https://github.com/quartznet/quartznet/pull/1263/files#diff-44c906f55711b5e57ea683966d93a955da35dc7bb67d3ef0d37a951c316f312e) both via `SchedulerBuilder` and DI configuration.
