### ISSUE TITLE
NRE within at Quartz.Simpl.PropertySettingJobFactory.SetObjectProperty() when job run

### ISSUE THREAD

**Issue by BrendanGrant** [quartznet/quartznet#1220]
I'm very new to Quartz, but as part of the sample code out there I strung together a mechanism to call a particular class on a schedule, but then found that every time it was called, when in the debugger, a NullReferenceException would be thrown with in at Quartz.Simpl.PropertySettingJobFactory.SetObjectProperty(), and upon hitting F5 to continue, things would proceed normally.

![image](https://user-images.githubusercontent.com/11591952/121835564-38ccb580-cc97-11eb-8599-51a18b4e329c.png)

In my opinion, this NRE shouldn't be throwing and us superfluous.

This against the 3.3.2 NuGet of Quartz, when run in a .NET Core 3.1 or .NET 5.0 console app.

I know the problem stems in part from me passing an ILogger through a JobDataMap to be used within the service/class being called, as yanking that causes things to run normally... however leaving it in and ignoring the exception sees the desired class reference get to my service where it is used.

Attached is a stripped down repro of this, where every minute, on the minute it will attempt to call the service, and hit the NRE just prior to success.

This is the code which sets up the scheduler and job:

            ILoggerFactory logger = LoggerFactory.Create(builder =>
            {
                builder.AddFilter("Microsoft", Microsoft.Extensions.Logging.LogLevel.Error)
                       .AddFilter("System", Microsoft.Extensions.Logging.LogLevel.Error)
                       .AddConsole();
            });

            var jdm = new JobDataMap();
            jdm.Add("Logger", logger.CreateLogger(nameof(DemoCrashingService)));
            IJobDetail job = JobBuilder.Create<DemoCrashingService>()
                .UsingJobData(jdm)
                .Build();

            ITrigger trigger = TriggerBuilder.Create()
                .WithCronSchedule("0 0/1 * * * ?") //Every minute
                .Build();

            // construct a scheduler factory
            StdSchedulerFactory factory = new StdSchedulerFactory();

            // get a scheduler
            IScheduler scheduler = await factory.GetScheduler();
            await scheduler.ScheduleJob(job, trigger);
            await scheduler.Start();

[Quartz Repro.zip](https://github.com/quartznet/quartznet/files/6645471/Quartz.Repro.zip)

**Comment by lahma** [comment]
Have you considered using the [MS DI support](https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/microsoft-di-integration.html) to inject your logger?

**Comment by lahma** [comment]
Closing as obsolete.
