### ISSUE TITLE
Remove SimpleThreadPool from examples?

### ISSUE THREAD

**Issue by barsv** [quartznet/quartznet#1230]
Minor thing. I see in examples in several places `["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz",` Should it be removed from examples if SimpleThreadPool was removed in v.3.0?

**Comment by lahma** [comment]
Yes generally it doesn't make sense to show the option of type as it's usually the default. I would welcome a PR to update the docs / and or the examples.
