### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by dngoins** [quartznet/quartznet#125]
When using StdSchedulerFactory to get the Schedule, and invoking the schedulejobs method passing in a collection of triggers, this method appears to cause a memory leak.

I've left the process hosting Quartz running for hours with some blank dummy triggers that simply do nothing and the process just keeps growing in memory.

The application averages about 8mb in memory without the schedule jobs call, however when I add this 1 line of code back in the process memory climbs over time, and when left running 24 hours, the memory reached 450mb and it was still increasing.

Please help.

**Comment by mail2ikhan** [comment]
I am getting exactly the same Memory Leak issue with Quartz 2. Here is the code, please advice
public class HelloJob implements Job
{
	public void execute(JobExecutionContext context1)
	throws JobExecutionException {
		context1.getJobDetail().getJobDataMap().clear();
		System.out.println("Hello Quartz! 123");	
		SchedulerRepository repo = SchedulerRepository.getInstance();
		for(Scheduler scheduler : repo.lookupAll()) {
			try {
				System.out.println(scheduler.getCurrentlyExecutingJobs().size());
				for(JobExecutionContext context : scheduler.getCurrentlyExecutingJobs()) {
					if(context.getNextFireTime().before(new Date())) {
						//Past triggered Job enteries : It will keep on increasing with the count of 1 after every execution
						System.out.println("Not Required =" + context.getJobDetail().getKey() + ", Job = " + context.getJobInstance());
					} else {
						// It will come here only once per execution
						System.out.println("Legitimate instance   =" + context.getJobDetail().getKey() + ", Job = " + context.getJobInstance());
					}
				}
			} catch (SchedulerException e) {
				e.printStackTrace();
			}
		}
	}	
}



public class CronTriggerExample {
	public static void main( String[] args ) throws Exception
    {    	   	
		JobKey jobKey = new JobKey("dummyJobName", "group1");
    	JobDetail job = JobBuilder.newJob(HelloJob.class)
				.withIdentity(jobKey).build();
    	Trigger trigger = TriggerBuilder
				.newTrigger()
				.withIdentity("dummyTriggerName", "group1")
				.withSchedule(
						CronScheduleBuilder.cronSchedule("0/1 * * * * ?"))
				.build();    	
    	Scheduler scheduler = new StdSchedulerFactory().getScheduler();    	
    	//Listener attached to jobKey
    	scheduler.getListenerManager().addJobListener(
    			new HelloJobListener(), KeyMatcher.keyEquals(jobKey)
    	);
    	scheduler.start();
    	scheduler.scheduleJob(job, trigger);    
    }
}

**Comment by mail2ikhan** [comment]
Just implemented a hack, but still searching for a proper Quartz solution. Call clear() every time Job is executed, this will clear un-necessary stuff : -

	private void clear(Scheduler scheduler) {
		
		Object quartzScheduler = getFieldValue(scheduler, "sched");
		Object jobMgr = getFieldValue(quartzScheduler, "jobMgr");
		@SuppressWarnings("unchecked")
		Map<String, JobExecutionContext> executingJobs = (Map<String, JobExecutionContext>)getFieldValue(jobMgr, "executingJobs");
		List<String> removalList = new ArrayList<String>();
		for(Map.Entry<String, JobExecutionContext> entry : executingJobs.entrySet()) {			
			if(entry.getValue().getNextFireTime().before(new Date())) {
				removalList.add(entry.getKey());
			} 
		}
		
		for(String key : removalList) {
			executingJobs.remove(key);
		}

	}
	
	private Object getFieldValue(Object parent, String fieldName) {
		Object value = null;
		Class clazz = parent.getClass();
		Field[] fields = clazz.getFields();
		 fields = clazz.getDeclaredFields();
		for(Field field : fields) {
			if(field.getName().equalsIgnoreCase(fieldName)) {
				field.setAccessible(true);
				
				try {
					value = field.get(parent);
				} catch (IllegalArgumentException e) {
					value = null;
				} catch (IllegalAccessException e) {
					value = null;
				}
				
			}
		}
		return value;
	}

**Comment by trinathm** [comment]
I am also facing same here. Upon scheduling jobs, the RAM usage is normal. Once the jobs are executed then the memory usage is keep on increasing. Did someone able to fix it ?

**Comment by lahma** [comment]
Please try to create a simplest possible console application that fires your job in for loop without Quartz being used and see if the memory still increases. I'm afraid the cause most probably is related to how the job itself handles resources (until proven otherwise).

**Comment by trinathm** [comment]
Finally I am able to figure out the issue. In our case, we are using Custom JobFactory and Simple Injector for creating the instances of jobs and to inject other dependencies. Simple Injector is not disposing the objects that are been created and injected. Because of this un-managed threads are been increasing for each run of the job. We were able to fix this issue.

**Comment by lahma** [comment]
Great to hear you got it sorted. The great simplification is that Quartz only produces jobs mostly and they or their producers tend to be the culprit if any.

**Comment by zwkenyen** [comment]
I  have the same problem.

**Comment by zwkenyen** [comment]
when I run a empty job。the memory increasing 8kb in very time of job running

**Comment by carmelormz** [comment]
@mail2ikhan Hi mail2ikhan, does this hack works if you have concurrent jobs? 

thanks

**Comment by kevin0459** [comment]
I have same issue.i am using 3.0.7 version with .net core.did anyone find solution ?

**Comment by v-bessonov** [comment]
I'm from Novermber 2021 using version 3.3.3 still have same annoying issue

**Comment by lahma** [comment]
I'd say with 99% confidence that it's not Quartz leaking and instead something you've built. I'm happy to be proven wrong with a repro case though.

**Comment by v-bessonov** [comment]
Here's link to project https://github.com/v-bessonov/QuartzMemoryLeak
if you run app for some time, you can see that total memory increase

**Comment by lahma** [comment]
Run it for a while, can't see any major leak here:

```
Total In KB: 29136
Total In KB: 30188
Total In KB: 30192
Total In KB: 30196
Total In KB: 30200
Total In KB: 30200
Total In KB: 30108
Total In KB: 30108
Total In KB: 30108
Total In KB: 30108
Total In KB: 30108
Total In KB: 30108
Total In KB: 30108
Total In KB: 30080
Total In KB: 30080
```
Btw, you probably want your job to have correct signature, e.g.: 

```csharp
public Task Execute(IJobExecutionContext context)
{
    Worker.Run();
    return Task.CompletedTask;
}
```
You seem to mix async and non-async constructs like Thread.Sleep.

**Comment by v-bessonov** [comment]
I ran app about an hour and got memory leak as it shown on graph

**Comment by lahma** [comment]
You running on release mode? What if you run for a day? How many megabytes it leaks per hour?

When GC isn't under pressure it might not need to clean all things.

**Comment by v-bessonov** [comment]
On our production  we've got around 100 jobs some working every minute and in 2 days memory  from 100MB goes to 400MB and docker container crushes

**Comment by lahma** [comment]
And if you take a memory dump, what is taking the memory?

**Comment by v-bessonov** [comment]
I don't have access to memory dump

**Comment by lahma** [comment]
Then it's all guessing here. I believe there are thousands of Quartz installations that do not leak memory, or people are just very quiet about them leaking it. 

I just cannot fix or diagnose anything if I cannot see Quartz mismanaging resources or something.

I would strongly suggest that you setup a watchdog service that takes a memory dump when threshold is reached. Or just manually, here's some reference: https://devblogs.microsoft.com/dotnet/collecting-and-analyzing-memory-dumps/ .

**Comment by v-bessonov** [comment]
What about project I done with memory leak?

**Comment by lahma** [comment]
I've now let it run for 2 hours, the process does not increase its memory usage. You should observe the process memory usage, like from Windows Task Manager and see how it behaves. CLR can increase it's memory footprint while there's no memory pressure.

**Comment by sasaPantic** [comment]
Can you give some suggestions hoe did you solve the problem. I have a memory leak too. My job process some json files but whe the job finishes the memory remains very high.
What I noticed that if I wrap my job logic inside
```
var task = Task.Run(async() => {
// code here
//...
});
task.Wait();
task.Dispose();
GC.Collect();
```
then the memory free up. Any suggestion please?
