### ISSUE TITLE
Ability to  specify an offset from the last weekday of the month

### ISSUE THREAD

**Issue by strangetoo** [quartznet/quartznet#1287]
Hello,

I'd like to have a cron expression like **0 0 8 LW-1 * ?** or **0 0 8 LW-2 * ?**

The reason for it is that we want to send some reports to our colleagues. Тhey have to complete certain work based on these reports by the end of the month, and they need more than one day to do this.

Best regards

**Comment by lahma** [comment]
Like you've probably noticed, I don't think this is available out of the box. Would you like to offer a PR to remedy the situation?
