### ISSUE TITLE
Support for 'L' in cron expression combinations

### ISSUE THREAD

**Issue by i8beef** [quartznet/quartznet#1288]
**Is your feature request related to a problem? Please describe.**

We require the ability to schedule arbitrary schedules on specific days of the month + "last day of month". I notice in the cron expression builder this is expressly disallowed: https://github.com/quartznet/quartznet/blob/29ba6a0fb6a1d9fb0ec36480a4cd34c3d99e7105/src/Quartz/CronExpression.cs#L614

**Describe the solution you'd like**

Would like to see this available as an option, so someone could do something like "15th and last day of month", etc. in a single cron expression.

**Describe alternatives you've considered**

1. Add a custom calendar that could limit 28th, 29th, 30th, and 31st on demand to black list days until "current month final day", tied with any "last day" selection to a cron date of 28th + this calendar to increment to "real" last day.
2. Using two schedules instead of one. We have some direct dependency on there being a SINGLE schedule right now so this isn't a great option for us.
3. Create a custom trigger that wraps the cron trigger impl and adds this functionality (something like, creating TWO on the fly, splitting the cron expression into two, one every other day and one just the 'L' case, running both and then comparing for "next").

**Additional context**

If you can specify the reasoning this is explicitly disabled right now, I might be able to look and make a PR for this...

**Comment by jafin** [comment]
@lahma consider this complete, merged in v4.
