### ISSUE TITLE
When StdScheduler's Shutdown is called, creating a new instance right away and scheduling task throws exception

### ISSUE THREAD

**Issue by LalitAtAristocrat** [quartznet/quartznet#1289]
Issue:
When StdScheduler's Shutdown method is called, creating a new instance right away and scheduling task throws exception. This issue was discovered because of failure of a test method.

Reason:
To create a new instance of StdScheduler, we create a new instance of StdSchedulerFactory and asks it to return a scheduler. Since we are not passing scheduler name, it picks the default one, creates a new instance and saves it with the name in repository(SchedulerRepository) which is singleton(SchedulerRepository.Instance) and thus shared between all instances of factory. When Shutdown is called on StdScheduler, it first tries to kill or wait for tasks to complete and then marks the scheduler as shutdown.

Next time when we create a new instance, it first checks if there is already a scheduler with same name in repository. If yes, it checks if it is shutdown already and if not it returns the same scheduler. Now, since after shutdown is called on scheduler, it does a few things before marking the scheduler as shutdown and does it asynchronously, there is a window in which if we create a new instance of scheduler and try using it, it might get an instance which is being shutdown. This can lead to exception when trying to schedule a task on it.

**Comment by LalitAtAristocrat** [comment]
We can fix this issue if we can return QuartzScheduler's IsShuttingDown property from StdScheduler via IScheduler interface and check it instead of IsShutDown property in StdSchedulerFactory's GetScheduler method.


            if (sched != null)
            {
                if (sched.IsShuttingDown)
                {
                    schedRep.Remove(SchedulerName);
                }
                else
                {
                    return sched;
                }
            }

**Comment by lahma** [comment]
There have been some improvements to this in 3.x line (release pending). Closing this and we can reopen if still a problem.
