### ISSUE TITLE
Make set of constant with configuration names strings

### ISSUE THREAD

**Issue by Vampire2008** [quartznet/quartznet#1297]
**Is your feature request related to a problem? Please describe.**
If you want to configure Scheduler inside code you have to go to documentation to find available settings. You cannot view available setting using tools like Intellisense.

**Describe the solution you'd like**
I suggest to add some classes with constants that contains settings names. Also I suggest add constant with available settings values.
```csharp
var settings = new NameValueCollection();
settings[QuartzProperty.Scheduler.InstanceName] = "My instance";
settings[QuartzProperty.Scheduler.InstanceId] = InstanceId.Auto;
```
This `QuartzProperty` returns string that represent name of parameter.
```
QuartzProperty.Scheduler.InstanceName  = "quartz.scheduler.instanceName"
QuartzProperty.Scheduler.InstanceId = "quartz.scheduler.instanceId"
InstanceId.Auto = "AUTO"
```
Also they can return only parts.
```
QuartszProperty = "quartz"
QuartzProperty.Scheduler = "quartz.scheduler"
SchedulerSection = "scheduler"
SchedulerSection.InstanceNameProperty = "instanceName"
```

**Describe alternatives you've considered**
Another alternative I suggest use configuration class instead of `NameValueCollection`.
```csharp
var settings = new QuartsSettings();
settings.Scheduler.InstanceName = "My instance";
settings.Scheduler.InstanceId = InstanceId.Auto;

var scheduler = new StdSchedulerFactory(settings);
```

**Additional context**
I created a little part for testing.
[Props.zip](https://github.com/quartznet/quartznet/files/7148226/Props.zip)

**Comment by lahma** [comment]
Some of the options are not known beforehand (like plugins which have properties Quartz don't know), but some well-known properties are already exposed via scheduler factory. 

Have you checked the public ones already?

SchedulerBuilder and MS IoC integration use those, and they also give you programmatic configuration capabilities to some degree at least.

**Comment by Vampire2008** [comment]
I now have found `SchedulerBuilder`.
I just found using `NaveValueCollection` for config in project on my job and the idea came up.
