### ISSUE TITLE
MariaDB 10.6 support

### ISSUE THREAD

**Issue by souchprod** [quartznet/quartznet#1305]
**Is your feature request related to a problem? Please describe.**

After updating from MariaDB 10.3 to 10.6, i notice that quartz, when we store the jobs in db, is not working anymore.
I et various errors like Out Of Memory or ssl connection error (without using ssl)

```
Failure occurred during job recovery: Failed to obtain DB connection from data source 'default': MySql.Data.MySqlClient.MySqlException (0x80004005): SSL Connection error.
 ---> System.AggregateException: One or more errors occurred. (Cannot determine the frame size or a corrupted frame was received.)
```

**Describe the solution you'd like**
Provide with an update embedding an updated MySql provider.

**Additional context**
v 3.3.3

thanks!

**Comment by lahma** [comment]
That sounds odd. You should be able to run any version of the driver you choose. So upgarding to this specific version causes problems, could it be a driver problem?

**Comment by souchprod** [comment]
Hi, just figured out that we can use MysqlConnector as a provider! 
That was not obvious in the documentation that we could, had to dig the source to notice it ~
Even the latest Mysql.Data provider fail to operate with MariaDb 10.6.4, zero issues with MysqlConnector so no problem anymore.
