### ISSUE TITLE
StartDelay option delays web application start and not just the scheduler

### ISSUE THREAD

**Issue by ArturDorochowicz** [quartznet/quartznet#1313]
**Describe the bug**

There's possibly an issue with `QuartzHostedServiceOptions.StartDelay` option which was recently introduced in 3.3.3 (via #1166).

If this value is set, all `IHostedService`s after `QuartzHostedService` are delayed. In a typical Asp.Net Core application this will include the web host itself. I don't think this is the desired result.
 
I looked at #1166 and saw that it ultimately is about awaiting `QuartzScheduler.StartDelayed`. I was surprised to learn that the implementation of `StartDelayed` is a `Task.Delay` followed by a `Start`. I was somehow expecting a regular start and then a delay in scheduling, if it makes sense.

I hope I can offer some critique of the current implementation of `QuartzScheduler.StartDelayed`. If it is the desired behavior then I think such api is redundant and leads to confusion. It's redundant, because developers are perfectly capable of adding a delay on their own before calling `Start`. As to confusion, I think that the comment in #1166: 
```csharp
// when we need to init another IHostedServices first
options.StartDelay = TimeSpan.FromSeconds(10);
```
shows that the author of that PR made the same assumption I would make and thought that `StartDelayed` would return normally (quickly) and only somehow delay the scheduling (though that's wrong thinking still as it's prone to races; the correct approach would be to simply register other hosted services before Quartz)     

**Version used**

3.3.3

**To Reproduce**

**Expected behavior**

`StartDelay` should not cause a delay in starting other hosted services.

**Comment by lahma** [comment]
Thanks for the report. Would you like to provide a PR to improve things?

I believe this is related and discusses the behavior in length: https://github.com/dotnet/runtime/issues/36063 .

**Comment by ArturDorochowicz** [comment]
@lahma I think something like #1314 should fix it, but haven't tested it. Note that there's a change in behavior such that exceptions from Start (regular one, not delayed), which used to stop the application startup, won't do that anymore.

**Comment by lahma** [comment]
Thanks for the PR, looks to align well with recommendations.

About the application startup and detecting problems (good catch!), would it make sense to actually have to versions of the the background service: the old one and this new one and choosing between them based on whether delays startup is enabled (with warnings in API docs about the behavior)?

**Comment by ArturDorochowicz** [comment]
I agree that keeping these startup exception when we can is better.

In the simplest version that's literally just not awaiting StartDelay in the original code, something like: 
```csharp
        public async Task StartAsync(CancellationToken cancellationToken)
        {
            scheduler = await schedulerFactory.GetScheduler(cancellationToken);

            if (options.Value.StartDelay.HasValue)
            {
               // not awaiting
                var ignored = scheduler.StartDelayed(options.Value.StartDelay.Value, cancellationToken);
            }
            else
            {
                await scheduler.Start(cancellationToken);
            }
        }
```

But I also looked at the java version and they for instance hide that delay already in scheduler `startDelayed` which returns `void`, https://github.com/quartz-scheduler/quartz/blob/d42fb7770f287afbf91f6629d90e7698761ad7d8/quartz-core/src/main/java/org/quartz/core/QuartzScheduler.java#L553-L571
```java
    public void startDelayed(final int seconds) throws SchedulerException
    {
        if (shuttingDown || closed) {
            throw new SchedulerException(
                    "The Scheduler cannot be restarted after shutdown() has been called.");
        }

        Thread t = new Thread(new Runnable() {
            public void run() {
                try { Thread.sleep(seconds * 1000L); }
                catch(InterruptedException ignore) {}
                try { start(); }
                catch(SchedulerException se) {
                    getLog().error("Unable to start scheduler after startup delay.", se);
                }
            }
        });
        t.start();
    }
```
I think I like this better, but I suppose it would technically be a breaking change in quartznet.

 @lahma  What do you think?

**Comment by lahma** [comment]
Looking at the code here 

https://github.com/quartznet/quartznet/blob/09b33a20ef5e1caf710fa07ac83a17bcfb0ed7bc/src/Quartz/Core/QuartzScheduler.cs#L397-L409

It indeed is a bit silly, I think it really should just discard the task and return `Task.CompletedTask` . Not sure how breaking fixing this would be, the bug actually is "StartDelayed should not block" I guess. Fixing it will both align with Java version and then fix this issue at hand.

**Comment by ArturDorochowicz** [comment]
@lahma Ok, so you're saying to do this in QuartzScheduler:
```csharp
        public virtual Task StartDelayed(
            TimeSpan delay,
            CancellationToken cancellationToken = default)
        {
            if (shuttingDown || closed)
            {
                throw new SchedulerException(
                    "The Scheduler cannot be restarted after Shutdown() has been called.");
            }
            Task.Run(async () =>
            {
                await Task.Delay(delay, cancellationToken).ConfigureAwait(false);

                try
                {
                    await Start(cancellationToken).ConfigureAwait(false);
                }
                catch (SchedulerException se)
                {
                    log.ErrorException("Unable to start scheduler after startup delay.", se);
                }
            }, cancellationToken);
            return Task.CompletedTask;
        }
```
This avoids breaking the API.

I was thinking about changing this method to return `void`, that's why I said it would be a breaking change. 

What do you want to do with this test?
https://github.com/quartznet/quartznet/blob/35b8532dc005af2fc907b6d2516c2e4bf40f833b/src/Quartz.Tests.Unit/Core/QuartzSchedulerTest.cs#L99-L110
Delete or wait 2s+? Not a great choice.

**Comment by ArturDorochowicz** [comment]
I have updated #1314 with your suggestion.

**Comment by lahma** [comment]
Thanks for working on this!

**Comment by sander1095** [comment]
Hi @lahma , any clue when this will be released? Thanks!

**Comment by lahma** [comment]
@sander1095 you should be able to get latest main build from the MyGet feed.

**Comment by sander1095** [comment]
Thanks for the quick reply. I am not very sure I can use MyGet in my organization. Do you know when a more "stable" nuget release is planned? Thanks!

**Comment by lahma** [comment]
No timeline at the moment, it takes some time to prepare and go trough release notes etc. It will be same kind of binary as in MyGet feed though (different version number of course).
