### ISSUE TITLE
Support for MSSQL Schema for jobStore

### ISSUE THREAD

**Issue by jafin** [quartznet/quartznet#1335]
**Is your feature request related to a problem? Please describe.**

Schema namespace support for SqlServer jobStore.  
There is a workaround at the moment, by setting a schema in the quartz.jobStore.tablePrefix, such as `[schema].QRTZ_` but this may not be commonly known, and perhaps is not the ideal solution. (https://stackoverflow.com/questions/34801446/how-to-configure-quartz-net-database-schema-name)

**Describe the solution you'd like**

Ability to set a schema name for the jobStore, something like  quartz.jobStore.schemaName

Things this may impact:

* The existing table creation scripts, which are hard coded to `dbo` and any schema migration scripts that also hardcode to `dbo`
*  If implemented, and someone was already using the tablePrefix workaround, create an outcome should they also set a schemaName. Possibly this is an error scenario.

**Describe alternatives you've considered**

Existing workaround of using quartz.jobStore.tablePrefix

**Comment by lahma** [comment]
Might this be more of a documentation issue? I'm not sure if schema concept is transferrable between different database implementations.  So maybe if we would highlight a tip or add a section to persistent store related docs so it would be easier to find.
