### ISSUE TITLE
Replace use of SchedulerDetailsSetter

### ISSUE THREAD

**Issue by drieseng** [quartznet/quartznet#1407]
We currently use reflection to set the name and id of the scheduler instance on the job store and the threadpool.
The corresponding properties are part of the **IJobStore** and **IThreadPool** interfaces, and as such there's no need to use reflection.

@lahma, is it ok to create a PR for this?

**Comment by lahma** [comment]
Sure, go ahead.

**Comment by tonyqus** [comment]
Is there a PR created for this issue?

**Comment by tonyqus** [comment]
@lahma  I have created a PR #1613.
