### ISSUE TITLE
Remove try/catch from Clone() methods

### ISSUE THREAD

**Issue by drieseng** [quartznet/quartznet#1415]
We always have a try/catch block in our `Clone()` methods to hide the underlying cause when cloning fails.

**For example:**
```cs
/// <summary>
/// Creates a new object that is a copy of the current instance.
/// </summary>
/// <returns>
/// A new object that is a copy of this instance.
/// </returns>
public virtual DirtyFlagMap<TKey, TValue> Clone()
{
    DirtyFlagMap<TKey, TValue> copy;
    try
    {
        copy = (DirtyFlagMap<TKey, TValue>) MemberwiseClone();
        copy.map = new Dictionary<TKey, TValue>(map);
    }
    catch (Exception)
    {
        throw new Exception("Not Cloneable.");
    }

    return copy;
}
```

This makes the generated IL/ASM bloated, and does not offer any added value as the caller can now only guess why cloning failed.

@lahma, is it ok to remove these try/catch blocks?

**Comment by lahma** [comment]
It's OK to remove, this could go directly to main too.
