### ISSUE TITLE
global.json | BDN

### ISSUE THREAD

**Issue by drieseng** [quartznet/quartznet#1423]
As part of the switch to NUKE, a **global.json** file was introduced in the root of the repo.
Since then, I can no longer run BDN targeting .NET (5.0 or 6.0). If I target .NET Framework 4.8, it works just fine.
Removing the **global.json** resolves this issue.

@lahma Do you have any idea what may be causing this? Can you reproduce this issue at your end? I work up to the moment were you've selected the benchmark to run.

**Comment by lahma** [comment]
Can't easily say what is currently causing this, for local experiments and benchmarking probably easiest to delete global json for now.

**Comment by lahma** [comment]
Closing as this is fixed in v4 branch.
