### ISSUE TITLE
QuartzHostedService: Wait for ApplicationStarted

### ISSUE THREAD

**Issue by Timovzl** [quartznet/quartznet#1432]
Hosted services and (by extension) **Quartz jobs are started before the application has successfully started**. For example, if the application serves HTTP requests, the jobs are started before it is ready to respond to those requests - **even before the app can respond to health checks**.

This is particularly annoying for smart deployments. For example, one might use Kubernetes to spin up new application instances and consider them successfully started once they answer a health check positively. Only after this happens do we include the new instances in the load balancer and do we spin down the old application instances. However, if the new instances fail to become healthy in a timely manner, they are spun down again. **The issue is that such never-officially-included instances may have already started running jobs.**

**Solution**

The problem would be mostly **mitigated if the Quartz hosted service would wait for application startup to complete**:

```cs
await Task.Delay(Timeout.InfiniteTimeSpan, // Wait "indefinitely", until ApplicationStarted is triggered
    this.HostApplicationLifetime.ApplicationStarted) // IHostApplicationLifetime injected in ctor
    .ContinueWith( _ => {}, TaskContinuationOptions.OnlyOnCanceled) // Without an OperationCanceledException
    .ConfigureAwait(false));
```

This way, at least we know that the application has managed to start successfully. For example, any unrelated hosted services that cause startup failure will now automatically _precede_ our jobs, which is good.

Optionally, this behavior could be configured by a boolean, `QuartsHostedServiceOptions.AwaitApplicationStarted`. However, I see no issue with the delay, and I consider the timing to be more correct, so I believe the adjusted behavior should be the default.

Could such a default be considered a breaking change? Probably not: Currently, there are no guarantees that a failure in a Quartz job will occur _before_ startup completes (and thus would have the ability to prevent a successful startup). In actuality, they _might_ happen early and prevent startup, or they _might_ happen later and _not_ prevent it. Going from an unpredictable scenario to a predictable seems non-breaking to me, but please correct me if I am overlooking something.

**Alternatives**

There is `QuartzHostedServiceOptions.StartDelay`. However, arbitrary delays are bad; startup times may be unpredictable.

**Additional Context**

We might consider the need to solve this problem as a design flaw in `BackgroundService`.

Services that perform startup and/or shutdown logic should implement `IHostedService`. Services that implement _background logic_ (like Quartz jobs, arguably) should inherit from `BackgroundService`. This changes what methods the service needs to implement, in a way that makes the most sense for the situation.

For `IHostedService`, it makes sense that `StartAsync` is invoked before a host starts listening and application startup is considered completed, as an `IHostedService` is permitted to cause application startup to fail (since .NET Core 3). This enables startup dependencies.

However, `BackgroundService` _also_ runs its `Execute` method before startup, as a result of `IHostedService.StartAsync` being invoked. I would argue that the abstract `BackgroundService` class should be responsible for awaiting the `ApplicationStarted` token. (In fact, I might open an issue with this very suggestion.)

Regardless, `BackgroundService.Execute` is currently being invoked early, so we should handle the situation as well as possible.

**Comment by lahma** [comment]
Thanks for bringing this up and with such a detail! 

In a way a odd that application can start with Quartz running but missing partial services (async I guess) - a question whether Quartz should win here if other services were "non-mandatory", but I agree, ideally we probably would wait for everything else to succeed as Quartz usually is a sidecar service.

If the proposed changed works, waiting for the host to be operable, I would very much welcome a PR.

I'm also pinging @andrewlock in hopes of getting some feedback, he's way more expert in this subject matter and helped with the original hosted service.

**Comment by andrewlock** [comment]
Yep, the analysis here is spot on, I wrote [a series of posts](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-3/) looking at startup and background tasks etc, and the replatforming onto the generic host in .NET Core 3.0 changed the order of these things.

The proposed solution is exactly what I've used in various cases. in fact I used pretty much this code just the other day 🙂 I would probably update the proposed snippet slightly to make sure we handle the cancellation token passed into `BackgroundTask.ExecuteAsync()`, so that the service shuts down gracefully, but other than that, it looks good to me.

> Optionally, this behavior could be configured by a boolean, QuartsHostedServiceOptions.AwaitApplicationStarted. However, I see no issue with the delay, and I consider the timing to be more correct, so I believe the adjusted behavior should be the default.

Personally I would be inclined to add this as an option, and not change the existing behaviour, but that's just me 🙂 The arguments about no guarantees seem reasonable.

**Comment by lahma** [comment]
Thank you @andrewlock for the insights, I think we have an agreement that the change is welcome. @Timovzl I would appreciate a PR to tweak the behavior and maybe we can try to ping Andrew again if he happened to have the time to review it based on discussion.

**Comment by Timovzl** [comment]
> In a way a odd that application can start with Quartz running but missing partial services [...]

Yeah. Originally, an `IHostedService` was started _after_ the host, and could not cause application startup to fail. It's as if, when they changed this (for the better, I think), they overlooked the fact that a "regular" `IHostedService` is intended for startup logic and should indeed be run before startup and help it to succeed or fail, whereas this does not make as much sense for a `BackgroundService`.

> The proposed solution is exactly what I've used in various cases. in fact I used pretty much this code just the other day 🙂

It's good to hear that I'm not the only one to have come up with this.

> [...] make sure we handle the cancellation token passed into BackgroundTask.ExecuteAsync() [...]

Definitely agreed. I'll make a PR and take this into consideration. It's possible that the `ApplicationStopping` token could be used instead of this, which might make things easier, but then I'll make sure to include tests to confirm that assumption.

**Comment by lahma** [comment]
Closing this as fixed, thank you for the PR!
