### ISSUE TITLE
Job with a trigger registration API

### ISSUE THREAD

**Issue by SeanFeldman** [quartznet/quartznet#145]
Consider the following scenario where a job is defined

``` C#
 var jobDetail = JobBuilder.Create<ImportGeoDatabaseJob>()
                        .WithIdentity("ImportGeoDatabaseJob", "ImportGroup")
                        .Build();
```

and associated with a trigger

``` C#
            var immediateTrigger = TriggerBuilder.Create()
                .WithIdentity("ImmediateTrigger", "ImportGroup")
                .ForJob(jobDetail) // <--- job detail is provided to trigger
                .StartAt(DateBuilder.FutureDate(1, IntervalUnit.Second))
                .Build();
```

According to current API, in order to schedule job with trigger, we'd need to do it for the first time specifying _both_

``` C#
scheduler.ScheduleJob(jobDetail, immediateTrigger);
```

I'd like to suggest to drop `jobDetail` from `ScheduleJob` method since we've got its information when registered with trigger by calling `ForJob` method passing job detail object.

**Comment by lahma** [comment]
`ForJob` does provide the detail, but it's only used to record the actual key. The built trigger does not contain the trigger and API unfortunately cannot determine the target in `ScheduleJob`. The fluent interface in this case is a bit misleading but not much to do here. Closing for now.
