### ISSUE TITLE
Use injected repository service instead of static singleton

### ISSUE THREAD

**Issue by momvart** [quartznet/quartznet#1453]
**Is your feature request related to a problem? Please describe.**
I observed this problem when added quartz to my ASP.NET project and integration tests started to fail because of the error "Scheduler with the name xxx already exists". After investigations, I found out that this is because of a shared context between different instances of `WebApplicationFactory`. Reading the source codes led me to [this line](https://github.com/quartznet/quartznet/blob/42f0ec89bb567d40bfc771f56724746fe61831f0/src/Quartz/Impl/StdSchedulerFactory.cs#L1101) which shows a static repository is being used as a singleton. As the tests run in shared memory space, this static object is also shared between them.

Although the error could be solved by defining locks in custom hosted services, this behavior is breaking the isolation of tests and requires additional considerations in any case. For example, we cannot use separate databases for each test if they are going to run in parallel.

**Describe the solution you'd like**
Register the repository as a singleton service and inject it into the dependent classes.

Also relates to #399.

**Comment by lahma** [comment]
I think this requires some breaking changes in order to work. Unless you can figure out a way to support in 3.x without breaking API and compatibility? Scheduling for v4 for now.

**Comment by kolpav** [comment]
@lahma Is this problem still present on latest dev version? I added quartz into my integration tests using `WebApplicationFactory` with same problem described above its bummer quartz is not working well with it as the job scheduling is what I was looking the most to test. Is there some workaround for now? Knowing if this is still on your radar would be enough so I don't spend more time investigating well known problem. Other than that using quartz is a pleasure 🙏

**Comment by lahma** [comment]
Probably is still present in the latest dev version. A lot of changes are needed to make Quartz use DI services instead of current configuration scheme (and still support the old one to a degree).

In tests you could manually try to remove scheduler from scheduler repository or assign unique name (GUID or something) for each created scheduler.

**Comment by kolpav** [comment]
@lahma Exactly what I am trying right now, thank you for quick response.

**Comment by rogierpennink** [comment]
> @lahma Exactly what I am trying right now, thank you for quick response.

I'm not sure if you ever got it to work. I ran into exactly the same issue: I'm trying to run multiple integration tests for jobs in parallel using `WebApplicationFactory`.

The solution that ended up working for me was instantiating a new `WebApplicationFactory` instance per test, along with an integration-test specific path for the quartz configuration in my Startup.cs file:

```csharp
services.AddQuartz(q =>
{
    q.UseInMemoryStore();
    q.UseMicrosoftDependencyInjectionJobFactory();

    if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "IntegrationTest")
    {
        q.SchedulerId = Guid.NewGuid().ToString();
        q.SchedulerName = Guid.NewGuid().ToString();
    }
    
    // Rest of config...
});
```

**Comment by kolpav** [comment]
@lahma Hello is this going to be fixed in next `3.` version? I am not sure if https://github.com/quartznet/quartznet/pull/1588 was eventually merged [it seems](https://github.com/quartznet/quartznet/pull/1588#issuecomment-1166486529) there were conflicts and author not responding.

**Comment by lahma** [comment]
@kolpav it's in v3 branch and available on MyGet already, but not in v4 (main).

**Comment by lahma** [comment]
And I mean thread-safety, not injection.
