### ISSUE TITLE
DBContext Issue with 3.3.3: System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by princefishthrower** [quartznet/quartznet#1461]
**Describe the bug**

Each time my job fires, I get the error:

```
 ---> System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'MyDbContext'.
```

**Version used**

3.3.3

**To Reproduce**

Here is my setup in my `Startup.cs`:

```csharp
            services.AddQuartz(q =>
            {
                // Allows us to use dependency injection in all our job classes
                q.UseMicrosoftDependencyInjectionJobFactory();

                // Run a job every minute
                var myJobKey = new JobKey("MyJob");
                q.AddJob<MyJob>(opts => opts
                    .WithIdentity(myJobKey));
                q.AddTrigger(opts => opts
                    .ForJob(myJobKey)
                    .WithIdentity("MyJobTrigger")
                    .WithCronSchedule("0 0/1 * * * ?"));
            });

            services.AddQuartzServer(options =>
            {
                // when shutting down we want jobs to complete gracefully
                options.WaitForJobsToComplete = true;
            });
```

**Expected behavior**

According to the docs, using:

```
q.UseMicrosoftDependencyInjectionJobFactory();
```

should: 

> also injects scoped services (like EF DbContext) without problems

docs link: https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/microsoft-di-integration.html#di-aware-job-factories

**Additional context**
I should also mention I am using aspnetboilerplate, perhaps that is the culprit? Though I'm configuring everything with Quartz through `Startup.cs`, so actually aspnetboilerplate shouldn't come into play at all here... 

Not sure what I'm missing. Any pointers, ideas, or help would be much appreciated!

**Comment by lahma** [comment]
Maybe you can add debugger to db context dispose and see who is calling it from the stack trace?

**Comment by princefishthrower** [comment]
This in the end was indeed due to ASP.NET Boilerplate. Jobs should be configured via the docs: https://aspnetboilerplate.com/Pages/Documents/Quartz-Integration

Unfortunately ASP.NET Boilerplate requires use of their own `Abp.Quartz` package. Following the docs link above I was able to successfully schedule jobs and triggers (though there is a new separate issue that the jobs don't actually fire, I was able to fix this scoping issue)

**Comment by lahma** [comment]
Thanks for closing the loop on this and great that you got it figured out. ABP was before Quartz had it's built-in IoC configuration so that's probably the cause of this disparity.

**Comment by princefishthrower** [comment]
Ahhh, this may also be relevant to whoever finds this: https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3757

Need to add `[UnitOfWork]` to the class.
