### ISSUE TITLE
TriggerUtils.ComputeFireTimesBetween returning incorrect fire times

### ISSUE THREAD

**Issue by bluehunter** [quartznet/quartznet#148]
The method is modifying the StartTimeUtc and EndTimeUtc of the Trigger, thus overriding These values set by the user. The method should not modify anything but just calculate upcoming occurrences.

Have a look at the TriggerUtils.ComputeFireTimes method and observe that it is not modifying the Trigger at all and thus returning correct results.

Regards
Bluehunter

**Comment by kristinannabel** [comment]
I found the same problem. 
Code sample below:

- Trigger:
`var myTrigger = TriggerBuilder.Create()
                .WithIdentity(id, partition)
                .StartAt(DateTimeOffset.UtcNow.AddHours(2))
                .ForJob("job1", partition)
                .Build();`

- Test:
`var startTime = DateTimeOffset.UtcNow;
 var fireTimes = TriggerUtils.ComputeFireTimesBetween(myTrigger, null, startTime, startTime.AddHours(3));
`

Expected fireTimes to contain date equal to DateTimeOffset.UtcNow.AddHours(2). but contains date equal to startTime variable instead.

When running this IRL, not with TriggerUtils.ComputeFireTimesBetween, Scheduler starts job on correct date statet in StartAt.
