### ISSUE TITLE
Triggered jobs ignore lock(x)

### ISSUE THREAD

**Issue by ndenkha** [quartznet/quartznet#1483]
**lock(x) is ignored by Quartz jobs**

I have a legacy Quartz scheduler implemented as a Windows service. When I create only one job at a time and have my service process one job at a time every 10 seconds, everything works fine. But, when I schedule multiple jobs and the service processes the same job type (but different key i.e. each job points to different data records and nothing shared between the jobs) then I get AccessViolationException when the job calls a method that deals with GDI+ Graphics object. Basically, when multiple triggered jobs start calling this method that's when the AccessViolationExcepiton is thrown and in turn, it causes all kinds of strange behavior within the app, e.g. Quartz starts failing to trigger other jobs, and files get corrupted.

And when I use lock(lockObj), the lock call is not honored as if the threads (jobs) are completely different processes and not threads.

Somehow, it seems like Graphics GDI+ isn't thread-safe EVEN though my jobs don't share any data, and I'm trying to use lock() to prevent threads from accessing the critical section, but the way Quartz.net is triggering the jobs doesn't seem as if they're normal threads running inside the one process that is the Windows Service.

**Quartz version: 3.3.3**

All prior versions versions

**To Reproduce, use lock(x) in jobs and it will not lock anything**

From any iJob implementation instantiate such a class and call its method that uses lock(x)

    public class MyClass
    {
	private readonly object _lockingObj = new object();

	[HandleProcessCorruptedStateExceptions]
	public Bitmap CreateImageFromText(string text, string fontName, int fontSize, string fontFileName, string sigFilename)
	{
		Log.Info($"CreateImageFromText() - Started for sigFilename: {sigFilename}");

		int width = 0;
		int height = 0;
		Bitmap textImage = null;

		lock (_lockingObj)
		{
			//Create the Font object for the image text drawing
			using (Font font = GetFontObject(fontName, fontSize, fontFileName))
			{
				try
				{
					Log.Info($"CreateImageFromText() - Created font object for sigFilename: {sigFilename}");

					//Create a graphics object to measure the text's width and height
					using (var baseImg = new Bitmap(1, 1))
					{
						using (Graphics grfx = Graphics.FromImage(baseImg))
						{
							// This is where the bitmap size is determined.
							var sizeF = grfx.MeasureString(text, font);	// **** AcessViolationException is EITHER IS THROWN BY THIS LINE ****
							width = (int)sizeF.Width;
							height = (int)sizeF.Height;
						}
					}

					Log.Info($"CreateImageFromText() - Created grfx-1 object for sigFilename: {sigFilename}");

					//Create the bmpImage again with the correct size for the text and font
					textImage = new Bitmap(width, height);

					//Add the colors to the new bitmap
					using (Graphics grfx = Graphics.FromImage(textImage))
					{
						grfx.Clear(System.Drawing.Color.White);
						grfx.TextRenderingHint = TextRenderingHint.AntiAlias;

						Log.Info($"CreateImageFromText() - will DrawString() text: {text}, sigFilename: {sigFilename}");

						using (var solidBrush = new SolidBrush(System.Drawing.Color.Navy))
						{
							grfx.DrawString(text, font, solidBrush, 0, 0);	// **** or AcessViolationException is THROWN BY THIS LINE ****
							grfx.Flush();
						}
					}
				}
				catch (Exception ex)
				{
					Log.Error($"CreateImageFromText() - Errored: {ex.Message}", ex);
					return null;
				}
			}
		}

		Log.Info($"CreateImageFromText() - Ended for sigFilename: {sigFilename}");
		return textImage;
	}
	
	public static Font GetFontObject(string fontName, int fontSize, string fontFileName)
	{
		using (PrivateFontCollection fonts = new PrivateFontCollection())
		{
			fonts.AddFontFile(fontFileName);

			System.Drawing.FontFamily fontFamily = fonts.Families[0];

			bool isBold = "Brush".IndexOf(fontName) < 0;

			Font font;

			if (!isBold)
				font = new Font(fontFamily, fontSize);
			else
				font = new Font(fontFamily, fontSize, isBold ? FontStyle.Bold : FontStyle.Regular, GraphicsUnit.Point);

			return font;
		}
	}
    }

**Comment by cedral** [comment]
You left out static. They way you have it each instance is using it's own lock object which is why they don't block each other. Change it to:

private static readonly object _lockingObj = new object();

**Comment by ndenkha** [comment]
Sorry, I forgot to mention that I've already tried this, and even turned the whole class and the method to static. The lock(x) is skipped regardless.

fyi, if I make this config change and process one thread/job at a time, then everything works fine with no errors, but of course there's a reason why I have this set to 10, otherwise jobs will take longer to get procssed.

<property key="quartz.threadPool.threadCount" value="10" />
TO:
<property key="quartz.threadPool.threadCount" value="1" />

**Comment by lahma** [comment]
There's not a single line of Quartz related code in the example. If you think that locking (which should use static variable) is broken, that's more like an issue for the CLR team?

**Comment by ndenkha** [comment]
The example is just a method that gets called from within a Quartz job.
I do have another ticket opened with the MS team, but I use lock statement in other apps that use multiple threads and it works as expected.
I will try another thing today and update you.

**Comment by ndenkha** [comment]
I've created a test project and lock(x) is working as expected. Closing this ticket as it's concluded to be related to the GDI+ issue unsupported role in Windows Services.
