### ISSUE TITLE
 QuartzHealthCheck never recovers after detecting failure

### ISSUE THREAD

**Issue by bencyoung-Fignum** [quartznet/quartznet#1496]
**Describe the bug**

The error count can only be incremented but is never cleared if things start working.

**Version used**

3.3.3

**To Reproduce**

Start a quartz app with the DB down and then start the DB. The health check always reports an error.

**Expected behavior**

I'd expect the health check to start reporting success when the DB comes up

**Comment by bencyoung-Fignum** [comment]
I may be able to raise a PR if that's an acceptable route?

**Comment by lahma** [comment]
Sure,  that would be great!

**Comment by bencyoung-Fignum** [comment]
At the moment it seems to report unhealthy if there's any job errors whereas I'd expect it to be more of an infrastructural test? I.e. it's ok if jobs are failing but not if there are DB errors? Is there a way to tell the difference? The other option is to just check if the job store is healthy rather than listen for general errors?

**Comment by lahma** [comment]
I think it would be sufficient to check that scheduler is running and job store operates. A single small query should suffice, even trying to get non-existing item as long as error is what is expected.

**Comment by bencyoung-Fignum** [comment]
I think this is done.

**Comment by bencyoung-Fignum** [comment]
I've simplified and tested this now
