### ISSUE TITLE
InvertTimeRange property in DailyCalendar

### ISSUE THREAD

**Issue by qzavyer** [quartznet/quartznet#1507]
### Discussed in https://github.com/quartznet/quartznet/discussions/1506

<div type='discussions-op-text'>

<sup>Originally posted by **qzavyer** February  3, 2022</sup>
Hi, I try get the DailyCalendar from my scheduler, but in this instance InvertTimeRange property always false. In DailyCalendar.Clone I don't see where this property copying in new instance of Calendar:

```
public override ICalendar Clone()
{
    DailyCalendar dailyCalendar = new DailyCalendar(base.CalendarBase, RangeStartingTime, RangeEndingTime);
    CloneFields(dailyCalendar);
    return dailyCalendar;
}
```

and 

```
protected BaseCalendar CloneFields(BaseCalendar clone)
{
    clone.Description = Description;
    clone.TimeZone = TimeZone;
    clone.CalendarBase = CalendarBase?.Clone();
    return clone;
}
```</div>

**Comment by lahma** [comment]
Seems like a bug. Would you like to offer a PR with a test case and a fix?

**Comment by qzavyer** [comment]
I can try but I never participated in opensource projects. I don't how I can do it

**Comment by lahma** [comment]
OK, all good. Here's a some guidance https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github how to get started, but if you feel that it's something your don't want to do at this point, we can put into TODO queue. 

It's a bit easier when community members participate, but of course the barrier of entry is always a bit higher for the first contribution.

**Comment by lahma** [comment]
Great work, I hope you've found the contribution process painless and nice. All help is always appreciated!
