### ISSUE TITLE
UseJsonSerializer() results in System.InvalidCastException

### ISSUE THREAD

**Issue by andymartin** [quartznet/quartznet#1514]
Using JsonSerializer to persist to AdoJobStore I get the following exception:

Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Messaging.ServiceRequestType'.

This makes no sense. The entire point of serialization is to be able to persist and transmit complex data types. Why would you use serialization at all if you can only persist strings? What is the point of having a JobDataMap that accepts anything other than strings if they cannot be persisted? Why is the JsonSerializer recommended if it doesn't actually serialize the job data?

**Comment by lahma** [comment]
You can always write your own serializer with your own rules how to handle complex data types.

**Comment by andymartin** [comment]
Is there an example of how to do this? I see the docs for customizing the json.net settings, but I don't see how that can apply to an entire object. Thanks!

**Comment by lahma** [comment]
Basically you just need to implement `IObjectSerializer`, you can start with the current one as template https://github.com/quartznet/quartznet/blob/main/src/Quartz.Serialization.Json/Simpl/JsonObjectSerializer.cs . Then register via DI or configuration, it either API or behind a key:

https://github.com/quartznet/quartznet/blob/e48565c0e5f80103fac191a4cc94bb5c7f06bac9/src/Quartz/SchedulerBuilder.cs#L404-L410

**Comment by andymartin** [comment]
Awesome! Thank you!
