### ISSUE TITLE
Please remove reference on Quartz from Quartz.OpenTelemetry.Instrumentation.csproj

### ISSUE THREAD

**Issue by ImoutoChan** [quartznet/quartznet#1518]
**Is your feature request related to a problem? Please describe.**
It's unnecessary. Almost all instrumentation libraries don't reference their main project. See SqlClient, for example.

**Describe the solution you'd like**
Just delete the reference and copy string constants (that's the only reason for this reference)

**Describe alternatives you've considered**
There aren't any

**Comment by lahma** [comment]
Didn't know this is such a problem. Instrumentation is moving into contrib project anyway [with this PR](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/129) so I'm not going to make changes for it in this repo. Thanks for the report though.
