### ISSUE TITLE
Remote Microservices Code - JobBuilder.Create method should support string for fully qualified assembly name

### ISSUE THREAD

**Issue by siva538** [quartznet/quartznet#1523]
**Is your feature request related to a problem? Please describe.**
Currently Quartz supports multiple schedulers. In our current scenario, the setup of the jobs is happening from a location where the code access do not present for the remote Job types. This is causing massive over engineering of dynamically generating the class type etc. that is not needed in the first place.

i.e. public static JobBuilder Create(Type jobType) or the generic method, mandatorily needs Type available during the time of creation of the Job. 

**Describe the solution you'd like**

public static JobBuilder Create(string jobType); with this string overload, the string passed in to this method can directly be inserted into the backend database, instead of the quartz library trying to use - AssemblyQualifiedNameWithoutVersion()

**Describe alternatives you've considered**
As I mentioned we had to generate a type dynamically with the system.reflection support, which is not only difficult to implement but also not maintainable.

**Additional context**
NA

**Comment by lahma** [comment]
Should be supported scenario with v4 now.
