### ISSUE TITLE
Fired Trigger doesn't add record in to QRTZ_FIRED_TRIGGERS

### ISSUE THREAD

**Issue by mannok** [quartznet/quartznet#1539]
From my understanding, all triggers in `QRTZ_SIMPLE_TRIGGERS` will be added to `QRTZ_FIRED_TRIGGERS` after it has been fired. However, I found there still nothing inside `QRTZ_FIRED_TRIGGERS` even those triggers in `QRTZ_SIMPLE_TRIGGERS` existing and being deleted?

**Comment by lahma** [comment]
QRTZ_FIRED_TRIGGERS is runtime state to know that trigger is actively executing, it's also a way for recover process to know which triggers were left running when scheduler unexpectedly went down etc. There's a sample history plugin separately if you want historical information .
