### ISSUE TITLE
day-of-month and day-of-week both support in CronExpression

### ISSUE THREAD

**Issue by findmoon** [quartznet/quartznet#1543]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is day-of-month and day-of-week can not both specify. Ex. `0 0 12 1/14 * MON, THU, FRI` means '14th day-of-month from 1 through 31 and on MONDAY, THURSDAY, FRIDAY at 12:00:00'

But `CronExpression.IsValidExpression("0 0 12 1/14 * MON, THU, FRI")` will return false, I try many CronExpression, the result is day-of-month and day-of-week is mutual exclusion.

**Describe the solution you'd like**
Is it possible to support day-of-month and day-of-week both specify. In Linux Crontab, `0 12 1/14 * MON,THU,FRI` seems legal 

[crontab](https://crontab.guru/#0_12_1/14_*_MON,THU,FRI)

![image](https://user-images.githubusercontent.com/18387852/158323807-5ea7ded8-e9d4-4a26-b88e-be0437b1f643.png)

AND, `0 0 12 1/14 * MON, THU, FRI` seem not correct expression that I want schedule. 

I want schedule `every two weeks and on MONDAY, THURSDAY, FRIDAY at 12:00:00 `, `MON/14, THU/14, FRI/14` also will express this schedule, But it is invalid increments exceed 7 in day-of-week.

Think you!

**Comment by jafin** [comment]
Just noting the above request does align with crontab spec where day-of-month and day-of-week are inclusive not exclusive.  

> The specification of days can be made by two fields (day of the month and day of the week).
> 
> If month, day of month, and day of week are all <asterisk> characters, every day shall be matched.
> 
> If either the month or day of month is specified as an element or list, but the day of week is an <asterisk>, the month and day of month fields shall specify the days that match.
> 
> If both month and day of month are specified as an <asterisk>, but day of week is an element or list, then only the specified days of the week match.
> 
> Finally, if either the month or day of month is specified as an element or list, and the day of week is also specified as an element or list, then any day matching either the month and day of month, or the day of week, shall be matched.

**Comment by dougmorris** [comment]
@lahma can you confirm this is now in place as the issue was close. I am looking at version 3.14.0 and it produces and error when attempting to use DayOffWeeK and DayOfMonth together.

```
System.FormatException: Support for specifying both a day-of-week AND a day-of-month parameter is not implemented.
   at Quartz.CronExpression.BuildExpression(String expression)
```

**Comment by jafin** [comment]
@dougmorris I did the PR against main (v4.) unless someone else patched v3.x it may not be there.

**Comment by dougmorris** [comment]
@jafin thank you for the update - appreciate it!
