### ISSUE TITLE
Microsoft DI integration does not working with Microsoft.Extensions.Hosting v7 preview

### ISSUE THREAD

**Issue by AntonioFalcao** [quartznet/quartznet#1544]
**Describe the bug**

Configuration using `appsettings.json`, `QuartzOptions` and configuration section `Quartz` does not work with `Microsoft.Extensions.Hosting` in version 7 (preview).

**Version used**

Quartz: **3.3.3**
.NET: **7.0.100-preview.1.22110.4**
Microsoft.Extensions.Hosting: **7.0.0-preview.2.22152.2**

**To Reproduce**

**appsettings.json**

```json
{
  "Quartz": {
    "quartz.scheduler.instanceName": "Quartz ASP.NET Core Sample Scheduler"
  }
}
```

**Startup.ConfigureServices**

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<QuartzOptions>(Configuration.GetSection("Quartz"));
}
```

**Comment by lahma** [comment]
And the said setup worked for you with the earlier version?

**Comment by lahma** [comment]
There should be a new release on MyGet feed shortly, please try if it fixes the problem - based on my testing it should now work.

**Comment by AntonioFalcao** [comment]
> There should be a new release on MyGet feed shortly, please try if it fixes the problem - based on my testing it should now work.

It's working now man, thanks for that!
