### ISSUE TITLE
DeleteJob returns false when RAMJobStore is used

### ISSUE THREAD

**Issue by Sobotkama** [quartznet/quartznet#1579]
**Describe the bug**

According to its summary, `IScheduler.DeleteJob` returns `true if the Job was found and deleted.`
However, when I use RAMJobStore and the job has no triggers, it returns false. The job does indeed get deleted, it's just the return value that is wrong.

**Version used**

3.4.0

**To Reproduce**

```c#
var group = "group";
var name = "name";

var job = JobBuilder.Create()
    .StoreDurably()
    .OfType(typeof(TestJob))
    .WithIdentity(name, group)
    .RequestRecovery()
    .Build();

await m_scheduler.AddJob(job, false);
var jobKey = new JobKey(name, group);
    
var get1 = await m_scheduler.GetJobDetail(jobKey);  //returns the job, as expected

var succ = await m_scheduler.DeleteJob(jobKey);    //returns false for some reason
        
var get2 = await m_scheduler.GetJobDetail(jobKey);      //returns null as expected
```

where m_scheduler is obtained like so:
```c#
var factory = new StdSchedulerFactory ();
IScheduler m_scheduler = await m_factory.GetScheduler();
```
with no config files (quartz uses the default config)

**Expected behavior**

`IScheduler.DeleteJob` returns `true`, as it does with AdoJobStore.

**Additional context**
I believe the problem is in RAMJobStore.cs:

```c#
private bool RemoveJobInternal(JobKey jobKey)
{
    lock (lockObject)
    {
        bool found = false;
        var triggersForJob = GetTriggersForJobInternal(jobKey);
        foreach (IOperableTrigger trigger in triggersForJob)
        {
            RemoveTriggerInternal(trigger.Key);
            found = true;
        }

        if (jobsByKey.Remove(jobKey) || found)
        {
            if (jobsByGroup.TryGetValue(jobKey.Group, out var grpMap))
            {
                if (grpMap.Remove(jobKey) && grpMap.Count == 0)
                {
                    jobsByGroup.Remove(jobKey.Group);
                }
            }
        }
        return found;
    }
}
```
`found` is what eventually gets returned from `IScheduler.DeleteJob`, but it only gets set to `true` if the job has any triggers.

**Comment by lahma** [comment]
Thanks for the report, your analysis seems correct. Would you like to submit a PR targeting 3.x branch?

**Comment by Sobotkama** [comment]
@lahma Sure, I'm not sure what to do with the tests though. Should I add an assertion to all of the `TestBasicStorageFunctions`s or add a new test case somewhere?

**Comment by lahma** [comment]
I think if you can add a test case like the one shows here as a separate one it should be fine, thanks.
