### ISSUE TITLE
Add UseMySqlConnector overload for MS DI database configuration

### ISSUE THREAD

**Issue by Timovzl** [quartznet/quartznet#1616]
`UsePersistentStore` enables implementation-specific extension methods, such as `UseMySql`. These dictate both the dialect and the specific database provider used. We can do better.

As a rule, we should depend on abstractions, not specific third-party packages. The developer should choose the concrete database provider. All that Quartz needs is a way to produce a `DbConnection` on demand.

Concretely, the issue I am running into is a code base that uses the truly async [MySqlConnector](https://github.com/mysql-net/MySqlConnector/) (for good reasons), with Quartz's MySQL implementation being tightly coupled to MySql.Data. This results in the need for two different MySQL connectors in one application. Additional complications arise, such as one connector needing `UseXaTransactions=False` to exhibit the desired behavior, but the other rejecting that option, defaulting to that behavior instead.

**Scope**

Although I am requesting this feature primarily for the MySql implementation, it would make sense to have for all the ADO.NET-based implementations.

**Proposed Solution**

Next to `SchedulerBuilder.AdoProviderOptions.ConnectionString`, we could introduce `SchedulerBuilder.AdoProviderOptions.ConnectionFactory`. A `Func<DbConnection>` type would do nicely.

If only `ConnectionString` is set, we maintain the existing behavior. If only `ConnectionFactory` is set, we use that to provide connections, and these are expected to come with their connection strings preassigned.

If _both_ properties are set, then the connection factory is used to produce a `DbConnection`, and then the connection string is used to assign `DbConnection.ConnectionString`. Although this may seem unimportant, it provides a sensible way of handling the presence of _both_ properties, and it fulfills a niche use case where the developer wants to separately provide `DbConnection` instantiation vs. `ConnectionString` selection.

**Alternative Solution**

An alternative solution might be to specify the assembly name, namespace, and type name of the concrete `DbConnection` type to use. We would rely on it having a default constructor. However, I consider this solution inferior. Not only are the strings obscure and error-prone, but they lack the `Func<DbConnection>`'s ability to configure the `DbConnection` in different ways, should the developer so desire.

**Comment by Timovzl** [comment]
> s.SetProperty("quartz.dataSource.default.provider", "MySqlConnector");

@lahma Many thanks to you for this alternative, sir! That is a great relief already.

I believe the feature request still has merit, since it takes away the duplication of the knowledge of both connection string and provider. I'd like to leave the feature request open, unless there are serious objections.

**Comment by Timovzl** [comment]
@lahma I think there is still merit to a `Func<DbConnection>` over a connection string. I personally tend to always have such an abstraction available. There is one place with the knowledge of how to produce `DbConnection` objects.

Could we extract a connection string _from_ such an object? Sure, with a helper method that obtains a `DbConnection`, gets its connection string, disposes the `DbConnection`, and returns the connection string. But that is exactly the kind of workaround that a neat registration method should help avoid.

Although #1621 solves the specific use case that lead to me create this feature request, it does not fulfill the feature request itself, and I would consider the feature to be a superior solution. I request reopening this one.

**Comment by lahma** [comment]
There's already [IDbProvider](https://github.com/quartznet/quartznet/blob/main/src/Quartz/Impl/AdoJobStore/Common/IDbProvider.cs). Which you can use to create connections etc. I think there's no need to add yet another abstraction?
