### ISSUE TITLE
Cron-Expression throws FormatException

### ISSUE THREAD

**Issue by LeMixer** [quartznet/quartznet#1647]
When trying to schedule a job using a cron-expression, this get's thrown:
```
System.FormatException: Unexpected end of expression.
   at Quartz.CronExpression.BuildExpression(String expression)
   at Quartz.CronExpression..ctor(String cronExpression)
   at Quartz.CronExpression.ValidateExpression(String cronExpression)
   at Quartz.CronScheduleBuilder.CronSchedule(String cronExpression)
   at Quartz.CronScheduleTriggerBuilderExtensions.WithCronSchedule(TriggerBuilder triggerBuilder, String cronExpression
```

**3.4.0**

**To Reproduce**

```cs
async Task StartBackroundTask()
            {
                StdSchedulerFactory factory = new();
                IScheduler scheduler = await factory.GetScheduler();

                IJobDetail job = JobBuilder.Create<LeaderboardJob>()
                    .WithIdentity("postleaderboards", "leaderboard")
                    .Build();

                ITrigger trigger = TriggerBuilder.Create()
                    .WithCronSchedule("0 0,21 * * *")
                    .ForJob("postleaderboards", "leaderboard")
                    .Build();

                await scheduler.ScheduleJob(job, trigger);
                await scheduler.Start();
            }
```
**Expected behavior**

The job should be scheduled for every day at midnight and 9pm.

**Comment by jafin** [comment]
Does this work? `0 0 0,21 1/1 * ? *` (untested)

**Comment by ismdiego** [comment]
I think this is not an issue. The expression: "**0** 0 0,21 * * ?" works for me. Also, the one that @jafin wrote works too.

In your original cron expression the seconds part was missing. Here is mandatory (see https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/crontrigger.html#format). And the Day of month or Day of week part must also be "?" (one of them).

**Comment by LeMixer** [comment]
Yeah, this may not be an issue. Both of your cron-expressions worked fine and I also rewrote mine, but I was confused, because the one I originally used, worked fine on my linux machine, when scheduling the execution of a Python script using crontab.

**Comment by lahma** [comment]
> Yeah, this may not be an issue. Both of your cron-expressions worked fine and I also rewrote mine, but I was confused, because the one I originally used, worked fine on my linux machine, when scheduling the execution of a Python script using crontab.

Crontab doesn't handle seconds, so Quartz's format is a bit different, because we want to run even crons jobs with seconds-precision. [CronMaker](http://www.cronmaker.com/) can be a useful tool to build schedules.
