### ISSUE TITLE
Not really an Issue, Just a question I have not found any answers for

### ISSUE THREAD

**Issue by Injac** [quartznet/quartznet#165]
Hi,
I have built an quartz cluster using Windows Azure with the following (test) configuration:

- 4 Worker Roles, each hosting a separate scheduler
-One dedicated SQL Server Standard 2014 instance, 7GB RAM, only hosting the Quartz database
-Azure Service Bus queue that is sending serialized objects to create triggers and jobs for different users

Every instance (Worker Roles) are listening to that queue. The queue itself is delivering all the messages to the different worker-roles. Duplicate messages are not delivered.

I created a simple console application, that sends serialized objects with all the required data to add new jobs to the different schedulers.

All Worker Roles are synchronized and run exactly to the second in the same time-zone (UTC) as well as the SQL-Server VM (UTC) as well.

What I did to test is, I created a simple console app, that sends 10000 jobs to the service bus queue with different job-id's (using GUIDS), to ensure not duplicates are sent through.

All of the schedulers are configured like this:

 properties["quartz.scheduler.instanceName"] = "SameForAll";
 
 properties["quartz.scheduler.instanceId"] = RoleEnvironment.CurrentRoleInstance.Id;
            //properties["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz";
properties["quartz.threadPool.threadCount"] = "14";
properties["quartz.threadPool.threadPriority"] = "Normal";
properties["quartz.jobStore.misfireThreshold"] = "60000";
properties["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz";
properties["quartz.jobStore.useProperties"] = "false";
properties["quartz.jobStore.dataSource"] = "default";
properties["quartz.jobStore.tablePrefix"] = "QRTZ_";
properties["quartz.jobStore.clustered"] = "true";

(Sorry if the code is messed up)

I tested different values for "quartz.threadPool.threadCount", I doubled the SQL Server RAM, even tripled it, watched it using SQL-Server Profiler and more.

The scheduler VM's have all 7GB of RAM as well. After a very short time, I get this lock exceptions all the time (row lock, sql server based).

Everything else works very smoothly. All jobs are cron-based jobs, from hourly execution to execution times of 5 minutes. The jobs are chosen randomly to create a nice set of test-jobs.

So here is my question:

-Why is there nearly no documentation for the enterprise features or a sample project?
-Do I have to pay to get those information's 
-I read everywhere that Quartz is able to manage millions of jobs, how can this be done?
-Who can help me?

**Comment by lahma** [comment]
Closing for now, please post findings here though.
