### ISSUE TITLE
Previous JobTypeInformation attributes on job class must now be on the interface

### ISSUE THREAD

**Issue by skotl** [quartznet/quartznet#1655]
**Describe the bug**

I've been having problems trying to get `[PersistJobDataAfterExecution]` and `[DisallowConcurrentExecution]` to be recognized when they decorate the IJob class as  per the documentation.

Looking through the code it seems that `JobDetailImpl.cs` only checks for the attributes on the *interface* rather than the class. I think this change was made here: #1345 

Question: is it intentional that the attributes will no longer be recognized on the class? Seems like a very subtle breaking change.

**Version used**

3.4.0

**To Reproduce**

```csharp

[PersistJobDataAfterExecution]
[DisallowConcurrentExecution]
internal class RequestAccountTransactionsJob : IJob, IRequestAccountTransactionsJob 
{

  // job code
}
```

```csharp
internal class JobFailureHandler : IJobListener
{
   // listener code...

   public async Task JobToBeExecuted(IJobExecutionContext context,  CancellationToken cancellationToken = new CancellationToken())
    {
        context.JobDetail.JobDataMap.PutAsString("test", DateTime.UtcNow);
    }
   // ...
```

Force the job to retry, break in the listener code and check `context.JobDetail.JobDataMap`. Also check `context.JobDetail.ConcurrentExecutionDisallowed` and `context.JobDetail.PersistJobDataAfterExecution`

They are both false unless the job's `IRequestAccountTransactionsJob` has the attributes

**Expected behavior**

Per the documentation, decorating the IJob-derived class with the attributes should set them true

**Additional context**

**Comment by lahma** [comment]
This test case passes, what am I missing?

```csharp
[Test]
public void AttributesAreBeingObeyed()
{
    var jobDetail = JobBuilder.Create<RequestAccountTransactionsJob>().Build();
    jobDetail.ConcurrentExecutionDisallowed.Should().BeTrue();
    jobDetail.PersistJobDataAfterExecution.Should().BeTrue();
}

[PersistJobDataAfterExecution]
[DisallowConcurrentExecution]
internal class RequestAccountTransactionsJob : IJob
{
    public Task Execute(IJobExecutionContext context) => Task.CompletedTask;
}
```

**Comment by skotl** [comment]
First off - thanks very much for the prompt response!

Turns out the problem is that I am creating requests with the interface (I'm using .Net 6 and DI) and everything works as expected from a scheduling perspective _except_ that the attributes aren't honored on the injected class. Switching the attributes to the interface does work.

So this test works (apologies it's xunit!):

```csharp
[Fact]
    public void AttributesAreBeingObeyed()
    {
        var jobDetail = JobBuilder.Create<RequestAccountTransactionsJob>().Build();
        Assert.True(jobDetail.ConcurrentExecutionDisallowed);
        Assert.True(jobDetail.PersistJobDataAfterExecution);
    }
```

But this test fails (when the attrs are on the class, not the interface):

```csharp
[Fact]
    public void AttributesAreBeingObeyed()
    {        //  *** create via interface injection **
        var jobDetail = JobBuilder.Create<IRequestAccountTransactionsJob>().Build();
        Assert.True(jobDetail.ConcurrentExecutionDisallowed);
        Assert.True(jobDetail.PersistJobDataAfterExecution);
    }
```

That's ok as I can address either by creating the concrete class or adding the attributes to the interface.
The question is - is this expected behavior (and is `JobBuilder.Create<interface>()` a supported operation)?

**Comment by lahma** [comment]
JobBuilder,Create with interface is quite hard to support as Quartz wouldn't know what type to instantiate. JobBuilder is not DI aware by itself.

**Comment by skotl** [comment]
Fair enough. In which case it's clear I didn't follow the docs correctly so will close - thanks for the prompt attention, and all the work on an excellent project!
