### ISSUE TITLE
DailyCalendar doesn't include first and last millisecond of day in checks

### ISSUE THREAD

**Issue by lpnam0201** [quartznet/quartznet#1665]
**Describe the bug**
I have a Scheduler with DailyCalendar (01:00 - 05:00). I tried to register a trigger with CronSchedule (0 0 0 * * ? *), which is midnight and should not fall within the range of DailyCalendar.
An exception is thrown.
Quartz.SchedulerException: 'Based on configured schedule, the given trigger 'group1.TestJobTrigger' will never fire.'

**Version used**

Quarzt 3.4.0

**To Reproduce**

Please see attachment. 
[TestQuartz.zip](https://github.com/quartznet/quartznet/files/9126956/TestQuartz.zip)

**Expected behavior**

No exception. The trigger is registered successfully.

**Additional context**
So I did some debugging at Quartz's code and I think my problem is at this line
https://github.com/quartznet/quartznet/blob/db27aa0d18e86fc82d067d3ddfb2ea7cd6fbe935/src/Quartz/Impl/Calendar/DailyCalendar.cs#L457
My `timeUtc` is midnight, which is exactly the same at `startOfDayInMillis`, therefore it failed the condition (here I expect it to return true so that my trigger is valid)
My question is why does the condition have to be `timeUtc > startOfDayInMillis`, instead of `>=`?
My current workaround is to change my Cron to 1 second after midnight, to avoid the exception.

Many thanks and have a great day.

**Comment by lahma** [comment]
Thanks for the report, should now be fixed in 3.x and main branches.
