### ISSUE TITLE
About quartz.jobStore in netcore

### ISSUE THREAD

**Issue by denisding** [quartznet/quartznet#1686]
when I use the config:
```
quartz.jobStore.type = Quartz.Impl.AdoJobStore.JobStoreTX, Quartz
quartz.dataSource.quartzDS.provider = SQLite
quartz.dataSource.quartzDS.connectionString = Data Source=./quartzDS.db
```
I got a error:
System.AggregateException:“One or more errors occurred. (Could not Initialize DataSource: quartzDS)”

the innerexception is:
FileNotFoundException: Could not load file or assembly 'System.Data.SQLite, Culture=neutral, PublicKeyToken=null'. 

but I use the .net 6 in my project with import Microsoft.Data.Sqlite, and is not System.Data.SQLite。

Please help me, What should I do

**Comment by lahma** [comment]
You should configure [SQLite-Microsoft](https://github.com/quartznet/quartznet/blob/6c81befdb55bda55b6dbc596630c2a19c1aef973/src/Quartz/Impl/AdoJobStore/Common/dbproviders.netstandard.properties#L98) as provider then.
