### ISSUE TITLE
The LogProvider doesn't contains CreateLogger in the latest release 3.4.0 version.

### ISSUE THREAD

**Issue by SimonLiu1981** [quartznet/quartznet#1691]
The LogProvider doesn't contains CreateLogger in the latest release 3.4.0 version.
I just using serilog in Quartz, and find the CreateLogger function is missing

`var serilogLogger = new LoggerConfiguration()`
`               .MinimumLevel.Verbose()`
`               .WriteTo.File("log.txt", rollingInterval: RollingInterval.Day)`
`               .CreateLogger();`
`            var loggerFactory = new LoggerFactory().AddSerilog(serilogLogger);            `
`            LogProvider.SetCurrentLogProvider(loggerFactory);`
`            LogProvider.CreateLogger // function missing in v3.4.0`

**Comment by jafin** [comment]
I checked out repo's current main, and it appears it is there:

```c#
  public static void ConfigureSerilogLogger()
        {
            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .WriteTo.Console()
                .CreateLogger();

            var loggerFactory = new LoggerFactory()
                .AddSerilog(Log.Logger);
            LogProvider.SetLogProvider(loggerFactory);
            LogProvider.CreateLogger<Logging>();
        }
```

Do you still have an issue?
