### ISSUE TITLE
DeleteJob does not fire ISchedulerListener.JobDeleted event

### ISSUE THREAD

**Issue by wilchn** [quartznet/quartznet#1694]
**Describe the bug**

ISchedulerListener.JobDeleted is not getting called when invoke IScheduler.DeleteJob() to a durable job.

According to doc, ISchedulerListener.JobDeleted will be called by the IScheduler when a IJobDetail has been deleted.

**Version used**

3.4.0

**To Reproduce**

Below is the Unit Test file based from [SchedulerListenerTest.cs](https://github.com/quartznet/quartznet/blob/6c81befdb55bda55b6dbc596630c2a19c1aef973/src/Quartz.Tests.Unit/SchedulerListenerTest.cs)
```csharp
        [Test]
        public async Task TestJobDeleted()
        {
            Qtz205TriggerListener triggerListener = new Qtz205TriggerListener();
            Qtz205ScheListener schedulerListener = new Qtz205ScheListener();
            NameValueCollection props = new NameValueCollection();
            props["quartz.scheduler.idleWaitTime"] = "1500";
            props["quartz.threadPool.threadCount"] = "3";
            props["quartz.serializer.type"] = TestConstants.DefaultSerializerType;
            IScheduler scheduler = await new StdSchedulerFactory(props).GetScheduler();
            scheduler.ListenerManager.AddSchedulerListener(schedulerListener);
            scheduler.ListenerManager.AddTriggerListener(triggerListener);

            var jobKeyToDelete = new JobKey("test", "test");
            var triggerKeyToDelete = new TriggerKey("test", "test");
            IJobDetail job = JobBuilder.Create<Qtz205Job>()
                .WithIdentity(jobKeyToDelete)
                .StoreDurably(true)
                .Build();
            ITrigger trigger = TriggerBuilder.Create()
                .WithIdentity(triggerKeyToDelete)
                .WithSimpleSchedule(x => x.WithInterval(TimeSpan.FromSeconds(1)))
                .Build();
            await scheduler.ScheduleJob(job, trigger);

            await scheduler.Start();
            await Task.Delay(5000);

            var triggerCount = (await scheduler.GetTriggerKeys(GroupMatcher<TriggerKey>.AnyGroup())).Count;
            var beforeDeleteJobCount = (await scheduler.GetJobKeys(GroupMatcher<JobKey>.AnyGroup())).Count;

            await scheduler.DeleteJob(jobKeyToDelete);

            var afterDeleteJobCount = (await scheduler.GetJobKeys(GroupMatcher<JobKey>.AnyGroup())).Count;

            await scheduler.Shutdown(true);

            Assert.AreEqual(1, jobExecutionCount);
            Assert.AreEqual(1, beforeDeleteJobCount, "test job is durable. It will remain even after trigger ends");
            Assert.AreEqual(0, triggerCount, "Expected to be 0 because it trigger only once");
            Assert.AreEqual(0, afterDeleteJobCount, "Expected to be 0 because test job got deleted");
            Assert.AreEqual(1, schedulerListener.JobDeletedCount, "Expected JobDeletedCount to be 1"); // <-- Test failed here
        }
```
Full code:
[SchedulerListenerTest.txt](https://github.com/quartznet/quartznet/files/9276937/SchedulerListenerTest.txt)

**Expected behavior**

ISchedulerListener.JobDeleted() should get called when IScheduler.DeleteJob()

**Comment by lahma** [comment]
Looking at the code paths, the listener should be invoked. Maybe you could create a failing test case and even, better fix for the possible issue?

**Comment by wilchn** [comment]
Updated the original post to include unit test. Also this seems only happens to durable job

**Comment by lahma** [comment]
This test case you provided passes as green for me both on 3.x and main branch.

**Comment by wilchn** [comment]
Strange. In my machine it's failed.
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/40131841/183316261-00de5e1a-472a-47f4-9b99-2ec2c9e54fd5.png">


I'm running in macOS M1 mac, dotnet core 6.0.7.

Attached the whole solution:
[QuartzUnitTest.zip](https://github.com/quartznet/quartznet/files/9277818/QuartzUnitTest.zip)

**Comment by lahma** [comment]
Can you test the latest myget version (readme has the details)? I think this might have been fixed with https://github.com/quartznet/quartznet/issues/1579 .

**Comment by wilchn** [comment]
Yes. Working when using preview 3.4.1 20220717. Thanks

**Comment by lahma** [comment]
Thanks for verifying, closing as will be fixed with next release.
