### ISSUE TITLE
Add automatic database creation and schema check

### ISSUE THREAD

**Issue by tvardero** [quartznet/quartznet#1695]
> Another major complaint is about automatic creation of database schema. Since Quartz.NET use sql script instead of  code-first ORM (such as Entity Framework), the initialization setup experience is not as good as Hangfire.  
> 
> Do you think we can add Entity framework based database schema creation feature? If you agree adding this to 4.0, I'm willing to work on that.

_Originally posted by @tonyqus in https://github.com/quartznet/quartznet/issues/988#issuecomment-1130785688_

EF is not must have, but automatic DB creation is. There could be some developers scared of SQL scripts :D

**Comment by tvardero** [comment]
It was answered: 

> > Please consider replacing MS DI with AutoFac. We did see a few unexpected issues happen in MS DI and Scoped lifecycle are not reliable at all. I believe it's kind of design issue of MS DI.
> 
> Or Lamar, or DryIoc.. the list goes on. There's already an [Autofac integration](https://github.com/alphacloud/Autofac.Extras.Quartz) that you can use. 
> 
> > I haven't dive deep into the code. Do you think it's possible to support any method with automatic IJob task creation?
> 
> I don't personally like the Hangfire way of things when we start to talk about persisted jobs. Clean and simple for in-memory jobs but complexity starts to hit with things like `() => someService.Method(counter++)`, how to handle all context and captures, makes things harder to test too IMO.
> 
>  > Do you think we can add Entity framework based database schema creation feature? If you agree adding this to 4.0, I'm willing to work on that.
> 
> I don't think we need EF to just handle schema. Because schema doesn't change that often I think it would be enough to detect via switch whether intitial schema creation is allowed and the schema is missing. Maybe add support for detecting database schema version and if it's different from what Quartz requires, give a startup error.

_Originally posted by @lahma in https://github.com/quartznet/quartznet/issues/988#issuecomment-1131207149_

**Comment by jafin** [comment]
@tvardero maybe this mees your needs.  https://github.com/appany/AppAny.Quartz.EntityFrameworkCore.Migrations

**Comment by lahma** [comment]
Schema management is currently out of scope for the base library and as noted, there are some community projects for that.
