### ISSUE TITLE
Allow changing DataSource name using built-in extension methods on SchedulerBuilder.PersistentStoreOptions

### ISSUE THREAD

**Issue by devbased** [quartznet/quartznet#1709]
**Is your feature request related to a problem? Please describe.**
I'm trying to setup aspnetcore integration tests with multiple databases in a single testhost (using xUnit) and noticed that some of the Quartz internals (e.g. SchedulerRepository, DbConnectionManager) are using static members which are shared between test runs.

In case of SchedulerRepository, there is pretty simple workaround - just generate unique SchedulerName per test.

The situation is more complicated with DbConnectionManager. Currently there's no possibility to setup name of the DataSource, it is hardcoded to 'default'.
<br />
**Describe the solution you'd like**
I would like an overload for UseSqlServer extension method with DataSource name parameter.
<br />
**Describe alternatives you've considered**
Copy-paste Quartz private/protected code and configure needed settings manually.
Perhaps I'm missing something and there is an easy way to implement the tests as I need.
<br />
**Additional context**
Reference to code:
https://github.com/quartznet/quartznet/blob/6c81befdb55bda55b6dbc596630c2a19c1aef973/src/Quartz/SchedulerBuilder.cs#L519-L520
https://github.com/quartznet/quartznet/blob/6c81befdb55bda55b6dbc596630c2a19c1aef973/src/Quartz/SchedulerBuilder.cs#L452-L458

**Comment by lahma** [comment]
I think this is generic configuration and not limited to UseSqlServer, would you like to offer a PR against v3 branch?

**Comment by devbased** [comment]
@lahma Of course, see #1710
There a lot of code duplication in PersistentStoreOptions and AdoProviderExtensions so I did small refactoring.
Not sure how to run all of those integration tests with different providers.. 😥 Unit tests are passing.
