### ISSUE TITLE
Microsoft DI integration does not working with Microsoft.Extensions.Hosting RC1

### ISSUE THREAD

**Issue by AntonioFalcaoJr** [quartznet/quartznet#1748]
**Describe the bug**

Configuration using `appsettings.json`, `QuartzOptions`, and configuration section `Quartz` does not work with `Microsoft.Extensions.Hosting` in version RC1.

**Version used**

Quartz: **3.4.0**
.NET: **7.0.100-rc.1.22431.12**
Microsoft.Extensions.Hosting: **7.0.0-rc.1.22426.10**

**To Reproduce**

**appsettings.json**

```json
{
  "Quartz": {
    "quartz.scheduler.instanceName": "Quartz ASP.NET Core Sample Scheduler",
    "quartz.scheduler.instanceId": "AUTO",
    "quartz.jobStore.dataSource": "default",
    "quartz.dataSource.default.provider": "SqlServer",
    "quartz.serializer.type": "json",
    "quartz.jobStore.type": "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
    "quartz.jobStore.clustered": true,
    "quartz.jobStore.driverDelegateType": "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz"
  }
}
```

**Startup.ConfigureServices**

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<QuartzOptions>(Configuration.GetSection("Quartz"));
}
```

**Logging**

```log
[11:20:41 INF] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
[11:20:41 INF] Quartz Scheduler created
[11:20:41 INF] RAMJobStore initialized.
[11:20:41 INF] Scheduler meta-data: Quartz Scheduler (v3.4.0.0) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
NOT STARTED.
Currently in standby mode.
Number of jobs executed: 0
Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.
[11:20:41 INF] Quartz scheduler 'QuartzScheduler' initialized
[11:20:41 INF] Quartz scheduler version: 3.4.0.0
[11:20:41 INF] Adding 0 jobs, 0 triggers.
[11:20:41 INF] JobFactory set to: MassTransit.QuartzIntegration.MassTransitJobFactory
[11:20:41 INF] Scheduler QuartzScheduler_$_NON_CLUSTERED started.
```

**Comment by lahma** [comment]
I think we fixed this in [version 3.4.0](https://github.com/quartznet/quartznet/releases/tag/v3.4.0).

**Comment by AntonioFalcaoJr** [comment]
> I think we fixed this in [version 3.4.0](https://github.com/quartznet/quartznet/releases/tag/v3.4.0).

Fixed the bug description, in fact, the problem occurs in version **3.4.0**

**Comment by lahma** [comment]
OK thanks for confirming there's still problem with the latest. I don't currently have the 7 series installed or under investigation so all help is always appreciated. I think the earlier problem was caught by enabling "catch all exceptions" while running in debug mode. There was some trouble there.

**Comment by AntonioFalcaoJr** [comment]
> I think we fixed this in [version 3.4.0](https://github.com/quartznet/quartznet/releases/tag/v3.4.0).

It was actually fixed in version **3.4.0** and **.NET 7 preview 1**. But the problem came back in **RC1**

**Comment by lahma** [comment]
OK it seems that you were the original reporter for the earlier problem, so you might have some insight in the issue, sorry about that 😄

**Comment by lahma** [comment]
This should now be fixed (again) in 3.x and main branches. Thanks for reporting!

**Comment by AntonioFalcaoJr** [comment]
Everything is OK on 3.5.0, Thanks again!

**Comment by lahma** [comment]
Thanks for confirming, enjoy the release!
