### ISSUE TITLE
Cron schedule of "0 30 * ? * *" or "0 30 * * * ?" not triggering on the 30th minute of each hour

### ISSUE THREAD

**Issue by atrauzzi** [quartznet/quartznet#1749]
**Describe the bug**

Cron schedule of `"0 30 * ? * *"` or `"0 30 * * * ?"` not triggering on the 30th minute of each hour

**Version used**

`3.4.0`

**To Reproduce**

```csharp
            configuration.ScheduleJob<HalfHour>((trigger) =>
            {
                trigger
                    .WithIdentity("half-hour", "time")
                    .StartNow()
                    .WithCronSchedule("* 30 * ? * *");
            });
```

**Expected behavior**

I have scheduled jobs for every hour and every minute and they are working fine.  But when I try to have this half hour one, it doesn't trigger and it almost appears as though it's triggering along with my hourly cron.

**Comment by lahma** [comment]
It's hard for me to believe that there's a bug on Quartz's side for such a simple expression.

```c#
var trigger = TriggerBuilder.Create()
    .StartNow()
    .WithCronSchedule("0 30 * ? * *")
    .Build();

var fireTimes = TriggerUtils.ComputeFireTimes((IOperableTrigger) trigger, calendar: null, numTimes: 10);
foreach (var time in fireTimes)
{
    Console.WriteLine(time);
}
```

Outputs:
```
2022-09-18 07:30:00 +00:00
2022-09-18 08:30:00 +00:00
2022-09-18 09:30:00 +00:00
2022-09-18 10:30:00 +00:00
2022-09-18 11:30:00 +00:00
2022-09-18 12:30:00 +00:00
2022-09-18 13:30:00 +00:00
2022-09-18 14:30:00 +00:00
2022-09-18 15:30:00 +00:00
2022-09-18 16:30:00 +00:00
```

Your example code has cron expression that fires every second though I believe. Probably good idea to enable more logging and see what is going on.
