### ISSUE TITLE
ICronTrigger for multiple time zones (suggestion)

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [quartznet/quartznet#179]
Now ICronTigger has TimeZone settings. But image a situation that there is a task that should be run at 1:00 AM on Mondays for several time zones. It would be cool if I don't have to create multiple cron trigger instances for each time zone, but set multiple time zones for one trigger and have the time zone which the trigger is fired for in IJobExecutionContext.

**Comment by lahma** [comment]
Closing as the solution is to use as many triggers as needed.
