### ISSUE TITLE
UseConnectionProvider<> fails 

### ISSUE THREAD

**Issue by justmara** [quartznet/quartznet#1795]
**Describe the bug**

There was a new `UseConnectionProvider<>()` [added](https://github.com/quartznet/quartznet/pull/1312/files) in recent versions, but it does not work :)

It fails trying to set up `provider` property for... provider:
```
Quartz.SchedulerException: ConnectionProvider type 'My.PostgresConnectionProvider' props could not be configured...

Quartz.SchedulerException
ConnectionProvider type 'My.PostgresConnectionProvider' props could not be configured.
   at Quartz.Impl.StdSchedulerFactory.Instantiate()
   at Quartz.Impl.StdSchedulerFactory.GetScheduler(CancellationToken cancellationToken)
... 
Quartz.SchedulerConfigException
Could not parse property 'provider' into correct data type: No writable property 'provider' found
   at Quartz.Util.ObjectUtils.SetObjectProperties(Object obj, NameValueCollection props)
   at Quartz.Impl.StdSchedulerFactory.Instantiate()

System.MemberAccessException
No writable property 'provider' found
   at Quartz.Util.ObjectUtils.SetPropertyValue(Object target, String propertyName, Object value)
   at Quartz.Util.ObjectUtils.SetObjectProperties(Object obj, NameValueCollection props) 
```

**Version used**

v 3.5.0

**To Reproduce**

```
     c.UsePostgres(db =>
     {
         db.UseConnectionProvider<PostgresConnectionProvider>();
     });

    public class PostgresConnectionProvider : IDbProvider
    {
        private readonly IPostgresConnectionFactory _factory;

        public PostgresConnectionProvider(IPostgresConnectionFactory factory) => _factory = factory;

        public string ConnectionString {
            get => _factory.GetConnectionString();
            set { }
        }
        
        public DbMetadata Metadata { get; }
        public DbConnection CreateConnection() => _factory.GetConnection();
        public DbCommand CreateCommand() => new NpgsqlCommand();
        public void Initialize() { }
        public void Shutdown() { }
    }

    public interface IPostgresConnectionFactory
    {
        string GetConnectionString();
        NpgsqlConnection GetConnection();
    }
```

**Expected behavior**

The provider must be instantiated and added to providers collections

**Additional context**

The concept itself seems to be wrong. It requires you to register exact `.Use[Postgres|MySql|etc]()` and only its registration method gives you an instance of AdoProviderOptions for `UseConnectionProvider<>()` to called on. But this call must be replacing the provider supplied by the `.Use*()` method. So you must register provider and then override it. But this configuration still fails, because initial `.Use*()` uses `UseGenericDatabase()` call that adds `quartz.dataSource.{dataSourceName}.provider` property, that cannot be applied to `IDbProvider` then. And `AdoProviderOptions` is internal, so you cant register its options normally without reflection or adding the required options manually for all the string keys.

If I want to add custom db provider using existing AdoProviderOptions methods, I am forced to write som ugly crap like this

```
                c.SetProperty("quartz.jobStore.dataSource", SchedulerBuilder.AdoProviderOptions.DefaultDataSourceName);
                var db = (SchedulerBuilder.AdoProviderOptions) Activator.CreateInstance(
                    typeof(SchedulerBuilder.AdoProviderOptions),
                    BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.CreateInstance,
                    null, new object[] { c, SchedulerBuilder.AdoProviderOptions.DefaultDataSourceName }, null)!;
                
                db.UseDriverDelegate<PostgreSQLDelegate>();
                db.UseConnectionProvider<PostgresConnectionProvider>();
```
Note that dataSource name is still set manually via direct key set, because there is no method  for it. This is always set via `Use*()` database methods.

Looks like the solution for this behaviour would be altering `UseConnectionProvider<>()` method like this:
```
            public void UseConnectionProvider<T>() where T : IDbProvider
            {
                options.SetProperty($"quartz.dataSource.{DefaultDataSourceName}.connectionProvider.type", typeof(T).AssemblyQualifiedNameWithoutVersion());
                options.Properties.Remove($"quartz.dataSource.{DefaultDataSourceName}.provider");
            }
```

But I'm not sure if this would break anything else or am I simply using it wrong...
Currently this workaround works:
```
                c.UsePostgres( db => db.UseConnectionProvider<PostgresConnectionProvider>());
                c.Properties.Remove($"quartz.dataSource.{SchedulerBuilder.AdoProviderOptions.DefaultDataSourceName}.provider");
```

**Comment by lahma** [comment]
Thanks for the detailed report. Should now be fixed in 3.x branch and soon available on the MyGet feed.
