### ISSUE TITLE
Add Quartz.XmlSerializers asembly in nuget package

### ISSUE THREAD

**Issue by maximpashuk** [quartznet/quartznet#181]
Then I am debugging in visual studio, I have an option "Debug->Exceptions->Managed Debugging Assistant" enabled.

This causes showing me BindingFailure exception, which is annouing.

I this this is in code
https://github.com/quartznet/quartznet/blob/ffe0f333b0b67ba8f39e5137ace82867d0b9c75f/src/Quartz/Xml/XMLSchedulingDataProcessor.cs#L227

XmlSerializer.Deserialize tries to find special satellite Quartz.XmlSerializer assembly, if this assembly cannot be found, it compiled in background.

This would be nice if you provide this Quartz.XmlSerializer assembly together with Quartz.

Consider visual studio project setting "Generate serialization assembly" in "Build" section.

**Comment by lahma** [comment]
Closing this as it's quite easy to ignore specific exception types in current visual studio versions. Can be reopened if someone wants to make a PR.

**Comment by zeng16107** [comment]
i met this issues in below enviroment:
vs2019, win10  Quartz.NET-3.0.7.

it looks like i hardly resolve this issue now.
