### ISSUE TITLE
quartz.dataSource.NAME.connectionStringName doesn't work

### ISSUE THREAD

**Issue by nikriaz** [quartznet/quartznet#1839]
**Describe the bug**

Named connection string from appsettings.json isn't recognized while .Net Core `services.AddDbContext `can read this string, and the string itself works as a string in `quartz.dataSource.NAME.connectionString` as well. Exception is: _Stopped program because of exception Quartz.SchedulerException: Named connection string 'Quartz' not found for DataSource: myDS"_

**Version used**

3.5.0

**To Reproduce**

```
  "ConnectionStrings": {
      "Quartz": "data source=SERVER.domain.local;initial catalog=Quartz;integrated security=True;MultipleActiveResultSets=True;App=Quartz"
  },
  "Quartz": {
      "quartz.dataSource.myDS.connectionStringName": "Quartz"
  }
```

**Comment by lahma** [comment]
Would you like to help out and create a PR against the 3.x to fix the issue?

**Comment by nikriaz** [comment]
I would love to but I'm afraid I'm not enough qualified. I looked on the source code and was unable to understand how you read connection strings from appsettings.json at all.

**Comment by lahma** [comment]
Fixed in 3.x branch and available on MyGet feed as preview.
