### ISSUE TITLE
Development of already published app when persistent store is used

### ISSUE THREAD

**Issue by nikriaz** [quartznet/quartznet#1840]
**Is your feature request related to a problem? Please describe.**
It's unclear how to continue to develop already published app if the app uses persistent store. It looks like a persistence store should be always in clustered mode otherwise further development is dangerous or not possible. Also, keeping time in sync between production and dev machines can be challenging. 

**Describe the solution you'd like**
Safe handling of the connection to the store if the development environment is detected

**Comment by lahma** [comment]
What actually is requested here? Is this a question or some actual feature request?

**Comment by lahma** [comment]
Cross-posted to https://stackoverflow.com/questions/74577989/quartz-net-scheduler-dev-vs-production-best-practice-when-use-sql-as-a-store so closing here.
