### ISSUE TITLE
Microsoft DI integration does not working with Microsoft.Extensions.Hosting .NET 7

### ISSUE THREAD

**Issue by AntonioFalcaoJr** [quartznet/quartznet#1866]
**Describe the bug**

Configuration using `appsettings.json`, `QuartzOptions`, and configuration section `Quartz` does not work with `Microsoft.Extensions.Hosting` in 7.

**Version used**

Quartz: **3.5.0**
.NET: **7.0.100**
Microsoft.Extensions.Hosting: **7.0.0**

**To Reproduce**

**appsettings.json**

```json
{
  "Quartz": {
    "quartz.scheduler.instanceName": "Quartz ASP.NET Core Sample Scheduler",
    "quartz.scheduler.instanceId": "AUTO",
    "quartz.jobStore.dataSource": "default",
    "quartz.dataSource.default.provider": "SqlServer",
    "quartz.serializer.type": "json",
    "quartz.jobStore.type": "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
    "quartz.jobStore.clustered": true,
    "quartz.jobStore.driverDelegateType": "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz"
  }
}
```

**Startup.ConfigureServices**

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<QuartzOptions>(Configuration.GetSection("Quartz"));
}
```

**Logging**

```log
[12:01:15 INF] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
[12:01:15 INF] Quartz Scheduler created
[12:01:15 INF] RAMJobStore initialized.
[12:01:15 INF] Quartz Scheduler 3.5.0.0 - 'QuartzScheduler' with instanceId 'NON_CLUSTERED' initialized
[12:01:15 INF] Using thread pool 'Quartz.Simpl.DefaultThreadPool', size: 10
[12:01:15 INF] Using job store 'Quartz.Simpl.RAMJobStore', supports persistence: False, clustered: False
[12:01:15 INF] Adding 0 jobs, 0 triggers.
[12:01:15 INF] JobFactory set to: MassTransit.QuartzIntegration.MassTransitJobFactory
[12:01:15 INF] Scheduler QuartzScheduler_$_NON_CLUSTERED started.
```

**Comment by AntonioFalcaoJr** [comment]
This is a silent problem. Is it possible to throw an exception or log an error at this point?

**Comment by lahma** [comment]
First I was like "haven't we fixed this at least one already", then I felt too much familiarity and checked... yes, you've reported the earlier problems too. Why can't we just get this to work 😞

**Comment by lahma** [comment]
I'm not quite sure about this. I started the v3.x branch and Quartz.Examples.AspNetCore, changed to net7.0 and output was correct to me ("Quartz ASP.NET Core Sample Scheduler"was there) so the configuration was read.

**Comment by AntonioFalcaoJr** [comment]
The code has been the same since the first report; I just upgraded the package. Let me see if I am missing anything

**Comment by AntonioFalcaoJr** [comment]
Sorry about that; it's working.

**Comment by lahma** [comment]
No worries, enjoy Quartz!
