### ISSUE TITLE
Code Analysis fails after updating to 2.2.4

### ISSUE THREAD

**Issue by TrevorPilley** [quartznet/quartznet#187]
I have just updated from Quartz.NET 2.2.3 to Quartz.NET 2.2.4 and am now receiving the following error when my CI build runs on my build server (it runs Code Analysis in release mode):

CA0055	Error Running Code Analysis	CA0055 : Could not load D:\Build\Management.Service\bin\Release\Management.Service.exe. The following error was encountered while reading module 'Quartz': Could not resolve type reference: [mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]System.Runtime.CompilerServices.ExtensionAttribute.

This doesn't happen on my development machine which is running VS 2013 and has .NET 4.5 and 4.5.1 installed, however it does on my build server which is running VS 2012 and has .NET 4.5 and 4.5.1 installed.

I suspect that the error is related to your use of ILMerge, see this for further info - http://www.mattwrock.com/post/2012/02/29/What-you-should-know-about-running-ILMerge-on-Net-45-Beta-assemblies-targeting-Net-40.aspx

**Comment by lahma** [comment]
2.3.1 is the latest try with this.
