### ISSUE TITLE
What is warning "ConnectionAndTransactionHolder passed to RollbackConnection was null, ignoring"?

### ISSUE THREAD

**Issue by camping89** [quartznet/quartznet#190]
I received a lot of warning "ConnectionAndTransactionHolder passed to RollbackConnection was null, ignoring". 

So my question is :
1) What is the warning?
2) Does it affect the job? 
3) Should I ignore it?
![image](https://cloud.githubusercontent.com/assets/6166970/3904112/e85eacc0-22d4-11e4-8fe7-adff6f843034.png)

**Comment by tjj2762** [comment]
Kinda late to the party here, but this warning can be caused by if your database goes offline while your service is running. Start your service, then kill SQL Server in services and you will then see these messages dump like this.
