### ISSUE TITLE
When using latest Quartz with System.Diagnostics.DiagnosticSource 7.0.0.0 or higher then jobs get stuck

### ISSUE THREAD

**Issue by Sicos1977** [quartznet/quartznet#1941]
When using Quartz.Net with System.Diagnostics.DiagnosticSource 7.0.0.X a job gets started but then gets stuck. When reverthing back to System.Diagnostics.DiagnosticSource 6.0.0.0 everything works as expected.

I also tried to add a binding redirect like this but that does not make any difference

```
			<dependentAssembly>
				<assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-7.0.0.1" newVersion="7.0.0.1"/>
			</dependentAssembly>
```

**Comment by lahma** [comment]
The issue template should ask things like version used and environment, if it doesn't for you can you add some details anyway?

**Comment by Sicos1977** [comment]
Sorry about that :-)

**Describe the bug**

When using Quartz.Net with System.Diagnostics.DiagnosticSource 7.0.0.X a job gets started but then gets stuck. When reverthing back to System.Diagnostics.DiagnosticSource 6.0.0.0 everything works as expected.

I also tried to add a binding redirect like this but that does not make any difference

```
			<dependentAssembly>
				<assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral"/>
				<bindingRedirect oldVersion="0.0.0.0-7.0.0.1" newVersion="7.0.0.1"/>
			</dependentAssembly>
```
**Version used**

Quartz.Net 3.6.2

**To Reproduce**

Upgrade System.Diagnostics.DiagnosticSource to version 7.0.0.0 or higher and execute a job

**Expected behavior**

Job gets run without getting stuck

**Additional context**
I think there are some code breaking changes in System.Diagnostics.DiagnosticSource 7 that Quartz.net is not handling correctly.

**Comment by lahma** [comment]
Are you running on old full framework or > NET 6?

**Comment by Sicos1977** [comment]
It is on .net framework 4.8

**Comment by Sicos1977** [comment]
Is it possible that you fix this issue in the near feature? It's a little bit anoying when I forget to exclude this package when updating all nuget packages to the latest version.

**Comment by lahma** [comment]
If you are in a hurry, we do take pull requests, I think you even have the repro on your machine.

**Comment by Sicos1977** [comment]
Have to make some time for that :-)

**Comment by Sicos1977** [comment]
I had some time to fix this... see pull request --> #2029

**Comment by Sicos1977** [comment]
Well I want to try to get you some logging but did see there was a new Diagnostic source version so I updated this to version 7.0.2 and now the problem is gone :-) . I don't know what has changed but I don't have to problem anymore where to job just gets stuck. 

Always nice those weird errors that solve themself.
