### ISSUE TITLE
Unable to get any job related information when using IObserver

### ISSUE THREAD

**Issue by dima-zhemkov** [quartznet/quartznet#1966]
**Describe the bug**

Because of changes in [this](https://github.com/quartznet/quartznet/commit/2ffb5a312a734745cf66ee1dba56e3451dacfa5d) commit I can no longer get any information about job or trigger when using `IObserver<in T>.OnNext` since you pass anonymous type to diagnostic listener.

**Version used**

3.6.2

**Expected behavior**

Pass to diagnostic listener some specific type that contains job and trigger details

**Comment by lahma** [comment]
Can you create a PR showing the shape of data you are expecting, the previous version was throwing exceptions and causing problems so it wasn't good either.
