### ISSUE TITLE
[FEATURE REQUEST] AggressiveInlining ThrowHelper methods to make Stacktrace little more useful

### ISSUE THREAD

**Issue by jafin** [quartznet/quartznet#1978]
## Feature Request

At present the ThrowHelper class wraps Exceptions.  Each method is attributed with NoInlining.  This has the effect of causing the stacktrace in release mode to be not as useful as it could.

## Proposal

Change the ThrowHelper methods to be 
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
```

#### BEFORE
![image](https://user-images.githubusercontent.com/127927/227824390-009a8e28-1c15-4994-909d-90f126c71891.png)

#### AFTER

Note the inlined ThrowHelper is gone. 
![image](https://user-images.githubusercontent.com/127927/227824435-6879f3a8-3880-4830-86ae-5f5e1bd609ba.png)

**Comment by lahma** [comment]
This is the opposite what [the throw helper pattern](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/diagnostics/throwhelper#technical-details) tries to do, so this is a no-go.

**Comment by jafin** [comment]
Ok so if I understand, this provides `smaller and efficient code` according to that description, but still with the added stacktrace line as a small side effect

> Note
>
>This will also result in a slightly different stack trace, as the exception will be thrown by this helper method instead of directly >by the original caller. The practical result is still the same as throwing an exception directly.

**Comment by lahma** [comment]
Yes,  this optimizes the callsite. Exceptions are exceptional stack's last element isn't that important. BCL has this behavior too.
