### ISSUE TITLE
Add non-generic implementation of IServiceCollectionQuartzConfigurator.ScheduleJob

### ISSUE THREAD

**Issue by MikeL9286** [quartznet/quartznet#1988]
**Is your feature request related to a problem? Please describe.**
When scheduling jobs by convention, you don't always have the explicit types of jobs. It's common to get all implementations of an interface and then act on that list. Only having a generic style implementation of ScheduleJob makes this difficult.

**Describe the solution you'd like**
Add a non-generic implementation of ScheduleJob to ServiceCollectionExtensions for IServiceCollectionQuartzConfigurator.

Existing ScheduleJob<T> implementation becomes...
```
public static IServiceCollectionQuartzConfigurator ScheduleJob<T>(
        this IServiceCollectionQuartzConfigurator options,
        Action<ITriggerConfigurator> trigger,
        Action<IJobConfigurator>? job = null) where T : IJob
{
    return ScheduleJob(options, typeof(T), trigger, job);
}
```

New ScheduleJob implementation...
```
public static IServiceCollectionQuartzConfigurator ScheduleJob(
        this IServiceCollectionQuartzConfigurator options,
        Type jobType,
        Action<ITriggerConfigurator> trigger,
        Action<IJobConfigurator>? job = null)
{
    if (!typeof(IJob).IsAssignableFrom(jobType))
    {
        throw new ArgumentException($"Argument must be of type {nameof(IJob)}", nameof(jobType));
    }
          
    //etc...
}
```

**Comment by lahma** [comment]
Thanks for the suggestion. Could you instead create a PR containing the change `ScheduleJob<T>` calling the new overload passing `typeof(T)`. If you would like it to be in 3.x series then you would need to target the 3.x branch with the change.
