### ISSUE TITLE
There is no metadata information for provider 'OracleODP' (Parameter 'providerName')

### ISSUE THREAD

**Issue by hochun836** [quartznet/quartznet#1992]
**Describe the bug**

when I try [Job Stores](https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/job-stores.html),

`quartz.dataSource.myDS.provider = OracleODP` // error : There is no metadata information for provider 'OracleODP' (Parameter 'providerName')

`quartz.dataSource.myDS.provider = OracleODPManaged` // correct

**Version used**

Quartz 3.6.2

**Expected behavior**

As the doc descirbes the `OracleODP` and `OracleODPManaged` supported, I think this error makes misunderstanding

**Comment by lahma** [comment]
Thank  you for the report. Can you instead create a PR fixing relevant documentation to the form you would like (note that there are folders for different versions). The confusion comes from the fact that `OracleODPManaged` is for the netstandard (NET Core/ >= NET5) and the `OracleODP`  is for full framework, these are different drivers.
