### ISSUE TITLE
return PersistJobDataAfterExecution flag in SelectJobDetail

### ISSUE THREAD

**Issue by wuuer** [quartznet/quartznet#2005]
PersistJobDataAfterExecution flag is set to true.
but the flag in the result of SelectJobDetail is always false.

**Comment by lahma** [comment]
A PR would be welcome.

**Comment by wuuer** [comment]
> A PR would be welcome.

PR 2 times
always failed

**Comment by wuuer** [comment]
created a PR again
https://github.com/quartznet/quartznet/pull/2012

**Comment by jafin** [comment]
@wuuer  how are you submitting your PR, it says 0 files changed?  Very strange.

**Comment by wuuer** [comment]
> @wuuer how are you submitting your PR, it says 0 files changed? Very strange. EDIT now it says 1 line. Could you create a branch with your changes, it looks like your PR off main. Also you are targeting main (which is 4.x) Not sure if your PR relates to v4 or v3. If 3, you'll need to target the 3.x branch for your PR.

It is v4.
now it got stuck in pr-tests-integration-postgres / ubuntu-latest (pull_request)

**Comment by wuuer** [comment]
I reopened the PR and all checks have passed
