### ISSUE TITLE
Quartz.Server.exe as a windows service access denied

### ISSUE THREAD

**Issue by lpunderscore** [quartznet/quartznet#205]
I installed Quartz.Server.exe as a windows service.

Everything went smoothly until I tried to connect it to a database.

After setting up the configuration options in the quartz.server.exe.config file, I kept getting an access denied when starting the service.

After a lot of playing around with the configuration settings, It turns out I needed to add this line:

```
<add key="quartz.jobStore.clustered" value="true"/>
```

If the line is not there, or the value is false, the service will simply not start. I went through the entire documentation and I just can't find it anywhere that this setting should be required when working with a database implementation (ramstore not clustered will start just fine too).

My entire quartz section for reference:

```
<quartz >

<!-- Sql connection information -->
<add key="quartz.scheduler.instanceName" value="JobsEngine"/>
<add key="quartz.scheduler.instanceId" value="instance_one"/>
<add key="quartz.threadPool.threadCount" value="10"/>
<add key="quartz.threadPool.threadPriority" value="Normal"/>
<add key="quartz.scheduler.idleWaitTime" value ="5000"/>
<add key="quartz.jobStore.misfireThreshold" value="60000"/>



<!--Uncomment this section to use database -->
<add key="quartz.jobStore.type" value="Quartz.Impl.AdoJobStore.JobStoreTX, Quartz"/>
<add key="quartz.jobStore.clustered" value="true"/>
<add key="quartz.jobStore.dataSource" value="default"/>
<add key="quartz.jobStore.driverDelegateType" value="Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz"/>
<add key="quartz.dataSource.default.connectionString" value="Server=(local);Database=jobs;Trusted_Connection=True;"/>
<add key="quartz.dataSource.default.provider" value="SqlServer-20"/>
<add key="quartz.jobStore.tablePrefix" value="jobs-"/>
<add key="quartz.jobStore.useProperties" value="true"/>
<!-- Database section end -->


<!--Export (make available remotly) the service -->
<add key="quartz.scheduler.exporter.type" value="Quartz.Simpl.RemotingSchedulerExporter, Quartz" />
<add key="quartz.scheduler.exporter.port" value="555" />
<add key="quartz.scheduler.exporter.bindName" value="Scheduler" />
<add key="quartz.scheduler.exporter.channelType" value="tcp" />
<add key="quartz.scheduler.exporter.channelName" value="httpQuartz" />
</quartz>
```

**Comment by glocken** [comment]
It didn't work for me...
I have exactly the same issue with Quartz 3.5.0. When I use RAMJobStore quartz service starts with no problem but when replaced with JobStoreTX it doesn't start.

This is what I did to fix the issue:

- Unblocking the zip file.
- Assigned "Full Control" permission to the main folder in case of raising other permission related stuff.
- Move "Quartz Server" folder to "Program Files (x86)".

This is my quartz.config db setting:

quartz.jobStore.type = Quartz.Impl.AdoJobStore.JobStoreTX, Quartz
quartz.jobStore.tablePrefix = dbo.QRTZ_
quartz.jobStore.driverDelegateType = Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz
quartz.jobStore.dataSource = myDs
quartz.dataSource.myDS.connectionString = Server=localhost\sql2017;Database=********;User Id=*****;Password=*****
quartz.dataSource.myDS.provider = SqlServer
quartz.jobStore.clustered = false

#Configuring AdoJobStore to use strings as JobDataMap values (recommended)
quartz.jobStore.useProperties = true
