### ISSUE TITLE
Performance issues reading large job objects from AdoJobStore on SQL Server

### ISSUE THREAD

**Issue by OronDF343** [quartznet/quartznet#2054]
**Describe the bug**

Reading very large JobDetail objects from SQL Server is extremely slow due to https://github.com/dotnet/SqlClient/issues/593

I have changed the read at [this line](https://github.com/quartznet/quartznet/blob/e40294119921ba04f27cb050338dbfff26b566c8/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs#L130) to be synchronous in order to work around the issue temporarily, which fixed it for me.

To work around this issue, if possible, `StdAdoDelegate` should pass `CommandBehavior.SequentialAccess` to `ExecuteReaderAsync`. [Link to docs](https://learn.microsoft.com/en-us/dotnet/api/system.data.commandbehavior?view=net-7.0)

Additionally, the code of `StdAdoDelegate` could use some optimization, [see here](https://github.com/quartznet/quartznet/blob/e40294119921ba04f27cb050338dbfff26b566c8/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs#L591). The bytes are written to a `MemoryStream` which is immediately discarded. Please consider using `MemoryPool` or `RecycleableMemoryStream` instead of allocating byte arrays.

**Version used**

* Quartz 3.6.2
* .NET 6.0
* Microsoft.Data.SqlClient 5.1.1

**To Reproduce**

Schedule any job object that has a size in the order of megabytes, then wait for the trigger to fire.

**Comment by lahma** [comment]
Would you like to submit a PR containing improvements?

**Comment by OronDF343** [comment]
I am interested in doing so. I'll see what I can do next week, but probably will only be able to submit a PR in the week after the next.

**Comment by lahma** [comment]
Great to hear.  Please note that 3.x branch is there for servicing v3.
