### ISSUE TITLE
Make Quartz.QuartzHostedService public or add extension method to remove hostedservice for integration testing

### ISSUE THREAD

**Issue by rf-0** [quartznet/quartznet#2088]
**Describe the bug**

Because Quartz.QuartzHostedService is internal, it is not possible to specifically remove quartz hosted service for integration tests.

**Version used**

Quartz.AspNetCore 3.6.2

**To Reproduce**

[Code/class
](https://github.com/quartznet/quartznet/blob/main/src/Quartz/Hosting/QuartzHostedService.cs)

**Expected behavior**

Ability to do the following:
services.Remove(services.Single(static s => s.ImplementationType == typeof(Quartz.QuartzHostedService)));
services.AddSingleton<Quartz.QuartzHostedService>();

**Additional context**
Required for integration testing (stop/start hosted services manually)

**Comment by lahma** [comment]
You can probably workaround the problem by checking `ImplementationType.Name`.

**Comment by rf-0** [comment]
Magic strings is usually a bad idea. Also, i want to be able to do the following:

// Arrange
var quartzHostedService = messageServiceFactoryFixture.Services.GetRequiredService<Quartz.QuartzHostedService>(); //error

// Act
await quartzHostedService.StartAsync(CancellationToken.None);
await quartzHostedService.StopAsync(CancellationToken.None);

// Assert
etc...

**Comment by rf-0** [comment]
Magic strings is usually a bad idea. Also, i want to be able to do the following:

// Arrange
var quartzHostedService = serviceFactoryFixture.Services.GetRequiredService<Quartz.QuartzHostedService>(); //error

// Act
await quartzHostedService.StartAsync(CancellationToken.None);
await quartzHostedService.StopAsync(CancellationToken.None);

// Assert
etc...

**Comment by lahma** [comment]
Yes workaround is a different thing from a fix.

Can you submit a PR against 3.x branch to make the hosted service class `public sealed class`?
