### ISSUE TITLE
Memory leak with the Microsoft Dependency Injection job factory

### ISSUE THREAD

**Issue by danports** [quartznet/quartznet#2099]
**Describe the bug**

Quartz.NET appears to leak memory when running jobs with the Microsoft.Extensions.DependencyInjection job factory.

**Version used**

3.6.3

**To Reproduce**

https://github.com/danports/MemoryLeakTest

**Expected behavior**

Memory usage should remain relatively stable; instead, it increases without bound:
![image](https://github.com/quartznet/quartznet/assets/8728855/df2a80e5-bd60-4453-ae94-1e08a720cb1d)

**Additional context**
I'm wondering if Quartz.NET is not properly disposing the service scope created for running jobs - when I review the heap in the debugger, it appears that none of the `ApplicationDbContext` instances are freed even though some of the `TestJob` instances are.

**Comment by asulwer** [comment]
you are creating a job every second, forever.  in that job you are creating a million Person objects that are being added to the MySQL DB context?  but never saved just added?  the local Person context is growing and nothing is ever saved to the DB?  it appears that memory is created/used quicker than it is being freed.  maybe, slow it down a bit?

**Comment by asulwer** [comment]
as suspected.  the work the job is doing is not finishing before the next job starts.  the queue is growing faster than it can shrink because the amount of work each job performs.  reduce how many Person objects that are being created per job from 1,000,000 to 1,000 and the memory issue goes away.  my guess is that you created a stress test but labeled it memory leak.

**Comment by danports** [comment]
Yeah, you're right, even slapping `[DisallowConcurrentExecution]` on the `TestJob` is sufficient to eliminate the memory issue in this code. The actual issue I've been having for the past couple of months is a process hitting memory limits after repeated failed runs of one of its Quartz jobs that sometimes throws a `DbUpdateConcurrencyException`. It's clear from process memory stats that the memory from the job runs where a `DbUpdateConcurrencyException` is thrown is never reclaimed, and the onset of this issue correlates with when I switched this process from another scheduling engine to Quartz.NET. I need to do some more work to refine my repro project - I assumed that I had replicated the issue when I hadn't yet. Sorry about that, I'll update this once I make some progress with the repro project.

**Comment by danports** [comment]
Alright, the repro project replicates my actual problem now - but the updated version seems to be pointing to an issue with the Sentry .NET SDK, not Quartz.NET: https://github.com/getsentry/sentry-dotnet/issues/2516

I will run some more experiments and see if I can rule out any issues with Quartz.NET (e.g. by removing it from the repro project altogether), and if I can, I'll close this.

**Comment by danports** [comment]
When I remove Quartz.NET from the repro project (by cutting out the scheduler and executing the `TestJob` directly), I am unable to reproduce the problem, so I can't yet rule out an issue with Quartz.NET. Continuing to dig deeper.

**Comment by danports** [comment]
Alright, upon further investigation, this is an issue with neither Quartz.NET nor the Sentry .NET SDK - it's a known problem with the runtime (https://github.com/mono/mono/issues/19665), which apparently gets triggered through the (indirect) interactions between Quartz.NET and Sentry when a Quartz job fails and Sentry logs the exceptions. I guess I got lucky with the previous scheduling engine I was using because it didn't trigger this issue, which made me suspect Quartz.NET when it was actually the runtime at fault. Sorry for the false alarm!
