### ISSUE TITLE
Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly mscorlib

### ISSUE THREAD

**Issue by sa4720k** [quartznet/quartznet#215]
I recently downloaded the 2.3 release of Quartz.net.  I included it within my ASP.NET web forms application using .NET Framework 4.0 with Visual Studio 2013.  Quartz.net and my program run fine on the development machine (Windows 7) and on our Test server (Windows Server 2008 R2).  However, when I deploy the code/assemblies to the production server (also Windows Server 2008 R2) I get the following exception:

Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, publicKeyToken=b77a5c561934e089

I have searched all over the Internet for a solution to this problem.  Some say that it's because I'm developing on a system that has .NET Framework 4.5, or that I need to install .NET Framework 4.5, or that one of the assemblies is made for .NET Framework 4.5, or something to do with ILMerge.

Nothing I've done seems to work.  I've checked all of my assemblies with Telerik's JustDecompile, and none of my code is referencing 4.5.  I'm also not using ILMerge, and the production server does not have 4.5 installed on it, and I can't install it on there (customer does not want to, yet).

It seems that Quartz.net used to have this issue with their 2.1.1 version that was supposed to have been fixed in 2.1.2, but it seems to be back again in 2.3.

Please, can someone tell me how to fix this problem?  I've run out of things to try.

Thanks.

**Comment by lahma** [comment]
Should be fixed with 2.3.1
