### ISSUE TITLE
TryGet functions not behave like standard .NET functions

### ISSUE THREAD

**Issue by dtila** [quartznet/quartznet#2175]
**Describe the bug**

All the TryGet functions return default values despite the key is not present in the dictionary.
Example: TryGetInt, will return 0 if the key is not present
Given the https://github.com/quartznet/quartznet/blob/main/src/Quartz/Util/StringKeyDirtyFlagMap.cs#L35

The issue resides with the fact that when the key is retrieved (and does not exists) will have the null value. The null value will be passed in the Convert.ToInt32(null) and return 0.

Hence the TryGetint will return true, despite the key does not exists.

This is in contradictory with the Dictionary.TryGetValue since it returns true only if the key was present in the dictionary.

**Version used**

Latest version, the bug exists in master as well.

**To Reproduce**

`!context.MergedJobDataMap.TryGetInt("KEY", out int continuousEmptyPages) - will ALWAYS return true`

**Expected behavior**

The return should be false if the key is not present

**Additional context**

A workaround exists of course. 
Example this code:
```
 if (!context.JobDetail.JobDataMap.TryGetInt(ConsecutiveEmptyPagesKey, out int continuousEmptyPages ))
 // do something if the key does not exists
```
can be made as a workaround like this:
```
 int continuousEmptyPages = 0;
 if (context.JobDetail.JobDataMap.ContainsKey(ConsecutiveEmptyPagesKey))
     continuousEmptyPages = context.JobDetail.JobDataMap.GetIntValue(ConsecutiveEmptyPagesKey);
else
 // do something if the key does not exists
```

**Comment by lahma** [comment]
I believe this was fixed by #2125
