### ISSUE TITLE
Quartz 2.2.4 : CalendarIntervalTriggerImpl doesn't consider WeeklyCalendar while calculating next fire time after.

### ISSUE THREAD

**Issue by lalitnchaudhari** [quartznet/quartznet#218]
We are using Quartz 2.2.4 version and CalendarTrigger with WeeklyCalendar.

It was identified that when we set weekly calendar with few days (lets say. Mon, Tue) and we built a CalendarTrigger with intervals in weeks as 2. Consider today is Monday, In this scenario the next fire time which Quartz calculates is todays time as its a first occurance of the trigger. 

Expected:- After first fire Quartz CalendarTrigger should calculate and displays the time of Tuesday, as the calendar has provided to this trigger and it would be next fire time. 

Actual:- After first fire Quartz calculates the next fire time as next to next monday as it applies intervals only for calculating next fire time and doesn't consider the weekly calendar. Hence skipping next calendar day occurance (Tue in above scenario).

Root Cause:- 
While debugging it was found that, GetFireTimeAfter(...) method of CalendarIntervalTriggerImpl.cs doesn't consider calendar for calculating next fire time for weekly case. It's just considering RepeatInterval * 7 for calculation.

We tried some code changes to make this workable and found it working. For that we needed to pass calendar along for GetFireTimeAfter(...) method which toched-upon few files. 
Here I have attached few high level code changes:

Changes in CalendarIntervalTriggerImpl.cs
![image](https://cloud.githubusercontent.com/assets/10279148/5538010/ddd0cc92-8ad1-11e4-8e60-b8db03eadb05.png)

Utilizing parameter Calendar which is passed to method (code changes in case of Weekly):
![image](https://cloud.githubusercontent.com/assets/10279148/5538039/1f0fc4d8-8ad2-11e4-8157-1fa153a943b9.png)

Some other changes are done on WeeklyCalendar.cs file, GetNextIncludedTimeUtc(...) method to return correct day timestamp based on the provided startDay.  

![image](https://cloud.githubusercontent.com/assets/10279148/5538076/e1955a5e-8ad2-11e4-914d-e03c27702bb2.png)

Let me know if this clarifies the issue.

**Comment by lalitnchaudhari** [comment]
Hi,

Any recent updates on this issue?

**Comment by lahma** [comment]
Could you provide the code that you have used for testing your scenario? The proposed changes don't seem to make enough sense at the moment.

**Comment by lalitnchaudhari** [comment]
Hi Lamha,

Here is code which I wrote quickly to test this scenario, hopefully it would be helpful for you to understand this issue better.
-------------------------------------------------------------------------------------------
IJobDetail job = JobBuilder.Create<PORecocilationJob>()
                .WithIdentity("100", "MyJobGroup")
                .Build();

            //Adding weekly calendar to trigger on Monday and Tuesday.
            var weeklyCalendar = new WeeklyCalendar();
            weeklyCalendar.SetDayExcluded(DayOfWeek.Monday, false);
            weeklyCalendar.SetDayExcluded(DayOfWeek.Tuesday, false);

            //Adding weekly calendar in scheduler. Which is of Monday and Tuesday.
            QuartzScheduler.Scheduler.AddCalendar("MyCalendar", weeklyCalendar, true, true);

            var repeatIntervalsInWeeks = 2;
            ITrigger trigger1 = TriggerBuilder.Create()
                   .ForJob(new JobKey(job.Key.Name, job.Key.Group))
                   .WithIdentity("MyTrigger", "MyTriggerGroup")
                   .StartAt(DateTime.Now.AddHours(1.0).ToUniversalTime()) //Adding 1 hr difference as a fire time.
                   .EndAt(DateTime.Now.AddYears(1))
                   .ModifiedByCalendar("MyCalendar") //Need to fire on Manday and Tuesday
                   .WithCalendarIntervalSchedule(x => x.WithIntervalInWeeks(repeatIntervalsInWeeks).WithMisfireHandlingInstructionDoNothing()) //Need to fire after every 2 weeks on Mon and Tue.
                   .Build();

            QuartzScheduler.Scheduler.ScheduleJob(job, trigger1);


            //Retrieving infromation from saved trigger about the next fire timings.
            var weeklyTrigger = QuartzScheduler.Scheduler.GetTrigger(new TriggerKey("MyTrigger", "MyTriggerGroup"));

            var firstFireTimeOfMonday = weeklyTrigger.GetNextFireTimeUtc(); //This should be first occurance of execution Corresponding to Monday.

            var secondFireTimeOfTuesday = weeklyTrigger.GetFireTimeAfter(firstFireTimeOfMonday); //This should be of Tuesday's time. This should be next fire time after Monday's fire time.       
-------------------------------------------------------------------------------------------

Using Quartz 2.2.4, "secondFireTimeOfTuesday" comes to be the datetime which would occure after 2 weeks after first fire time monday. Means as follows:
firstFireTimeOfMonday = 1/5/2015 6:00:00 AM
secondFireTimeOfTuesday = 1/19/2015 6:00:00 AM

This was the issue I was talking about in the conversation/explaination, GetFireTimeAfter doesn'e consider the calendar what we supplies to it, it just considers intervals in weeks and calculates accordingly.

Is there any specific way to create such trigger with calendar, have we missed something in creating trigger?

When we put our changes as described in initial convesation of this thread, we could able to get next fire time correctly (of Tuesday's time) as per calendar.

**Comment by lahma** [comment]
What you describe here does not make entirely sense. Quartz respects the calendar but your schedule cannot be applied to it.

You want a trigger that fires every two weeks, OK so say it's Monday. How could this trigger fire on Tuesday as it's not two weeks apart from last fire time? Calendar can restrict the schedule that is already occurring, but cannot expand it to times that are not part of the trigger's schedule.

What you can do is create two triggers, one for Monday and one for Tuesday and make them trigger every two weeks.

Hope this helps.
