### ISSUE TITLE
Incorrect NextFireTime when 'schedule-trigger-relative-to-replaced-trigger' = 'true'

### ISSUE THREAD

**Issue by cookav** [quartznet/quartznet#219]
When using XML config with 'schedule-trigger-relative-to-replaced-trigger' set to 'true' the NextFireTime property is first set to a next fire time after the old trigger's fire time (https://github.com/quartznet/quartznet/blob/03fa4641c543833460d696823d010cf2c64269ab/src/Quartz/Xml/XMLSchedulingDataProcessor.cs#L943), which is what I would expect, but a few lines later, when job is rescheduled, it is changed to a trigger's first fire time (https://github.com/quartznet/quartznet/blob/03fa4641c543833460d696823d010cf2c64269ab/src/Quartz/Core/QuartzScheduler.cs#L976) which in case of replacing a trigger might be well in the past. Such trigger is considered 'misfired' and is fired again, even if it was previously fired on schedule.

I use XML config, AdoJobStore and CronTriggers. Every program restart causes XML config file to be processed again and even if nothing changed jobs and triggers are replaced which because of the issue described above causes all triggers to be fired again. Is it a bug or is it 'by design' and I'm misusing some of the features?

**Comment by lahma** [comment]
I'm not sure if I'm following. The line you have linked is only a return value that is used to inform about the reschedule process. XmlSchedulingDataProcessor does not use it at all? It's just used for sanity check that the trigger works as expected (has a fire time).

Could the misfire you describe be happening because the trigger was actually expected to run while the program was restarting (last expected next run was in the past)?

**Comment by cookav** [comment]
The problem is that the next fire time of a trigger is being changed by a call to ComputeFirstFireTimeUtc(cal) so it's effectively more than just a sanity check. Please have a look at its implementation for a CronTrigger: https://github.com/quartznet/quartznet/blob/35afe6acdd7f08a543e323e3673329f68f027155/src/Quartz/Impl/Triggers/CronTriggerImpl.cs#L872.

**Comment by lahma** [comment]
Ah now I see your point, thanks for the clarification!

**Comment by lahma** [comment]
This should be now hopefully fixed in master, will be part of 2.3.1.
