### ISSUE TITLE
Rename JobStoreSupport.RetryableActionErrorLogThreshold

### ISSUE THREAD

**Issue by kenbrubaker** [quartznet/quartznet#220]
I'm now instrumenting my code to find the quartz trigger state issue I mentioned in #213. I noticed that you have a `JobStoreSupport.MisfireThreshold` `TimeSpan` property that is configured as milliseconds. It may be confusing to have another configuration property named `Threshold` that is not time based. Perhaps a better name is `RetryableActionErrorLogInterval`?

If you like it, I can send another pull request with the change.

**Comment by kenbrubaker** [comment]
Well maybe that doesn't make sense either since there also is a `JobStoreSupport.DbRetryInterval`. Perhaps `RetryableActionErrorLogCount`? Er. `Gap`, `SkipCount`, ...

**Comment by lahma** [comment]
I think threshold as a name is valid. As hindsight it might have been better to rename the other one as JobStoreSupport.MisfireThresholdMilliseconds, but that would be a API breaking change. Maybe we go with the original and let the user find info from docs? This would be a feature not used by a regular user that often anyway I guess.

**Comment by kenbrubaker** [comment]
Yup
