### ISSUE TITLE
Unknown configuration property 'quartz.config'

### ISSUE THREAD

**Issue by delta-emil** [quartznet/quartznet#2212]
**Describe the bug**

If you let the `StdSchedulerFactory` load the configuration from a file specified the environment variable "quartz.config" (defined in `StdSchedulerFactory.PropertiesFile`), then you get a `Quartz.SchedulerConfigException` saying `Unknown configuration property 'quartz.config'`

**Version used**

Appeared in v3.8.0, was not present in v.3.7.0

Seems to have been caused by https://github.com/quartznet/quartznet/commit/5562a9a6221531cb7a569cdc801c73ef06ab22da

That change introduced an explicit allowed list of configuration values, which doesn't include "quartz.config", but "quartz.config" is always added from the environment variables by `OverrideWithSysProps`.

**To Reproduce**

```cs

    [Test]
    public async Task TestFactoryShouldLoadPropertiesFromFileWhosePathIsGivenByEnvVariable()
    {
        var tempFile = Path.GetTempFileName();
        try
        {
            const string InstanceName = "TestInstance";

            File.WriteAllText(tempFile, $"{StdSchedulerFactory.PropertySchedulerInstanceName}={InstanceName}");

            Environment.SetEnvironmentVariable(StdSchedulerFactory.PropertiesFile, tempFile);

            var factory = new StdSchedulerFactory();
            factory.Initialize(); // <- optional, because `GetScheduler` does it anyway
            var scheduler = await factory.GetScheduler();

            Assert.AreEqual(InstanceName, scheduler.SchedulerName);
        }
        finally
        {
            try
            {
                File.Delete(tempFile);
            }
            catch (Exception)
            {
                // ignore temp file delete error
            }

            Environment.SetEnvironmentVariable(StdSchedulerFactory.PropertiesFile, null);
        }
    }
```

**Expected behavior**

Using environment variable "quartz.config" to specify the path to the config file should not cause an exception.

Perhaps  `OverrideWithSysProps` should explicitly skip environment variable "quartz.config" (`StdSchedulerFactory.PropertiesFile`)?

**Comment by lahma** [comment]
Thanks for the detailed bug report and test case. Skipping this in override seems reasonable. Would you like to take a stab creating a fix via a PR against the 3.x branch?

**Comment by feiazifeiazi** [comment]
赞。
