### ISSUE TITLE
Option to stop the constant logging of "Batch acquisition of 0 triggers"

### ISSUE THREAD

**Issue by tarockx** [quartznet/quartznet#2219]
**Is your feature request related to a problem? Please describe.**
Whenever a QuartzNet scheduler is running, it constantly spams the "Batch acquisition of 0 triggers" line to the logs, as shown in the following screenshot:
![image](https://github.com/quartznet/quartznet/assets/10919460/56602cc0-d34a-47f0-af0f-58eb3dfd0713)

**Describe the solution you'd like**
It would be great to have an option to disable this logging in the Quartz configuration 

**Describe alternatives you've considered**
You can configure logging to exclude the DEBUG level, but this is not ideal in my opinion, as you might actually want to log debug messages, just not the constant "Batch acquisition of 0 triggers" line which in a lot cases is pretty useless and just pollutes the logs.

**Comment by lahma** [comment]
Well it's called debug level logging for a reason. DEBUG level shouldn't be normal use case unless you are trying to diagnose a problem. INFO should be a good option with Quartz.

**Comment by jafin** [comment]
@tarockx this should be a feature of your logger.  For Example with Serilog, you can set the minimum logging level per namespace.  In your example Debug level for namespace `Quartz.Core.QuartzScheduler.Thread`

Serilog also has a `Filter.ByExcluding(Matching.With ....)`  you could tweak to filter on a match of the log.

**Comment by tarockx** [comment]
> @tarockx this should be a feature of your logger. For Example with Serilog, you can set the minimum logging level per namespace. In your example Debug level for namespace `Quartz.Core.QuartzScheduler.Thread`
> 
> Serilog also has a `Filter.ByExcluding(Matching.With ....)` you could tweak to filter on a match of the log.

This is indeed the correct solution, don't know why I didn't think of it. I think this issue can be closed.
