### ISSUE TITLE
Breaking change in a minor release

### ISSUE THREAD

**Issue by remcoros** [quartznet/quartznet#229]
I left a comment on this closed issue (#226), but want to raise awareness of the issue upgrading Quartznet 2.3 to Common Logging 3.

In my opinion, and following semantic versioning, you should not introduce major breaking changes in minor releases.

Updating Quartz from 2.3 > 2.3.1 should not force the consumer to upgrade a MAJOR dependency, which itself has a huge breaking change (ILog interface has changed and moved to a different assembly).

This breaks all dependent libraries (e.g. NInject Quartz extension, Topshelf logging, even your own code!)

I really didn't expect this from such a mature and widely used library.

Damage has already been done, but please, maintainers, could you take this into account in future patches and releases.

**Comment by lahma** [comment]
If we are talking about the same semantic versioning (http://semver.org/) it addresses the issue of API versioning. Quartz.NET 2.3.1 contained no API changes and bugfixes were backwards compatible. I'm aware of the issue that Common.Logging is not backwards compatible, hence their version changed from 2.x to 3.x.

Had there been a version 2.4, it still would have broken the same way *if* one has external dependencies with same logging library. NuGet updates to Common.Logging 3 without considering these kind of issues too much, there's detailed discussion about NuGet here https://github.com/net-commons/common-logging/issues/74 .

So in a situation like this, whether the version had been 2.4 or 2.3.1. the easiest path would be do a simple VCS revert, set upper-bound in packages.config for Quartz to be 2.3 and wait for dependent libraries to upgrade to Common.Logging 3.x series.

**Comment by remcoros** [comment]
If your library (in this case quartz) depends on 3rd party libraries, those 3rd party libraries are somewhat part of your own api. So in that sense, if you upgrade a dependent library, which itself has a huge breaking change, you introduce a breaking change for the users of your own library.

I know it's an easy fix if you do proper version control (in my case, it was indeed a simple revert after realizing this).

Of-course, whatever version number you assign, it doesn't magically fix things. But it's about communication to your users.

Semantic versioning is not just about your own CODE or API, it's about proper communication of changes within the library to the users of that library. In this case, semantic versioning demands a major release for ANY breaking change.

If I see a 2.3 > 2.3.1 release, I think: minor patch, most likely no breaking changes.
If I see a 2.3 > 2.4 release, alarm bells go off and I know more care should be taken in upgrading.
