### ISSUE TITLE
Latest, multiple WebApplications under one process are severely unable to run!!!

### ISSUE THREAD

**Issue by ccnetcore** [quartznet/quartznet#2299]
**Describe the bug**

Hello, my dear Quartz.net organization.I started multiple .netcore webhosts in one process， Will report an error:
System.AggregateException:“One or more errors occurred. (Scheduler with name 'QuartzScheduler' already exists.)”
I have the complete and simplest examples and error messages

你好，我亲爱的Quartz.net组织。我在一个进程中的启动多个.netcore webhosts，quartz将会报错 ：
System.AggregateException:“One or more errors occurred. (Scheduler with name 'QuartzScheduler' already exists.)”
我有完整而简单的示例和错误信息

**Version used**

.net  :  .net8

Quartz.AspNetCore  :  3.8.1

**To Reproduce**

The simplest example, in the attachment, is very simple

附件中最简单的例子非常简单

**Expected behavior**

I hope to use Quarzt normally and run it normally without any errors in the demo program
Perhaps it's not necessarily necessary to release a new version of the quartz package, and even if we can provide a solution first, I would be happy to do so. I am willing to actively cooperate

我希望正常使用Quarzt能够在demo程序中不报错，正常运行
也许不一定是要发布新的quartz包版本，即使是能先提供解决方式也非常乐意，我愿意积极进行配合

**Additional context**
There are many demands for this, such as opening web API interfaces on the CS side and modularizing the web. I hope all the experts can see me and I will actively cooperate! I'm not very grateful! Long live Quartz.net!

这种需求挺多的，例如在cs端开webapi接口、web的模块化等，希望各位大佬能够看到我，我将积极配合！不甚感激！Quartz.net万岁！

**Comment by ccnetcore** [comment]
Example（示例）：
[JobDemo.zip](https://github.com/quartznet/quartznet/files/14627835/JobDemo.zip)

**Comment by lahma** [comment]
You need to have distinct names for each scheduler started in the same process.
