### ISSUE TITLE
DailyTimeIntervalScheduleBuilder.InTimeZone() not working when using AdoJobStore

### ISSUE THREAD

**Issue by dandufeu** [quartznet/quartznet#232]
It seems that when using AdoJobStore persistence, the DailyTimeIntervalSchedule InTimeZone() feature does not work as expected. After scheduling the job, the TimeZone of the trigger reverts back to the default time zone.

I did not find any posts online with a known issue or anyone else encountering this problem, which made me a little skeptical (also because I'm new to using Quartz.NET). However, looking at the latest source in [DailyTimeIntervalTriggerPersistenceDelegate.cs](https://github.com/quartznet/quartznet/blob/master/src/Quartz/Impl/AdoJobStore/DailyTimeIntervalTriggerPersistenceDelegate.cs) and [SimpleTriggerPersistenceDelegate.cs](https://github.com/quartznet/quartznet/blob/master/src/Quartz/Impl/AdoJobStore/SimpleTriggerPersistenceDelegate.cs), I don't see any handling for TimeZone as there exists for Cron triggers, and I believe this is where the problem lies.

Here is a sample code snippet. The intent is to run a job every X minutes during business hours (in another time zone) on a specific day of the week.

```C#
ITrigger trigger = TriggerBuilder.Create()
	.WithIdentity(triggerKey)
	.UsingJobData(jobData)
	.WithDailyTimeIntervalSchedule(
		x => x.WithIntervalInMinutes(repeatInterval)
			.StartingDailyAt(TimeOfDay.HourAndMinuteOfDay(startHour, startMinute))
			.EndingDailyAt(TimeOfDay.HourAndMinuteOfDay(endHour, endMinute))
			.OnDaysOfTheWeek(dayOfWeek)
			.InTimeZone(TZInfo)
		)
	.ForJob(MyJob)
	.Build();

Scheduler.ScheduleJob(trigger);

// Test the Timezone
IDailyTimeIntervalTrigger triggerTest = (DailyTimeIntervalTrigger)Scheduler.GetTrigger(triggerKey);
Debug.Assert(triggerTest.TimeZone.Id == TZInfo.Id);  
```

The assertion on the last line fails when using AdoJobStore persistence (more importantly, the expected fire times are not for the time zone selected). It all seems to work fine when **not** using AdoJobStore persistence.

If this can be verified as an issue, any suggestions for a good solution would be welcome.

**Comment by lahma** [comment]
This is actually a duplicate #136. This requires database schema changes to work.
