### ISSUE TITLE
Add possibility  on AdoJobStore to clear on startup

### ISSUE THREAD

**Issue by SvenIJK** [quartznet/quartznet#2329]
**Issue that I am having**
On startup, Quartz registers the jobs and triggers with DI integration, and it overwrites existing jobs and triggers with the same name.
But when I rename the job or trigger, it is added to the DB, and 2 jobs or triggers with the same values (except the name) are active.

**Desired solution**
A possibility to get the scheduler within the services.addQuartz call, to clear the scheduler before adding/overwriting new jobs/triggers.

**Additional context**
SO post [here](https://stackoverflow.com/questions/78345280/quartz-net-how-to-get-the-scheduler-using-di-integration-to-clear-the-scheduler) with a bounty of 100

**Comment by jafin** [comment]
One option would be to delete the existing job and add the new job

```c#
scheduler.DeleteJob(new JobKey("JobName1", "JobGroup1"));
```

I can't recall if Quartz has a rename job feature.  Curious how are you renaming the jobs now?

**Comment by SvenIJK** [comment]
Unfortunately that won't work, because I add everything with reflection at startup.
Within the Job class I added 2 props:

```c#
public JobKey JobKey => new JobKey("RemoveExpiredLocksJob");

public Action<ITriggerConfigurator> TriggerConfigurator => trigger => trigger
    .WithIdentity("RemoveExpiredLocksTrigger")
    .ForJob(JobKey)
    .StartNow()
    .WithCronSchedule("0 * * * * ?");
```

At startup, I get all the classes inheriting from IJob and get the 2 props to dynamicly add the jobs and triggers.
I don't use a rename function, it's just when I change the Jobname within the Jobkey, and let the scheduler add the same job again, it adds the job instead of overwriting, as it thinks it is a new one, because of the updated name.

**Comment by lahma** [comment]
Because DI container registration processor inherits from `XMLSchedulingDataProcessor` it could provide same kind of behavior for [pre-processing commands](https://github.com/quartznet/quartznet/blob/72fce9c599e020f4db0b0c77d277f9971d947a6f/src/Quartz/Xml/XMLSchedulingDataProcessor.cs#L233-L293) that are part of XML configuration.

**Comment by SvenIJK** [comment]
How cool that you respond to my thread Marko! Thanks for joining in!

It seems that those pre-processing commands require a name of a job/trigger to delete, but when a developer changes the name of a job/trigger, we don't want to manually specify the name of the old job/trigger that it has to delete first.

Isn't it just possible to call scheduler.clear somewhere? (it is yet unclear for me where exactly I can use these xml configurations)

**Comment by SvenIJK** [comment]
I found it! Getting the scheduler within the `AddQuartz` passing the properties, just initialized within the function like this:
```c#
services.AddQuartz(options =>
{
    options.InterruptJobsOnShutdown = false;
    options.InterruptJobsOnShutdownWithWait = true; // only when services.AddQuartzHostedService options.WaitForJobsToComplete is also true
    options.UsePersistentStore(s =>
    {
        s.UseProperties = true;
        s.UseSqlServer(sqlServer =>
        {
            sqlServer.ConnectionString = configuration["ConnectionString"];
            sqlServer.TablePrefix = "Qrtz_";
        });
        s.UseNewtonsoftJsonSerializer();
    });

    // Clear DB before adding the jobs and triggers
    ISchedulerFactory schedFact = new StdSchedulerFactory(options.Properties);
    IScheduler sched = schedFact.GetScheduler().Result;
    sched.Clear().Wait();

    if (assemblies?.Any() == true)
    {
        foreach (Assembly assembly in assemblies)
        {
            IEnumerable<Type> jobTypes = assembly.GetTypes().Where(t => t.GetInterfaces().Contains(typeof(IJobExtenstions)));

            foreach (Type jobType in jobTypes)
            {
                IJobExtenstions jobInstance = FormatterServices.GetUninitializedObject(jobType) as IJobExtenstions;
                options.AddJob(jobInstance.GetType(), jobInstance.JobKey);
                options.AddTrigger(jobInstance.TriggerConfigurator);
            }
        }
    };
});
```
