### ISSUE TITLE
AnnualCalendar SetDayExcluded does not update internal data structures if base calendar excludes date

### ISSUE THREAD

**Issue by tgeorge73** [quartznet/quartznet#233]
I was attempting to create an Annual Calendar from a WeekdayCalendar where Saturdays and Sundays are excluded.

After creating the annual calendar, I was adding more excluded days...  What I found was that if I added a day that falls on a Saturday or Sunday in that given year, the day is not added to the excludeDays array (because it is already 'excluded').  Therefore in subsequent years, this day (when not on an excluded weekday) would not be excluded as directed in the calendar setup...

I can see where, with the base calendar inheritance, it may be redundant at times to exclude a day already excluded by a base calendar (say an Annual calendar from an Annual Calendar or Monthly Calendar), but in this situation it does not appear to work.

I believe the simple fix is to change SetDayExcluded to always set the exclude flag as directed on that particular calendar regardless of the base calendars however I am not sure what the effect of this change would be on the library as a whole...

**Comment by lahma** [comment]
Thanks for reporting this - this was a valid concern, now fixed in master.
