### ISSUE TITLE
Initialization fails when Window's TCP/IP Media Sense is disabled ("Cannot run without an instance id" exception)

### ISSUE THREAD

**Issue by jeanfrancoisdesrosiers-eaton** [quartznet/quartznet#2336]
**Description**
Could be related to bug #503 for which the root cause seemed unknown.
When Window's TCP/IP Media Sense setting is disabled, an exception is raised at initialization. 
This setting is required to work with virtual IP addresses or connectionless messaging, for example, Windows Clustering, Database redundancy (such as Oracle), etc. See [https://docs.oracle.com/en/database/oracle/oracle-database/12.2/cwwin/disabling-windows-media-sensing.html]()

The raised exception is:
System.AggregateException: One or more errors occurred. ----> System.InvalidOperationException: Cannot run without an instance id.
Quartz.Impl.StdSchedulerFactory.<Instantiate>d__65.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Quartz.Impl.StdSchedulerFactory.<Instantiate>d__65.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Quartz.Impl.StdSchedulerFactory.<GetScheduler>d__69.MoveNext()

**Version used**
Any and all

**To Reproduce**
Stop your app or service containing Quartznet
Disable Media Sense by typing this command in an elevated Windows cmd prompt:
`netsh interface ipv4 set global dhcpmediasense=disable`

Verify the new setting for Dhcp Media Sense is in place by typing  
`netsh interface ipv4 show global`

Run your app/service.
Witness the exception.

Enable Media Sense by typing this command in an elevated Windows cmd prompt:
`netsh interface ipv4 set global dhcpmediasense=enable`

Verify new setting for Dhcp Media Sense is in place by typing  
`netsh interface ipv4 show global`

Run your app/service.
Witness it runs fine.

**Expected behavior**

An handling of different Windows behavior under this setting should be put in place, as this is a setting required to work with connectionless messaging and legitimately, albeit sporadically, used. It shouldn't cause an obscure crash. Or maybe the exception should be more explicit in this case.

**Comment by lahma** [comment]
Cannot easily reproduce, maybe you can submit a PR to propose a fix if you find out what's happening.
