### ISSUE TITLE
Website not rendering (quartz-scheduler.net)

### ISSUE THREAD

**Issue by Erijoda** [quartznet/quartznet#2344]
**Describe the bug**

Vuepress was updated to 2.0.0-rc.7 but the lockfile (package-lock.json) is referencing 2.0.0-rc.9.
This causes an error during build of docs while still producing distribution. The built file does not render documentation as seen on quartz-scheduler.net.

Was able to get an error-free build by rebuilding package-lock.json by deleting node_modules, deleting package-lock.json, and running npm i.

**Comment by lahma** [comment]
Thank you for reporting this, the website should be up and running again.
