### ISSUE TITLE
Upgrading from 3.3.3 to 3.8.1 resulted in error: communicating with remote scheduler

### ISSUE THREAD

**Issue by ndenkha** [quartznet/quartznet#2355]
**Describe the bug**

Our system has different components that use Quartz, some Windows Services, and some Web APIs. We've upgraded Quartz in the past and never had this issue, but this time we upgraded the Nuget package from version 3.3.3 to the latest 3.8.1, and when we released this build, different components using Quartz started erroring with this error during the deployment process

Quartz.SchedulerException: Error communicating with remote scheduler. ---> System.Runtime.Remoting.RemotingException: Server encountered an internal error. For more information, turn off customErrors in the server's .config file.

**Version used**

Version: 3.8.1

**To Reproduce**

No special coding, but have different components, e.g. an API and a Windows service, one running version 3.3.3 and one 3.8.1, and have them communicate with each other through the call

`scheduler.ScheduleJob(job.Trigger);`

**Expected behavior**

Different system components running different Quartz libraries should communicate and work fine with each other, it's shouldn't be required that all microservices or APIs be upgraded to the latest version all at the same time, that's impossible without bringing the entire system down.

**Additional context**

**Comment by lahma** [comment]
Feel free to investigate and submit an PR to improve interoperability between such version jumps, there's no capacity to test and validate such scenarios.

**Comment by ndenkha** [comment]
I'll try to find time to do so, thanks.
