### ISSUE TITLE
Incorrect multiplication factor in DailyTimeIntervalScheduleBuilder.EndingDailyAfterCount()

### ISSUE THREAD

**Issue by intexx** [quartznet/quartznet#236]
On [line #396](https://github.com/quartznet/quartznet/blob/master/src/Quartz/DailyTimeIntervalScheduleBuilder.cs#L396) the equation is currently:
  `intervalInMillis = TimeSpan.FromSeconds(interval * 60 * 24);`
It should instead be:
  `intervalInMillis = TimeSpan.FromSeconds(interval * 60 * 60);`.

**Comment by lahma** [comment]
Thanks for reporting this, now fixed in master.

**Comment by intexx** [comment]
You're welcome, keep up the good work  :-)
