### ISSUE TITLE
.net core 6 adding QuartzOptions from appsettings.json is not reflected in scheduler properties and compile error for UseXmlSchedulingDataProcessor

### ISSUE THREAD

**Issue by MNirmala** [quartznet/quartznet#2390]
**Describe the bug**
.net Core 6 adding QuartzOptions in program.cs does not add the details to scheduler
calling UseXmlSchedulingDataProcessor in AddQuartz in program gives compilation error
Don't see the quartzsettings
**Version used**
.net core 6
With which version did you encounter this behavior.

**To Reproduce**

Ideally code samples or event unit test.

**Expected behavior**

**Additional context**

**Comment by lahma** [comment]
There's a working example here: https://github.com/quartznet/quartznet/tree/3.x/src/Quartz.Examples.AspNetCore

**Comment by MNirmala** [comment]
Thanks Marko.
I am in the process of migrating Quartz from .net framework to .net core.
We used XMLSchedulingDataProcessorPlugin
How do we use the same in .net core

**Comment by lahma** [comment]
If it isn't too much trouble for you, maybe you could check the sample I linked?
