### ISSUE TITLE
Set MisfireInstruction.IgnoreMisfirePolicy globally

### ISSUE THREAD

**Issue by abdielcs** [quartznet/quartznet#2395]
As far as I can see, there is no direct way to set MisfireInstruction.IgnoreMisfirePolicy for all triggers. It must be done individually in the schedule, depending on whether it's a SimpleTrigger or CronTrigger.
I managed to do it in this way:
```
var trigger = triggerBuilder.Build();
if (trigger is AbstractTrigger)
{
      (trigger as AbstractTrigger).MisfireInstruction = MisfireInstruction.IgnoreMisfirePolicy;
}
await scheduler.ScheduleJob(job, trigger);
```
I'd like to know your opinion on this workaround and whether you think it's appropriate to create a global configuration for this option.

**Comment by lahma** [comment]
Explicitly stating the misfire policy for each configuration feels like the way to go. Changing global defaults can be misleading and cause hard to understand problems when behavior differs from expected.
