### ISSUE TITLE
NativeJob crashes when workingDirectory parameter is missing

### ISSUE THREAD

**Issue by viebrix** [quartznet/quartznet#2405]
After Upgrading Quartz.NET, I have the issue that in NativeJob the handling of workingDirectory is not the same as before.

In older versions providing a workingDirectory wasn't needed. It was an optional parameter.
Now with version 3.9.0 NativeJob breaks with an exception: 
`Quartz.SchedulerException: Job threw an unhandled exception. ---> System.Collections.Generic.KeyNotFoundException: Key workingDirectory not found`

I suspect, that this line in [NativeJob.cs](https://github.com/quartznet/quartznet/blob/b9ea62626c5581ee5402c733ab61630fe75fc894/src/Quartz.Jobs/Job/NativeJob.cs#L83) produces the error.
`        var workingDirectory = data.GetString(PropertyWorkingDirectory);`
In older versions GetString behaved in another way. Null values in GetString were no problem. Now it seems to break something. See also https://github.com/quartznet/quartznet/pull/2125 

This [line of code](https://github.com/quartznet/quartznet/blob/b9ea62626c5581ee5402c733ab61630fe75fc894/src/Quartz.Jobs/Job/NativeJob.cs#L140)  with string? seems to show that null values are allowed and it is intended to skip the workingDirectory parameter:
`private int RunNativeCommand(string command, string parameters, string? workingDirectory, bool wait, bool consumeStreams)`

Thank you in advance for investigating.

**Comment by viebrix** [comment]
https://github.com/quartznet/quartznet/pull/2406

**Comment by lahma** [comment]
Fixed in 3.x, main does not suffer from this.
