### ISSUE TITLE
Use CommonServiceLocator for Dependency Resolution in StdSchedulerFactory

### ISSUE THREAD

**Issue by crmckenzie** [quartznet/quartznet#241]
Quartz is currently only really architected to DI jobs. This is my first time using Quartz and the first thing I wanted to do failed: DI a JobListener. If you used CommonServiceLocator to instantiate types (you could move your ObjectUtils behind an implementation of that interface), I could replace the ServiceLocator with Ninject, or Castle, or whatever and the library wouldn't care.

I can submit a PR if you would like.

**Comment by lahma** [comment]
Sure a PR is always welcome for review. I think this should be done against quartznet-3 branch as this is quite big change.

What a bout using a minimal interface introduced by Quartz so we wouldn't need yet another lib dependency?

**Comment by lahma** [comment]
I'm closing this for now, I would not want to introduce dependency library so I'll leave this support for outside libraries/job factories.
