### ISSUE TITLE
BlobTriggers do not serialize NextFireTime, resulting in them never firing

### ISSUE THREAD

**Issue by ewortzman** [quartznet/quartznet#2426]
**Describe the bug**

Attempting to convert from Quartz2 binary serialization to Quartz3 JSON serialization using the serializer linked [here](https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/system-text-json.html#migrating-from-binary-serialization). When a Blob Trigger is serialized using the JSON serializer, the `nextFireTime` value is not included, resulting in this value not being loaded and the [trigger never firing](https://github.com/quartznet/quartznet/blob/main/src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs#L2757-L2766), since, for Blob Triggers, the value in the QRTZ_TRIGGERS table does not overwrite the serialized value in the QRTZ_BLOB_TRIGGERS table when `Delegate.SelectTrigger` is [called](https://github.com/quartznet/quartznet/blob/main/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Triggers.cs#L708-L718)

**Version used**

3.10

**To Reproduce**

Create a blob trigger, and write it to the database using JSON Serialization

**Expected behavior**

The trigger should fire

**Additional context**

I don't know if blob triggers are no longer supported, or if they are and simply do not work as expected.

**Comment by lahma** [comment]
This should now be fixed, for custom trigger types having more properties you need to register custom converter(s).

**Comment by ewortzman** [comment]
this issue does not appear to be resolved.  Using the latest release (3.11) I am still noticing the same behavior.  NextFireTime does not get serialized to the database, and the Quartz_Triggers table is not consulted for Blob triggers, and therefore blob triggers never fire.

**Comment by lahma** [comment]
Can you show a failing test case or a repository showing example code demonstrating the problem?

**Comment by ewortzman** [comment]
Sure. I'll put something together when I have some time.

**Comment by ewortzman** [comment]
put together this sample repo: https://github.com/ewortzman/quartz-blob-bug

very straightforward example of the bug.  When you run the code, it immediately begins returning a warning stating 

```
warn: Quartz.Impl.AdoJobStore.JobStoreTX[0]
      Trigger mygroup.myTrigger returned null on nextFireTime and yet still exists in DB!
```

Which aligns with what we would expect given the bug: the blob trigger is deserialized and the QRTZ_TRIGGERS table is not consulted to retrieve the NextFireTime, so Quartz thinks the trigger shouldn't fire and ignores it.

I attempted to manually resolve the issue by [forcing serialization of NextFireTimeUtc](https://github.com/ewortzman/quartz-blob-bug/compare/fix-attempt?expand=1#diff-d48e55bfd13174b18d78f369e7cb80237503c8b4fa00a43845717d6d797a321eR9-R25), but this is clunky and not something I should have to do in every subclass I implement.

**Comment by lahma** [comment]
So you linked to `System.Text.Json` documentation in the original issue description and your sample is `Newtonsoft`. Which one is it?

**Comment by ewortzman** [comment]
I'm using newtonsoft.  The issue predates the STJ implementation.  The docs I linked were updated with STJ documentation after I posted this issue.

**Comment by ewortzman** [comment]
but I don't think the bug is, strictly speaking, relevant to the serialization framework used.  I think the proper approach would be, regardless of whether we have a blob trigger or not, to always join the trigger to the QRTZ_TRIGGERS table and use that value for NextFireTime.  Have a single source of truth for NextFireTime in the database (the QRTZ_TRIGGERS table).

**Comment by lahma** [comment]
> I'm using newtonsoft. The issue predates the STJ implementation. The docs I linked were updated with STJ documentation after I posted this issue.

Well if the URL has STJ it's been STJ only documentation... It seems that we probably fixed and ensured the proper behavior under wrong library then.

**Comment by lahma** [comment]
Let's reopen and see if there's something more we can do then.

**Comment by ewortzman** [comment]
> > I'm using newtonsoft. The issue predates the STJ implementation. The docs I linked were updated with STJ documentation after I posted this issue.
> 
> Well if the URL has STJ it's been STJ only documentation... It seems that we probably fixed and ensured the proper behavior under wrong library then.

huh.  ok, my mistake.  apologies.

I think there once was documentation that only had one serialization section and I didn't notice that it had changed.

**Comment by lahma** [comment]
Is the STJ based serializer something that you could experiment with? That would be the way go forward anyway.

**Comment by ewortzman** [comment]
I can give it a try. In the mean time I think I've mainly worked around my issue via the manual fix mentioned above. I'll let you know when I have a chance to try STJ

**Comment by lahma** [comment]
I've tested a bit more and yes, this needs some configuration options that would allow you to inject custom serializers for triggers that are not of the "supported types".

**Comment by lahma** [comment]
#2480 was merged to 3.x maintenance which should make it relatively easy to create custom trigger serialization handlers.

**Comment by ewortzman** [comment]
Hello. 

Sorry to come back to such an old issue.  I was moved off our Quartz-related project to a different project for a few months and am just now coming back to it.

I've upgraded my [sample code](https://github.com/ewortzman/quartz-blob-bug) to the latest stable version, 3.13.1, and still experience the same issue.  Is the recommendation that all custom trigger classes will require custom serializers? That seems clunky. 

I'll give STJ a shot, as mentioned last summer, and see what happens, but I think it will likely cause the same issue.  My recommendation is that Blob triggers should be joined to the QUARTZ_TRIGGERS table in order to get the next fire time from that table, rather than requiring that it be serialized.

**Comment by lahma** [comment]
Custom trigger types sounds like a very small domain. I wouldn't expect that projects would need to ever implement more than one or two types, custom triggers are a rare case.

If you have ideas for a PR that is backwards compatible and doesn't require database schema changes I'm all ears.

**Comment by ewortzman** [comment]
Fair enough.  We use them extensively (though not sure we should), perhaps because we have some antiquated logic around the timing of certain types of jobs. I don't expect you to devote a significant amount of time on an uncommon use case.  If I can fix it with a PR I will, but we'll see what my time brings.

Thanks.
