### ISSUE TITLE
Add support for DbDataSource

### ISSUE THREAD

**Issue by Hawxy** [quartznet/quartznet#2436]
The ecosystem trend for database connection management is to use the recently added `*DbDataSource` to manage the connection pool between all application dependencies. 

A common example is a user using `Npgsql.DependencyInjection` to add a `NpgsqlDataSource` to the DI container, which Quartz could resolve as a generic `DbDataSource`. It'd be great if Quartz supported this.

**Comment by lahma** [comment]
Can you help out with a PR?

**Comment by Hawxy** [comment]
I'll see what I can do.
