### ISSUE TITLE
Quartz Blocks Program Exit Without Being Started

### ISSUE THREAD

**Issue by jamarchist** [quartznet/quartznet#246]
This blocks
```
class Program
{
    private static void Main(string[] args)
    {
        var quartz = StdSchedulerFactory.GetDefaultScheduler();
    }
}
```

while this doesn't
```
class Program
{
    private static void Main(string[] args)
    {
        var quartz = StdSchedulerFactory.GetDefaultScheduler();
        quartz.Shutdown();
    }
}
```

It doesn't make sense that you should have to Shutdown something you never Started.

**Comment by lahma** [comment]
So is this a real use case scenario that you want to create scheduler without using it? You can always construct scheduler factory with property "quartz.scheduler.makeSchedulerThreadDaemon" set to true. Then your program will exit before everything is properly cleaned (if that is what you really want).

**Comment by jamarchist** [comment]
I'm sure it's not a very common case. I had an app that could be used in one of two modes:
* execute a single task specified by a command line argument
* begin scheduling and executing a series of tasks (and run indefinitely; in this case, it was installed as a windows service)

I was creating a container, including registering an instance of ```IScheduler``` created with ```StdSchedulerFactory.GetDefaultScheduler```, before determining which mode the app would run in, so if you ran it in single task mode it would hang at the end even though quartz hadn't been needed at all. It was easily solved by moving the ```IScheduler``` registration to a point after determining that the mode it was running in needed quartz (or could have been solved with a different registration approach, now that I think about it). But I thought it was strange that what quartz really wanted me to do was Shutdown in a branch of my application that had never called Start.

If the 'makeSchedulerThreadDaemon' approach is the solution, that works for me. It wasn't apparent to me from the documentation (though I didn't read about all of the different scheduler factory options; my bad).

Also, FWIW to anyone else who may read this, I'm using Autofac and TopShelf, but *not* using either of the Quartz integration libraries for those.
