### ISSUE TITLE
Deadlock on StdSchedulerFactory.GetScheduler() when performSchemaValidation is on with Npgsql

### ISSUE THREAD

**Issue by Julie-BC** [quartznet/quartznet#2468]
**Describe the bug**

Since the schema validation implementation, I've got a deadlock on the StdSchedulerFactory.GetScheduler() call if "quartz.jobStore.performSchemaValidation" is set to true (default value).

**Version used**

I've tried all versions from the 3.5.0 to the last one.
I didn't have this issue on the 3.4.0

**To Reproduce**

I don't know if it is sufficient to reproduce but I've got this configuration : 
```json
    "Quartz": {
        "quartz.jobStore.type": "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
        "quartz.jobStore.driverDelegateType": "Quartz.Impl.AdoJobStore.PostgreSQLDelegate, Quartz",
        "quartz.jobStore.tablePrefix": "QUARTZ.QRTZ_",
        "quartz.jobStore.dataSource": "ModuleConsoleScheduler",
        "quartz.jobStore.lockHandler.type": "Quartz.Impl.AdoJobStore.StdRowLockSemaphore, Quartz",
        "quartz.serializer.type": "newtonsoft",
        "quartz.dataSource.ModuleConsoleScheduler.connectionString": "myconnectionstring",
        "quartz.dataSource.ModuleConsoleScheduler.provider": "Npgsql"
    }
```
I've tried to run the [PostrgreSQL script](https://github.com/quartznet/quartznet/blob/4428ec9b581959d421508fdd125bbc1d5c62d8b7/database/tables/tables_postgres.sql) to create the tables, but got same issue : a task keeps waiting on this stack 
![image](https://github.com/user-attachments/assets/2a49ec65-d982-4e2d-b9d3-8f3af3eae7c8)

**Expected behavior**

The expected behavior is that it just work like it work when the schema verification is off. Or at least, it produce some error, or a timeout.

**Additional context**

I use the npgsql 7.0.7 package and Postgre 14

**Comment by lahma** [comment]
This feels to be quite unique problem to your setup as Quartz is being tested with schema validation on against Postgres and there must *many* installations of Quartz in the world with this validation on and working.

**Comment by Julie-BC** [comment]
That's right, this issue actually came from our usage. Sorry. I close it.
