### ISSUE TITLE
.Net 4.0 build requires .Net Framework 4.5

### ISSUE THREAD

**Issue by chrish619** [quartznet/quartznet#247]
Due to linking difference between .Net Framework 4.0 & .Net Framework 4.5 for ExtensionAttribute (assembly mscorlib)

The .Net 4.0 build requires .Net 4.5 to be installed on the running machine.
For my instance, I have downgraded to the .Net 2.0/.Net 3.5 which runs fine.

This only becomes an obstacle on WinServer 2003 or similar (otherwise I would upgrade to .net 4.5)

**Comment by lahma** [comment]
With which version? The latest release should have fixed past issues.

**Comment by chrish619** [comment]
This ocurred in v2.2.4

Will upgrade to v2.3.1, and re-test

**Comment by lahma** [comment]
Closing for now, please add comments if problem persists.
