### ISSUE TITLE
API Documentation Page Not Found

### ISSUE THREAD

**Issue by ahaleiii** [quartznet/quartznet#2478]
Attempting to navigate to the [API Documentation](https://quartznet.sourceforge.io/apidoc/3.0/html) page results in a 404 description page.

![image](https://github.com/user-attachments/assets/c95eca90-db0a-40cc-8857-c62c2eacdd54)

This link can be found:
- In the current [README](https://github.com/quartznet/quartznet/blob/8ce7d902a9f2691f12deffb3f755dd83306598a1/README.md?plain=1#L32)
- On the [Quartz documentation site](https://www.quartz-scheduler.net/documentation/quartz-3.x/quick-start.html) in the list of content with the title `API Documentation`

All versions appear to be broken:
- <https://quartznet.sourceforge.io/apidoc/3.0/html>
- <https://quartznet.sourceforge.io/apidoc/2.0/html>
- <https://quartznet.sourceforge.io/apidoc/1.0/html>

**Comment by lahma** [comment]
Thanks for reporting. Sourceforge had messed something up and I had to copy documentation back to its original place. I've now refreshed 3.x documentation with fresh look and also v4 API documentation has been generated for the first time.
