### ISSUE TITLE
Support multiple CronExpression in one string

### ISSUE THREAD

**Issue by monsieurleberre** [quartznet/quartznet#252]
Hello, 

For my personal needs, I have implemented scheduling a job on multiple CronTriggers, by passing them in a single string like this :
"0 0 03-07 ? \* MON-FRI | 0 35/15 07 ? \* MON-FRI | 0 05/15 08-14 ? \* MON-FRI | 0 0/10 15-16 ? \* MON-FRI | 0 05/15 17-23 ? \* MON-FRI"
On this example, 
- from 3am to 7am the job starts every hour
- then at 7am it starts at 7:35 and triggers every 15mn, so 7:35 and 7:50
- then from 8 to 14 starts at 5, 20, 35 and 50 past the hour
- etc...

Ideally I would like to push this logic out of my code and be able to pass this kind of strings directly to the Quartz schedulers, which would then schedule the jobs accordingly.

Is that something you think is worth doing? I have not yet contributed to the Quartz scheduler project, and have no clue how involved that change could be. Is anyone able to tell me if I would be embarking in a 5 month development trying to do it?

Thanks for your answers.

**Comment by lahma** [comment]
Thank you for your interest in the project! I'm unsure about the value proposition. This sounds like same as below code that is quite use case specific:

    string input = "0 0 03-07 ? * MON-FRI | 0 35/15 07 ? * MON-FRI | 0 05/15 08-14 ? * MON-FRI | 0 0/10 15-16 ? * MON-FRI | 0 05/15 17-23 ? * MON-FRI"";
    var job = JobBuilder.Create<NoOpJob>().Build();
    var crontTriggers = input.Split('|').Select(x => x.Trim()).Select(cronExpression => TriggerBuilder.Create().WithCronSchedule(cronExpression).Build());
    scheduler.ScheduleJob(job, new HashSet<ITrigger>(crontTriggers), replace: false);

As being so specific I'm afraid we shouldn't change the scheduler interface for this. Maybe you can have an extension method on your project's side that adds functionality to IScheduler?

**Comment by haydenhancock** [comment]
Are you sure this works the same for Quartz 3.0.7? The ScheduleJob task doesn't take a collection of triggers? 

This would be helpful to have because if you want to create triggers provided by configuration. For example, I want to control the triggers from a settings files instead of hard-coding this.
