### ISSUE TITLE
Not all exceptions are logged

### ISSUE THREAD

**Issue by Olivercomputing** [quartznet/quartznet#253]
I am trying to track down debuggable information on an exception being thrown at startup: Failure occurred during job recovery.

I do not see this exception being logged in any way. Should it be? Is the Quartz code designed to log all exceptions? (if not, it should) Or is there something I'm missing?

**Comment by lahma** [comment]
The exceptions usually flow through back to upper layers and Common.Logging is then utilized to write them. You need to have Common.Logging configured to delegate to log4net or NLog or similar to get anything written to files etc.
