### ISSUE TITLE
Self-rescheduling example doesn't work

### ISSUE THREAD

**Issue by IGx89** [quartznet/quartznet#2557]
**Describe the bug**

Hello! I used the code shown under the "Self-Rescheduling" section in the docs (https://www.quartz-scheduler.net/documentation/quartz-3.x/how-tos/rescheduling-jobs.html#self-rescheduling) to set up rescheduling for my job if an issue occurs. It's throwing an exception when run:

```
Quartz.JobExecutionException: Failed to execute Job 'DEFAULT.ReportingNightly' of type 'MyApp.Jobs.ReportingNightlyJob' ---> Quartz.SchedulerException: Trigger's related Job's name cannot be null
   at Quartz.Impl.Triggers.AbstractTrigger.Validate()
   at Quartz.Impl.Triggers.SimpleTriggerImpl.Validate()
   at Quartz.Core.QuartzScheduler.<ScheduleJob>d__83.MoveNext()
```

It appears to be due to the self-rescheduling code example being incorrect, not setting the job. How should that be done?

**Version used**

3.12.0

**To Reproduce**

```csharp
public async Task Execute(IJobExecutionContext context)
{
    // something happens, that tells you to delay the processing
    // like getting an HTTP 429 - Too Many requests
    var oldTrigger = context.Trigger;
    var newTrigger = TriggerBuilder.Create()
        .WithIdentity($"{oldTrigger.Key.Name}-retry", oldTrigger.Key.Group)
        .StartAt(DateTimeOffset.UtcNow.AddMinutes(5))
        .Build();
    await context.Scheduler.ScheduleJob(newTrigger);
}
```

**Expected behavior**

Job re-runs in 5 minutes.

**Additional context**

**Comment by lahma** [comment]
If it's only missing configuration line `.ForJob(context.JobDetail)` maybe you could create a PR to fix the issue after you've checked whether it works then? Each page has [Help us by improving this page](https://github.com/quartznet/quartznet/edit/main/docs/documentation/quartz-3.x/how-tos/rescheduling-jobs.md) link.

**Comment by IGx89** [comment]
Sure! I can test if that is indeed the proper solution, and if it fixes it then I can submit a PR.
