### ISSUE TITLE
Professional support for Quartz.net?

### ISSUE THREAD

**Issue by Olivercomputing** [quartznet/quartznet#257]
Are any individuals or organizations offering professional support for Quartz.net?

**Comment by Olivercomputing** [comment]
Hmm, after 2 weeks with no answer, it appears that this answers itself. Evidently, there is not.

**Comment by lahma** [comment]
Sorry for the delay. This was left in TODO box for too long for various reasons.

If with professional you mean commercial, no, I'm not aware of organizations or individuals that offer support with fixed SLAs.

However, we have a mailing list where you can reach other users and share questions and answers: https://groups.google.com/group/quartznet/ .

The mailing list is best place to ask questions and guidance and in case of bugs or feature requests these GitHub issues are preferred.

**Comment by Olivercomputing** [comment]
Thank you for answering. I'll use the mailing list in the future for non-development questions.

Are you potentially available for sporadic paid support?

**Comment by lahma** [comment]
I cannot give no promises on paid support, mostly because of time constraints. Honestly I hope that possible problems could be solved together with the community. New feature development is another story of course because that could need a non-trivial development effort.
