### ISSUE TITLE
Some Cron expression examples are invalid

### ISSUE THREAD

**Issue by reduckted** [quartznet/quartznet#2583]
**Describe the bug**

Some of the example Cron expressions in the documentation are not valid.

https://github.com/quartznet/quartznet/blob/5b7efa00e44b1bab908385bfaba1fabb8b419f1b/docs/documentation/quartz-3.x/how-tos/crontrigger.md#L75-L96

**Version used**

`3.13.0`

**To Reproduce**

```cs
Console.WriteLine("| Expression | `ValidateExpression` result |");
Console.WriteLine("|---|---|");

foreach (var expression in new string[] {
    "0 0 12 ** ?",
    "0 15 10 ? **",
    "0 15 10 ** ?",
    "0 15 10 ** ? *",
    "0 15 10 ** ? 2005",
    "0 *14* * ?",
    "0 0/5 14 ** ?",
    "0 0/5 14,18 ** ?",
    "0 0-5 14 ** ?",
    "0 10,44 14 ? 3 WED",
    "0 15 10 ? * MON-FRI",
    "0 15 10 15 * ?",
    "0 15 10 L * ?",
    "0 15 10 L-2 * ?",
    "0 15 10 ? * 6L",
    "0 15 10 ? * 6L",
    "0 15 10 ? * 6L 2002-2005",
    "0 15 10 ? * 6#3",
    "0 0 12 1/5 * ?",
    "0 11 11 11 11 ?"
}) {
    Console.Write("| `" + expression + "` |");

    try {
        CronExpression.ValidateExpression(expression);
        Console.WriteLine("valid |");
    } catch (Exception ex) {
        Console.WriteLine(ex.Message + " |");
    }
}
```

Output is:
| Expression | `ValidateExpression` result |
|---|---|
| `0 0 12 ** ?` |Illegal characters after asterisk: ** |
| `0 15 10 ? **` |Illegal characters after asterisk: ** |
| `0 15 10 ** ?` |Illegal characters after asterisk: ** |
| `0 15 10 ** ? *` |Illegal characters after asterisk: ** |
| `0 15 10 ** ? 2005` |Illegal characters after asterisk: ** |
| `0 *14* * ?` |Illegal characters after asterisk: *14* |
| `0 0/5 14 ** ?` |Illegal characters after asterisk: ** |
| `0 0/5 14,18 ** ?` |Illegal characters after asterisk: ** |
| `0 0-5 14 ** ?` |Illegal characters after asterisk: ** |
| `0 10,44 14 ? 3 WED` |valid |
| `0 15 10 ? * MON-FRI` |valid |
| `0 15 10 15 * ?` |valid |
| `0 15 10 L * ?` |valid |
| `0 15 10 L-2 * ?` |valid |
| `0 15 10 ? * 6L` |valid |
| `0 15 10 ? * 6L` |valid |
| `0 15 10 ? * 6L 2002-2005` |valid |
| `0 15 10 ? * 6#3` |valid |
| `0 0 12 1/5 * ?` |valid |
| `0 11 11 11 11 ?` |valid |

**Expected behavior**

All example Cron expressions should be valid.

**Additional context**
Putting a space around the `*` in the invalid expressions makes them valid. I assume it's just a typo in the docs and that `**` and `*14*` is not meant to be valid.

**Comment by jafin** [comment]
Thanks my fault, looks like 3e2a857f running lintfix broke it...    I'll try and organise a fix PR soon.
