### ISSUE TITLE
Invalid cron expression: 0 0-45/5 9 * * ?

### ISSUE THREAD

**Issue by ramyomar** [quartznet/quartznet#259]
I want to trigger a job every five minutes from 9:00 to 9:45. What's wrong with `0 0-45/5 9 * * ?`? I get the following error:

    The value '0 0-45/5 9 * * ?' is invalid according to its datatype

I use XML configuration. My `<trigger>` is of type `<cron>`

**Comment by lahma** [comment]
The problem is that the CRON validation rules with XML schema have its limits. You should be able to use expression like this if you use programmatic configuration.

**Comment by ramyomar** [comment]
That's good to know. Thank you. I worked around it by getting rid of the incremental operator and I specified the minutes I want in a comma separated list i.e. 0,5,10,15...etc.

**Comment by lahma** [comment]
OK, good to hear, sorry for the inconvenience.
