### ISSUE TITLE
Implement IReadOnlyDictionary for DirtyFlagMap

### ISSUE THREAD

**Issue by perringaiden** [quartznet/quartznet#2596]
**Is your feature request related to a problem? Please describe.**
`System.Collections.Generic.CollectionExtensions.GetValueOrDefault` cannot be used on `DirtyFlagMap` or `JobDataMap`, because it only implements `IDictionary`.

**Describe the solution you'd like**
Implement `IReadOnlyDictionary` in `DirtyFlagMap`.

**Describe alternatives you've considered**
Older methods of retrieving values such as `TryGetValue` or using `AsReadOnly` work, but would be easier if the stock extensions worked directly.

**Comment by lahma** [comment]
Would you like to send a PR against 3.x branch?

**Comment by lahma** [comment]
Now in both `3.x` and `main` branches.
