### ISSUE TITLE
[Question] Trigger broadcast

### ISSUE THREAD

**Issue by zabulus** [quartznet/quartznet#2597]
**Is your feature request related to a problem? Please describe.**
We're using Quartz in clustered environment and we would like to use it in broadcast scenario. Job triggered on one node is executed on all other nodes. In opposite to current behavior where job is executed on one node.

**Describe the solution you'd like**
**Describe alternatives you've considered**
I see here several alternatives:
1. Trigger pinning. During triggering explicitly specify node where job will execute. We have a membership mechanism, so it's possible just specify list of nodes to trigger job at.
2. Explicit broadcast. During trigger in cluster mode somehow specify that this should be executed on all nodes and forward responsibility to Quartz to figure everything itself.
3. Another option comes to my mind is distributed ISchedulerListener. Currently only listeners on the same node receive information about scheduling of a job. If other nodes could receive events about a job was triggered, they might trigger job on theirs side as well.

Currently we'll implement custom notification mechanism over tcp channel to trigger jobs, but this is something we would like to avoid.

**Comment by lahma** [comment]
Sounds like a cool idea, but first thing that comes to my mind is the problem of knowing what are "all nodes". Nodes are dynamic and during broadcast there might be new appearing and some disappearing, of course that would be quite highly unlike case but broadcast sounds like something that might happen often. 

Would a messaging solution with publish-subscribe work better in this case?
