### ISSUE TITLE
Cron expression is a bit complex

### ISSUE THREAD

**Issue by zeusro** [quartznet/quartznet#262]
Create like this

     .WithCronSchedule("0 30 10-13 ? * WED")

is not friendly and hard to understand.
Why Not creating like this:

     .WithCronSchedule(int repeatCount,Timespan timespan,list<DayOfWeek> l,list<short> monthOfYear,list<short> year)

what I suggest is just a demo.  I wish it could help you.

**Comment by lahma** [comment]
Have a look at CronSchedulerBuilder, it has various static methods to create schedules without using string presentation directly, like:

    AtHourAndMinuteOnGivenDaysOfWeek(int hour, int minute, params DayOfWeek[] daysOfWeek)

**Comment by zeusro** [comment]
Oh,thank you very much! I just  learnt it from the website and I didn't see that method

http://www.quartz-scheduler.net/documentation/quartz-2.x/tutorial/index.html
