### ISSUE TITLE
Support generic job types with AdoJobStore

### ISSUE THREAD

**Issue by julianoappelklein** [quartznet/quartznet#266]
The function GetStorableJobTypeName (in Quartz.Impl.AdoJobStore.StdAdoDelegate) is not generationg a valid class name for generic types.
Below, the code, with a possible solution.

        protected virtual string GetStorableJobTypeName(Type jobType)
            {
            if (jobType.AssemblyQualifiedName == null)
            {
                throw new ArgumentException("Cannot determine job type name when type's AssemblyQualifiedName is null");
            }

            int idx = jobType.AssemblyQualifiedName.IndexOf(',');
            // find next
            idx = jobType.AssemblyQualifiedName.IndexOf(',', idx + 1);

            string retValue = jobType.AssemblyQualifiedName.Substring(0, idx);

            if (jobType.IsGenericType) //fix for generic types
            {
                retValue = string.Concat(retValue, "]]");
            }

            return retValue;
        }

**Comment by kjgorman** [comment]
Hey @julianoappelklein I also just found this issue today... With some googling I found this thread on the mailing list from a few years ago: https://groups.google.com/forum/#!msg/quartznet/RfGM_omHma8/3kNRxzuk3IsJ where @lahma basically says generic jobs are not supported :sob:

But, I think at the very least a clause like

```csharp
if (jobType.IsGenericType)
{
    throw new ArgumentException("A job type may not be generic"); // or whatever
}
```

should be added, as the current exception (an argument exception in `System.RuntimeTypeHandle.GetTypeByName`...) is not very helpful, and only occurs after you try and fetch the job with an invalid type name.

**Comment by lahma** [comment]
Couldn't figure out a good reason any more not to support generic job type so it's now supported :)

**Comment by julianoappelklein** [comment]
Very nice!
