### ISSUE TITLE
UseProperties does not work as expected (IMHO)

### ISSUE THREAD

**Issue by mcliment** [quartznet/quartznet#268]
According to the documentation:

> The "quartz.jobStore.useProperties" config parameter can be set to "true" (defaults to false) in order to instruct AdoJobStore that all values in JobDataMaps will be strings, and therefore can be stored as name-value pairs, rather than storing more complex objects in their serialized form in the BLOB column. This is much safer in the long term, as you avoid the class versioning issues that there are with serializing your non-String classes into a BLOB.

In the case of Quartz.NET, the difference is basically that if `useProperties` is `false` (default) a `JobDataMap`is binary serialized into the blob fields.

On the other hand, setting `useProperties` to `true` serializes a `NameValueCollection` which is more convenient (depends on .NET core version and not on Quartz version) but I'd have expected some kind of string serialization, more readable and more compact than `BinaryFormatter` result.

For the record, I've tested this scenario with the Java counterpart and the data persisted when using `useProperties` to `true` was:

```
#
#Wed Jun 03 13:57:42 CEST 2015
Hello=World
```

Which actually is the desirable behavior (I don't think the date is needed, anyway).

What do you think?

**Comment by Jawvig** [comment]
Whilst I think a green fields implementation should probably do something human readable, I don't see how a change could be made easily now with existing users and data. If a new version of JobDataMap were to be implemented, I'd much rather it allowed my own .NET type to be passed (maybe a generic IJob interface) and that this would serialize to the DB as JSON via the Newtonsoft library. But this is in wishlist territory!

**Comment by mcliment** [comment]
Ok, seems fair.

Right now, this can be solved using a custom `IObjectSerializer`. This way doesn't add a dependency on any external JSON library and serialization is up to the user.

If I can help somehow, just tell me.

**Comment by lahma** [comment]
This might be something to have in v3 with some additional config switch that would use DataContractJsonSerializer .

**Comment by lahma** [comment]
Since v3 alpha there's been ability to use Json.NET as serializer. It's still byte version in db but we might need a separate issue for string-based storage (and type info in db to help round-tripping). And a PR would be even more awesome.
