### ISSUE TITLE
How to determine if a particular job is currently executing

### ISSUE THREAD

**Issue by christianarg** [quartznet/quartznet#274]
Hi,

I haven't found how to determine if a particular job is currently executing on the documentation. 

One of my devs queried [QRTZ_FIRED_TRIGGERS] by JOB_NAME (and trigger name depending the case). This gets the job done but it doesn't look very nice.

Is there a proper way of doing it using the Quartz API?

Edit: We use cluster mode so, I understand that we can't use Scheduler.GetCurrentlyExecutingJobs 

Thanks

**Comment by lahma** [comment]
Currently there is no API support for this, so querying the table is the (brittle) way to go for now.
