### ISSUE TITLE
Memory Leak with Quartz 2.2.1 implementation of CronTrigger

### ISSUE THREAD

**Issue by mail2ikhan** [quartznet/quartznet#275]
I can see in java heap dump, QuartzScheduler keeps on adding JobExecutionContext instances of all the past executions in a HashMap. List keeps on adding tens of thousands of JobExecutionContext instances which is leading to out of memory issue. These old instances are not required at all.  Every JobExecutionContext instance keep a new instance of Job that make the situation worse. Here is the sample code to replicate the issue : - 
public class HelloJob implements Job
{
public void execute(JobExecutionContext context1)
throws JobExecutionException {
System.out.println("Hello Quartz! 123");

SchedulerRepository repo = SchedulerRepository.getInstance();
for(Scheduler scheduler : repo.lookupAll()) {
try {
System.out.println(scheduler.getCurrentlyExecutingJobs().size());
for(JobExecutionContext context : scheduler.getCurrentlyExecutingJobs()) {
if(context.getNextFireTime().before(new Date())) {
//Past triggered Job enteries : It will keep on increasing with the count of 1 after every execution
System.out.println("Not Required =" + context.getJobDetail().getKey() + ", Job = " + context.getJobInstance());
} else {
// It will come here only once per execution
System.out.println("Legitimate instance =" + context.getJobDetail().getKey() + ", Job = " + context.getJobInstance());
}
}
} catch (SchedulerException e) {
e.printStackTrace();
}
}
}

}

public class CronTriggerExample {
public static void main( String[] args ) throws Exception
{

JobKey jobKey = new JobKey("dummyJobName", "group1");
JobDetail job = JobBuilder.newJob(HelloJob.class)
.withIdentity(jobKey).build();
Trigger trigger = TriggerBuilder
.newTrigger()
.withIdentity("dummyTriggerName", "group1")
.withSchedule(
CronScheduleBuilder.cronSchedule("0/1 * * * * ?"))
.build();

Scheduler scheduler = new StdSchedulerFactory().getScheduler();

//Listener attached to jobKey
scheduler.getListenerManager().addJobListener(
new HelloJobListener(), KeyMatcher.keyEquals(jobKey)
);
scheduler.start();
scheduler.scheduleJob(job, trigger);

}
}

**Comment by mail2ikhan** [comment]
Just implemented a hack, but still searching for a proper Quartz solution. Need to Call clear() every time Job is executed, this will clear un-necessary stuff : -

private void clear(Scheduler scheduler) {

    Object quartzScheduler = getFieldValue(scheduler, "sched");
    Object jobMgr = getFieldValue(quartzScheduler, "jobMgr");
    @SuppressWarnings("unchecked")
    Map<String, JobExecutionContext> executingJobs = (Map<String, JobExecutionContext>)getFieldValue(jobMgr, "executingJobs");
    List<String> removalList = new ArrayList<String>();
    for(Map.Entry<String, JobExecutionContext> entry : executingJobs.entrySet()) {          
        if(entry.getValue().getNextFireTime().before(new Date())) {
            removalList.add(entry.getKey());
        } 
    }

    for(String key : removalList) {
        executingJobs.remove(key);
    }

}

private Object getFieldValue(Object parent, String fieldName) {
    Object value = null;
    Class clazz = parent.getClass();
    Field[] fields = clazz.getFields();
     fields = clazz.getDeclaredFields();
    for(Field field : fields) {
        if(field.getName().equalsIgnoreCase(fieldName)) {
            field.setAccessible(true);

            try {
                value = field.get(parent);
            } catch (IllegalArgumentException e) {
                value = null;
            } catch (IllegalAccessException e) {
                value = null;
            }

        }
    }
    return value;
}

**Comment by TrymBeast** [comment]
Java? As far as I know this is the .NET repo.
I think this is the place you want to go: http://jira.terracotta.org/jira/browse/QTZ.

**Comment by lahma** [comment]
Closing issue as not .NET port related.
