### ISSUE TITLE
Cron expressions Issue

### ISSUE THREAD

**Issue by oizie** [quartznet/quartznet#279]
Hi, I have some cron expressions that are in standard cron like: "Every Minute : * * * * * ", " Every Hour : 0 * * * * ", every Sunday at 1am : "0 1 * * 0" and quartz doesn't understand giving an error or in the case of 3rd example just puts the wrong day of the week.
How can I use quartz using this expressions? It seems that quartz its using some other type of cron expressions.
I am using cron expressions as explained in here : "http://unixhelp.ed.ac.uk/CGI/man-cgi?crontab+5"

**Comment by lahma** [comment]
Please see Quartz.NET documentation about how to build proper cron expression. Quartz indeed has a custom variant of expression.

http://www.quartz-scheduler.net/documentation/quartz-2.x/tutorial/crontrigger.html
