### ISSUE TITLE
Bug in XSD schema: cannot set <misfire-instruction>IgnoreMisfirePolicy</misfire-instruction>

### ISSUE THREAD

**Issue by maximpashuk** [quartznet/quartznet#280]
I am using Quartz 2.3.2.

Then I am using TriggerBuilder, I can easily call on any type of trigger.

``` c#
.WithMisfireHandlingInstructionIgnoreMisfires()
```

But when I am using quartz_jobs.xml file for setting triggers, I am not able to set

``` xml
<misfire-instruction>IgnoreMisfirePolicy</misfire-instruction>
```

I am getting an error:

```
Quartz.Xml.ValidationException: The 'http://quartznet.sourceforge.net/JobSchedulingData:misfire-instruction' element is invalid - The value 'IgnoreMisfirePolicy' is invalid according to its datatype 'http://quartznet.sourceforge.net/JobSchedulingData:simple-trigger-misfire-instructionType' - The Pattern constraint failed.
```

So I think that current XSD schema restricts common misfire types: SmartPolicy, IgnoreMisfirePolicy.
Please add this types in xsd schema patterns.

**Comment by forsti83** [comment]
I am facing the same issue. Is there any workaround?
