### ISSUE TITLE
Separate interfaces into standalone assembly and package

### ISSUE THREAD

**Issue by vchekan** [quartznet/quartznet#284]
When implementing a quartz job in a plugin architecture application, I linked quartz assembly to get IJob interface. In result, I pulled internal implementation assemblies, Common.Logging.*
It would be much nicer to have interfaces in their own package with minimal or no dependencies.

**Comment by lahma** [comment]
This is the story with Quartz.NET v3 (alpha stage now), there are no external dependencies.
