### ISSUE TITLE
Don't put job_scheduling_data_2_0.xsd into nuget content

### ISSUE THREAD

**Issue by vchekan** [quartznet/quartznet#285]
I think it would be nicer to avoid putting job_scheduling_data_2_0.xsd file into nuget content target. When doing so, this file is added to the root of user's project every time package is installed/upgraded. Most project are trying to keep their root folder well organized and odd files from nuget packages look odd.

Perhaps it would be better to link this file as a resource in the assembly, so in case of need it is easily accessible.

**Comment by AntonSemenovKazan** [comment]
I do not undeerstand too - why this file appears.
Does it really need in root?

**Comment by lahma** [comment]
Won't be part of NuGet packages in v3.
