### ISSUE TITLE
Add support to the DisallowConcurrentExecution attribute for placement on Interfaces

### ISSUE THREAD

**Issue by alexmarshall132** [quartznet/quartznet#286]
We have some pretty large and complicated jobs which are instantiated by a dependency injection container (Ninject). These jobs also should not be run concurrently (legacy system, too hard to refactor or reimplement). We store the interfaces type names in the database as the job classe names and then create instances using Ninject. The current implementation of DisallowConcurrentExecution doesn't support placement on interfaces, therefore we can't apply it to any of our jobs, which we really need.

**Comment by lahma** [comment]
This would effectively mean multiple inheritance in a way (contradicting requirements). I'm closing for now but I'm open for a PR addressing this properly (both RAMJobStore and AdoJobStore).
