### ISSUE TITLE
Add support to JobBuilder for specifying that a job should have concurrent execution disallowed

### ISSUE THREAD

**Issue by alexmarshall132** [quartznet/quartznet#287]
Because we use a Dependency Injection container for creating our job instances, we store the Interface names in the database rather than the class names. It would be great if JobBuilder had support for explicitly setting DisallowConcurrentExecution rather than relying on the attribute being present on the class name, because that attribute does not support placement on interfaces (classes only)

**Comment by lahma** [comment]
I'm closing this as it's not easy to provide run-time support for this. If still needed a PR with support for interfaces can be considered.
