### ISSUE TITLE
GetNextValidTimeAfter - System.AccessViolationException

### ISSUE THREAD

**Issue by RFlipper** [quartznet/quartznet#288]
Hello, 

I noticed an issue, I have an unit test with following code that calculate next scheduled date: 

```
var cron = new Quartz.CronExpression("0 30 15 */1 * ?");
DateTimeOffset? nextFire = cron.GetNextValidTimeAfter(DateTime.Now);
Assert.IsNotNull(nextFire);
```

The code throws System.AccessViolationException with description: 
`Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

I use last Quartz 2.3.3 version and .Net Framework 4.5, my project is built for x64 platform.

Also I saw similar questions on StackExchange, but in my case it repeats on two machines 
http://stackoverflow.com/questions/20803005/how-to-parse-cron-expression-in-quartz

UPD: The issue repeats on my VMs, but the code works on my laptop.

**Comment by lahma** [comment]
I think this is more of a build configuration issue on Quartz.NET's consumer side, so closing as Quartz.NET is any CPU.
