### ISSUE TITLE
SQL Server database design is ..... less than optimal ......

### ISSUE THREAD

**Issue by marcscheuner** [quartznet/quartznet#291]
SQL Server database structure leaves a lot to be desired.....

Have a look at just this table:

```
CREATE TABLE [dbo].[QRTZ_CALENDARS]
(
    [SCHED_NAME] [NVARCHAR] (100) NOT NULL ,
    [CALENDAR_NAME] [NVARCHAR] (200) NOT NULL ,
    [CALENDAR] [IMAGE] NOT NULL
 )

ALTER TABLE [dbo].[QRTZ_CALENDARS] WITH NOCHECK 
ADD CONSTRAINT [PK_QRTZ_CALENDARS] 
PRIMARY KEY CLUSTERED ([SCHED_NAME], [CALENDAR_NAME]) 
```

Two main points I would fix right away:
- do not use the "Image" datatype anymore - it's been deprecated since SQL Server 2005 and will be removed soon. Use "VARBINARY(MAX)" instead which offers all the same goodness
- Having the clustering key on the two rather large NVARCHAR columns is bad for two reasons:
  (1) it's really large (potentially up to 604 bytes!! Darn close to the 900 byte index entry limit)
  (2) it's of varying length (twice!) 
  
  Both points together this for a horribly bad clustering key. I would recommend using a "INT IDENTITY" or "BIGINT IDENTITY" surrogate key instead which would be _significantly_ more efficient 

And also: ALL UPPERCASE is really not necessary anymore and makes it just sooo much harder to read the table and column names. Can't we use normal Camel casing (initial uppercase, rest of the word is lowercase) for identifiers, and ALL UPPERCASE only for T-SQL keywords (TABLE, INT, etc.)?

**Comment by lahma** [comment]
Yes this is a known feature/problem. The database is modeled quite directly to be compatible with Java  version which makes the code also follow the same logic. 

It would be quite an undertaking to change the all scripts, create migration scripts for *all* supported databases and rewrite the DB access layer. The solution should also map nicely between databases. This is something that I have not yet found the dire need to do.

But a pull request is always welcome. There's a lot to migrate and test + document if this needs to be done.

**Comment by lahma** [comment]
Varbinary is now in master, bigger primary key change would need as noted, quite a lot of work.
