### ISSUE TITLE
Installing database scripts for ADO.NET Jobstore from the NuGet package

### ISSUE THREAD

**Issue by marcscheuner** [quartznet/quartznet#292]
Currently, when I install Quartz.NET using the NuGet package (highly preferred way to do it!) I don't get the SQL Server database scripts to create the necessary tables for the ADO.NET job store. This is rather annoying....

NuGet easily supports installation of just plain "content" files (like SQL scripts) - I would highly recommend adding those database scripts as content to your NuGet package so they get installed along with the binary assembly

**Comment by lahma** [comment]
A bit of an two-edged sword here. Just adding the XML schema file caused a bit of unhappiness. When you have 7 SQL files installed to each project you reference Quartz from, people might get annoyed. 

I'd argue that the DB scripts are more infrastructure problem and should be part of DB migration framework, say RoundhousE. They usually are not part of the consuming code base as they are ran against the database quite separately.

**Comment by lahma** [comment]
I'm closing this as I feel that NuGet at its current form doesn't play well here. Database schema scripts need to be delivered unfortunately separately.
