### ISSUE TITLE
GetBooleanFromDbValue

### ISSUE THREAD

**Issue by wahlstrand** [quartznet/quartznet#294]
This function in src/Quarts/Impl/AdoJobStore/StdAdoDelegate.cs crashes when called from row 815 in the same class.

Reason seems to be that when using an SQL DB the jobdetails Is_Durable is set as a varchar, Convert.ToBoolean(string) doesn't seem to be able to handle things like Convert.ToBoolean("1").

Or is there another reason for this internal crash?

**Comment by lahma** [comment]
Are you using the proper delegate for your database? With SQL Server you should be using SqlServerDelegate. See here for an example:

http://jvilalta.blogspot.fi/2010/04/configuring-quartznet-with-adonet-job_28.html

The lock handler can be omitted for best performance.

**Comment by lahma** [comment]
Closing this as probable cause was wrong database delegate.
