### ISSUE TITLE
How to open / close a Form in Execute method

### ISSUE THREAD

**Issue by tynabee** [quartznet/quartznet#295]
My goal is 
   - open a window form at a specific time
   - Close the form that already open above at a specific time
When I try to close a form in Execute(IJobExecutionContext context) method, a error occurred
"Source Not Found You need to find JobRunShell.cs to view the source for the current call stack frame".
Please give me the simple demo project

**Comment by pelife** [comment]
I can't see how you can do this. Quartz scheduler is a background process, specially if you host this as a windows service.
One way to achieve this, is making the quartz run a communication with your windows form application via WCF duplex comunication.

1 - Create the program to run schedule and open an endpoint to make subscription available to win application.

2 - Create the windows form application and make it register in the service running Quartz

3 - As soon as a job gets triggered in your service, you send the notification to the windows applications that subscribed to the service.

That is how I see this can be done but someone else may have a better idea.

**Comment by lahma** [comment]
Here you might better of just time Timer objects if you just want to have fixed form opening and closing times.

**Comment by tynabee** [comment]
I would like to use Quartz to retrieve my goals as below:

     - Open a form after 20 seconds when app started: The form will display a dynamic picture

       using class JobStartListener : IJob
 
 - Close a form ( the form opened above ) after open 10 seconds

         using class JobStopListener : IJob

The issues are: 

      - Cannot close the form, it caused Cross-thread
 
Please refer my attached source code and give me your assistance.
( Change file from .PNG to .zip and unzip  )

![quartzopenform](https://cloud.githubusercontent.com/assets/14268994/10219397/cbfd8a62-6868-11e5-819a-c139b8146f4c.PNG)

Thank you very much.

**Comment by pelife** [comment]
You should definitely not use quartz for this. If I understand it right, you are trying to use quartz to make a splash screen.
http://www.codeproject.com/Articles/6511/Transparent-Splash-Screen
http://www.codeproject.com/Articles/21062/Splash-Screen-Control

you may find better solutionsin devexpress and syncfusion (paid UI component suites).

**Comment by tynabee** [comment]
Actually, I will not use quartz to make a splash screen. I will implement complex task, at every specific time a monitoring form will open, execute some task and close. Opening and closing form will follow schedule setting.

**Comment by tynabee** [comment]
Anyone can help me ? Please refer my source code above ( quartzopenform ).
