### ISSUE TITLE
How to become Quartz.NET contributor?

### ISSUE THREAD

**Issue by vgl** [quartznet/quartznet#296]
Hi,
I used Quartz.net few times in financial related projects and its realy cool, its ready to production + it has integration with Spring.NET. I'm greatful to @lahma and quartz.net community for work You've done.
Currently i just started working on solution that requires to run some jobs periodicaly and web ui is reqired for that. I just started it and I see that Quartz V3 will have same functionality that i want to implement, basically web api to control scheduler and ui + live logs. 
So i think instead of creating my own wheel i can help with Quartz.NET V3, so we can relase it as soon as possible, so we can start using its awesome features:)
So i would like to help, because I like this project and i like to use in my projects and I think I can help.
Is there any "contributor initiation" procedure?
P.S. Also is there any V3 features list or some roadmap?

**Comment by lahma** [comment]
Thank your for your interest!

There's no big ceremonies for becoming a contributor. All help is always welcome via pull requests, here's some rough guidelines (which are not set in stone).

* we try to follow Java Quartz to keep conventions to same and API approachable from both worlds
** yes, this has its downsides
* please respect the coding standards in place (whitespace, naming, notation), it's always wrong for some people. but it's how we roll (for now)
* new work should be done against v3 branch via pull requests from your feature branch (not master)
* testing and documentation is always welcome too, web documentation has its own branch
* please discuss ideas before going on to an implementation frenzy :)

As discussed the road map comes from the issues (probably should create a wiki page for this): 

https://github.com/quartznet/quartznet/milestones/3.0

I hope to have some time soon to go through the web UI again and have a stab on features.

Beta testing the work in progress would be great on a non mission critical system. The web UI won't work against the old branch I'm afraid.

Happy to answer more question!

**Comment by vgl** [comment]
Cool, does v3 is stable as far as it can be for now with code that in branch? Old functionality works same? Is there any ci for QuartzNet project?

**Comment by GieltjE** [comment]
The functionality is the same, but you'll have to modify your code to adapt to the new async setup. (I have compiled v3 in order to get rid of the damned common.logging).

**Comment by vgl** [comment]
I man that it's stable or not? What Quartz v3 uses instead of common.logging and why it's damned @GieltjE ? 
Regards

**Comment by GieltjE** [comment]
Because quartz.net would not run without it, the tooling always wanted to remove it from all projects because there were no references to it and if common.logging updated it usually broke quartz.net.

**Comment by lahma** [comment]
I'm closing this but all the help is always welcome, v3 is shaping quite nicely (async, LibLog already there in alphas).
