### ISSUE TITLE
Cannot build quartznet-3

### ISSUE THREAD

**Issue by pelife** [quartznet/quartznet#297]
I tried to build the quartznet-3 but there are a lot of errors comming. Does it have any dependencies ? I am trying to build in Visual Studio 2012.

There are some instructions that I didn't know was possible to use:
Ex.:
QuartzScheduler.cs
```c#
log.ErrorException($"Error while notifying SchedulerListener of paused job. Job={jobKey}", e);
```
it complains about the $ symbol.

ExecutingJobsManager.cs
```c#
public virtual string Name => GetType().FullName;
```
it complains about not finding de ";" symbol.

**Comment by lahma** [comment]
Quartz.NET v3 branch requires C# 6 compiler as it uses the new language constructs. Visual Studio 2015 should make it easy, but it seems that VS2013 can be tweaked too: http://stackoverflow.com/questions/27093908/how-to-enable-c-sharp-6-0-feature-in-visual-studio-2013 . 

So unfortunately Visual Studio 2012 is not supported for now. You can always install the command line tools (SDK) for .NET 4.5 and use mbuild to build the solution file.

**Comment by pelife** [comment]
Thanks for the update
