### ISSUE TITLE
 Getting Domain in Quartz with web app 

### ISSUE THREAD

**Issue by eminyuce** [quartznet/quartznet#300]
Hi, I am using quartz in the asp.net mvc app and trying to find out domain name from IJob implementation. Is it possible to get domain name inside IJob implementation?

I am using Ninject to initiate  scheduler jobs.

```
    kernel.Bind<ISchedulerFactory>().To<NinjectSchedulerFactory>();
        kernel.Bind<IScheduler>().ToMethod(ctx => ctx.Kernel.Get<ISchedulerFactory>().GetScheduler()).InSingletonScope();
        kernel.Bind<IBaseTasksScheduler>().To<LiquidTasksScheduler>().WithConstructorArgument("scheduler", kernel.Get<IScheduler>());
        kernel.Get<IBaseTasksScheduler>().Start(); 
```

 public class TestJob : IJob
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

```
    public void Execute(IJobExecutionContext context)
    {
      var domain= GetWebAppDomainNameFromSomewhere();
        Logger.Trace("TestJob is ScheduledTasks running.");
    }
}
```

**Comment by vgl** [comment]
Hi,
I think you can get it at runtime using several ways.
1 call web app method of asp.net mvc app in execute method using http client, or whatever rest library you like. But if you need to know domain name before making app call then this variant is not for you.
2 predefined domain name when job is creating and pass domain name to JobDataMap and in execute method retrieve it from that dictionary.
