### ISSUE TITLE
New QuartzNet web site

### ISSUE THREAD

**Issue by vgl** [quartznet/quartznet#301]
I visited hangfire.io and it's pretty cool, I think we need to renew Quartz.met site. I think we can use some bootstrap theme from wrapbootstrap.com
What you think?

**Comment by lahma** [comment]
Sure, I've actually been planning to do a UI refresh for the site. Just haven't had the time yet. If you want to give it a try there's the gh-pages branch that has the site content.

**Comment by lahma** [comment]
As it happens, the new web site was just launched after a mere wait of 5 years.
