### ISSUE TITLE
How to build and run Quartz v3

### ISSUE THREAD

**Issue by vgl** [quartznet/quartznet#302]
After pulling v3 branch its impossible to build and run solution easily. 
Build.cmd failed with messages -
....
BUILD FAILED

C:\Masaishi\quartznet\Quartz.build(185,10):
Property evaluation failed.
Expression: ${common-logging-dll}
              ^^^^^^^^^^^^^^^^^^
    Property 'common-logging-dll' has not been set.

Total time: 0.9 seconds.

How to build and run Web app?
There is no project in solution to do it easily

**Comment by GieltjE** [comment]
#299 has some quick fixes and covers this bug report.

**Comment by lahma** [comment]
I've updated to intermediate solution where Quartz.sln should build pretty cleanly with standard Visual Studio 2015. There's also Quartz.All.sln that contains also the server and web projects.

Hope this helps.
