### ISSUE TITLE
Names on jobs have changes, can't change them in the JOB_DETAILS

### ISSUE THREAD

**Issue by Rab815** [quartznet/quartznet#303]
After changing the organization of the solution for the individual jobs, the resulting namespace has changed and there doesnt' seem to be a way to alter the  JOB_CLASS_NAME column in the JOB_DETAILS table

**Comment by lahma** [comment]
From API perspective that's delete and add, but I'd say it's easier just to run a SQL update which changes the names to new ones with replace function etc. Don't run against production first...
