### ISSUE TITLE
Unable to upgrade from 2.3.2 to 2.3.3 with NuGet

### ISSUE THREAD

**Issue by cmorsucci** [quartznet/quartznet#304]
When i try to upgrade from 2.3.2 to 2.3.3 i have this error from NuGet:

Install failed. Rolling back...
Package 'Quartz 2.3.3' does not exist in project '*****'

Any Ideas?

**Comment by lahma** [comment]
I'd say this some temporary issue in your Visual Studio/NuGet setup. I've seen the upgrade succeed many times. Maybe try a clean VCS checkout and upgrade etc.
