### ISSUE TITLE
CoreCLR Windows/Linux/Mac support?

### ISSUE THREAD

**Issue by agonzalezm** [quartznet/quartznet#305]
Is there any plan to support Quartz.net on new MS .net coreclr stack that can runs on windows/linux/mac?

**Comment by lahma** [comment]
That would be nice to have, I have not yet played with the current version of the stack and it will probably require some work to get builds rolling. But something to investigate for sure!

**Comment by agonzalezm** [comment]
Do you know any estimation? Most popular packages are already providing beta packages for DNX Core. So it would be nice to have one for quartz.

**Comment by lahma** [comment]
I'm afraid it can be quite an undertaking. I've played a bit with DNX target now and I see many things missing which will require some restructuring and conditional compilation madness.

So no dates to give but if you want to have a go at it, I'd love to review pull request.

**Comment by lahma** [comment]
Closing this as alpha releases should now run on all platforms supported by > netstandard1.3.
