### ISSUE TITLE
IDirectoryScanListener listen to multiple directories

### ISSUE THREAD

**Issue by cknightdevelopment** [quartznet/quartznet#306]
Right now it looks like the `IDirectoryScanListener` is only able to listen to one directory at a time. I think it would be nice to have it be able to listen to multiple directories. Would this be a welcome contribution to the project right now? I would be happy to work on this in a fork and submit a pull request.

**Comment by cknightdevelopment** [comment]
I just wanted to circle back and see if this might be a welcome contribution to the project before I start working on it. What are your thoughts? Thank you.

**Comment by lahma** [comment]
Sorry for the delay. You can actually have as many job+listener pairs as you want. I would recommend having job per directory so get the benefits of concurrency.

Does having multiple listeners (one per directory job) sound feasible?

**Comment by cknightdevelopment** [comment]
What I am doing today is I am scanning multiple different directories, each with their own job+listener pair. What I would like to have is one job+listener pair (scanner) that can scan multiple directories. My use case is that I have several directories with the same kind of files in them that need to be processed in the same way. I do not want to have to make a separate job+listener pair for each one (can be up to a hundred directories). In this scenario I would like the `IDirectoryScanListener` to be able to be passed a collection of directories to scan. Does this make sense? Is this use case currently covered by the library? Thanks!

**Comment by lahma** [comment]
OK that sounds pretty reasonable considering your use case. Probably the easiest change would be to have both DIRECTORY_NAME and DIRECTORY_NAMES supported by the job and then aggregate results for all directories and then notify single plugin.

If done against quartznet-3 branch could use Parallel etc for better performance (release time frame uncertain then though).

**Comment by cknightdevelopment** [comment]
I will plan on making this enhancement on a fork of the `quartznet-3` branch, and work to make use of the new features available in the framework. Thank you for the direction on how to go about implementing this feature. I will work on this and submit a pull request when I think it is ready for review. Thanks!

**Comment by cknightdevelopment** [comment]
I am trying to use the build file and had a few issues with it trying to use variables that were not assigned. I got those out of the way for now, but it looks like NAnt is trying to use .NET 4.0 and csc.exe for that, which is causing it to throw errors when it hits new C# 6 language features. How are you working around this? Is there a way to point NAnt to the newer compiler?

**Comment by cknightdevelopment** [comment]
I was able to just build the Quartz project in Visual Studio, after I had NAnt create assembly info classes for me. That should be good enough for now.
