### ISSUE TITLE
CronExpression.IsValidExpression Returning true for invalid expression

### ISSUE THREAD

**Issue by ronydj** [quartznet/quartznet#315]
It is occurring  when validating this expression:

"0 0 15 ? \* FRI*"

code:

CronExpression.IsValidExpression("0 0 15 ? \* FRI*")

**Comment by Sicos1977** [comment]
I had the same problem and used this component to validate the cron expressions.
https://github.com/bradyholt/cron-expression-descriptor

You can set an option to raise an exception on the .GetDescription method when the CRON rule is invallid

**Comment by lahma** [comment]
I've made parsing stricter for characters after weekday, should cover this case.
