### ISSUE TITLE
.NET Framework 4.5.2

### ISSUE THREAD

**Issue by Romanx** [quartznet/quartznet#319]
Hey,

Could we have a build / package that contains a 4.5.2 build of Quartz. Microsoft have stopped support for [4, 4.5, 4.5.1](https://support.microsoft.com/en-us/gp/framework_faq/en-us?wa=wsignin1.0) and libraries are dropping support for 4.0 meaning we can't use them in Quartz.

I'd be happy to send a pull request for this if you're interested.

**Comment by danielmarbach** [comment]
when Microsoft announced the end of support for 4.5 and 4.5.1 they explicitly stated the following:

> Will I need to recompile/rebuild my applications to make use of .NET 4.5.2?

> No, .NET 4.5.2 is a compatible, in-place update on top of .NET 4, .NET 4.5, and .NET 4.5.1. This means that applications built to target any of these previous .NET 4.x versions will continue running on .NET 4.5.2 without change. No recompiling of apps is necessary.


http://blogs.msdn.com/b/dotnet/archive/2014/08/07/moving-to-the-net-framework-4-5-2.aspx

**Comment by Romanx** [comment]
@danielmarbach Forgive me if i'm being dense but you're suggesting that Quartz will pick up at 4.5.2 dll with no issues as i thought that wasn't the case? If so i'll have a look at testing this and report back when i find the time.

**Comment by lahma** [comment]
4.5.2 is advertised as drop-in replacement, and pretty much is. You can run 4.5 binaries with 4.5.x and 4.6 without issues.
