### ISSUE TITLE
Failure obtaining db row lock: Timeout expired

### ISSUE THREAD

**Issue by edr999** [quartznet/quartznet#320]
Hi
We are having Quartz.net in 5 machine cluster. in the last couple of days we had 3 times that quartz seems to be dead. it cannot create locks and doesnt run jobs

our configuration is

"
*
<quartzProperties>
	quartz.scheduler.instanceName=1234</quartz.scheduler.instanceName>
	quartz.scheduler.instanceId=instance_one</quartz.scheduler.instanceId>
	quartz.threadPool.type=Quartz.Simpl.SimpleThreadPool, Quartz</quartz.threadPool.type>
	quartz.threadPool.threadCount=200</quartz.threadPool.threadCount>
	quartz.threadPool.threadPriority=Normal</quartz.threadPool.threadPriority>
	quartz.jobStore.misfireThreshold=60000</quartz.jobStore.misfireThreshold>
	quartz.jobStore.type=Quartz.Impl.AdoJobStore.JobStoreTX, Quartz</quartz.jobStore.type>
	quartz.jobStore.useProperties=false</quartz.jobStore.useProperties>
	quartz.jobStore.dataSource=default</quartz.jobStore.dataSource>
	quartz.jobStore.tablePrefix=QRTZ_</quartz.jobStore.tablePrefix>
	quartz.jobStore.clustered=true</quartz.jobStore.clustered>
	quartz.jobStore.clusterCheckinInterval=10000</quartz.jobStore.clusterCheckinInterval>
	quartz.jobStore.lockHandler.type=Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz/quartz.jobStore.lockHandler.type>
	<quartz.jobStore.driverDelegateType=Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz</quartz.jobStore.driverDelegateType>
</quartzProperties>

thanks
Edr

**Comment by lahma** [comment]
What database, have you checked DB server logs? If SQL Server make sure to use SqlServerDelegate (and then you can also remove quartz.jobStore.lockHandler.type for optimized access).

One thing to check is DB server backup schedule, does it match with the exception occurrence (DB truly being locked while backup is taken).

Closing for now, we can reopen if new information can be gathered to track down if there is something to look into.
