### ISSUE TITLE
Issue when deleting a job

### ISSUE THREAD

**Issue by GaryBesta** [quartznet/quartznet#322]
I am getting a SchedulerException when trying to delete a job on one machine

Unable to unschedule trigger [DEFAULT.cc9bea0a-8bc8-48c7-b292-49997f1cf6a3] while deleting job [DEFAULT.70639d8e-4d26-455b-ae08-2184da288952]

c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Core\QuartzScheduler.cs in DeleteJob at line 817:17

Boolean DeleteJob(Quartz.JobKey)

The job that fails to delete is scheduled to run at 12:00 Monday to Friday. The schedule regeneration code runs at 23:55 on Saturday.

When trying to reproduce locally I am unable to get an error when deleting the jobs regardless of how many times I run it, or if the job is running while it recreates the schedule.

Any ideas on where to go with this one please?

**Comment by lahma** [comment]
Need a proper stack trance and exception message. Impossible to know what's really going on with this description.

**Comment by rr-media** [comment]
Got the same exception.
In my case it most likely happens if job is executing in the same time and trigger managed to be deleted in parallel thread (process), so QuartzSchedule.DeleteJob method throws this "trigger not found" exception.

**Comment by findusl** [comment]
Got the same exception. There is no useful Stacktrace available, the Exception is generated `at org.quartz.core.QuartzScheduler.deleteJob(QuartzScheduler.java:966)` without any information about the root cause.

**Comment by lahma** [comment]
Not sure if Java can be source for exceptions in this .NET library 😉

**Comment by findusl** [comment]
Very good point, wrong quartz scheduler library.
