### ISSUE TITLE
Dependency on C5, but no reference in NuGet package.

### ISSUE THREAD

**Issue by Szczawik** [quartznet/quartznet#324]
Quartz.net references C5.dll, and when the NuGet package is installed to create a client application, it does not pull C5.dll along. Later, some techniques like plug-in assembly discovery (EMF..., and others), may blow up being unable to iterate over Quartz.dll, because its dependency is missing in the directory.

Please consider either separating the code that clients need into a different project without C5 dependency, or indicating the dependency in the NuGet package.

Also, you could consider separating the code that developers need to use from the Quartz.dll assembly to develop custom tasks (IJob). So effectively you could end-up with 3 assemblies: 1 for implementing a client, 1 for implementing tasks, and for hosting a server (with dependencies of two prior assemblies).

**Comment by lahma** [comment]
Things should be easier with v3 where C5 (or any other library) is no longer a dependency for Quartz.dll. The first alpha 1 version is already out.
