### ISSUE TITLE
DST transition issue for daily time interval trigger in specific time zone.

### ISSUE THREAD

**Issue by dliljhammar** [quartznet/quartznet#341]
Hi,
I detected a strange behavior in our daily interval jobs that ran across the DST hour on sunday (located in Sweden (W. Europe Standard Time). We suddenly hade repeat of our triggers the entire night until we reached the triggers daily end time. I have extracted our setup code for these triggers and provide a sample code here (DST sprong forward at 27/3 01.59.59), followed by the output of the calculated fire times. I would very much appreciate some guidance regarding this issue since I am unabled to detect what I have done incorrectly. Testing days around DST gives correct calculation of fire times.

SAMPLE CODE: (I have set my computers time running in specified timezone to the day of DST) 
var timeZone = TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time");
var dailyTrigger = TriggerBuilder.Create()
    .WithIdentity("testTrigger", "testGroup")
    .WithDailyTimeIntervalSchedule(x => 
        x.OnDaysOfTheWeek(new [] { DayOfWeek.Sunday})
         .StartingDailyAt(TimeOfDay.HourAndMinuteOfDay(1, 0))
         .EndingDailyAt(TimeOfDay.HourAndMinuteOfDay(6, 0))
         .WithInterval(30, IntervalUnit.Minute)
         .InTimeZone(timeZone))
         .Build();

var futureFireTimes = TriggerUtils.ComputeFireTimes(dailyTrigger as IOperableTrigger, null, 50);
foreach (var fireTime in futureFireTimes) {
    Console.WriteLine("Local: {0}, UTC: {1}", fireTime.LocalDateTime, fireTime.UtcDateTime);  
}

OUTPUT:
Local: 2016-03-27 01:00:00, UTC: 2016-03-27 00:00:00
Local: 2016-03-27 01:30:00, UTC: 2016-03-27 00:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00 // DST spring forward
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
Local: 2016-03-27 03:00:00, UTC: 2016-03-27 01:00:00
Local: 2016-03-27 03:30:00, UTC: 2016-03-27 01:30:00
....

BR
Daniel

EDIT:
I missed this at time of posting but seem to be the same issue as #332.

**Comment by lahma** [comment]
This case should work better now with release 2.5, here's sample output from my testing:

Local: 2016-03-27 01:00:00Z, UTC: 2016-03-27 00:00:00Z
Local: 2016-03-27 01:30:00Z, UTC: 2016-03-27 00:30:00Z
Local: 2016-03-27 03:00:00Z, UTC: 2016-03-27 01:00:00Z
Local: 2016-03-27 03:30:00Z, UTC: 2016-03-27 01:30:00Z
Local: 2016-03-27 04:00:00Z, UTC: 2016-03-27 02:00:00Z
Local: 2016-03-27 04:30:00Z, UTC: 2016-03-27 02:30:00Z
Local: 2016-03-27 05:00:00Z, UTC: 2016-03-27 03:00:00Z
Local: 2016-03-27 05:30:00Z, UTC: 2016-03-27 03:30:00Z
Local: 2016-03-27 06:00:00Z, UTC: 2016-03-27 04:00:00Z
Local: 2016-04-03 01:00:00Z, UTC: 2016-04-02 23:00:00Z
Local: 2016-04-03 01:30:00Z, UTC: 2016-04-02 23:30:00Z
Local: 2016-04-03 02:00:00Z, UTC: 2016-04-03 00:00:00Z
Local: 2016-04-03 02:30:00Z, UTC: 2016-04-03 00:30:00Z
Local: 2016-04-03 03:00:00Z, UTC: 2016-04-03 01:00:00Z
Local: 2016-04-03 03:30:00Z, UTC: 2016-04-03 01:30:00Z
Local: 2016-04-03 04:00:00Z, UTC: 2016-04-03 02:00:00Z
Local: 2016-04-03 04:30:00Z, UTC: 2016-04-03 02:30:00Z
Local: 2016-04-03 05:00:00Z, UTC: 2016-04-03 03:00:00Z
Local: 2016-04-03 05:30:00Z, UTC: 2016-04-03 03:30:00Z
Local: 2016-04-03 06:00:00Z, UTC: 2016-04-03 04:00:00Z
Local: 2016-04-10 01:00:00Z, UTC: 2016-04-09 23:00:00Z

Closing for now in hope of that release 2.5 addressed this issue.
