### ISSUE TITLE
Purpose of virtual `JobRunShell.RequestShutdown`

### ISSUE THREAD

**Issue by danielmarbach** [quartznet/quartznet#346]
Can anyone explain to me the use case of  `JobRunShell.RequestShutdown`?

https://github.com/quartznet/quartznet/blob/quartznet-3/src/Quartz/Core/JobRunShell.cs#L114

**Comment by lahma** [comment]
Directly ported from Java version, ability to react for scheduler shutting down if using a custom job run shell that has more wits/resources.
