### ISSUE TITLE
Quartz.CronExpression.IsSatisfiedBy claims to ignore milliseconds but doesn't

### ISSUE THREAD

**Issue by jlpetz** [quartznet/quartznet#349]
I tried using this function from Powershell Quartz.CronExpression.IsSatisfiedBy(), but kept getting a false result for things that should have satisfied the check.

The function claims it ignores milliseconds but does not.
"/// Note that  milliseconds are ignored, so two Dates falling on different milliseconds"

Upon inspection of the function/method here.
https://github.com/quartznet/quartznet/blob/master/src/Quartz/CronExpression.cs#L396

There needs to be either.
1. The input of the function 'dateUtc' needs to be recreated without milliseconds. Similar to how 'test' is created in the function(removes the millisecond component) but without changing the time by one second. This would then allow the equals comparison to work as intended.
2. If we don't want to create a new DateTimeOffset object based on the function input 'dateUtc' but without milliseconds(ie. allocate more memory for this). Then perhaps just changing the comparison from equals to a check of having a value between -1000 and +1000 milliseconds(ie. leess than 1 second).

**Comment by jlpetz** [comment]
To Test in powershell

# Load the required Quartz.NET library which provides the cron expresion parsing, http://www.quartz-scheduler.net
Add-Type -Path (Join-Path $PSScriptRoot ".\Quartz.dll")
Add-Type -Path (Join-Path $PSScriptRoot ".\Common.Logging.Core.dll")
Add-Type -Path (Join-Path $PSScriptRoot ".\Common.Logging.dll")

# Adjust the below cron from '12' to whatever the current hour is in your local TZ. This should then satify every check until the hour in your TZ tick over
$thisCron = [Quartz.CronExpression]::new("* * 12 ? * *")

# Get a timestamp of now
$now = [DateTimeOffset]::UtcNow
# Get a timestamp which is identical to the above but without milliseconds
$nowNoMilli = [DateTimeOffset]::new($now.Year, $now.Month, $now.Day, $now.Hour, $now.Minute, $now.Second, $now.Offset);

# The below check on the timestamp with milliseconds will almost always return false
$thisCron.IsSatisfiedBy($now).ToString()

# This will be true
$thisCron.IsSatisfiedBy($nowNoMilli).ToString()

**Comment by lahma** [comment]
That was one long-standing bug. Thanks for reporting this and sorry it took so long to fix, fortunately you figured out the workaround.
