### ISSUE TITLE
Quartz.CronExpression.IsSatisfiedBy inefficient feature request

### ISSUE THREAD

**Issue by jlpetz** [quartznet/quartznet#350]
This is less of an issue and more a feature request.

Quartz.CronExpression.IsSatisfiedBy seems broken for me anyway so I will override this function and use my own version. See -> https://github.com/quartznet/quartznet/issues/349

However I also noted when looking at the code of the function that it works by subtracting a second then after that using GetTimeAfter(). After this the only thing it returns is TRUE or FALSE.

This seems inefficient to me. Why not have the function return an object which contains the TRUE/FALSE in addition to the DateTimeOffset provided by GetTimeAfter()? As logically if someone is checking IsSatisfiedBy() and it is false, they are likely then interested in when the next run is. By providing this extra info it means a second call in the users program doesn't need to call GetTimeAfter() again. Doing the same calculation twice.

**Comment by lahma** [comment]
I think it breaking the API for this use case might not be worth the effort. Calculating cron expression in pretty fast, unless we talk about many thousands of calculations. If more performance is required one can always just replicate the logic to get necessary date info too.

Thanks for bringing this to attention though, #349 fix already landed.
