### ISSUE TITLE
Support for Oracle ODP.NET 12c Release 4

### ISSUE THREAD

**Issue by CarlKo** [quartznet/quartznet#354]
Could you help to upgrade scheduler can support for Oracle ODP.NET 12c Release 4?

Thanks.

**Comment by lahma** [comment]
I think you should be fine just by using assembly redirects. It's hard to target specific Oracle (or any) library version so as long as their API stays stable you should be able to just redirect the DLLs to version you want to use.

**Comment by CarlKo** [comment]
Thanks for your kind advice.
