### ISSUE TITLE
Cron expression - other implementation

### ISSUE THREAD

**Issue by Puchaczov** [quartznet/quartznet#357]
Hello, I noticed that Quartz cron expression implementation doesn't support many usefull features especially when you mix complex types. For example, you don't support "0 0 0 1W \* \* *" expressions. I know it is time consuming to implement all features could appear in such expression. 

So would you guys be interested in replacing your existing implementation with other?

I'm asking becouse I'm author of one. I'm interested in integrate it at least in fork of quartz but maybe you would like to use it too. I create this library becouse I would like to have software that can handle every, literally every cron expression you would imagine. Based on MIT license. 

It's generally not in stable phase yet, I have to fight a little things more and write more tests for evaluator and few more things but I could look around in Quartz source to investigate how tightly coupled it is.

What do you think? maybe some contraindications?

**Comment by GieltjE** [comment]
I would love to see some more CronScheduleBuilder functions, to allow specifying items like "day of the month", month, "day of week" etc via enumerations (and a List<> for year), that would eliminate the need for expressions in most cases and prevent unexperienced users from writing faulty expressions.

**Comment by Puchaczov** [comment]
True, but your evaluator still have to support complex mixed types, without it, more functions will be useless.

**Comment by lahma** [comment]
I'm closing this as I'd rather see improvements for CronScheduleBuilder, there are other trigger types now too that should help.
