### ISSUE TITLE
Schedule job with one trigger vs multiple

### ISSUE THREAD

**Issue by thnk2wn** [quartznet/quartznet#362]
I have to do something silly like this to support scheduling a job for the first time (where I create the job detail and the trigger) as well as scheduling an existing job detail with a new trigger for subsequent times. One or the other will throw errors in either the initial or subsequent cases. This isn't intuitive. 

```C#
  if (1 == TriggerCounter)
    _quartzScheduler.ScheduleJob(jobDetail, trg);
  else
    _quartzScheduler.ScheduleJob(trg);
```

**Comment by lahma** [comment]
If you just want to add triggers for job just add the job first (AddJob) and then the triggers when necessary (ScheduleJob).
