### ISSUE TITLE
One-time simple triggers not deleted after recovery with .RequestRecovery(false)

### ISSUE THREAD

**Issue by epsteing** [quartznet/quartznet#363]
With RequestRecovery(**false**), if a long-running zero recurrence simple trigger fires, then the server crashes, when the server is restarted, the trigger is never deleted, even though the trigger cannot fire again.

With RequestRecovery(**true**), if a long-running  zero recurrence simple trigger fires, then the server crashes, is restarted, **then crashes a second time, is restarted**, the trigger is never deleted, even though the trigger cannot fire again.

**Comment by lahma** [comment]
I believe this cleanup logic was fixed some time ago already.
