### ISSUE TITLE
Support for Npgsql version 3.0.3.0

### ISSUE THREAD

**Issue by ubiqs** [quartznet/quartznet#369]
We are using PostGreSQL and using the latest version of Npgsql 3.0.3.0 in our project.
When we try to use Quartz it expects Npgsql version 2.0.11.0.

This is causing issues for us to support different versions of same dll in the one project.

Can current scheduler .net code work with Npgsql 3.0.3.0 ? If yes then can we add support of it in the 
dbproviders.properties file

**Comment by lahma** [comment]
Have you tried creating an assembly binding redirect to redirect all version from 0.0.0.0-3.0.3.0 to 3.0.3.0? That should do the trick if API hasn't changed.

**Comment by ubiqs** [comment]
Thanks Marko. It worked
