### ISSUE TITLE
QUESTION: Is JobChainingJobListener Functionality Cluster Aware in 2.x?

### ISSUE THREAD

**Issue by brianhyder** [quartznet/quartznet#381]
I am currently in a situation where I need to chain a series of jobs or cancel a running job as updated information comes in through our API. 

Environment:
Clustered environment: APIs that have scheduler instances to schedule jobs and worker process with a scheduler instance to execute jobs.

The Problem:
We have an API that updates an object and triggers a one time job to pre-calculate some data and persist it.  If the object changes we need to wipe out the calculated data and regenerate it.  In the case where an object is updated via our API while a job is already running to calculate the data from the previous update I need to either:
1. Cancel the currently running job
2. Chain the job after the currently job so that the stale data does not mix with the current set of data

The Research:
I first looked into `IScheduler.Interrupt` but it is not cluster aware and neither is `IScheduler.GetCurrentlyExecutingJobs`.  Canceling the jobs would then require an external means of communicating with each scheduler instance to see if the jobs are running within the context of that scheduler instance.

I then came across `JobChainingJobListener`.  I am curious to know if this is cluster aware or if I would still need a mechanism to register the listener on the scheduler instance where the job is executing.

Any insight would be greatly appreciated.  As a followup question: if the functionality is not provided in 2.x is it something that is being considered for 3.x?

**Comment by lahma** [comment]
Circling back as going through old issues. The listeners might not be a god fit in this scenario. Maybe store received data as TODO in some table and then poll with jobs that schedule workers based on that. Schedulers are not cluster aware in the sense, only taking required locks to ensure cluster members process data correctly.
