### ISSUE TITLE
DailyTimeIntervalTriggerImpl prevents altering EndTimeOfDay to a later time of day

### ISSUE THREAD

**Issue by DrCopyPaste** [quartznet/quartznet#382]
Hi,

this is probably not the most popular thing to do, but when I try to alter an already built trigger's (WithDailyTimeIntervalSchedule) EndTimeOfDay to a later time of the day I get the Exception:

> End time of day cannot be before start time of day

despite EndTimeOfDay being after StartTimeOfDay.

I looked into
**src/Quartz/Impl/Triggers/DailyTimeIntervalTriggerImpl/DailyTimeIntervalTriggerImpl.cs**
The implementations of property StartTimeOfDay and property EndTimeOfDay don't seem consistent to me,

Shouldn't the code line:
`if (sTime != null && endTimeOfDay != null && endTimeOfDay.Before(value))`

actually be

`if (sTime != null && endTimeOfDay != null && value.Before(sTime))`

Sample Code:

```
IJobDetail job = JobBuilder.Create<DummyJob>()
    .WithIdentity("DummyJob", "DEFAULT")
    .Build();

ITrigger myTrigger = TriggerBuilder.Create()
    .ForJob(job)
    .WithIdentity("MyIdentity", "DEFAULT")
    .WithDailyTimeIntervalSchedule(s => s
        .StartingDailyAt(new TimeOfDay(12, 0, 0))
        .EndingDailyAt(new TimeOfDay(15, 0, 0))
        .OnEveryDay()
    )
    .Build();

((DailyTimeIntervalTriggerImpl)myTrigger).EndTimeOfDay = new TimeOfDay(16, 0, 0);
```

**Comment by lahma** [comment]
With a slight delay, this is now fixed and coming out in 2.6.
