### ISSUE TITLE
Obsolete files in repository

### ISSUE THREAD

**Issue by GieltjE** [quartznet/quartznet#391]
The quartznet-3 branch has 4 obsolete files:
src/Quartz/NetCoreStubs/ApartmentState.cs
src/Quartz/NetCoreStubs/ThreatInteruptedException.cs
src/Quartz/NetCoreStubs/ThreadPriority.cs
src/Quartz/NetCoreStubs/TypeFilterLever.cs

These were removed from the .csproj sometime ago but never deleted.

**Comment by lahma** [comment]
Thanks for reporting, removed from repo now.
