### ISSUE TITLE
 Clustered schedulers fire the same job and execute it at the same time

### ISSUE THREAD

**Issue by ghost** [quartznet/quartznet#397]
Hi,

I have 2 servers with time synchronization mechanism, and there is a clustered quartz scheduler instance at each node that connects to the same SQLServer database to pick up triggers and jobs. 

The problem I'm having is that sometimes the same job gets executed twice because the schedulers at each node acquire the same trigger for the same job.  I was able to replicate this behaviour using the sample Quartz.Server by creating two instances of it and run both at the same time.

My configuration is as below:

```
quartz.scheduler.instanceName = ServerScheduler
quartz.scheduler.instanceId = AUTO
quartz.threadPool.type = Quartz.Simpl.SimpleThreadPool, Quartz
quartz.threadPool.threadCount = 10
quartz.threadPool.threadPriority = Normal
quartz.plugin.xml.type = Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin, Quartz
quartz.plugin.xml.fileNames = ~/quartz_jobs.xml
quartz.jobStore.type = Quartz.Impl.AdoJobStore.JobStoreTX, Quartz
quartz.jobStore.driverDelegateType = Quartz.Impl.AdoJobStore.StdAdoDelegate, Quartz
quartz.jobStore.dataSource = default
quartz.jobStore.useProperties = true
quartz.jobStore.clustered = true
quartz.jobStore.misfireThreshold = 900000
quartz.jobStore.lockHandler.type = Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz
quartz.dataSource.default.connectionString = Server=(local);Database=QuartzTest;Integrated Security=SSPI;
quartz.dataSource.default.provider = SqlServer-20
```

Am I missing something or is this an expected behavior?

As a workaround, if I add `DisallowConcurrentExecution`attribute to the IJob implementation, the problem does not happen, so am I supposed to always use this attribute when having a clustered scheduler?

**Comment by lahma** [comment]
Are you sure there's a single trigger that's being ran against the job at the same time or are there multiple triggers in the quartz_jobs.xml?

**Comment by ysasaki1985** [comment]
Hi, 

I setup quartz_jobs.xml as below. I created 8 independent jobs + a single trigger against each. Each trigger runs every 10 seconds.

    <job>
        <name>sampleJob1</name>
        <group>sampleGroup</group>
        <description>Sample job for Quartz Server</description>
        <job-type>Quartz.Server.SampleJob, Quartz.Server</job-type>
        <durable>true</durable>
        <recover>false</recover>
    </job>
    <job>
      <name>sampleJob2</name>
      <group>sampleGroup</group>
      <description>Sample job for Quartz Server</description>
      <job-type>Quartz.Server.SampleJob, Quartz.Server</job-type>
      <durable>true</durable>
      <recover>false</recover>
    </job>
    ....more
    (8 jobs in total)

    <trigger>
      <cron>
        <name>sampleCronTrigger1</name>
        <group>sampleCronGroup1</group>
        <description>Cron trigger to simply fire sample job</description>
        <job-name>sampleJob1</job-name>
        <job-group>sampleGroup</job-group>
        <cron-expression>0/10 * * * * ?</cron-expression>
      </cron>
    </trigger>
    <trigger>
      <cron>
        <name>sampleCronTrigger2</name>
        <group>sampleCronGroup2</group>
        <description>Cron trigger to simply fire sample job</description>
        <job-name>sampleJob2</job-name>
        <job-group>sampleGroup</job-group>
        <cron-expression>0/10 * * * * ?</cron-expression>
      </cron>
    </trigger>
    ....more
    (8 triggers in total)

**Comment by lahma** [comment]
Closing due to issue's old age. Configuration was generic even though database seems SQL Server, should use SQL Server specific configuration.
