### ISSUE TITLE
Common.Logging - Compiled against wrong version

### ISSUE THREAD

**Issue by jonreis** [quartznet/quartznet#398]
The release notes state: Update Common Logging to v3.3.1, nuget also shows a dependency on this.

However; if I use ILSpy to check the version that Quartz 2.4 is linked against it shows:

// Common.Logging, Version=3.0.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e
// Common.Logging.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=af08829b84f0328e

ILSpy shows this for Common.Logging:

// Common.Logging, Version=3.3.1.0, Culture=neutral, PublicKeyToken=af08829b84f0328e
// Common.Logging.Core, Version=3.3.1.0, Culture=neutral, PublicKeyToken=af08829b84f0328e

Is a mistake?

**Comment by lahma** [comment]
Thanks for reporting this, the upgrade was incomplete w.r.t. build script. I'll push version 2.4.1 out later this evening.
