### ISSUE TITLE
Singleton pattern for scheduler not working (Scheduler with the name xxx already exists)

### ISSUE THREAD

**Issue by mobedi** [quartznet/quartznet#399]
I have followed [**Tarun Arora**'s workaround](http://geekswithblogs.net/TarunArora/archive/2013/01/19/quartz.net-windows-service-on-server-important-configuration-steps-to-remember.aspx) for having a singleton pattern for the scheduler. The section is called _Fixing “Scheduler with the name xxx already exists.” issue_. For simplicity, I paste the code here:

```
public class Scheduler
{
    public readonly IScheduler Instance;
    public string Address { get; private set; }

    private readonly ISchedulerFactory _schedulerFactory;


    public Scheduler(string server, int port, string scheduler)
    {
        Address = string.Format("tcp://{0}:{1}/{2}", server, port, scheduler);
        _schedulerFactory = new StdSchedulerFactory(GetProperties(Address));

        try
        {
            Instance = _schedulerFactory.GetScheduler();

            if (!Instance.IsStarted)
                Instance.Start();
        }
        catch (SchedulerException ex)
        {
            throw new Exception(string.Format("Failed: {0}", ex.Message));
        }
    }

    private static NameValueCollection GetProperties(string address) 
    {
        var properties = new NameValueCollection();
        properties["quartz.scheduler.instanceName"] = "ServerScheduler";
        properties["quartz.scheduler.proxy"] = "true";
        properties["quartz.threadPool.threadCount"] = "0";
        properties["quartz.scheduler.proxy.address"] = address;
        return properties;
    }

    public IScheduler GetScheduler()
    {
        return Instance;
    }
}
```

However, I cannot seem to get the Singleton aspect of this approach working. The line `Instance = _schedulerFactory.GetScheduler();` throws an exception when the Scheduler already exists. And this happens when I'd like to get an instance of my scheduler while the scheduler already exists. But if I'm not mistaken Singleton pattern is supposed to return the **ONLY** available version of my instance. That means, if the instance does not exist, it should create one and otherwise it should return the one that is already instantiated. 

Can we get this singleton working somehow? Or am I doing something wrong?

**Update 1**: The root of the exception is in the `Bind()` method of the `SchedulerRepository`class.

```
public virtual void Bind(IScheduler sched)
{
    lock (syncRoot)
    {
        if (schedulers.ContainsKey(sched.SchedulerName))
        {
            throw new SchedulerException(string.Format(CultureInfo.InvariantCulture, "Scheduler with name '{0}' already exists.", sched.SchedulerName));
        }

        schedulers[sched.SchedulerName] = sched;
    }
}
```

So I guess the question is, what are the dangers of nullifying the`schedulers[sched.SchedulerName]` entry and reassigning it to the new `sched`?

**Update 2**: I have temporarily changed the above method to this. Hope nothing tragic happens. It seems to be working now. But please hit me up if you have any comments.

```
lock (syncRoot)
{
    if (!schedulers.ContainsKey(sched.SchedulerName))
    {
        schedulers[sched.SchedulerName] = sched;
    }          
}
```

**Comment by rmacfadyen** [comment]
This is still happening in 3.0.7 and seems to be a significant problem.

Having to wrap SchedulerFactor GetScheduler in my own singleton can be error prone. And potentially very tricky to get right... inside a lock() statement you can't use "await" you must use GetAwaiter().GetResult().

This exposes my code to potential deadlocks, at least from everything I've been reading about GetAwaiter().GetResult(). There doesn't seem to be concrete advice on how to do this correctly.

As an aside... why does the factory need to produce a singleton anyway?

**Comment by mehrdad-goudarzi** [comment]
I had the same problem with the 3.4.0 version and after upgrading to 3.5.0, it is gone.
