### ISSUE TITLE
Question about why interval trigger might stop firing

### ISSUE THREAD

**Issue by robborden** [quartznet/quartznet#400]
I seem to have random instances where my WithSimpleSchedule trigger stops firing.  There are no exceptions, and my program is still running, however it is no longer firing the trigger.   Below you can see how I am creating my job and my trigger. 

```
ISchedulerFactory schedulerFactory = new StdSchedulerFactory();
            var scheduler = schedulerFactory.GetScheduler();
            scheduler.Start();

var job = JobBuilder.Create(serviceClass)
                                        .WithIdentity(serviceClass.FullName, "ServiceGroup")
                                        .SetJobData(dataMap)
                                        .Build();

var trigger = TriggerBuilder.Create()
                    .WithIdentity(config.ServiceName + "Trigger", "ServiceGroup")
                    .WithSimpleSchedule(x => x
                        .WithInterval(config.SleepIntervalSpan)
                        .WithMisfireHandlingInstructionNextWithExistingCount()
                        .RepeatForever())
                    .Build();

scheduler.ScheduleJob(job, trigger);
```

My JobInstance target class also implements the following attributes:

```
[PersistJobDataAfterExecution]
[DisallowConcurrentExecution]
```

Am I doing something wrong such as not enabling misfire handling, or not handling misfires properly?  Other than the setting `.WithMisfireHandlingInstructionNextWithExistingCount()` I am not doing anything else to handle a misfire. 

 Any help would be greatly appreciated.  Keep up the good work, Quart.NET is awesome!

**Comment by robborden** [comment]
This just happened again.  No exceptions, the process is still running.  It has been up for 2 weeks and with no explanation it just stops firing the trigger.  Anyone have any ideas?  Am I doing something wrong?

**Comment by aph5nt** [comment]
any update on this?

**Comment by robborden** [comment]
I've since upgraded to the latest .NET Core version now, and I haven't had this issue since then.  I was using Mono previously.  Will report back if I experience this issue again.
