### ISSUE TITLE
.net core how to get properties ?

### ISSUE THREAD

**Issue by myccy8** [quartznet/quartznet#401]
/// <summary>

        /// Gets the properties parser.
        /// </summary>

        /// <returns>The properties parser</returns>
        protected virtual PropertiesParser GetPropertiesParser()
        {
            NameValueCollection settings =
# if CONFIGURATION

```
            (NameValueCollection)ConfigurationManager.GetSection(sectionName) ??
```
# endif // CONFIGURATION

```
            new NameValueCollection();
        PropertiesParser result = new PropertiesParser(settings);
        return result;
    }
```

.net core how to get properties ?

**Comment by lahma** [comment]
I think this issue is now obsolete as .NET core also supports configuration manager. You can always also specify custom quartz.config file containing settings you need.
