### ISSUE TITLE
Which application type?

### ISSUE THREAD

**Issue by dpedrelli** [quartznet/quartznet#402]
Is there anything that discusses the different Visual Studio application types, in relation to Quartz.NET?  I have several ASP.NET Core MVC apps hosted at a data center.  I want to create a new application that is dedicated to scheduled tasks.  Is one type better than another?  The few examples I have seen were all console apps.  Would a Windows Service be better?  I saw some posts saying that it can be done with ASP.NET.  However, if the app is dormant, because it is not called by any users, will it still fire?

Thanks.

**Comment by lahma** [comment]
Windows service is the best option to keep scheduler running reliably. Unless you can ensure always on functionality for your web app and that it doesn't recycle without restarting the scheduler too.
