### ISSUE TITLE
Make QueuedTaskScheduler public

### ISSUE THREAD

**Issue by Crazyht** [quartznet/quartznet#404]
I implement MongoDb Job store, and it's useful if I can reuse your QueuedTaskScheduler directly. 

Actualy, I have copied class into my library, but I prefer directly use your class.

Thx

**Comment by lahma** [comment]
I'm a bit hesitant to open this for public consumption, it's really an internal thing at least for now I wouldn't want is to be pubilc API surface and something to worry about when doing changes.
