### ISSUE TITLE
Is this a known issue? (Sometime Execute method is not triggered)

### ISSUE THREAD

**Issue by djvidov** [quartznet/quartznet#405]
Hello,
I've start to use quartznet inside of a windows service in order to start/stop some apps at a given time and it works well in 99.x % of cases. But sometime even if at previous execution (Execute(IJobExecutionContext context)) the method: context.Trigger.GetNextFireTimeUtc() returns me:
2016-09-16 20:49:00.0119305 - GetNextFireTimeUtc: **9/16/2016 5:56:00 PM +00:00**. Job: 7
but at 9/16/2016 5:56:00 PM never happens. and at 6:00:00 PM it works as usual.
this is a known issue or somebody had that issue?

Thank you!
Ovidiu RUDI

**Comment by djvidov** [comment]
I think I found the mistake: <add key="quartz.jobStore.misfireThreshold" value="10" /> probably 10 milliseconds was not enough ...

**Comment by lahma** [comment]
Closing as I think you got it sorted out. Enjoy Quartz!
