### ISSUE TITLE
MVC runs.  Windows Service fails.

### ISSUE THREAD

**Issue by dpedrelli** [quartznet/quartznet#410]
I created an MVC app that uses Quartz, placed the Quartz settings in the web.config, and the app runs fine.  I created a Windows Service and it runs, as long as I do not put the Quartz settings into the app.config (which are complied into <app>.exe.config).  Without the app.config settings, the service starts, and runs.  When I put the Quartz settings into app.config, the service either does not start or it starts and immediately terminates.  The only thing that Event Viewer reports is that the Faulting Module is KERNELBASE.dll.  Is it possible to configure Quartz through code, without using the app.config?  Are there any known issues that might lead to this failure?

Thanks.

**Comment by lahma** [comment]
Please see the sample server project, it uses Topshelf to create a Windows service that can be ran as a regular command line application and registered as a Windows service. This should help you get proper errors out when running from command line (if even viewer showed nothing).

https://github.com/quartznet/quartznet/tree/2.x/server/Quartz.Server
