### ISSUE TITLE
It does not work in the schedule server?

### ISSUE THREAD

**Issue by oguzhansari** [quartznet/quartznet#415]
Hi!

I prepare everything as follows.

**ScheduleTasks.cs**
`
using Quartz;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using Vandalina.Areas.vdAdmin.Controllers;
using Vandalina.Areas.vdAdmin.Models;

namespace Vandalina.Helpers
{
    public class ScheduledTasks : IJob
    {
        public void Execute(IJobExecutionContext context)
        {
            string ServerMapPath = context.JobDetail.JobDataMap.GetString("HttpContext");
            IntegrationController.ScheduleProccess(ServerMapPath);
        }
    }
}
`

**ScheduledTrigger.cs**
`
using Quartz;
using Quartz.Impl;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using Vandalina.Areas.vdAdmin.Models;

namespace Vandalina.Helpers
{
    public class ScheduledTrigger
    {
        public void Main(System.Web.HttpContext HttpContext)
        {
            try
            {
                ISchedulerFactory schedulerFactory = new StdSchedulerFactory();
                IScheduler scheduler = schedulerFactory.GetScheduler(); // Yeni scheduler(Zamanlayıcı) tanımlayalım
                scheduler.Start(); // Scheduler(Zamanlayıcı) ı başlatalım
                IJobDetail job = JobBuilder.Create<ScheduledTasks>()
                .UsingJobData("HttpContext", HttpContext.Current.Server.MapPath(""))
                .WithIdentity("ScheduledTasks", "excgroup")
                .Build();

```
            vandalinaEntities db = new vandalinaEntities();
            Random rastgele = new Random();
            int? ScheduleTaskHour = db.Store.FirstOrDefault().ScheduleTaskHour;
            int? ScheduleTaskMinute = db.Store.FirstOrDefault().ScheduleTaskMinute;
            ScheduleTaskHour = ScheduleTaskHour == null ? 8 : ScheduleTaskHour;
            ScheduleTaskMinute = ScheduleTaskMinute == null ? 0 : rastgele.Next(0, 59);

            ICronTrigger trigger = (ICronTrigger)TriggerBuilder.Create()
            .WithIdentity("ScheduledTasks", "excgroup") // Trigger name ve group
            .WithCronSchedule("0 "+ ScheduleTaskMinute + " "+ ScheduleTaskHour + " * * ?") // Zamanlama
            .Build();
            scheduler.ScheduleJob(job, trigger);
        }
        catch (SchedulerException EX)
        {
            try
            {
                using (System.IO.StreamWriter file = new System.IO.StreamWriter(HttpContext.Current.Server.MapPath("/Logs/schedulelogs.txt"), true))
                {
                    DateTime dt = DateTime.Now;
                    file.WriteLine("|| " + dt + " [Start] ---------------------->");
                    file.WriteLine("Data = " + EX.Data);
                    file.WriteLine("HelpLink = " + EX.HelpLink);
                    file.WriteLine("HResult = " + EX.HResult);
                    file.WriteLine("InnerException = " + EX.InnerException);
                    file.WriteLine("Message = " + EX.Message);
                    file.WriteLine("Source = " + EX.Source);
                    file.WriteLine("StackTrace = " + EX.StackTrace);
                    file.WriteLine("TargetSite = " + EX.TargetSite);
                    file.WriteLine("TargetSite Name = " + EX.TargetSite.Name);
                    file.WriteLine("TargetSite Module = " + EX.TargetSite.Module);
                    file.WriteLine("TargetSite DeclaringType = " + EX.TargetSite.DeclaringType);
                    file.WriteLine("|| " + dt + " [Finish] ---------------------->");
                    file.WriteLine("");
                }
            }
            catch (Exception)
            {
            }
        }
    }
}
```

}

`

Application_Start

`
            Helpers.ScheduledTrigger scheduler = new Helpers.ScheduledTrigger();
            scheduler.Main(System.Web.HttpContext.Current);

`
Localhost it working.
But the server does not work.
Do you need to make IIS settings?
How IIS settings.?

Please help me.

**Comment by lahma** [comment]
Cannot really decipher what could be wrong using this information. Maybe open discussion on the mailing list or SO if problem is still relevant.

**Comment by bborad** [comment]
Hi @oguzhansari 

did you get this working at all?

I am facing similar problem if not same.

Thanks
