### ISSUE TITLE
Assistance with documentation

### ISSUE THREAD

**Issue by cknightdevelopment** [quartznet/quartznet#417]
I have been using Quartz.NET for the last few years and have really benefited from including the library in my projects. I have contributed a pull request to the project ( #311 ) and have few written a few instructional blog posts on Quartz.NET topics:
- [Dependency Injection for Quartz.NET](http://knightcodes.com/.net/2016/08/15/dependency-injection-for-quartz-net.html)
- [XML Configuration for Quartz.NET](http://knightcodes.com/.net/2016/08/15/xml-configuration-for-quartz-net.html)
- [Quartz.NET Listeners For Calendars, Triggers, and Jobs](http://knightcodes.com/.net/2016/08/18/quartz-dot-net-listeners.html)

When reading [your recent post](http://www.quartz-scheduler.net/2016/08/24/quartznet-3.0-alpha2-released.html) announcing the Alpha 2 of Quartz.NET 3.0 I saw that one of the known issues mentioned was the following:

> - Documentation lacking

As much as I have enjoyed using Quartz.NET, there have been times where I wished there was more documentation available. The library is so good and I think quality documentation would only serve to grow the popularity and usefulness of the library. I was wondering if I might be able to assist with this portion of the project by providing more comprehensive and clear documentation (especially for the new 3.0 release). I don't know your plans in this area or if you are already working on the documentation, but I wanted to see if I may be able to help. I am a very good writer and explain things clearly. Let me know if this might be a welcome way for me to contribute to the Quartz.NET project, and if so, how we might move forward.

Thank you!

**Comment by cknightdevelopment** [comment]
I wanted to f

**Comment by lahma** [comment]
Great to hear you have interest in documenting things, that's a rare thing. The documentation resides currently in separate branch: https://github.com/quartznet/quartznet/tree/gh-pages . So what you'll need is understanding about how GH pages work so you'll get pages running locally.  There's some Jekyll guidance here: https://jekyllrb.com/docs/quickstart/ .

So generally it's as easy as greating pull requests against that branch. Please discuss ideas beforehand so we are in agreement about where we can improve. FAQ might be something to improve, there are common question on stackoverflow and then there's too the Java versions documentation that is currently more comprehensive.

**Comment by cknightdevelopment** [comment]
I am glad to hear that this is a welcome way to contribute to the project! I use Jekyll/GitHub pages for my blog, so I am pretty familiar with how all of that works. I cloned the `quartz` repository locally, and after switching to the `gh-pages` branch I am able to successfully run the site locally. 

I was thinking I could make a branch off of the `gh-pages` branch and make my contributions there. This way they can be reviewed (GitHub will only "publish" what is in the `gh-pages` branch) by you, edits can be made, etc. and then you can pull/merge when we are satisfied. There a number of content & restructuring ideas I have for the documentation, but I will plan on starting with a small contribution to the `FAQ` or to the `Features` section.

Does this sound okay to you? Thanks.

**Comment by lahma** [comment]
All help with documentation is appreciated. The sources for documentation are now in main repo under docs folder and require node/npm for development. But it's still the markdown that we can trust. Closing this, but always welcoming help!
