### ISSUE TITLE
JobDataMap is empty in Job/Tigger Listener

### ISSUE THREAD

**Issue by mikeholczer** [quartznet/quartznet#421]
I'd like to be able to log the details of my jobs and their execution, so I was trying use listeners so that I could log the name, group, execution time, JobDataMap, etc from the IJobExecutionContext parameter of either ITriggerListener.TriggerComplete or IJobListener.JobWasExecuted.

What I'm finding is that in either of those methods, the JobDetail.JobDataMap property of the IJobExecutionContext parameter is empty. Is that expected? Is there a better way to log this type of data?

**Comment by mikeholczer** [comment]
The IJobExecutionContext.Get method is also returning null for keys that do exist in the job's job data map.

**Comment by lahma** [comment]
Can you give code for a repro? This sounds a bit odd as they should be supplied as-is.

**Comment by mikeholczer** [comment]
We stopped using Quartz due to the need for prioitization.
