### ISSUE TITLE
Offsetting a scheduler

### ISSUE THREAD

**Issue by ChangePlaces** [quartznet/quartznet#423]
Is it possible to offset a scheduler by a few seconds other than offsetting the timings for each trigger? 

e.g. I have a scheduler that interfaces with external machines where their clock maybe a few seconds out and certain jobs have to run within a certain precision. Clock syncing isn't possible due to having multiple schedulers running and offsetting task times isn't possible as the offset difference could change. 

Wo I was wondering if I could do something like; `myScheduler.TimingOffsetBySeconds(-3);`

**Comment by lahma** [comment]
You could provide you own [SystemTime.UtcNow](https://github.com/quartznet/quartznet/blob/master/src/Quartz/SystemTime.cs#L15) function that calculates something different than the actual "now".

**Comment by ChangePlaces** [comment]
That looks interesting, but from looking at the code isn't that only used during scheduler start and trigger creation? I still would not be able to change the offset from UTC other than at those times which would be useless if I needed to set the timings back / forward several seconds because trigger start would already be hardcoded using the previous offset.

**Comment by lahma** [comment]
It's used when polling and checking for next triggers to run. It's the system clock for Quartz. I'd highly recommend getting the clocks in sync, everything else is just hacking around the real problem.

**Comment by ChangePlaces** [comment]
Unfortunately getting the clocks in sync is not possible - they're external machines I don't have control of.
