### ISSUE TITLE
Can't build 2.x branch with VS2015 on Windows 8.1

### ISSUE THREAD

**Issue by mao29** [quartznet/quartznet#424]
I'm trying to build sources from 2.x branch using MS Visual Studio 2015. It restores all needed packages but after that says "Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore." for Quartz.2010 project. But there is no project.json file and re-running NuGet restore just outputs "All packages are already installed and there is nothing to restore." 
How can I build Quartz.2010 with Visual Studio?

**Comment by lahma** [comment]
Please make sure you delete all project*json files, like project.lock.json. These are generated on master build and it confuses the 2.x branch where project.json is not used. NuGet tries to use references cached on disk in addition to the real references that should be used.

**Comment by mao29** [comment]
Yes, it helped. Thank you.
