### ISSUE TITLE
Improve JobStore configuration documentation.

### ISSUE THREAD

**Issue by tohagan** [quartznet/quartznet#425]
I eventually found the documentation for configuring persisted JobStores on our old favourite [ Stackoverflow](http://stackoverflow.com/questions/3821804/ado-net-with-quartz-net/21786658) but I think this really belongs in [Quartz Tutorial #9 - Job Stores](http://www.quartz-scheduler.net/documentation/quartz-2.x/tutorial/job-stores.html) for v2 and v3.   

This might reduce the risk of baldness for some devs due to  "lack of documentation" hair pulling :) .

- Thanks for Quartz!

**Comment by tohagan** [comment]
Another example of documentation induced baldness  ...  

- http://stackoverflow.com/questions/7961235/where-is-the-documentation-for-quartz-net-configuration-files

**Comment by lahma** [comment]
There's now new [Configuration Reference](https://www.quartz-scheduler.net/documentation/quartz-3.x/configuration/reference.html).

**Comment by tohagan** [comment]
Thanks!
