### ISSUE TITLE
Quartz.Net Test Mode

### ISSUE THREAD

**Issue by drusellers** [quartznet/quartznet#427]
Is there a way to "simulate" the passing of time in quartz? I'm working on some integration of Quartz with [MassTransit](https://github.com/masstransit/masstransit) and would love to have the ability to "pretend" 30 min has passed when testing our time out strategies.

Thank you,

**Comment by lahma** [comment]
You could provide your own [SystemTime.UtcNow](https://github.com/quartznet/quartznet/blob/master/src/Quartz/SystemTime.cs#L15) function that calculates something different than the actual "now". This is what Quartz polls against when checking whether triggers should fire / cleanup should be done.

**Comment by lahma** [comment]
I see that MassTransit has adopted the SystemTime so closing this. Please report back if you have issues with the approach.
