### ISSUE TITLE
error:ThreadPool type 'Quartz.Simpl.DefaultThreadPool' props could not be configured.

### ISSUE THREAD

**Issue by kylewell** [quartznet/quartznet#436]
Hi, when call the function QuartzServer.Initialize(), an error occur: "ThreadPool type 'Quartz.Simpl.DefaultThreadPool' props could not be configured.". What should I do? Thanks.

**Comment by lahma** [comment]
Need more information on this. There's probably a typo or something in your configuration. Inner exception probably has more details.

**Comment by ScutumGladius** [comment]
Hello,
I hahe the same Error 

properties["quartz.scheduler.instanceName"] = "RamQuartzScheduler";
properties["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz";
properties["quartz.threadPool.threadCount"] = "3";
properties["quartz.threadPool.threadPriority"] = "Normal";
properties["quartz.plugin.xml.type"] = "Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin, Quartz";
properties["quartz.plugin.xml.fileNames"] = "~/quartz_jobs.xml";
properties["quartz.serializer.type"] = "binary";

 ISchedulerFactory schedulerFactory = new StdSchedulerFactory(properties);

scheduler = await schedulerFactory.GetScheduler(); // <--- Boom
InitScheduler(scheduler);

Exception : ThreadPool type 'Quartz.Simpl.DefaultThreadPool' props could not be configured.

(From Nuget 3.0.0)

**Comment by lahma** [comment]
Need to ensure we give a warning level error here and not throw.
