### ISSUE TITLE
QuartzScheduler.Clear does not clear QRTZ_FIRED_TRIGGERS table

### ISSUE THREAD

**Issue by jirikanda** [quartznet/quartznet#437]
We use scheduler.Clear() to clear all jobs and triggers followed by new schedule creation. In the new schedule there are jobs and triggers with the same names.
Unfortunatelly, recovering jobs are not cleared well.

I guess the root cause is hidden in StdAdoDelege.ClearData(). I think there should be cleared QRTZ_FIRED_TRIGGERS table too. Should or should not this method call DeleteFiredTriggers method?

**Comment by lahma** [comment]
Can't see any harm on clearing the fired triggers when the triggers and jobs are gone. So now clearing that table too in Clear().
