### ISSUE TITLE
Configure travis or appveyor

### ISSUE THREAD

**Issue by jonny-novikov** [quartznet/quartznet#439]
Which one do you usually use in Open Source?
I can provide config if needed. 
It will prevent issues like https://github.com/quartznet/quartznet/issues/438

**Comment by lahma** [comment]
We are using appveyor, you can see the appveyor.yml in master's root. The build is fortunately green at the moment.

**Comment by jonny-novikov** [comment]
@lahma Well done! And can you add the badge?
