### ISSUE TITLE
job(Version:3.0.0-alpha2) not work after 4 hours in .net core 

### ISSUE THREAD

**Issue by imalexi** [quartznet/quartznet#440]
code:
`
public static void Main(string[] args)
        {
            NameValueCollection props = new NameValueCollection
                    {
                        { "quartz.scheduler.instanceName", "SchedulerName" },
                        { "quartz.threadPool.threadCount", "10" },
                        { "quartz.jobStore.misfireThreshold", "60000" },
                        { "quartz.jobStore.type", "Quartz.Simpl.RAMJobStore, Quartz" },
                        { "quartz.serializer.type", "json" }
                    };
            schFactory = new StdSchedulerFactory(props);
            var scheduler = await schFactory.GetScheduler();
            await scheduler.Start();

            var cancelJob = new JobDetailImpl("cancel", "orders", typeof(CancelOrderJob));

            // Trigger the job to run now, and then repeat every 15 seconds
            ITrigger cancelTrigger = TriggerBuilder.Create()
                .WithIdentity("cancelTrigger", "orders")
                .StartNow()
                .WithSimpleSchedule(x => x
                    .WithIntervalInSeconds(15)
                    .RepeatForever())
                .Build();

            // Tell quartz to schedule the job using our trigger
            await scheduler.ScheduleJob(cancelJob, cancelTrigger);

            while (true)
            {
                Task.Delay(6000).Wait();
            }
        }

`
os: ubuntu   and .net core  1.0.1
question 1:
the scheduler start ,After four hours The task will not work
question 2:
if use "quartz.config"
the StdSchedulerFactory can't auto load config file.

**Comment by lahma** [comment]
I can't easily reproduce the problem. Please try latest beta1, it should also automatically load the quartz.config file.
