### ISSUE TITLE
Quartz 3.0 GetScheduler() Synchronous version

### ISSUE THREAD

**Issue by gtaylor44** [quartznet/quartznet#441]
Is it possible to add a synchronous version of GetScheduler for console applications.

I'm bootstrapping a console application with the Start() method. Doesn't feel good calling an asynchronous method synchronously.

Is there another way to initialise the scheduler synchronously? This is the code i'm currently using in main method:

```
ISchedulerFactory schedFact = new StdSchedulerFactory();
IScheduler sched = schedFact.GetScheduler().GetAwaiter().GetResult();
if (!sched.IsStarted)
{
    sched.Start();
}
```

**Comment by lahma** [comment]
Quartz is all async now and there are no plans to add sync wrappers for the methods. You could create your  own extension methods if you need to though. So your code should work just fine, you can always have single method call for async Task method in main and wrap asyncness there until we have async Main support in .NET.

**Comment by schuettecarsten** [comment]
But *WHY* are you not using the Async suffixes?!

**Comment by gtaylor44** [comment]
Prior to C# 7.1 async Main (for console apps) was not properly supported. I see Quartz 3 finally has a stable release.

**Comment by lahma** [comment]
@schuettecarsten I think that discussion has been on the table enough in the .NET OSS community. Here's [NServiceBus's take on the matter](https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix).
