### ISSUE TITLE
Windows 10 Project support

### ISSUE THREAD

**Issue by kreuzhofer** [quartznet/quartznet#442]
Currently it is not possible to include the library into a Windows 10 Project. Can you fix this?

**Comment by lahma** [comment]
I think that would be non-trivial. There's dependency for System.Threading.Thread NuGet package and I guess that won't work with UWP apps? I haven't done UWP app development bug I guess this is a show-stopper for using Quartz v3 there.

**Comment by lahma** [comment]
All I can say for now is that netstandard13 is the lowest common denominator. If UWP cannot use such libs I'm sorry but it seems Quartz won't be a good fit.
