### ISSUE TITLE
Milestone Schedule and Release Date Plan for V3

### ISSUE THREAD

**Issue by creativethinker** [quartznet/quartznet#443]
Dears
Would you please let me know the release date plan for Milestone V3 which is in progress?
Regards

**Comment by blackie1019** [comment]
Same question want to know!

**Comment by lahma** [comment]
I'm on my summer vacation now that allows me to work more with v3 (with the cost of neglecting some family time). I'll try to push next alpha/beta next week. I'm sorry but cannot give any dates as this is not my full time job which would allow me to create road maps and schedules.
