### ISSUE TITLE
Api Documentation Missing

### ISSUE THREAD

**Issue by rastoroberto** [quartznet/quartznet#445]
Every link I found for apidoc it doesn't works.

https://quartznet.sourceforge.net/apidoc/3.0/html
http://apidoc.quartz-scheduler.net/

Can you please give me the right one?
Thank you very much.

**Comment by lahma** [comment]
Thanks for reporting this, I moved the site to be hosted with HTTPS and documentation links were incorrectly changed also, sourceforge does not support HTTPS where API documentation is hosted. I have now fixed the links.
