### ISSUE TITLE
Additional information: SchedulerPlugin type not specified for plugin 'jobInitializer'

### ISSUE THREAD

**Issue by twiti7** [quartznet/quartznet#446]
Quartz 2.4.1 FF4.6
When i have job initialization from app.config like this:
`<quartz>
    <add key="quartz.scheduler.instanceName" value="OrderImporterInstance" />
    <add key="quartz.threadPool.type" value="Quartz.Simpl.SimpleThreadPool, Quartz" />
    <add key="quartz.threadPool.threadCount" value="5" />
    <add key="quartz.threadPool.threadPriority" value="Normal" />
    <add key="quartz.plugin.xml.type" value="Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin, Quartz" />
    <add key="quartz.plugin.jobInitializer.failOnFileNotFound" value="true" />
    <add key="quartz.plugin.jobInitializer.scanInterval" value="120" />
    <add key="quartz.plugin.xml.fileNames" value="FirstJobImport.xml,SecondJobImport.xml" /> 
  </quartz>`

In code it looks:
   ISchedulerFactory sf = new StdSchedulerFactory();
   IScheduler sched = sf.GetScheduler();
   sched.Start();
I got error SchedulerPlugin type not specified for plugin 'jobInitializer'. When i change to initialize by name value collection everything is ok but i can't provide jobs definictions xml in more flexible way 

NameValueCollection properties = new NameValueCollection();
            properties["quartz.scheduler.instanceName"] = "XmlConfiguredInstance";

            // set thread pool info
            properties["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz";
            properties["quartz.threadPool.threadCount"] = "5";
            properties["quartz.threadPool.threadPriority"] = "Normal";

            // job initialization plugin handles our xml reading, without it defaults are used
            properties["quartz.plugin.xml.type"] = "Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin, Quartz";
            properties["quartz.plugin.xml.fileNames"] = "FirstJobImport.xml,SecondJobImport.xml";

            ISchedulerFactory sf = new StdSchedulerFactory(properties);
            IScheduler sched = sf.GetScheduler();
            
            Log.Info($"{nameof(Service.WinService)} Start command received.");
            sched.Start();

**Comment by lahma** [comment]
All keys targeting XML scheduling data processor plugin should have prefix of 'quartz.plugin.xml.' , so 'quartz.plugin.jobInitializer.' is wrong.
