### ISSUE TITLE
What is the status of Quartz.Web in v3?

### ISSUE THREAD

**Issue by PiotrPerak** [quartznet/quartznet#447]
I can't get it to compile from VS. Build.cmd says everything went fine but how do I start this application? When I navigate to `src\Quartz.Web` and run `dotnet run` I get `2. The project does not support the desired framework:`.

**Comment by PiotrPerak** [comment]
In build.fsx It looks like it isn't built at all? When add it to build it fails with many errors. That's why it's not added to build script. Do you think it's a lot of work to make it compile?

**Comment by lahma** [comment]
The .NET Core tooling is giving all sorts of grief at the moment. There hasn't been much movement on Web project front and I'm hoping that more stable .NET Core SDK release would help here.

**Comment by smartquant** [comment]
Added a patch file to do an initial conversion to asp.net core.
- Converted controllers
- Commented out SignalR references as it is not officially supported yet
- App initialization changed and made it dotnetcoreapp2.0

With these patches the Quartz.Web compiles at least. Feel free to use it.

[quartz.web.patch.zip](https://github.com/quartznet/quartznet/files/1136357/quartz.web.patch.zip)

**Comment by lahma** [comment]
Thank you for the help, I'm closing this issue for now.

**Comment by quickware** [comment]
I am not able to compile in vs 2017 now.
if I change the target in tsconfig.cs from es5 to es6 there are much less errors

**Comment by lahma** [comment]
It's not currently under active development, at some point I'll try to get the dependencies up to speed but currently I wouldn't hold my breath for a release due to resourcing constraints.
