### ISSUE TITLE
Write logs in separate log file for each Quartz Job

### ISSUE THREAD

**Issue by umartopia** [quartznet/quartznet#448]
Is there any way we can configure quartz + log4net such that, every quartz job will write to its own log file instead of everything being written in single log file?

**Comment by PiotrPerak** [comment]
How do you log? I use NLog and you can configure it so you can achieve what you want.

**Comment by umartopia** [comment]
I am currently using log4net as a logging library. Following is my configuration snippet:

`<?xml version="1.0" encoding="utf-8"?>

<log4net>

  <root>
    <level value="INFO" />
    <appender-ref ref="DummyLogAppender" />
    <appender-ref ref="DummyLog2Appender" />
    <appender-ref ref="DummyLog3Appender" />
    <appender-ref ref="EventLogAppender" />
    <appender-ref ref="ConsoleOutAppender" />
  </root>

  <appender name="ConsoleOutAppender" type="log4net.Appender.ConsoleAppender">
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%message,! %newline" />
    </layout>
  </appender>

  <appender name="DummyLogAppender" type="log4net.Appender.RollingFileAppender">
    <file value="D:\Logs\DummyLog.log" />
    <appendToFile value="true" />
    <rollingStyle value="Date" />
    <datePattern value=".yyyyMMdd'.log'" />
    <encoding value="utf-8" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern
        value="RRDE%property{EventId},! %date{MM/dd/yyyy hh:mm:ss tt},! %property{Priority},! %level,! %message,! %newline" />
    </layout>
  </appender>

  <appender name="DummyLog2Appender" type="log4net.Appender.RollingFileAppender">
    <file value="D:\Logs\DummyLog2.log" />
    <appendToFile value="true" />
    <rollingStyle value="Date" />
    <datePattern value=".yyyyMMdd'.log'" />
    <encoding value="utf-8" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern
        value="RRDE%property{EventId},! %date{MM/dd/yyyy hh:mm:ss tt},! %property{Priority},! %level,! %message,! %newline" />
    </layout>
  </appender>

  <appender name="DummyLog3Appender" type="log4net.Appender.RollingFileAppender">
    <file value="D:\Logs\DummyLog3.log" />
    <appendToFile value="true" />
    <rollingStyle value="Date" />
    <datePattern value=".yyyyMMdd'.log'" />
    <encoding value="utf-8" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern
        value="RRDE%property{EventId},! %date{MM/dd/yyyy hh:mm:ss tt},! %property{Priority},! %level,! %message,! %newline" />
    </layout>
  </appender>

  <appender name="EventLogAppender" type="log4net.Appender.EventLogAppender">
    <param name="ApplicationName" value="DummyAppName" />

    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern
        value="RRDE%property{EventId},! %date{MM/dd/yyyy hh:mm:ss tt},! %property{Priority},! %level,! %message,! %newline" />
    </layout>
    <filter type="log4net.Filter.LevelRangeFilter">
      <levelMin value="ERROR" />
      <levelMax value="FATAL" />
    </filter>
  </appender>

</log4net>`

**Comment by umartopia** [comment]
@PiotrPerak can you please give me a sample of your code. Like how did you achieve the same?

**Comment by PiotrPerak** [comment]
In nlog configuration file you can say where each logger should log too. I'm sure Log4net has this capability too.

```<rules>
    <logger name="MyProgram.Jobs.Job1" minlevel="Info" writeTo="job1File, console" final="true" />
</rules

**Comment by lahma** [comment]
I'm closing this as this is more logging library/framework related than actually Quartz.NET related.
