### ISSUE TITLE
could not load type 'Npgsql.NpgsqlCommandBuilder' from assembly 'Npgsql' when i  store job to postgresql

### ISSUE THREAD

**Issue by rosslight** [quartznet/quartznet#455]
When i try to store job to postgresql, i got  could not load type 'Npgsql.NpgsqlCommandBuilder' from assembly 'Npgsql'.  could you help to fix the issue?

My config:
NameValueCollection properties = new NameValueCollection();
properties["quartz.scheduler.instanceName"] = "TestScheduler";
properties["quartz.scheduler.instanceId"] = "instance_one";
properties["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz";
properties["quartz.threadPool.threadCount"] = "10";
properties["quartz.jobStore.misfireThreshold"] = "60000";
properties["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz";
properties["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.StdAdoDelegate, Quartz";
properties["quartz.jobStore.useProperties"] = "false";
properties["quartz.jobStore.dataSource"] = "default";
properties["quartz.jobStore.tablePrefix"] = "QRTZ_";
properties["quartz.dataSource.default.connectionString"] = "Server=127.0.0.1;Port=5432;Userid=postgres;Password=root;Database=myDS";
properties["quartz.dataSource.default.provider"] = "Npgsql";

Error:
Quartz.SchedulerException: Could not Initialize DataSource: default 
---> System.ArgumentException: Error while reading metadata information for provider 'Npgsql'
Parameter name: providerName ---> Quartz.SchedulerConfigException: Could not parse property 'commandBuilderType' into correct data type:
 Could not load type 'Npgsql.NpgsqlCommandBuilder' from assembly 'Npgsql'. 
 ---> System.TypeLoadException: Could not load type 'Npgsql.NpgsqlCommandBuilder' from assembly 'Npgsql'.
 
at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError,Boolean ignoreCase, Boolean reflectionOnly,
 StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, 
 ObjectHandleOnStack type, ObjectHandleOnStack keepalive)

**Comment by rosslight** [comment]
The i run my code with quartz souce code,  i can not meet the error.
I think maybe the error only exists in  version 3.0.0-alpha2

**Comment by rosslight** [comment]
My project base on .net core.

**Comment by lahma** [comment]
I think this was already fixed with d3fe4060e323a5d87225119a540161f55f7b90d5 . So part of next alpha drop.
