### ISSUE TITLE
[.NETCoreApp 1.1] Exceptions with job and scheduler listeners

### ISSUE THREAD

**Issue by MattJeanes** [quartznet/quartznet#459]
(CC @Shawson)

Hello, I understand the NET Core version is still in development but I couldn't find any existing GitHub issues and the problem is still there as of the latest NuGet build (3.0.0 alpha 2) I thought to raise this.

When using a `ISchedulerListener` or `IJobListener` I'm seeing unusual exceptions. Simply registering a `IJobListener` on anything will cause the job not to run with the following error being caught in the `ISchedulerListener.SchedulerError` method:

```
Unable to notify JobListener(s) of Job to be executed: (Job will NOT be executed!). trigger= group1.trigger1 job= group1.job1: JobListener 'MainJobListener' threw exception: Object reference not set to an instance of an object.
```

Meanwhile, if you disable the `IJobListener` so the job runs, you'll get another exception caught through the `ISchedulerListener.SchedulerError` method:

```
Job group1.job1 threw an exception.: Job threw an unhandled exception.
```

This happens even if the job ran absolutely fine. I've made a lovely little test repo which recreates this error for you, hope it helps 😄 

We're hoping to get our app using Quartz deployed soon, so any help on this would be great. Thank you!

Test repository: https://github.com/MattJeanes/QuartzNetCoreError

**Comment by lahma** [comment]
Thanks for the report and taking the time to create good repro of the problem, I've scheduled this for the next release of v3 alpha series.

**Comment by lahma** [comment]
I have now checked the code and it seems that you are returning null from a method that is expected to return a Task. You should change all your code that implements methods from ISchedulerListener to return Task.CompletedTask instead, otherwise it will throw as Quartz tries to await the return value, null is not allowed here.

Does this fix the issue?

**Comment by MattJeanes** [comment]
I'll try it out tomorrow, thanks for helping us out so quickly on this 😄

**Comment by Romanx** [comment]
@Iahma Maybe it'd be good to add an analyzer looking for these cases, the other I can likely think of is Execute on IJob.

**Comment by MattJeanes** [comment]
@lahma Yep, thanks that fixed everything. Thanks! ❤️ 

I'd like to add though, if there is no scheduler listener or job listener there is no indication that anything is wrong, it silently fails without any indication. Took me a couple of hours to work out how to actually get an error message out of it. I'd strongly recommend throwing some kind of exception that would be caught in the IDE or at least some way of letting the dev know something is wrong instead of silently failing.

But none-the-less thank you for your quick response, my issue is solved so I'm going to close this, but if you want to re-open this to use for adding a kind of failure indication then go right ahead 👍
