### ISSUE TITLE
Regression in 2.5, TriggerBuilder.UsingJobData(JobDataMap newJobDataMap) should ovewrite existing

### ISSUE THREAD

**Issue by kwaclaw** [quartznet/quartznet#460]
The fix for issue #212 has been applied on Jan 14, 2015, but has been reverted on Nov 26 2016.

**Comment by lahma** [comment]
This was an unfortunate change, I've scheduled it for next release. Thanks for bringing this up.

**Comment by lahma** [comment]
Now backed with a test case too.
