### ISSUE TITLE
The type initializer for 'Quartz.Util.TimeZoneUtil' threw an exception.

### ISSUE THREAD

**Issue by vikrant-verma** [quartznet/quartznet#462]
I am getting an error while using quartz in my project 
details:

Exception type: System.Configuration.ConfigurationErrorsException
Message       : Couldn't find type for class Microsoft.WindowsAzure.Diagnostics.DiagnosticMonitorTraceListener, Microsoft.WindowsAzure.Diagnostics, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.

please help..

**Comment by lahma** [comment]
Can you provide the full stack trace. It's quite hard to investigate with only this information.
