### ISSUE TITLE
how to open the project using vs2013?

### ISSUE THREAD

**Issue by SimpleSimple** [quartznet/quartznet#466]
it seems to open only using vs2015?

**Comment by lahma** [comment]
You need either VS2015 or VS2017, which both are free downloads (Community Edition).

**Comment by asulwer** [comment]
I tried this about a year ago and had todo a major conversion to compile correctly.  I also attempted to convert the x86 asm to x64 with limited success.  has the project been worked on since then?  I am talking about the c/c++ code not the Delphi code base

**Comment by lahma** [comment]
Neither c/c++ nor Delphi here, the project is written in c#.

**Comment by asulwer** [comment]
oops, commented on wrong thread!  let me delete!
