### ISSUE TITLE
Quartz is logging transient faults related to azure db connection as errors

### ISSUE THREAD

**Issue by octaviobffernandes** [quartznet/quartznet#470]
We are using quartz.net on our project connecting to an Azure SQL Server database.
Every now and then we are seeing error messages like these being logged by quartz:

```
[Error] Quartz.Impl.AdoJobStore.JobStoreTX Couldn't rollback ADO.NET connection. Transaction not connected, or was disconnected
System.Data.DataException: Transaction not connected, or was disconnected
   at Quartz.Impl.AdoJobStore.JobStoreSupport.CheckNotZombied(ConnectionAndTransactionHolder cth) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3591
   at Quartz.Impl.AdoJobStore.JobStoreSupport.RollbackConnection(ConnectionAndTransactionHolder cth) in c:\Program Files (x86)\Jenkins\workspace\Quartz.NET\src\Quartz\Impl\AdoJobStore\JobStoreSupport.cs:line 3364
```

This has to do with the not-so-stable nature of Azure SQL db connections, which increases the chances of having a transient fault during db operations.
Because of that, Microsoft even recommends to implement transient fault handling and having retry policies when performing operations on a Azure SQL db.

I've tried telling quartz to use a ReliableSqlConnection instead of the normal SqlConnection by editing <quartz> web.config section like this:
`<add key="quartz.dbprovider.customProvider.connectionType" value="Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.ReliableSqlConnection, Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.Data, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />`

But it does not work because ReliableSqlConnection class does not have a parameter-less constructor then quartz is not able to instantiate an object.

Is there any solution to this? 
I know this issue does not cause real problems because quartz will recover and keep querying the database periodically, but we really would like to get rid of the error message in case of the connection-related transient faults.

**Comment by lahma** [comment]
I've tweaked logging to transient error in rollback is now considered as debug level event.
