### ISSUE TITLE
Decrease log level for message when host name is too long

### ISSUE THREAD

**Issue by octaviobffernandes** [quartznet/quartznet#471]
On HostNameBasedIdGenerator.GetHostName() there is a Warning being logged when hostName is longer than the maxlength. 

```
 if (hostName != null && hostName.Length > maxLength)
                {
                    string newName = hostName.Substring(0, maxLength);
                    logger.WarnFormat("Host name '{0}' was too long, shortened to '{1}'", hostName, newName);
                    hostName = newName;
                }
```

We are seeing this log event everytime the scheduler is created, because the fully-qualified machine name is always longer than 20 for us.
I think there shouldn't be a warning for this. Warnings are meant for things that require special attention and this is just an information.

My suggestion is to change the level of this message to Info.

**Comment by lahma** [comment]
Thanks for the report, fix has been applied to 2.x and master branches.
