### ISSUE TITLE
QRTZ_FIRED_TRIGGERS.ENTRY_ID column length too small

### ISSUE THREAD

**Issue by cademoor** [quartznet/quartznet#474]
The QRTZ_FIRED_TRIGGERS.ENTRY_ID max length should be the addition of the:

SCHED_NAME.Length + BIGINT.MaxLength

**Comment by lahma** [comment]
Good catch, the size indeed should be more like 120 rather than the current 95.

**Comment by cademoor** [comment]
Thanks for the response. I can make that change in my use of Quartz.NET. Thank you very much for maintaining this project. It's incredible. I might wait to hear back from you on this additional comment before I decide what's best for me to do locally.

There is a slight inconsistency with the SCHED_NAME length. It's 100 in some cases and 120 in others. That might be intentional but wanted to bring it to your attention. Hopefully this is helpful.

If you end up liking the SCHED_NAME to be 120 everywhere, I can just adjust the ENTRY_ID to 140 (just +20 from the SCHED_NAME).

cade@cade-home /cygdrive/d/Work/tcp-we-thirdparty/Quartz.NET/quartznet
$ find . -type f -name *.sql |xargs grep "SCHED_NAME" |grep -n 100 > sched-name-100.txt
[sched-name-100.txt](https://github.com/quartznet/quartznet/files/966462/sched-name-100.txt)

cade@cade-home /cygdrive/d/Work/tcp-we-thirdparty/Quartz.NET/quartznet
$ find . -type f -name *.sql |xargs grep "SCHED_NAME" |grep -n 120 > sched-name-120.txt
[sched-name-120.txt](https://github.com/quartznet/quartznet/files/966463/sched-name-120.txt)

**Comment by lahma** [comment]
Yes, the 120 everywhere sounds reasonable. Could you please create a PR against 2.x branch? I can then merge it to master too (3.x), or if you want I happily accept two PRs too. I think whoever creates new schema would like to get it right the first time, for 2.x usage too.

**Comment by cademoor** [comment]
Sounds great. I just created two PRs (hoping I did it correctly so it's simpler for you to integrate).

In short, the SCHED_NAME is now a length of 120 everywhere and the ENTRY_ID is now a length of 140 everywhere.

**Comment by lahma** [comment]
Made sure that the change is also in 2.x branch, thanks again.
