### ISSUE TITLE
Quartz.Web in VS2017

### ISSUE THREAD

**Issue by br0dieman9** [quartznet/quartznet#477]
Hi,

I saw issue #447 What is the status of Quartz.Web in v3 was posted back in February.

I was wondering if you'd made any progress with the web project since that issue was opened.

I've tried downloading a zip file from github, I can build the Quartz.sln in VS2017, but the Quartz.Web project will not compile. Build produces this error:
![image](https://cloud.githubusercontent.com/assets/6833000/25631824/8fa32b86-2f3f-11e7-9398-922687b80bc9.png)

Running nuget restore causes more errors:
![image](https://cloud.githubusercontent.com/assets/6833000/25631869/b859eede-2f3f-11e7-8d0d-61334d3657d0.png)

I've also tried to use the build.cmd file to build the project (after cloning the github repo), which compiles successfully. Running dotnet run after the build.cmd errors out also:
![image](https://cloud.githubusercontent.com/assets/6833000/25634087/5a3650e2-2f47-11e7-8ad6-ca43e071cc52.png)

Please let me know if I am missing a step somewhere.

**Comment by lahma** [comment]
Closing as this is not currently in active development.
