### ISSUE TITLE
从SQL Server数据库中读取JOB怎么配置

### ISSUE THREAD

**Issue by huangqianjob** [quartznet/quartznet#482]
比如我的Job（是一个windows 服务）跑的时间是在数据库中某个表里，时间会跟着改变的，比如JOB1本来是每天10点跑，我现在去把数据库的配置改为11点跑，然后要立即生效。不能每次都改变配置后手动去重启服务，而是需要去自动更新JOB跑的时间

**Comment by lahma** [comment]
Sorry, I don't speak this language.

**Comment by Pinox** [comment]
Just right click in browser and "translate to English" :  

User comments in English : For example, My Job (a windows service) running time is a table in the database, will change with time, such as JOB1 could have been 10:00 every day to run, I'm going to change the configuration database of 11:00 run, and then to take effect immediately. After you can not always change the configuration to manually restart services, but need to automatically update JOB running time

**Comment by lahma** [comment]
And I still have problems understanding the issue. We can reopen when we have a bit more insight into the issue.

**Comment by Pinox** [comment]
Agree, purely for future ref ;)
