### ISSUE TITLE
Invalid cron expression validates as true.

### ISSUE THREAD

**Issue by vikrant-verma** [quartznet/quartznet#485]
### Version: x.y.z
2.4.1

### Expected behaviour

When I call the below method to check for validity of a cron expression, this should return false. 

CronExpression.IsValidExpression("* * * ? * *A&/5:"); // should return false.

### Actual behaviour

It is returning 'true', which is not correct. I also tried other combinations of cron string like:

"* * * ? *14 *", "* * * ? *A&/5 *" etc. In all these cases it is returning true.

### Steps to reproduce
Call the method  in C# code like below
CronExpression.IsValidExpression("* * * ? * *A&/5:");

It seems to be unexpected behaviour. 

Please, someone, have a look and clarify whats wrong here.

**Comment by vikrant-verma** [comment]
Is there any other better way to validate a cron expression?

**Comment by lahma** [comment]
I've made parsing now stricter for asterisk case, should flag your examples now as invalid expressions.
