### ISSUE TITLE
Add support for .NET Standard 2.0 preview

### ISSUE THREAD

**Issue by adamfur** [quartznet/quartznet#486]
### Expected behavior

Clean compile

### Actual behavior

Timeout/Alarm.cs(48,31): error CS0433: The type 'ThreadInterruptedException' exists in both 'Quartz, Version=3.0.0.0, Culture=neutral, PublicKeyToken=f6b8c98a402cc8a4' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' [ESX.csproj]

### Steps to reproduce

Use Quartz-3.0.0-alpha2 and .NET Standard 2.0-pre

**Comment by lahma** [comment]
Thanks for reporting this, I'm planning to prepare separate build target for netstandard20

**Comment by aford22** [comment]
Hi Iahma,

I too am encountering this error in .Net core. Have you an estimated publish date for the netstandard20 build?

Thanks,
Andrew

**Comment by lahma** [comment]
The version that can build against netstandard 2.0 is now in master. You can compile your own copy while waiting for alpha 3 to hit NuGet. I have still things to check before releasing the next drop.
