### ISSUE TITLE
how quartz save info(job,mapdata ) in ram

### ISSUE THREAD

**Issue by keyone2693** [quartznet/quartznet#488]
my question is how quartz save method parameters in ram for example I use this 
`ISchedule myTask = new AddFollowerSchedule(m2.Id, _instaApi);
 myTask.Run();`

**in AddFollowerSchedule class:**

```
public int iwId;
public IInstaApi ii;
public (int id , IInstaApi IInstaApi)
{
   iwId = id;
    ii = IInstaApi;
}
public void Run()
{
    IJobDetail job = JobBuilder.Create<AddFollower>()
    .WithIdentity("a-", "a")
    .UsingJobData("id", iwId)
    .UsingJobData("ii", ii)
     .Build();

      ITrigger trigger = TriggerBuilder.Create()
      .WithIdentity("atrigger-", "a")
       .WithCronSchedule("0 */5 * ? * *")
       .Build();
       ISchedulerFactory sf = new StdSchedulerFactory();
       IScheduler sc = sf.GetScheduler();
       sc.ScheduleJob(job, trigger);
       sc.Start();
}
```

 **in AddFollower :**
```
public AddFollower()
{ }
public async void Execute(IJobExecutionContext context)
{
     JobDataMap dataMap = context.JobDetail.JobDataMap;
     int iwId = dataMap.GetInt("id");
     IInstaApi IInstaApi = dataMap.GetInstaSharper("ii"); i change the source for doing this :)
     //some code
}
```

it's(quartznet) successfully save the value and send it to a method for  the run;
and I need to save that object (IInstaApi ) to ram like how quartz does that (info: I can't save that in DB or redis or ...
because it can't be sterilized)

@lahma can U tell how u save data in ram ?
tanks

**Comment by lahma** [comment]
Indexers should work with string keys and allow objects as value for job data map.
