### ISSUE TITLE
GetTimeBefore() not implemented

### ISSUE THREAD

**Issue by feitzi** [quartznet/quartznet#491]
The [Method GetTimeBefore(value)](https://github.com/quartznet/quartznet/blob/4d06bf2cbf6a6611e632624f38c67f86e36eedcf/src/Quartz/CronExpression.cs#L2117) isn't implemented. But it is visible int the current release and not declared as not implemented. 

My questions:

- Why is the method in the release? 
- Why nit throw a NotImplement Exception? 
- And is there any plan to support this method?

br
mathias

**Comment by lahma** [comment]
It would be a pain to implement for cron expression, so it will not be implemented in foreseeable future. The null semantics come from callers that can handle null better (for now).
