### ISSUE TITLE
Validation for quartz_jobs.xml

### ISSUE THREAD

**Issue by khosrojerdi** [quartznet/quartznet#492]
Hello guys.
I was wondering if there is any validation for "quartz_jobs.xml" file. For example we have had a case that the namespace of the job was not right in the config file so none of the jobs were executed and unfortunately there were no error or warnings to inform us about this issue. 
Can anyone tell me If there is any way to validate it or to somehow figure out there are some problems or mistakes in the xml file? 
If there is not any, would be added as a feature in the future?

**Comment by lahma** [comment]
I think that what we could do is add a flag that would be checked on XMLSchedulingDataProcessorPlugin.Initialize and validate that files are OK. Files are processed via job scheduling so only way to know about problems is reading the logs.

Test-reading the files on scheduler construction could allow us to crash early.

**Comment by lahma** [comment]
Now there is a flag FailOnSchedulingError for the plugin that will cause plugin to throw exception if XML file cannot be handled when plugin (scheduler) starts.
