### ISSUE TITLE
Support for MySql-51 on .NET Standard

### ISSUE THREAD

**Issue by bcuff** [quartznet/quartznet#493]
We're currently using MySql-51 on Windows using the full .NET Framework. We're in the process of migrating to .NET Core running on Linux. I noticed that MySql-51 is not currently supported in the [netstandard set of providers](https://github.com/quartznet/quartznet/blob/master/src/Quartz/Impl/AdoJobStore/Common/dbproviders.netstandard.properties). Any chance that there will be support for this in the future? Thanks.

See https://github.com/quartznet/quartznet/blob/master/src/Quartz/Impl/AdoJobStore/Common/dbproviders.properties#L159

**Comment by lahma** [comment]
Smoke test suite now passes for MySql.Data version 6.10.1-beta that has support netstandard 1.6. I'd appreciate if you had the time to compile from source and kick the tires a bit more.
