### ISSUE TITLE
[Documentation] Migration to markdonw

### ISSUE THREAD

**Issue by Ledragon** [quartznet/quartznet#495]
Hi,
First and foremost, thanks for the amazing job on this, quartz.net is a freaking awesome library!
I was thinking about changing the README and CHANGELOG formats to markdown, to make these more GitHub friendly, is it something that would be of interest for you?

**Comment by lahma** [comment]
Sure thing, as long as they are "readable enough" using standard text editor (they are part of the distribution zip file). Please submit a PR if you like. Glad to hear you are enjoying Quartz.NET!

**Comment by Ledragon** [comment]
You can see what it would look like  [here](https://github.com/Ledragon/quartznet). If OK for you, I will complete the changelog before submitting the PR

**Comment by lahma** [comment]
Looks good to me, PR is welcome.

**Comment by lahma** [comment]
And if I can also kindly ask you to combine (squash) the commits to single one, it should describe the change well enough.

**Comment by lahma** [comment]
Merged to master, thanks.

**Comment by Ledragon** [comment]
Most welcome, my pleasure!
