### ISSUE TITLE
Duplicate schedulers

### ISSUE THREAD

**Issue by Worthy7** [quartznet/quartznet#499]
I am using Abp which integrates Quartz.net.

I have a very major problem whereby multiple Quartz schedulers occur, at some time after i webdeploy my  app and then a recycle happens.

I am writing about my entire experience here:
https://github.com/aspnetboilerplate/aspnetboilerplate/issues/2274

But essentially, it seems that a recycle of the app pool, is either not letting the worker die, or it is re-configuring the schedule and creating duplicate entries.

What I do know is, that after some extensive thread analysis, there are not multiple threads or processes, and that IIS is managing to properly shut down old processes on a recycle. Which leads me to really wonder how the hell quartz is actually being shutdown and restarted when a recycle happens?

I see that you are not implementing "IRegisteredObject" as mentioned by Haacked : http://haacked.com/archive/2011/10/16/the-dangers-of-implementing-recurring-background-tasks-in-asp-net.aspx/

And I see that you don't use "IProcessHostPreloadClient" either to register the back end work (https://stackoverflow.com/questions/11140597/iis-app-pool-recycle-quartz-scheduling)

So how is work managed in quartz when an worker recycle happens?

**Comment by lahma** [comment]
Have you tried shutting down the scheduler gracefully (scheduler.Shutdown) on Application_End?

**Comment by Worthy7** [comment]
I believe the current implementation is:
https://github.com/aspnetboilerplate/aspnetboilerplate/blob/f10fa5205c780bcc27adfe38aaae631f412eb7df/src/Abp.Quartz/Quartz/QuartzScheduleJobManager.cs#L55

If it is not getting called properly, is there a chance this could somehow cause duplicate instances of quartz to start (or just one instance whereby the config had been initialized twice?)


We had this problem for 2 weeks and I could not solve it, so in the end I had to stop using Quartz.net, and also Abp's worker\job system from within the asp app. Instead I use Scheduled tasks to an Api endpoint for the scheduling and I moved the worker/job system into a separate console app. We haven't had any problems since.

I could not easily reproduce the problem outside of the production environment. Which is what led me to believe this is related to load - but it's still not 100%.

**Comment by lahma** [comment]
I quickly glanced the source code and it seems that they do  shutdown on application end, but probably would require some debugging to know what's happening in this particular case. It could be race condition or something too.

As you've discovered, you might be better of using external process to host jobs. That's actually recommended for Quartz.NET usage too as ASP.NET isn't too reliable when it comes to recycles etc. Common pattern is to have Windows service (Quartz.Server in zip distribution) and control that remotely, maybe using non-started ZeroSizeThreadPool scheduler from web application, sharing a database.  

Sorry that you've had less than optimal experience, but I'm closing for now as too many moving parts to pinpoint the actual thing to fix here.
