### ISSUE TITLE
Quartz.NET 2.3.3 issue with using Oracle Managed Data Access, fails with ORA-12514 TNS:listener does not currently know of service requested in connect descriptor

### ISSUE THREAD

**Issue by raviragamz** [quartznet/quartznet#500]
We see intermittent connection issues with Oracle Managed Data Access  when used in tandem with Quartz.NET 2.3.3. It fails with ORA-12514 TNS: listener does not currently know of service requested in connect descriptor. Do you know of any computability issues with Oracle Managed Data Access.

FYI, earlier we didn't see this issue with Oracle Unmanaged data access.

**Comment by lahma** [comment]
By earlier do you mean earlier version of earlier version of managed data access libraries? Anyway, I'm pretty confident this is not the doings of Quartz.NET as there has been little changes to Oracle support in a long time. So can't really offer much help here, sorry for that.
