### ISSUE TITLE
Cannot run without an instance id.

### ISSUE THREAD

**Issue by nicolas-martin** [quartznet/quartznet#503]
### Version: 2.2.4.400
Windows 10

### Expected behavior
Get a scheduler

### Actual behavior
Error thrown `Cannot run without an instance id.`

```csharp
var schedulerFactory = new StdSchedulerFactory();
_quartzScheduler = schedulerFactory.GetScheduler();
```
```
{"exceptiontype":"Quartz.SchedulerException","exceptionmessage":"Couldn't get host name!","innerexceptionmessage":"The requested name is valid, but no data of the requested type was found"
 ```

I don't understand why, I'm seeing this error. Where is it trying to get the instance id from? 

I also included the logs from Quartz. But I don't understand what it's trying to do either.

**Comment by lahma** [comment]
Somehow local host name resolution seems to fail. The code in question that doesn't seem to work in your case can be found [here](https://github.com/quartznet/quartznet/blob/2.x/src/Quartz/Simpl/HostNameBasedIdGenerator.cs#L51). I haven't run into this problem before and seems that not many others either. 

Is there something specific to you networking setup with the computer in question?

**Comment by nicolas-martin** [comment]
I think you're right, must be a DNS related issue.

I fixed it by overriding the 2 default configs

```
<add key="quartz.scheduler.instanceName" value="{string}" />
<add key="quartz.scheduler.instanceId" value="{int}" />
```
