### ISSUE TITLE
Make LibLog public

### ISSUE THREAD

**Issue by shatl** [quartznet/quartznet#509]
Please define *LIBLOG_PUBLIC* so integrations projects for Quartz can reuse it for logging.

**Comment by lahma** [comment]
Sorry but I won't make it public. For your integration use case it would feel sound, but for others consuming the package it would open up another set of functionality that we'd had to support and keep intact API-wise.

I suggest you just copy-paste the LibLog.cs file and fix the namespace to correspond the integration project's namespace. I've done the same in Quartz-dependent projects that cannot see the internal APIs. The net effect is the same, though copy-paste might feel bad.
