### ISSUE TITLE
Using JobStore by sqlite,set the quartz.jobStore.clustered="true" lead to error

### ISSUE THREAD

**Issue by chenjiongran** [quartznet/quartznet#513]
### Expected behavior
I set the jobStore.driverDelegateType ="SQLiteDelegate" and set the clustered=true, the IScheduler.ScheduleJob(job, trigger) can pass;

but it throw the  SQL syntax   exception.
### Steps to reproduce
finally,I found in the Quartz.Impl.AdoJobStore.StdRowLockSemaphore,the sql santance is error.
the sqlite does not suppor the "for update" key word
```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
  public static readonly string SelectForLock =
            string.Format(CultureInfo.InvariantCulture, "SELECT * FROM {0}{1} WHERE {2} = {3} AND {4} = @lockName FOR UPDATE",
                          TablePrefixSubst, TableLocks, ColumnSchedulerName, SchedulerNameSubst, ColumnLockName);

```

**Comment by lahma** [comment]
You should use UpdateLockRowSemaphore for databases that do not support FOR UPDATE:

`properties["quartz.jobStore.lockHandler.type"] = "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz";`
