### ISSUE TITLE
Would you please add support for latest Oracle Managed Data Access provider (12.2)

### ISSUE THREAD

**Issue by barser** [quartznet/quartznet#527]

**Comment by lahma** [comment]
You should be able to get this working by using simple assembly binding redirect. In the future Quartz will just pick the version it can find (provider names will not contain version). You can also see programmatic version of creating a custom provider [here](https://github.com/quartznet/quartznet/issues/517#issuecomment-327516196).

**Comment by barser** [comment]
Thank you! It helped.
