### ISSUE TITLE
Possibility to run jobgroups on own scheduler instance

### ISSUE THREAD

**Issue by jordyvaneijk** [quartznet/quartznet#528]
Hi there, 

Is it possible to have a clustered scheduler and be able to set which instance is responsible for what job / jobgroup?

I have multiple jobs some of them are long running CPU intensive and others are not. 
I would like to be able to use just one scheduler database and have multiple jobs in it and tell the job to only run on instance A if it is a CPU intensive job and on instance B if it is CPU unintensive

I hope someone can help me on this issue

**Comment by lahma** [comment]
Unfortunately it's not possible at the moment. Java Quartz has such a feature as a paid add-on, might be something in the future to support. So the easiest solution is to dedicate a scheduler without using clustering.

**Comment by lahma** [comment]
Closing as no near future plans to implement. Let's see if this pops up again or someone wants to implement.
