### ISSUE TITLE
Scheduling jobs with Quartz.Server

### ISSUE THREAD

**Issue by ChrisDoernen** [quartznet/quartznet#530]
Hi there,

until now we use the Quartz.Server along with a plugin to execute jobs which are currently scheduled in a WCF Service using a scheduler instance with the same configuration as the Quartz.Server.

We recently found out this is the wrong way (running several scheduler instances with the same name against the same tables: https://www.quartz-scheduler.net/documentation/best-practices.html), but somehow it works. Probably because the trigger fire late enough for the "WCF-scheduler" to be disposed. 

We guess the correct way would be to schedule the jobs using the Quartz.Server but we can not figure out how to do that.

Best regards
Chris

**Comment by lahma** [comment]
If you want to just schedule and control jobs you can create a scheduler configured with ZeroSizeThreadPool and not start it. This will work as a sort of CRUD interface against the database.

**Comment by ChrisDoernen** [comment]
Okay, makes sense.

Thank you very much! Quartz.NET is great.

Hava a nice weekend
Chris

**Comment by lahma** [comment]
Sure, no problem. Enjoy!
