### ISSUE TITLE
Third party dependecies

### ISSUE THREAD

**Issue by Tron4Ever** [quartznet/quartznet#533]
Hi,

in the readme it is outlined : 

This product includes software developed by the Apache Software Foundation (http://www.apache.org/)

What software is included ? We need this information as part of our third party approval process .

Thanks
Robin

**Comment by lahma** [comment]
Thank you for bringing this important issue into attention. I have now updated the docs for both 2.x and 3.x. I have documented the run-time dependencies in the acknowledgements section.

* v3  (master) https://github.com/quartznet/quartznet/blob/master/README.md
* v2.x (2.x branch) https://github.com/quartznet/quartznet/blob/2.x/README.md

Please let me know if you need further clarifications.
