### ISSUE TITLE
Can not open project in visual studio 2015,2017

### ISSUE THREAD

**Issue by roshanghangare** [quartznet/quartznet#536]
### Steps to reproduce

```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```

**Comment by lahma** [comment]
Solution opens fine in VS 2017. Please give at least an error you are seeing, impossible to know what might be the cause for your problem.

**Comment by roshanghangare** [comment]
I am getting below error in visual studio 2017,

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - Quartz, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz\Quartz.csproj"
	 - Quartz.Tests.Unit, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz.Tests.Unit\Quartz.Tests.Unit.csproj"
	 - Quartz.Tests.Integration, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz.Tests.Integration\Quartz.Tests.Integration.csproj"
	 - Quartz.Examples, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz.Examples\Quartz.Examples.csproj"
	 - Quartz.Serialization.Json, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz.Serialization.Json\Quartz.Serialization.Json.csproj"


No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - Solution Items, "Solution Items"
	 - src, "src"
	 - Quartz, "D:\Quartz\quartznet-master\quartznet-master\Quartz.sln"

![image](https://user-images.githubusercontent.com/10380827/32095598-543326aa-bb21-11e7-9ce1-da998cc2b2ed.png)

**Comment by lahma** [comment]
What is the exact version of visual studio? You must have .net core sdk 2.0 installed too.
