### ISSUE TITLE
Unable to open solution in visual studio 2017 

### ISSUE THREAD

**Issue by roshanghangare** [quartznet/quartznet#537]
I am getting below error in visual studio 2017,

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them.
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
- Quartz, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz\Quartz.csproj"
- Quartz.Tests.Unit, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz.Tests.Unit\Quartz.Tests.Unit.csproj"
- Quartz.Tests.Integration, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz.Tests.Integration\Quartz.Tests.Integration.csproj"
- Quartz.Examples, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz.Examples\Quartz.Examples.csproj"
- Quartz.Serialization.Json, "D:\Quartz\quartznet-master\quartznet-master\src\Quartz.Serialization.Json\Quartz.Serialization.Json.csproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
- Solution Items, "Solution Items"
- src, "src"
- Quartz, "D:\Quartz\quartznet-master\quartznet-master\Quartz.sln"

image

**Comment by roshanghangare** [comment]
![image](https://user-images.githubusercontent.com/10380827/32095662-86fbfd14-bb21-11e7-975a-ab7b524a9909.png)

**Comment by lahma** [comment]
Please don't open duplicate issues. Conversation can continue even though and issue would be closed.
