### ISSUE TITLE
Infinite loop when using fall-ahead DST as a boundary with CronScheduler

### ISSUE THREAD

**Issue by thegrima** [quartznet/quartznet#540]
### Version

Version: 2.6.1

### Expected behavior

Code below should return and generate a list of dates.

### Actual behavior

Infinite loop in CronTriggerImpl when calling ComputeFireTimesBetween.

I've managed to check that CronExpression::GetTimeAfter is always return the same incorrect value to the trigger, thus the loop.

### Steps to reproduce

```csharp
            var tzi = TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time");
            var begin = new DateTime(2017, 10, 29, 01, 00, 00, DateTimeKind.Utc);
            var end = new DateTime(2017, 10, 29, 03, 00, 00, DateTimeKind.Utc);

            var triggerBuilder = TriggerBuilder.Create();

            var schedulerBuilder = CronScheduleBuilder
                    .CronSchedule("0 0/15 * * * ?")
                    .InTimeZone(tzi);

            var trigger = triggerBuilder
                    .WithSchedule(schedulerBuilder)
                    .Build() as IOperableTrigger;

            var dates = TriggerUtils.ComputeFireTimesBetween(trigger, null,
                new DateTimeOffset(begin),
                new DateTimeOffset(end));

            foreach (var d in dates)
            {
                Console.WriteLine(d);
            }

            Console.ReadKey();
```

**Comment by lahma** [comment]
You code is somewhat "evil" for the logic as start time hits the daylights saving ambiguity. ComputeFireTimesBetween tried to compensate that you are asking for past date even though trigger is in mode "start now", start date is after your end date. Code would just work if you'd use date one hour earlier:

    var begin = new DateTime(2017, 10, 29, 00, 00, 00, DateTimeKind.Utc);

I think we can change the logic for ComputeFireTimesBetween to jump two hours more backwards when it notices you are asking for past dates, this would compensate for daylight savings better in that case.

**Comment by thegrima** [comment]
Infinite loop also occurs when we explicitly specify offset so there is no ambiguity :

            var tzi = TimeZoneInfo.FindSystemTimeZoneById("W. Europe Standard Time");
            var begin = new DateTime(2017, 10, 29, 02, 00, 00, DateTimeKind.Local);
            var end = new DateTime(2017, 10, 29, 06, 00, 00, DateTimeKind.Local);

            var triggerBuilder = TriggerBuilder.Create();

            var schedulerBuilder = CronScheduleBuilder
                    .CronSchedule("0 0/15 * * * ?")
                    .InTimeZone(tzi);

            var trigger = triggerBuilder
                    .WithSchedule(schedulerBuilder)
                    .Build() as IOperableTrigger;

            var dates = TriggerUtils.ComputeFireTimesBetween(trigger, null,
                new DateTimeOffset(begin, TimeSpan.FromHours(1)),
                new DateTimeOffset(end, TimeSpan.FromHours(1)));

            foreach (var d in dates)
            {
                Console.WriteLine(d);
            }

            Console.ReadKey();

**Comment by Ledragon** [comment]
Hi,
I actually managed to narrow the problem down to `CronExpression.cs`. If you check [here](https://github.com/Ledragon/quartznet/blob/2.x/src/Quartz.Tests.Unit/CronExpressionTest.cs) (line 671), the `GetTimeAfter` method changes the offset from +1 to +2, whilst the input date is univoquely provided. I think line 2012 in `CronExpression.cs` should only be called under certain circumstances, but I have no idea what conditions to place (I am thinking something like "the input is in UTC, don't touch"). Hope this helps

**Comment by lahma** [comment]
I'm closing this as an old issue which should not affect 3.x series. We can reopen if someone has ideas for pull request to improve things.
