### ISSUE TITLE
Is the standard scheduler thread safe?

### ISSUE THREAD

**Issue by bontibon** [quartznet/quartznet#541]
### Version: 3.0.0-alpha3
 

Is it safe to call `ScheduleJob`, `TriggerJob`, etc. on the `IScheduler`s returned from `StdSchedulerFactory` from multiple threads?

**Comment by lahma** [comment]
Should be, until proven otherwise. Both RAMJobStore and and AdoJobStore use locks when they access job/trigger storage.
