### ISSUE TITLE
*x.RunAsLocalSystem();

### ISSUE THREAD

**Issue by 18965824402** [quartznet/quartznet#543]
发生了 System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.ServiceProcess.ServiceAccount' from assembly 'System.ServiceProcess, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  Source=<无法计算异常源>
  StackTrace:
   at Topshelf.RunAsExtensions.RunAsLocalSystem(HostConfigurator configurator)
   at HSCP.Task.Program.<>c.<Main>b__0_0(HostConfigurator x) in E:\conan\conan.net\conan.Task\Program.cs:line 21
   at Topshelf.HostFactory.New(Action`1 configureCallback)

   HostFactory.Run(x =>
            {
                x.Service<MainService>((s) =>
                {
                    s.ConstructUsing(settings => new MainService());
                    s.WhenStarted(tr => tr.Start());
                    s.WhenStopped(tr => tr.Stop());
                });
         #        **x.RunAsLocalSystem();**
                x.SetDescription("");
                x.SetDisplayName("家政云平台任务管理器");
                x.SetServiceName("HSCP.Task");

**Comment by lahma** [comment]
I'll close for now until we get better description about what has happened, what should have happened etc.
