### ISSUE TITLE
How can I specify/disallow a scheduler to execute certain jobs? #help wanted

### ISSUE THREAD

**Issue by alexaadi** [quartznet/quartznet#545]
### Version: 2.2.3

I am not sure if this is the proper place where to address this. I am searching for this for more than 2 days now...

Here is what I want to achieve: 
one of our clients has this scenario:
client has 2 servers:
1. with website A & quartz 1
2. With website B, 10 Workflow hosts and Quartz 2
Both Quartz are pointing to same db, same instance name.

If we are using a specific workflow that will use a lot of resources from server B. That is why we want that by that time only certain jobs will be executed by quartz on server B, like printing. Other heavier jobs we want to be executed only by server A at that moment.

Otherwise, when we know that server B is not that busy we want to configure that we could use at full potential all quartz hosts.

Is this possible to achieve? 

Which is the moment I should I change?
1. The moment when I create a job and assign to a scheduler? 
2. I assume that if both quartz servers have same connection to DB, the jobs will be stored in same db so I should only play at the moment I want to trigger a job. Is it possible to do that?

**Comment by lahma** [comment]
Unfortunately this is not possible at the moment. This would require similar functionality that [Java Quartz Where](http://ww1.terracotta.org/documentation/4.0/quartz-scheduler/quartz-scheduler-where) provides.
