### ISSUE TITLE
Weekly calendar silently excludes Saturdays and Sundays on creation

### ISSUE THREAD

**Issue by bratmn** [quartznet/quartznet#549]
### Expected behavior

When new WeeklyCalendar instance is created, no days are excluded by default.

### Actual behavior

When new WeeklyCalendar instance is created, Saturdays and Sundays are excluded by default. This behavior is not documented and not expected. 

### Steps to reproduce

```csharp
var calendar = new WeeklyCalendar();
Assert.False(calendar.IsDayExcluded(DayOfWeek.Sunday));
Assert.False(calendar.IsDayExcluded(DayOfWeek.Saturday));
```

**Comment by lahma** [comment]
Thanks for reporting this, I've updated the class summary documentation to state the default of weekends being excluded.
