### ISSUE TITLE
Misleading documentation for the AnnualCalendar.DaysExcluded property

### ISSUE THREAD

**Issue by bratmn** [quartznet/quartznet#550]
### Expected behavior

AnnualCalendar.DaysExcluded has unambiguous and accurate documenting comment.

### Actual behavior

Currently documenting comment is as on the snippet below. Looks like copy-paste from different type of calendar. Text itself also contains typos and mistakes e.g. _The array **must of size** greater or equal 31_; or: _Get or the array_.

```csharp
        /// <summary>
        /// Get or the array which defines the exclude-value of each day of month.
        /// Setting will redefine the array of days excluded. The array must of size greater or
        /// equal 31.
        /// </summary>
```

### Steps to reproduce

not applicable

**Comment by lahma** [comment]
Thanks for reporting, I've tried to improve the documentation to be less ambiguous.
