### ISSUE TITLE
Spring cron scheduler

### ISSUE THREAD

**Issue by manujadli** [quartznet/quartznet#558]
Hello Guys,

Need some advice.. There is a situation. We have implemented cron scheduling using spring(basically spring cron scheduling). This is packaged as an ear and is deployed on a cluster. Cluster is having 2 manage servers. Since its a cluster, deployment goes on both the servers and scheduler starts from both. Now both executes the logic.. Is there any way to stop or bypass the execution logic if one scheduler is executing ?

### Steps to reproduce

```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```

**Comment by lahma** [comment]
Seems like Java Quartz issue, please see their forum for advice.
