### ISSUE TITLE
NullReferenceException when creating DbProvider

### ISSUE THREAD

**Issue by kingofzeal** [quartznet/quartznet#560]
### Expected behavior
I am able to create a DbProvider without any exceptions.

### Actual behavior
I am attempting to create multiple scheduler instances (asynchronously) at startup of my application, each connecting to their own data store. Occasionally, I get a `NullReferenceException` when trying to create the `DbProvider`. Additionally, Log4Net records the following:

```
 System.NullReferenceException: Object reference not set to an instance of an object.
    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
    at Quartz.Impl.AdoJobStore.Common.DbProvider.GetDbMetadata(String providerName) in c:\projects\quartznet-6fcn8\src\Quartz\Impl\AdoJobStore\Common\DbProvider.cs:line 111
    at Quartz.Impl.AdoJobStore.Common.DbProvider..ctor(String dbProviderName, String connectionString) in c:\projects\quartznet-6fcn8\src\Quartz\Impl\AdoJobStore\Common\DbProvider.cs:line 71
    at SchedulerServiceFactory`1.SetupScheduler(SchedulerSetting schedulerSetting) in ...\SchedulerServiceFactory.cs:line 45
```

### Steps to reproduce
Unfortunately, I am unable to reliably reproduce this issue. As I mentioned earlier, the service this is part of spins up multiple scheduler instances asynchronously. In a majority of cases, all the schedulers start up without any issues, but sometimes one fails or more fail. When they do fail, the failure is always at the same point:
```csharp
var provider = new DbProvider("SqlServer-20", schedulerSetting.ConnectionString.ToString()); //<-- NullReferenceException here
DBConnectionManager.Instance.AddConnectionProvider(dataSourceName, provider);
```
I have verified that the connection string is always populated/not null at this point, so I'm unsure of what would be causing this error.

**Comment by lahma** [comment]
I think this is a concurrency issue caused by the fact that you initialize asynchronously.  Workaround until fix is released is to have your code protected with locking:

lock (DBConnectionManager.Instance)
{
   var provider = new DbProvider("SqlServer-20", schedulerSetting.ConnectionString.ToString()); 
   DBConnectionManager.Instance.AddConnectionProvider(dataSourceName, provider);
}
