### ISSUE TITLE
Quartz.Core.ErrorLogger is not very helpful, needs more content

### ISSUE THREAD

**Issue by eman1986** [quartznet/quartznet#561]
currently if a job failed with Quartz.net you get a very unhelpful message

> An error occurred instantiating job to be executed.

is it possible to provide some more content to this, like stack trace or a reason _why_ it failed. Currently when this message pops up, it's impossible to know why it failed and adding something can at least help other developers know what they're doing wrong.

**Comment by lahma** [comment]
What kind of logging have you configured? What version of Quartz.NET are you using? There should be stack trace available as it flows to normal logging.

**Comment by eman1986** [comment]
version 2.6.1

NLog to log things

**Comment by lahma** [comment]
Added original exception message to constructed exceptions. If someone wants to refine further, pull requests are welcome.
