### ISSUE TITLE
Quartz upgrade from 2.6.1 to 3.0.0 breaks initialization

### ISSUE THREAD

**Issue by pblanton** [quartznet/quartznet#566]
I have a Windows Service that uses Spring / Quartz. It is using Spring.Scheduling.Quartz2 v2.0.1 and Quartz 2.6.1. The jobs work in the service, and also in my unit tests.

I can't see anything that jumps out at me as being wrong, but When I upgrade to Quartz v3.0.0 I get the following initialization exception...

{"Error thrown by a dependency of object 'Spring.Scheduling.Quartz.SchedulerFactoryObject#0' defined in 'file [D:\\RickCollab\\MortyService\\Morty.Tests\\bin\\Debug\\JerryKillerJobTests.Xml] line 60' : Initialization of object failed : Cannot resolve type [Spring.Scheduling.Quartz.JobDetailObject, Spring.Scheduling.Quartz2] for object with name 'JerryKillerJob' defined in file [D:\\RickCollab\\MortyService\\Morty.Tests\\bin\\Debug\\JerryKillerJobTests.Xml] line 37\r\n while resolving 'triggers[0]' to 'JerryKillerJobSimpleTrigger' defined in 'file [D:\\RickCollab\\MortyService\\Morty.Tests\\bin\\Debug\\JerryKillerJobTests.Xml] line 53'"}
  
Rolling back to Quartz 2.6.1 repairs the issue.

Any ideas?

**Comment by lahma** [comment]
I believe that Quartz 2.x integration won't work with 3.x as both IJob and IScheduler interfaces (among others) have changed. So a separate Spring.Scheduling.Quartz3 would be required.

**Comment by lahma** [comment]
Quartz support has been upgraded on Spring.NET side and it should work. At the moment you need to compile Spring.NET by hand though.
