### ISSUE TITLE
A specific CronExpression fails with "Input string was not in a correct format."

### ISSUE THREAD

**Issue by meastp** [quartznet/quartznet#568]
### Expected behavior

No error.

### Actual behavior

Fails with exception "Input string was not in a correct format."

### Steps to reproduce

```csharp
var cron_expr = "0 0 18-21/1 ? * MON,TUE,WED,THU,FRI,SAT,SUN";
CronExpression.IsValidExpression(cron_expr); // should be true, but throws exception
```
I have tested this with the http://www.cronmaker.com/ and it seems to work (no error and shows correct run times).

**Comment by lahma** [comment]
Thanks for reporting this, fixed now in master, will be part of next maintenance release 3.0.1.

**Comment by meastp** [comment]
Thank you for the quick fix (and release)!
