### ISSUE TITLE
Question - Using single Quartz DB instance for multiple quartz.server clustered services

### ISSUE THREAD

**Issue by Ravivishnubhotla** [quartznet/quartznet#569]
I am upgrading several existing quartz.server services each consisting of multiple jobs. These are jobs are clustered. In total I have 7 services. Can I have a single DB instance storing the job information for all these services? Is that an acceptable practice. Do you guys see any locking or db issues here?

Version - 3.0

### Steps to reproduce

```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```

**Comment by lahma** [comment]
This should be valid. If your hardware scales. You can share database by using different scheduler names if separation is needed.
