### ISSUE TITLE
The "0 0 0 ? * Mon/2" is an invalid cron string with quartz 3.0.1

### ISSUE THREAD

**Issue by guotuofeng** [quartznet/quartznet#573]
### Expected behavior

The  "0 0 0 ? * Mon/2" should be a valid cron string which should be triggered every two weeks on Monday.

In Quartz 2.5, it works fine.

### Actual behavior

The exception is thrown

System.FormatException: 'Illegal characters for this position: 'MON''

### Steps to reproduce

```csharp
            var cron_expr = "0 0 0 ? * Mon/2";
            CronExpression.IsValidExpression(cron_expr); // should be true, but return false

```

**Comment by lahma** [comment]
I believe this did parse as valid in 2.x but did never obey the every second week rule. This is why the validation now throws error as it's not supported.

**Comment by toolgood** [comment]
This error also exists in 3.06.

**Comment by lahma** [comment]
I believe this was fixed with https://github.com/quartznet/quartznet/pull/790 and already part of 3.1 beta 1.
