### ISSUE TITLE
I Can't build quartz.web project

### ISSUE THREAD

**Issue by xijianyao** [quartznet/quartznet#575]
I Can't build quartz.web project.
The project has many errors.
Like :
(TS) "Promise" must have the same type parameters.
Promise<T,R> need two type parameters.
Can't find module aurelia-framework.

Seems like typescript's error.But  I can not use typescript.
How can i resolve these errors.
![tim 20180123111538](https://user-images.githubusercontent.com/13430322/35256717-19ce72cc-0030-11e8-9f08-53064769948d.png)

**Comment by lahma** [comment]
Quartz.Web is not part of master's Quartz.sln so this should not be a problem if you try to compile from 3.0.1 sources. Web is not currently under active development.
