### ISSUE TITLE
Error communicating with remote scheduler.

### ISSUE THREAD

**Issue by Sicos1977** [quartznet/quartznet#578]
### Version: 3.0.1

Trying to get information from the scheduler with .NET remoting

```csharp
                var jobInfos = new List<JobInfo>();
                var jobGroups = _scheduler.GetJobGroupNames().Result;

                foreach (var group in jobGroups)
                {
                    var groupMatcher = GroupMatcher<JobKey>.GroupContains(group);
                    var jobKeys = _scheduler.GetJobKeys(groupMatcher).Result; // <--- this line is raising the exception
                    foreach (var jobKey in jobKeys)
                    {
                        var jobDetail = _scheduler.GetJobDetail(jobKey).Result;

                        var jobInfo = new JobInfo
                        {
                            JobKey = jobKey,
                            Description = jobDetail.Description,
                            Durable = jobDetail.Durable,
                            RequestRecovery = jobDetail.RequestsRecovery,
                            TriggersInfo = new List<JobTriggerInfo>(),
                            JobDataMap = JobDataMapToJobDataMapItem(jobDetail.JobDataMap),
                            Paused = true
                        };
....
```

### Expected behavior

Returning a list of jobkeys

### Actual behavior

Exception: Error communicating with remote scheduler.

Stack trace:
```
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Quartz.Simpl.IRemotableQuartzScheduler.GetJobKeys(GroupMatcher`1 matcher)
   at Quartz.Impl.RemoteScheduler.<>c__DisplayClass53_0.<GetJobKeys>b__0(IRemotableQuartzScheduler x)
   at Quartz.Impl.RemoteScheduler.CallInGuard[T](Func`2 func)
```

Has this something to do with your latest commit? #576 and if so is there an easy fix or do I need to clone the code and build it?

**Comment by lahma** [comment]
I just published 3.0.2, it should appear on NuGet soon. Please check if this fixes the issue.

**Comment by Sicos1977** [comment]
:-) I just manually compiled the code... checking it now if it fixes the problem

**Comment by Sicos1977** [comment]
Well it fixes one problem, but now I get (I think) a similar problem when retrieving the active jobs.

**Comment by Sicos1977** [comment]
It now fails on this line in my code:

`var contexts = _scheduler.GetCurrentlyExecutingJobs().Result;`

**Comment by Sicos1977** [comment]
When there are no jobs running then the remoting works but when there are jobs executing than it fails.

![image](https://user-images.githubusercontent.com/6692947/35380320-39ac72ee-01b9-11e8-9f72-8c9e859ffdd0.png)

**Comment by lahma** [comment]
Umm that seems pretty much horrifically  broken from start. These method has really been flying under the radar. To make it sensible it would need all different return value than context that is tightly bound to running server instance. 

Unfortunately I really don't have a fast and easy solution for this.

**Comment by Sicos1977** [comment]
I just debugged your source and the problem is with the CancellationToken ... this one is not serializable

```csharp
        /// <summary>
        /// Returns the cancellation token which will be cancelled when the job cancellation has been requested via
        /// <see cref="IScheduler.Interrupt(JobKey, CancellationToken)"/>
        /// or <see cref="IScheduler.Interrupt(string, CancellationToken)"/>.
        /// </summary>
        CancellationToken CancellationToken { get; }
```


Type 'System.Threading.CancellationTokenSource' in Assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.

**Comment by lahma** [comment]
Unfortunately that was just the tip of the iceberg, next things you would encounter are scheduler not being serializable etc.

**Comment by Sicos1977** [comment]
Well what I don't understand is why this does not work in v3.x it used to work fine in v2.x. What has changed and is it an option to use JSON instead or is this giving the same problems?

**Comment by Sicos1977** [comment]
Any tips for me where to look to fix this? And why did this work without problems in version 2.X?

**Comment by lahma** [comment]
I think it was around https://github.com/quartznet/quartznet/commit/1953d68b3926fbb1774253bccebfd727ffb66114#diff-2c121fd85ced5de8483fa985292b81b9L73 where things were shifting rapidly. Fields should have NonSerializable to indicate they are too statefull. Quick band-aid would be to have the old attributes restored.

In the long of course should have specialized DTO to describe running state.

**Comment by Sicos1977** [comment]
Well I have given up and switched back to an older version. They serialization is broken when you switched to using the IJobExecutionContextImpl interface instead of a class. I tried [NonSerialized] and [XmlIgnore] on almost every field in the class but the serializer just keeps ignoring them and fails when it tries to serialize the Scheduler property. Also tried ShouldSerializeScheduler but that also doesn't work.

**Comment by lahma** [comment]
I'll be travelling rest of the week so It'll be next week when I have next chance to try to fix this.

**Comment by Sicos1977** [comment]
I tried a new approach and that seemed to fix 2 problems.

```csharp
        [OnSerializing]
        [OnDeserialized]
        private void IgnoreNonSerializableProperties(StreamingContext context)
        {
            Scheduler = null;
            JobInstance = null;
        }
```
But now the problem is 
`System.Runtime.Serialization.SerializationException : Type 'System.Threading.CancellationToken' in Assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.`

And that one is not nullable.

I did some more reading and it seems that you cant control properties with attributes when serializing. And that is probably the root cause of this problem. You switched from private fields to properties because of the interface implementation.

**Comment by lahma** [comment]
Yes, they need to be converted to fields with [NonSerializable] attrribute.

**Comment by Sicos1977** [comment]
Nevermind, I think that I have fixed it. I just switched to properties with backing fields and put the NonSerializeble on them.

**Comment by Sicos1977** [comment]
Yes it is fixed, Ill send you a pull request for this :-)

**Comment by Sicos1977** [comment]
You should have a pull request now.

**Comment by Sicos1977** [comment]
I was just staring myself blind on this and the solution was just easy :-)
