### ISSUE TITLE
SQL command parameters are not defined in 'IsTriggerStillPresent' method

### ISSUE THREAD

**Issue by Devkamik** [quartznet/quartznet#579]
### Expected behavior
'IsTriggerStillPresent' method should be executed successfully if all input parameters were defined correctly.

### Actual behavior
The method always throws an System.Data.SqlClient.SqlException "Must declare the scalar variable '@triggerName'".

### Steps to reproduce
This method is used only in cases when a scheduler fails a loading of trigger extended properties with InvalidOperationException. So issue can be reproduced if the record with extended properties were deleted in database manually or as a result of some another issue.

```csharp
private async Task<bool> IsTriggerStillPresent(
            ConnectionAndTransactionHolder conn,
            CancellationToken cancellationToken)
        {
            using (var cmd = PrepareCommand(conn, ReplaceTablePrefix(SqlSelectTrigger)))
            {
                using (var rs = await cmd.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false))
                {
                    return await rs.ReadAsync(cancellationToken).ConfigureAwait(false);
                }
            }
        }
```

**Comment by lahma** [comment]
Thanks for reporting this, I've scheduled it for next maintenance release. A PR with addition to AdoJobStoreSmokeTest would be great!

**Comment by Sicos1977** [comment]
Any tips for me where to look to fix this? And why did this work without problems in version 2.X?
