### ISSUE TITLE
NextFireTimeUtc not set in JobListener after fired explicit

### ISSUE THREAD

**Issue by andersonrocha** [quartznet/quartznet#581]
### Expected behavior
I have a Listener linked to my Job. When the job is fired automatically in the **JobWasExecuted** method of the Listener, the property **context.NextFireTimeUtc property** is populated, but if I call the job explicitly with **`await sched.TriggerJob(new JobKey(nameJob))`**, the property is not set, even the job having a future execution.

### Steps to reproduce
Create a Job, implemment a IJobListener, and fired the job with:
`var sched = await StdSchedulerFactory.GetDefaultScheduler();`
`await sched.TriggerJob(new JobKey(nameJob))`

**Comment by lahma** [comment]
I believe this is because of the fact that `TriggerJob` creates a one-shot temporary trigger and the `JobWasExecuted` will reflect the running trigger's next fire time - which is none in this case.
