### ISSUE TITLE
Jobs is running and stays that forever but does not do anything

### ISSUE THREAD

**Issue by Sicos1977** [quartznet/quartznet#582]
Hi,

Quartz.Net version 3.0.2

With the following code I'm creating a job in the scheduler

```csharp
            GetJobAndTriggerKey(job, out var jobKey, out var triggerKey);

            if (Scheduler.CheckExists(jobKey).Result) return;

            IJobDetail schedulerJob;

            if (jobDataMap != null)
            {
                schedulerJob = JobBuilder.Create(job.GetType())
                    .WithIdentity(jobKey)
                    .WithDescription(job.Info)
                    .RequestRecovery(true)
                    .SetJobData(jobDataMap)
                    .Build();
            }
            else
            {
                schedulerJob = JobBuilder.Create(job.GetType())
                    .WithIdentity(jobKey)
                    .WithDescription(job.Info)
                    .RequestRecovery(true)
                    .Build();
            }


            ITrigger schedulerTrigger = (ISimpleTrigger) TriggerBuilder.Create()
                .WithIdentity(triggerKey)
                .WithDescription(job.Info)
                .StartNow()
                .Build();

            _scheduler.ScheduleJob(schedulerJob, schedulerTrigger);
```

The jobs gets created but nothing happens, the code that is inside the job is not executed and the jobs stays in the running state forever.

I added extra logging and this is what QuartzNet is saying about that job
```
[Quartz.Core.QuartzSchedulerThread] - [Debug] Batch acquisition of 0 triggers  
[Quartz.Core.JobRunShell] - [Debug] Calling Execute on job SystemJob.0@Stockist pipeline  
```

To me it looks like that the job has no trigger, but if so how did it get in the running state and why does is stay there forever?

Do you have any idea what is going wrong overhere?

**Comment by lahma** [comment]
Debugger should show the state of running jobs. Without seeing the actual job, hard to say. I hope that you are not at least using .Result inside the job - you should always call .GetAwaiter().GetResult() - Unwrap extension methods are quite easy to do.

**Comment by lahma** [comment]
You could also specify repeating explicitly, usually generic trigger builder does not show intent well:

```
TriggerBuilder.Create()
    .WithIdentity(triggerKey)
    .WithDescription(job.Info)
    .StartNow()
    .WithSimpleSchedule(x => x
        .WithInterval(TimeSpan.FromSeconds(1))
        .RepeatForever()
    )
    .Build()
```

**Comment by Sicos1977** [comment]
I don't want to run the job more then once. It should fire just once and then stop.

**Comment by lahma** [comment]
I would then just call IScheduler's TriggerJob:

```
        /// <summary>
        /// Trigger the identified <see cref="IJob" /> (Execute it now) - with a non-volatile trigger.
        /// </summary>
        public virtual async Task TriggerJob(
            JobKey jobKey,
            JobDataMap data,
            CancellationToken cancellationToken = default)
```

**Comment by Khoosham** [comment]
Hello looks like i am getting the same issue.
I have put logger in all my method to check if it goes inside..
i have started the trigger in IIS Preload function that check for the new jobs in my db with status new.
i have another scheduler/trigger that schedules the job where i have implemented myJobListener inside which i have the method JobTobeExecuted i have put a logger in that method it goes inside it but never to the Execute part.

if i start the scheduler thats check for my new jobs in db in application_start (global.asax) then it works fine.
Note that it was working before maybe v 3.0.1 i have upgraded to v3.0.2 recently but did not revert back to check.

Can you let me know the write way to start the main scheduler that check for new job in my db 
Thank you !

**Comment by Sicos1977** [comment]
My issue is solved, I had a custom JobListener with some code in the JobWasExecuted method. This code raised an exception in some cases and that prevented QuartzNet to remove the Job.

**Comment by Khoosham** [comment]
I solved the issue in my case as well
in the job listener method i was using Task.Completed which prevented the execute from happening.
I have use Task.FromResult(true); and inside JobExecutionVetoed Method Task.FromResult(false);
