### ISSUE TITLE
Does the method StartAt() understand time changes like a minute?

### ISSUE THREAD

**Issue by Pooriairoop** [quartznet/quartznet#585]
Quartz Version 3.0.2

Does the method `StartAt()` understand time?
I just wanted to test my job for one minute later to see if it work but nothing happened. does this method count minutes?

my code id like
`ISimpleTrigger trigger = (ISimpleTrigger)TriggerBuilder.Create()
            .WithIdentity("LCP", "weeklyMessages")
            .ForJob("LCPJob", "WeeklyMassages")
            .StartAt(registrationDate)
            .Build();`

and `registrationDate` is like
`JobScheduler.Start(DateTime.Now.AddMinutes(1), chatId);`

I expect the `DateTime.Now.AddMinutes` to pass one min after the recent time and job execute one minute later but nothing happens

**Comment by lahma** [comment]
You need to provide scheduler with UTC times, so this would be correct:

`JobScheduler.Start(DateTime.UtcNow.AddMinutes(1), chatId);`

Also remember to start the scheduler.
