### ISSUE TITLE
When  remoting scheduler is supported in dotnet core?

### ISSUE THREAD

**Issue by answerforever** [quartznet/quartznet#588]
I'm coding a job manager website by using quartznet library in my dotnet core project.So far,remoting scheduler is not supported in dotnet core 2.0,is there any plan for supporting in dotnet core 2.0?

**Comment by lahma** [comment]
The .NET Remoting will never be supported as .NET Core doesn't support that. Remote management is covered with this issue https://github.com/quartznet/quartznet/issues/511 , which doesn't have any timeline yet unfortunately.
