### ISSUE TITLE
Quartz.NET 3.0 application requires Full Control while accessing XML File

### ISSUE THREAD

**Issue by meetakherdekar** [quartznet/quartznet#591]
### Version: x.y.z
3.0 

### Expected behavior

Application should work fine even with Read & Execute permission

### Actual behavior

Application throws the error Access is Denied

### Steps to reproduce

Quartz.NET 3.0 uses using (var stream = File.Open(fileName, FileMode.Open)) to open the XML file.
By Default; File.Open uses FileAccess of ReadWrite when opening the file. Quartz only needs to read the file so it should use FileAccess.Read when opening the file.
Our Prod servers do not provide Full Control folders containing XML file and hence the application fails with the error Access denied when reading the xml file.

**Comment by lahma** [comment]
Thanks for reporting the issue, I've changed the reading to use FileAccess.Read.

**Comment by meetakherdekar** [comment]
When is 3.0.3 being released?

**Comment by lahma** [comment]
@meetakherdekar 3.0.3 is now available on NuGet.
