### ISSUE TITLE
Memory leak in Quartz Firebird combination

### ISSUE THREAD

**Issue by ankur-chhabra** [quartznet/quartznet#600]
The quartz scheduler thread is leaking around 100 Mb per day. I am using Quartz 3.0.0-beta 1 version.

It looks like CancellationToken source size is increasing due to the callbacks from Firebird.
The quartz is not clearing out the Callback references and the list continues to increase which in other words is increasing the size of Cancellation token source.

Hence with each passing day, the leakage is increasing.

**Comment by lahma** [comment]
Did you get a trace about what is keeping the references alive?

**Comment by ankur-chhabra** [comment]
Well we ran the memory profiler and it pointed to some cancellation token sources which were increasing in size and all of them were linked to Quartz scheduler thread and the call back functions..
![quartz1](https://user-images.githubusercontent.com/37005318/36931391-2f8b6082-1e69-11e8-9020-2d3406f3ee5d.png)
![q2](https://user-images.githubusercontent.com/37005318/36931392-327979c8-1e69-11e8-8f51-8b0d8c3a71c9.png)

**Comment by ankur-chhabra** [comment]
![callbacklist](https://user-images.githubusercontent.com/37005318/36931664-d64ba71e-1e6f-11e8-9bd6-3e6bab8977a9.png)

Attaching the growing callback list..

**Comment by ankur-chhabra** [comment]
Also, correct me if I am wrong...the Shtudown of scheduler is just cancelling the CanellationTokenSource..
There is no dispose of CanellationTokenSource..

**Comment by lahma** [comment]
Thank you for the detailed analysis.  You are correct, you cannot start a scheduler that has been shut down. I need to create a repro for this to analyze and get my head around it.

**Comment by lahma** [comment]
This was caused by wrong sharing of scheduler's token source to downstream services. Now fixed in master and the fix will be part of next maintenance release.

Thanks for the report and details!

**Comment by ankur-chhabra** [comment]
Thanks a lot for the quick commit.....Any tentative date for the next release 3.0.4 which will include this commit in it??

**Comment by lahma** [comment]
The 3.0.4 has been just released, you should see it on NuGet now.
