### ISSUE TITLE
Error: There is no metadata information for provider 'MySql-51'

### ISSUE THREAD

**Issue by KamranShahid** [quartznet/quartznet#601]
I have .net 4.5.2 application with quartz.net 3.0.4. I am trying to use adojobstore with mysql as database
My configuration is 
```

    <add key="quartz.scheduler.instanceName" value="DBScheduler" />
    <add key="quartz.threadPool.type" value="Quartz.Simpl.SimpleThreadPool, Quartz" />
    <add key="quartz.threadPool.threadCount" value="100" />
    <add key="quartz.threadPool.threadPriority" value="2" />
    <add key="quartz.scheduler.dbFailureRetryInterval" value="6000000000" />
    <add key="quartz.jobStore.driverDelegateType" value="Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz" />
    <add key="quartz.jobStore.tablePrefix" value="QRTZ_" />
    <add key="quartz.jobStore.misfireThreshold" value="600000" />
    <add key="quartz.jobStore.type" value="Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" />
    <add key="quartz.jobStore.dataSource" value="myDS" />
    <add key="quartz.dataSource.myDS.connectionString" value="Server=localhost;Port=3306;database=quartznet;Uid=root;pwd=root;allow user variables=true;CharSet=utf8;" />
    <add key="quartz.dataSource.myDS.provider" value="MySql-51" />
```

I am always getting error 
Could not Initialize DataSource: myDS
Inner Exception: There is no metadata information for provider 'MySql-51'
Parameter name: providerName

Please help me identify the problem

I have even tried `<add key="quartz.dataSource.myDS.provider" value="MySql" />`

**Comment by lahma** [comment]
Sorry about the confusion. The [documentation](https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/job-stores.html) was not up to date. Now I have updated the docs to not have the version postfix for the providers. So you should replace "Mysql-51" with "MySql".

**Comment by KamranShahid** [comment]
Thanks Lahma
One strange thing is that though mysql connector is installed in My GAC and other application is working fine. My Mysql.Data location in GAC was C:\Windows\Microsoft.NET\assembly\GAC_MSIL\MySql.Data
But quartz sample was not working. then i have manually copied the file and atleast above error is removed. Now investigating that why it is not referencing it from GAC.
Thanks a lot

**Comment by lahma** [comment]
3.x has removed strict versioning of DLLs, so it tries to load from working directory. This enables you to have reference in your project for the version you want without the need of binding redirects. You could get old behavior by manually registering specific version with strong key etc defined.

So easiest is to have PackageReference/packages.config/Reference to the version of connection you want to use.

**Comment by KamranShahid** [comment]
Thanks Lahma

**Comment by RavindraV07** [comment]
Hi ,
I am working Quartz 3.0.7 + with the Dot net core. I have given all the information but I am getting this error.

"Could not load file or assembly 'MySql.Data, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified."

Because for connecting to MySQL with the core I have added "Pomelo.EntityFrameworkCore.MySql"

    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.8" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.1.4" />
    <PackageReference Include="Quartz" Version="3.0.7" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />

/////////////////////////////////////////////////////////////////////////////

private NameValueCollection LoadQuartzProperties()
        {
            var NameValueCollection = new NameValueCollection();
            NameValueCollection.Add("quartz.scheduler.instanceName", "HomRoverScheduler");
            NameValueCollection.Add("quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz");
            NameValueCollection.Add("quartz.jobStore.driverDelegateType", "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz");
            NameValueCollection.Add("quartz.jobStore.useProperties", "false");
            NameValueCollection.Add("quartz.jobStore.dataSource", "myDS");
            NameValueCollection.Add("quartz.jobStore.tablePrefix", "QRTZ_");
            NameValueCollection.Add("quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz");
            //NameValueCollection.Add("quartz.jobStore.selectWithLockSQL", "select * from {0} LOCKS UPDLOCK WHERE LOCK_NAME = @lockName");
            NameValueCollection.Add("quartz.dataSource.myDS.provider", "MySql");
            NameValueCollection.Add("quartz.dataSource.myDS.connectionString", "server=homeroverrds---;database=--;user=--;pwd=--;TreatTinyAsBoolean=false");
            NameValueCollection.Add("quartz.threadPool.threadCount", "50");
            NameValueCollection.Add("quartz.threadPool.threadPriority", "1");
            return NameValueCollection;
        }

Shall I need to install Mysql.dll again?

Please help me.
