### ISSUE TITLE
Support  Oracle.ManagedDataAccess.Core

### ISSUE THREAD

**Issue by EwaldStricker** [quartznet/quartznet#609]
Versions: Quartz 3.0.4, Microsoft.AspNetCore.All 2.0.5, Oracle.ManagedDataAccess.Core 2.12.0-beta2

Expected behavior: Propper initialization
ISchedulerFactory sf = new StdSchedulerFactory();
sf.GetScheduler().Result;

Actual behavior: throws ArgumentOutOfRangeException: There is no metadata information for provider 'OracleODPManaged'

Steps to reproduce:
- quartz.config
...
quartz.jobStore.type = Quartz.Impl.AdoJobStore.JobStoreTX, Quartz 
quartz.jobStore.driverDelegateType = Quartz.Impl.AdoJobStore.OracleDelegate, Quartz 
quartz.jobStore.misfireThreshold = 60000
quartz.jobStore.tablePrefix = QRTZ_
quartz.jobStore.dataSource = OracleSqlDs
quartz.dataSource.OracleSqlDs.connectionString = Data Source= (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=hhhh)(PORT=pppp))(CONNECT_DATA=(SID=ssss)));User Id=myUsername;Password=myPassword;
quartz.dataSource.OracleSqlDs.provider = OracleODPManaged
...

csharp: see Expected behavior:

**Comment by lahma** [comment]
The beta driver hasn't support yet. You could try manually adding the configuration, [here's an example of adding such properties](https://github.com/quartznet/quartznet/blob/master/src/Quartz.Examples/quartz.config). [Current Oracle setup](https://github.com/quartznet/quartznet/blob/master/src/Quartz/Impl/AdoJobStore/Common/dbproviders.properties#L31) probably is the best to follow to get settings right.

**Comment by EwaldStricker** [comment]
Hi thanks foe the quick response
I can try it out later and will give you feedback. 

kr Ewald

Mit freundlichen Grüßen 

Ewald Stricker

Am 23.03.18 um 12:08 schrieb Marko Lahma

The beta driver hasn't support yet. You could try manually adding the configuration, [here's an example of adding such properties](https://github.com/quartznet/quartznet/blob/master/src/Quartz.Examples/quartz.config). [Current Oracle setup](https://github.com/quartznet/quartznet/blob/master/src/Quartz/Impl/AdoJobStore/Common/dbproviders.properties#L31) probably is the best to follow to get settings right.

**Comment by EwaldStricker** [comment]
Hi Iahma,
thanks for your answer. 
Do I  get you right:
Based on my technical requirements (target Framework .Net Core 2.0 not .NET Framework 4.6.1 that runs properly!) I have to use Oracle.ManagedDataAccess.Core 2.12.0-beta2 (using  Oracle.ManagedDataAccess. throws „ ... files are not compatible with that Framework“) which is not supported yet. 
So I have not an issue but a feature request?

**Comment by lahma** [comment]
Yes there is no out-of-the-box support for .NET Core version of Oracle data access libraries. You need to configure it in your quartz.config (or properties for scheduler) by yourself. This has not of course been tested how it behaves.

**Comment by lahma** [comment]
With 3.0.5 you should be able to use new provider with name OracleODPManaged out of the box.
