### ISSUE TITLE
Quartz 2.6.0: Trigger loop encountered using DailyTimeIntervalTrigger across DST start boundary

### ISSUE THREAD

**Issue by Wojtekxor2** [quartznet/quartznet#610]
This seemed to be fixed in the thread:
https://github.com/quartznet/quartznet/issues/332

However, in that version (2.6.0) that issue still happens:

In the trigger set-up like this:

ITrigger trigger1 = TriggerBuilder.Create()
                    .WithDailyTimeIntervalSchedule
                    (s =>
                        s.StartingDailyAt(TimeOfDay.HourAndMinuteOfDay(19, 0))
                         .EndingDailyAt(TimeOfDay.HourAndMinuteOfDay(23, 59))
                         .WithIntervalInMinutes(60)
                         .WithMisfireHandlingInstructionDoNothing()
                         .OnEveryDay()
                    )
                    .Build();

Before 19:00 o'clock the trigger starts straightforward and goes into infinite loop.
That happens only on the 25th of March 2018...

**Comment by lahma** [comment]
Fix ported for 3.x and 2.x branches.
