### ISSUE TITLE
Error communicating with remote scheduler

### ISSUE THREAD

**Issue by moumenmosa** [quartznet/quartznet#614]
I used it to connect on quartz.net V 3.0.4 in .net core but actually i faced issue while i try to connect using proxy it gave "Error communicating with remote scheduler."
the configration it is as below

key="quartz.scheduler.exporter.type" value="Quartz.Simpl.RemotingSchedulerExporter, Quartz" key="quartz.scheduler.exporter.port" value="555" key="quartz.scheduler.exporter.bindName" value="QuartzScheduler" key="quartz.scheduler.exporter.channelType" value="tcp" key="quartz.scheduler.exporter.channelName" value="httpQuartz" key="quartz.scheduler.instanceName" value="RemoteServerSchedulerClient" key="quartz.threadPool.type" value="Quartz.Simpl.SimpleThreadPool, Quartz" key="quartz.threadPool.threadCount" value="5" key="quartz.threadPool.threadPriority" value="Normal" key="quartz.scheduler.proxy" value="true" key="quartz.scheduler.proxy.address" value="tcp://127.0.0.1:555/QuartzScheduler" key="quartz.jobStore.type" value="Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" key="quartz.jobStore.dataSource" value="myDS" key="quartz.jobStore.driverDelegateType" value="Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz" key="quartz.jobStore.lockHandler.type" value="Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz" key="quartz.jobStore.tablePrefix" value="QRTZ_" key="quartz.jobStore.clustered" value="false" key="quartz.dataSource.myDS.connectionString" value="Server=.;Database=QuartzDB;Persist Security Info=True;User ID=sa;Password=123;" key="quartz.dataSource.myDS.provider" value="SqlServer" key="quartz.jobStore.useProperties" value="true" key="quartz.serializer.type" value="json"

i think still it is not supported for .net core :(

**Comment by lahma** [comment]
Yes, sorry about that. HTTP API would be requirement for .NET Core usage, which is tracked here #511 .
