### ISSUE TITLE
Quartz database is growing infinitely

### ISSUE THREAD

**Issue by kristofdc** [quartznet/quartznet#621]
### Expected behavior

Quartz database is NOT growing infinitely

### Actual behavior
* Web API 2 project (IIS / OWIN) - which need to run 7d/24h (-> without recycling)

* In case a job is putting an item in the JobDataMap item during an jobexecution, the $type parameter is added to the JobData in database. The value of $type extends each time the job puts an item in the JobDataMap.

JOB_DATA field in QRTZ_JOB_DETAILS table is growing infinitely:
"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib","$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib"
...
"$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib","$type":"System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib,System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib,System.Collections.
...

### Actual Configuration
```xml
    <!-- Scheduler -->
    <add key="quartz.scheduler.instanceName" value="MyScheduler" />

    <!-- ThreadPool -->
    <add key="quartz.threadPool.type" value="Quartz.Simpl.DefaultThreadPool, Quartz" />
    <add key="quartz.threadPool.threadCount" value="1" />

    <!-- JobStore -->
    <add key="quartz.jobStore.type" value="Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" />
    <add key="quartz.jobStore.tablePrefix" value="QRTZ_" />
    <add key="quartz.jobStore.clustered" value="false" />
    <add key="quartz.jobStore.lockHandler.type" value="Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz" />
    <add key="quartz.jobStore.driverDelegateType" value="Quartz.Impl.AdoJobStore.FirebirdDelegate, Quartz" />
    <add key="quartz.jobStore.dataSource" value="JobSchedulerDataSource" />

    <!-- use strings as JobDataMap values -->
    <add key="quartz.jobStore.useProperties" value="true" />

    <!-- DataSource -->
    <add key="quartz.dataSource.JobSchedulerDataSource.provider" value="Firebird" />

    <add key="quartz.plugin.jobInitializer.type" value="Quartz.Plugin.Xml.XMLSchedulingDataProcessorPlugin, Quartz.Plugins" />
    <add key="quartz.plugin.jobInitializer.fileNames" value="./quartz_jobs.xml" />
    <add key="quartz.plugin.jobInitializer.failOnFileNotFound" value="true" />
    <add key="quartz.plugin.jobInitializer.scanInterval" value="120" />

    <!--Serialization-->
    <add key="quartz.serializer.type" value="json" />
```

### Steps to reproduce
Calling context.JobDetail.JobDataMap.PutAsString() during job execution by using the configuration above.

JOB_DATA column ($type value) is shrinked after restarting the IIS process, but that's not what we want.

### Comments
I think there is a problem with the JSON serialization. (TypeNameHandling?)
Can anyone help to explain this behavior?

**Comment by lahma** [comment]
Sorry for the late reply. I'm so far been unable to reproduce this behavior, did you find the root cause?

**Comment by lahma** [comment]
I've changed the type name handling to be auto for the next 3.0.7 release, thanks for the feedback and details!
