### ISSUE TITLE
construct a schedulerFactory using NameValueCollection can not start

### ISSUE THREAD

**Issue by xijianyao** [quartznet/quartznet#625]
Hello 
  When I use NameValueCollection to construct a schedulerFactory like the picture first time.It can work and update the column LAST_CHECKIN_TIME of table [QRTZ_SCHEDULER_STATE] in one second.
  But I run this project in same setting of NameValueCollection the second time ormore time.It can not work and not update the column LAST_CHECKIN_TIME of table [QRTZ_SCHEDULER_STATE] .

 It only appear in using NameValueCollection Setting.When I configure this in quartz node in the config file like the second picture.It can awalys work.

![image](https://user-images.githubusercontent.com/13430322/40267555-f500a138-5b90-11e8-95c9-e7c7e6f2fe7f.png)

![image](https://user-images.githubusercontent.com/13430322/40267545-cc6dce26-5b90-11e8-9e17-8b3e78742bf8.png)

Please help me！！！

**Comment by lahma** [comment]
Good that you got the thing sorted out.
