### ISSUE TITLE
Quartznet not working with npgsql 4.0

### ISSUE THREAD

**Issue by shenzhigang** [quartznet/quartznet#626]
Quartznet 3.0.4 will throw exceptions when any trigger getting fired.  JobStore is postgres(9.6) and the npgsql version is 4.0rc-1. 
```
Exception thrown: 'System.IndexOutOfRangeException' in Npgsql.dll
Exception thrown: 'System.IndexOutOfRangeException' in mscorlib.dll
Exception thrown: 'Quartz.JobPersistenceException' in Quartz.dll
```
But it works fine with Npgsql3.x.

**Comment by lahma** [comment]
The RTM version of npgsql should work as discussed in https://github.com/npgsql/npgsql/issues/1951 , so you just need to wait for that.
