### ISSUE TITLE
DirectoryScanJob w/ Quartz.Impl.AdoJobStore.JobStoreTX

### ISSUE THREAD

**Issue by dashkan** [quartznet/quartznet#627]
I have a scheduled DirectoryScanJob configured to run every 5 seconds. The job works fine when using RAMJobStore.

Switching to AdoJobStore, the job is run the first time and fails to run subsequently. The job is put in "BLOCKED" state in the database.

### Version: x.y.z
 
3.0.4
### Expected behavior

Job runs every 5 seconds

### Actual behavior

Job runs one time

### Steps to reproduce

Switch to Ado Store w/ SQL Server

Create DirectoryScanJob w/ 5 second interval

I copied the DirectoryJobScan code locally and found that the call 

```csharp
JobDetailJobDataMap.Put(DirectoryScanJob.LastModifiedTime, newLastModifiedDate);
```

Does not reset the state back to 'AQUIRED'.

Simply adding after the Put call
```csharp
JobDetailJobDataMap.ClearDirtyFlag();
```

fixes the problem for now.

Looks like a problem in the Ado Store

**Comment by lahma** [comment]
Please test with latest 3.1 betas and see if this was fixed with latest locking fixes. We can reopen if still a problem.
