### ISSUE TITLE
Ability to save the state for paused jobs

### ISSUE THREAD

**Issue by MZade** [quartznet/quartznet#629]
This is related to the issue which is also described under:
    https://github.com/Microsoft/Recurring-Integrations-Scheduler/issues/45

The issue that we have is about the ability to save the trigger statuses when these are set in paused.

It seems that currently it is not possible to save the trigger statusses..i.e. it can be that triggers of a given job are set to paused status; But there is not a direct way to save this state and if the application is restarted, the jobs which were set in the paused state will become again active.

Do you think that it would be feasable to support saving the job trigger status when it is set to paused?

### Steps to reproduce

```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```

**Comment by lahma** [comment]
When you use AdoJobStore the trigger status is persisted to database. The state is remembered between restarts.

**Comment by lahma** [comment]
I'm closing the issue as it seems that Quartz.NET should provide the building blocks needed. I can try to answer questions if they rise in the referred issue.
