### ISSUE TITLE
PlatformNotSupportedException on RaspberryPi (Windows IoT)

### ISSUE THREAD

**Issue by bigdnf** [quartznet/quartznet#630]
### Expected behavior

StdSchedulerFactory.GetScheduler() should return scheduler

### Actual behavior

PlatformNotSupportedException is thrown - I checked in source code and it is failing in StdSchedulerFactory at ConfigurationManager.GetSection. It looks like it is not working on Raspberry. 

### Steps to reproduce

I'm using UWP 6.1.4 project with .net standard 2.0 libs on Visual studio 2017 15.7.2. When compile by hand and comment this line with ConfigurationManager the rest is working good. Maybe it could be eliminated by checking RuntimeInformation.OSArchitecture or RuntimeInformation.ProcessArchitecture - they return Arm on RPI.

```csharp
 StdSchedulerFactory factory = new StdSchedulerFactory();
 IScheduler scheduler = await factory.GetScheduler();
```

**Comment by bigdnf** [comment]
I can work on pull request but I would like to discuss proper solution. I found two solution for that: one is the check for RuntimeInformation.OSArchitectur but it will be not accurate if on other ARM hardware’s this feature will be available (I don’t know Is this currently true) or add some static property UseConfigurationManager and set it true for default so it can be set to false when someone or via quartz configuration system with some quartz.UseConfigurationManager property

**Comment by lahma** [comment]
Thanks for reporting the issue. I went ahead and added try-catch for those configuration reading parts. As you've noted it's non-fatal and configuration can be provided with separate files / configuring the scheduler factory.
