### ISSUE TITLE
JSON serialisation returning defaults for derived calendar settings

### ISSUE THREAD

**Issue by KeyDecoder** [quartznet/quartznet#634]
### Version: 3.0.5 
3.0.5 for Quartz.Net and Quartz.Serialization.Json.
SQL Server 14.0.2000.63 (using tables_sqlServer.sql script)
Tested using both Newtonsoft.Json 10.0.3 and 11.0.1

### Expected behavior

When using SQL Server and JSON serialisation, all calendar types should be able to be loaded from the database and have all the correct values for the various derived calendar classes.  This is after the scheduler has been shutdown and restarted so calendars are not loaded from internal cache.

### Actual behavior

Calendars loaded from database appear to have the base calendar information correct (Description, Timezone) but anything else defined in derived classes is always the default (ie. for WeeklyCalendar it is always set to the default of Saturday/Sunday).

Note this works fine with binary serialization.

The data in the database looks valid (casted via SQL to varchar(max) from varbinary(max))
```
{
	"$type": "Quartz.Impl.Calendar.AnnualCalendar, Quartz",
	"Description": "Christmas holiday calendar",
	"TimeZoneId": "E. Australia Standard Time",
	"BaseCalendar": null,
	"ExcludedDays": ["2000-12-25T00:00:00"]
}
```

### Steps to reproduce

1. Create new SQL database and create database tables
2. Run Quartz connected to database using quartz.serializer.type = json and Quartz.Serialization.Json package.
3. Start scheduler 
4. Add AnnualCalendar
```csharp
var createdCalendar = new AnnualCalendar {Description = "Christmas holiday calendar"};
var christmasDay = new DateTime(2018, 12, 25);
createdCalendar.SetDayExcluded(christmasDay, true);
await scheduler.AddCalendar("Christmas", createdCalendar, false, false);
```
5. Shutdown scheduler
6. Recreate and start new scheduler
7. Load calendar from scheduler
The description and timezone will be valid but DaysExcluded will be the default (no days).

```csharp
await scheduler.Shutdown();
factory = new StdSchedulerFactory(props);
scheduler = await factory.GetScheduler();
await scheduler.Start();
var readOutCalendar = await scheduler.GetCalendar("Christmas") as AnnualCalendar;
```

Full test app - [TestApp.zip](https://github.com/quartznet/quartznet/files/2105153/TestApp.zip)

**Comment by lahma** [comment]
Thanks for the detailed report and sorry for the delay. The fix was a bit more involved than what I was hoping for but should work now. Will be part of 3.0.6 release.

**Comment by KeyDecoder** [comment]
Awesome work, thanks for looking into and resolving this :thumbsup:
