### ISSUE TITLE
Triggers built with StartAt in the past, execute right away

### ISSUE THREAD

**Issue by Sebastriani** [quartznet/quartznet#636]
### Expected behavior
I expected that creating a trigger with a start date in the past, won't fire the job right away, and more so if it was configured to ignore misfires or has an TriggerBuilder.EndAt set also in the past.
I would expect that a trigger created with a StartAt in the past would fire only valid subsequent occurences if any.

### Actual behavior
If a trigger is created with a start date in the past, the job is fired right away, even with TriggerBuilder.EndAt set also in the past. Checking for GetNextFireTimeUtc() returns the date in the past as well.
Weirdly enough if you set SimpleScheduleBuilder.WithRepeatCount > 0, the trigger doesn't fire.
TriggerBuilder.EndAt only prevents the trigger from firing when using DailyTimeIntervalScheduleBuilder, it does not with the other 3, SimpleScheduleBuilder, CalendarIntervalScheduleBuilder and CronScheduleBuilder

### Steps to reproduce
This will fire the trigger right away.

```csharp
            ISchedulerFactory sf = new StdSchedulerFactory();
            IScheduler scheduler = sf.GetScheduler().Result;

            IJobDetail job = JobBuilder
                .Create<QuartzJob>()
                .WithIdentity("TestJob")
                .Build();

            TriggerBuilder tb = TriggerBuilder.Create()
                .WithIdentity("TestTrigger")
                .StartAt(new DateTime(2018, 1, 1));

            SimpleScheduleBuilder sch = SimpleScheduleBuilder.Create();
            sch.WithMisfireHandlingInstructionIgnoreMisfires();

            ITrigger trigger = tb.WithSchedule(sch).Build();

            scheduler.ScheduleJob(job, trigger);
            scheduler.Start();
```

The thing is that I'm developing a custom Task Scheduler with Quartz running in a Windows Service, when the service starts it loads schedule information for tasks from a database, and creates the corresponding in memory (RAMJobStore) jobs and triggers. 
Let's say that a Task is created with a start date for tomorrow Saturday and then recurring execution each week on Saturdays. If the the day past tomorrow (Sunday) the Windows Service is restarted, when realoading the schedules the jobs is executed right away because the trigger's StartAt is in the past.
Since all the task that are created remain in the database with it's orginal start date, if the service is restarted, all tasks are executed right away... I don't get it, is this the expected behaviour?

For instance, execute this and even the trigger is configured to run on Saturdays, no matter when you run this, it will execute right away because the StartAt is in the past:
```csharp
            ISchedulerFactory sf = new StdSchedulerFactory();
            IScheduler scheduler = sf.GetScheduler().Result;

            IJobDetail job = JobBuilder
                .Create<QuartzJob>()
                .WithIdentity("TestJob")
                .Build();

            TriggerBuilder tb = TriggerBuilder.Create()
                .WithIdentity("TestTrigger")
                .StartAt(new DateTime(2018, 1, 1));

            DailyTimeIntervalScheduleBuilder sch = DailyTimeIntervalScheduleBuilder.Create();
            sch.OnDaysOfTheWeek(DayOfWeek.Saturday);
            sch.StartingDailyAt(TimeOfDay.HourAndMinuteOfDay(12, 0));
            sch.EndingDailyAfterCount(1);

            ITrigger trigger = tb.WithSchedule(sch).Build();

            scheduler.ScheduleJob(job, trigger);
            scheduler.Start();
```
Probably I'm missing something about why this behaviour is correct, I would like to know what others think, although this seems a bug to me.

I'll have to get around this somehow.

Thanks, and great great library by the way!!!

**Comment by lahma** [comment]
Before I dwell into this more (I'm a bit short on time) I'd like to know why are you doing double bookkeeping by having triggers and jobs in your own database and then use Quart'z memory functionality? If you'd offer Quartz the database and AdoJobStore Quartz would have memory about past and could act more intelligently.

**Comment by Sebastriani** [comment]
Well, I don't store triggers and jobs as per Quartz does. I use my own database schema to store just schedules in my own simpler format. Then of course I have other tables with information about task and proceses but that information is not related to Jobs as Quartz sees them. 

I don't see it as double bookkeeping since once everything is loaded form the database and I custom generate jobs and triggers, everything for Quartz keeps working in memory and I don't ever read again from the database unless the service is restarted. Even if schedules are added, edited or deleted, I save information in the database as needed but I don't read back from it. To update Quartz I do it in memory.

All of this, first and foremost because the application I wrote is mission critical, and I wanted to rely as little as possible in 3rd party code that I don't have time to understand. 

Then, since it's tailored to custom needs, my code and the database schema are much simpler than the code and schema for AdoJobStore so, it's far easier for me (and anybody else) to fix/modify. I don't say my aproach is better, but I didn't have the time to learn all the inner workings of AdoJobStore, even more so being that I didn't find any in depth documentation but only Lesson 9 in the official documentation.

Also, the application has a UI ala "Windows Task Scheduler" to CRUD the schedules and I would have to learn and understand AdoJobStore, to be able to interface the UI to the database schema.

I solved the problem by changing my code logic a little and everything is working fine so far.

**Comment by lahma** [comment]
OK good to hear that you have the thing sorted, hopefully it plays out well for your use case.

**Comment by Sebastriani** [comment]
Despite you closed the issue, may I ask you if the behaviour I described is the expected?

**Comment by sheitmann** [comment]
> I solved the problem by changing my code logic a little and everything is working fine so far.

Can you give a hint what you changed? Might be helpful for people facing the same issue (like me). :)

**Comment by Sebastriani** [comment]
@sheitmann Well in my case, as you probably read, I store the schedules in a database but with a custom format, I'm not using Quartz ADOJobStore. I have my scheduler system runinng in a Windows Service and when the service starts, I create tasks in RAMJobStore with the schedules from the DB, something like that.

The tasks have a starting DateTime by which I set the TriggerBuilder.StartAt value on loading, of course recurring tasks created in the past have a starting DateTime in the past so, if the service has to be restarted, and because of the behaviour of Quartz, to avoid them to be run right away I do the following

```csharp
            // schedule is an instance of my custom schedule class
            if (schedule.StartDateTime <= DateTime.Now) 
            {   // StartDateTime in the past

                // Add the original start time to the 00hs of today 
                var newstart = DateTime.Now.Date.Add(schedule.StartDateTime.TimeOfDay);
                
                // If start time already passed, 
                if (newstart < DateTime.Now)
                {
                    // Set newstart to the same time but at next day
                    newstart = newstart.AddDays(1);
                }

                // tb is an instance of a TriggerBuilder created before
                tb.StartAt(newstart.ToUniversalTime()); 
            }
            else
            {
                tb.StartAt(schedule.StartDateTime.ToUniversalTime());
            }
```

Hope it helps.
