### ISSUE TITLE
let the cpu 100% in .net core

### ISSUE THREAD

**Issue by pigwing** [quartznet/quartznet#645]
### Expected behavior
let the CPU 100%

### Actual behavior
in a job i use perf to profiling my .net core,i am use quartz.net in .net core found that CorUnix::PROCRemoveThread CPU 100% and detail is https://github.com/AirleaderChina/Airleader-Open/blob/master/errorPho.png

### Steps to reproduce
in the picture

**Comment by lahma** [comment]
I'm sorry but there's not enough details here. What I decipher is that you are doing some sort of performance profiling, could that startavate some system resources? Based on [this](https://github.com/aspnet/SignalR/issues/2124#issuecomment-383400216) it could mean that there are too many threads.

But I really would need a sample application to understand what you are doing.

**Comment by pigwing** [comment]
thx a lot

**Comment by pigwing** [comment]
i have implement the JobFactory and register in di and the i can get the job in serviceProvider 
public class CoreJobFactory : IJobFactory
    {
        private readonly IServiceProvider _serviceProvider;

        public CoreJobFactory(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        public IJob NewJob(TriggerFiredBundle bundle, IScheduler scheduler)
        {
            return _serviceProvider.GetService(bundle.JobDetail.JobType) as IJob;
        }

        public void ReturnJob(IJob job)
        {
            var disposable = job as IDisposable;
            disposable?.Dispose();
        }
    }

**Comment by pigwing** [comment]
then i use the DisallowConcurrentExecution attribute,it will let the cpu 100% after run the job 7 or 8 hours,and about the job repeat-interval 3 seconds ,sometimes it spend greater than 3 seconds to complete once job,i not use DisallowConcurrentExecution attribute is ok.

**Comment by lahma** [comment]
I think this will create a large backlog of jobs waiting to trigger which will eventually cause exhaustion. DisallowConcurrentExecution will make triggered jobs wait and eventually there are too many to wait. Have you tried setting something else to thread pool size instead of the default 10? Default of then will allow only 10 concurrent jobs running, this is something that requires tuning based on available cores and system resources.

    quartz.threadPool.threadCount = 10

**Comment by pigwing** [comment]
thx

**Comment by lahma** [comment]
Is this something that should be processed under .NET Core CLR project? There's little I can help with now.

**Comment by pigwing** [comment]
haha await only , await ms clrcor member fix

**Comment by lahma** [comment]
I'm closing the issue for now, we can reopen if there's something more to do on Quartz's end. I hope that you get the threading issue sorted, sounds quite nasty.
