### ISSUE TITLE
Execute returns Task but Task never runs

### ISSUE THREAD

**Issue by rwil02** [quartznet/quartznet#648]
### Version: x.y.z
3.0.6
### Expected behavior

I would expect that the task would be run

### Actual behavior
Job class is instantiated because Execute method is called.
Code within task never appears to execute
In SQL tables, Trigger_State sits at BLOCKED until the application is restarted

When starting, checks if job and trigger exists, creates them if they don't.
Correctly created them, and correctly no longer attempts to.

### Steps to reproduce

 m_QuartzProperties.Add("quartz.scheduler.instanceName", "Task Scheduler");

                        m_QuartzProperties.Add("quartz.serializer.type", "json");
                        m_QuartzProperties.Add("quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz");
                        m_QuartzProperties.Add("quartz.jobStore.dataSource", "default");
                        m_QuartzProperties.Add("quartz.dataSource.default.connectionString", this.m_Config.Connection);
                        m_QuartzProperties.Add("quartz.jobStore.tablePrefix", "QRTZ_");
                        m_QuartzProperties.Add("quartz.jobStore.clustered", "false");
                        m_QuartzProperties.Add("quartz.jobStore.lockHandler.type", "Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore, Quartz");
                        m_QuartzProperties.Add("quartz.jobStore.driverDelegateType", "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz");
                        m_QuartzProperties.Add("quartz.dataSource.default.provider", "SqlServer");
                        m_QuartzProperties.Add("quartz.jobStore.useProperties", "true");

                        m_QuartzProperties.Add("quartz.threadPool.type", "Quartz.Simpl.SimpleThreadPool, Quartz");
                        m_QuartzProperties.Add("quartz.threadPool.threadCount", "10");
                        m_QuartzProperties.Add("quartz.threadPool.threadPriority", "Normal");
                        m_QuartzProperties.Add("quartz.jobStore.misfireThreshold", "60000");

```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```
public Task Execute(IJobExecutionContext context)
        {
//Hits breakpoint here
            return new Task(() => ProgramLoop(context));
        }

        private void ProgramLoop(IJobExecutionContext context)
        {
            //Never hits a breakpoint here
                if (null == context)
                {
                    Logging.LogMessage("Context not available", MillManager.Enums.LogLevel.Fatal);
                    return;
                }
….
}

TriggerKey emailTriggerKey = new TriggerKey("Email Queue", "Email");
                if (!sched.CheckExists(emailTriggerKey).Result)
                {
                    int m = m_Config.CheckInterval;
                    ITrigger emailTrigger = TriggerBuilder.Create().StartNow().WithIdentity(emailTriggerKey).WithSimpleSchedule((a) =>
                    {
                        a.WithIntervalInMinutes(m).RepeatForever();
                    }).ForJob(emailTaskKey).Build();
                    IJobDetail emailJob = JobBuilder.Create<ScheduledTasks.EmailTask>().WithIdentity(emailTaskKey).WithDescription("Send emails from Mill Manager email queue").Build();

                    sched.ScheduleJob(emailTrigger);
                }

**Comment by lahma** [comment]
Try changing your Execute method to:

```
public Task Execute(IJobExecutionContext context)
{
  ProgramLoop(context);
  return Task.CompletedTask;
}
```

There's no need to create new tasks.

**Comment by rwil02** [comment]
Had to implement CompletedTask (.NET 4.5) :)
What's the point of returning a task if you "have" to inline the processing?
(or is this just a simplification?)

**Comment by lahma** [comment]
If you don't have any really async code you need to return some Task, the task you were creating will never complete. So ideally you would have some async code paths and the artificial return would be unnecessary. Like so (from back of my head, might have API wrong):

```
public async Task Execute(IJobExecutionContext context)
{
    var user = await someService.LoadUser(context.MergedJobDataMap.GetAsString("targetUserId"));
    await emailService.SendDailyDigest(user);
}
```

Glad you got it working, I'm closing the issue for now.

**Comment by rwil02** [comment]
Ah.
I forgot to call Task.Start 
That was foolish of me.
