### ISSUE TITLE
Using SqlConnection.OpenAsync in AdoJobStore

### ISSUE THREAD

**Issue by redshift312** [quartznet/quartznet#657]
### Version: 3.0.6

How can the SqlConnection.OpenAsync be used in AdoJobStore with the default "SqlServer" provider? Is there any pitfalls of using it in Quartz.net?

**Comment by lahma** [comment]
You probably need to rewrite JobStoreSupport and descendants. I can make the change for 4.0 but probably rather not for 3.x as it's breaking for inheritors.
