### ISSUE TITLE
There is no metadata information for provider 'OracleODP'

### ISSUE THREAD

**Issue by leoterry-ulrica** [quartznet/quartznet#660]
###  properties below：
properties["quartz.scheduler.instanceName"] = "TestScheduler";
            properties["quartz.scheduler.instanceId"] = "instance_one";
            properties["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz";
            properties["quartz.jobStore.useProperties"] = "true";
            properties["quartz.jobStore.dataSource"] = "default";
            properties["quartz.jobStore.tablePrefix"] = "QRTZ_";
            properties["quartz.dataSource.default.connectionString"] = "Data Source=//xxxx:1521/orcl;User Id=dme_scheduler;Password=pass";
            properties["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.OracleDelegate, Quartz";
            properties["quartz.dataSource.default.provider"] = "OracleODP";

### exceptions

Quartz.SchedulerException:“Could not Initialize DataSource: default”
ArgumentOutOfRangeException: There is no metadata information for provider 'OracleODP'

**Comment by lahma** [comment]
.NET Core version (nestandard2.0) only supports OracleODPManaged, which is also supported by full framework version. 

* https://www.nuget.org/packages/Oracle.ManagedDataAccess/ - full framework
* https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.12.0-beta3 - .NET Core

**Comment by leoterry-ulrica** [comment]
Thankyou very much.
It does work.
