### ISSUE TITLE
Lost JobDataMap after JobWasExecuted in JobListener

### ISSUE THREAD

**Issue by huyjack178** [quartznet/quartznet#664]
I follow this blog to handle job failure. But the number of retries lost after JobWasExecuted.
Can anyone help me?
https://blog.harveydelaney.com/quartz-job-exception-retrying/

**Comment by lahma** [comment]
The blog was updated with requirement of [PersistJobDataAfterExecution], I believe that might have been the cause.

**Comment by Varorbc** [comment]
@lahma why quartznet doesn't provide an exception retry policy?
translate by google

**Comment by lahma** [comment]
@Varorbc it does, you can throw JobException with guidance how to act. DB store retries on transient exceptions too.

**Comment by Varorbc** [comment]
@lahma But I used memory store. I doesn’t get the relevant retry instructions. Did I miss something?

**Comment by lahma** [comment]
If your job throws [JobExecutionException](https://github.com/quartznet/quartznet/blob/master/src/Quartz/JobExecutionException.cs) you can define what happens.

**Comment by Varorbc** [comment]
Do you mean that?

```

            try
            {
                //do something
            }
            catch (Exception ex)
            {
                throw new JobExecutionException(ex)
                {
                    RefireImmediately = true
                };
            }

```

Perhaps the retry strategy mentioned in the article is more reasonable. There can be retry intervals and retry times instead of retrying immediately. What do you think?

**Comment by lahma** [comment]
If you want something more fine-grained, yes you should adapt from the article linked.

**Comment by Varorbc** [comment]
Does quartznet add this policy as an option? It will be very helpful.Thank you very much

**Comment by lahma** [comment]
Please create a PR if you want something included in the library.

**Comment by Varorbc** [comment]
#1045
