### ISSUE TITLE
IScheduler.ScheduleJobs deletes the job and triggers in alternative invocation

### ISSUE THREAD

**Issue by sunilranjansahoo** [quartznet/quartznet#666]
### Expected behavior

When invoking the ScheduleJobs methods, the triggers and job should be added or updated successfully.

### Actual behavior

When updating or adding the existing triggers with a single job, the triggers and job get deleted when invoking the method for first time and saved if we invoke the method second time with same triggers and job. So I am using the exact same code to invoke the ScheduleJobs method to add or update the triggers. Sample code as follows 

Scheduler.ScheduleJobs(jobAndTriggers, true);
Scheduler.ScheduleJobs(jobAndTriggers, true);

Where Scheduler is of type IScheduler and jobAndTriggers of type IReadOnlyDictionary<IJobDetail, IReadOnlyCollection<ITrigger>>.

### Steps to reproduce

Have one job and multiple triggers for the same job and call ScheduleJobs once and check DataBase. The triggers and job will not be there in database. Call the same method again with same parameters and check the database.

**Comment by lahma** [comment]
The logic only contains addition, there's no delete for anything in `ScheduleJobs`. I'm closing this and we can reopen if more complete sample is provided to see the problem better. You example was lacking `await` for the calls, that also might be an issue.
