### ISSUE TITLE
Quartz scheduler not working in Kubernetes

### ISSUE THREAD

**Issue by ivankaurov** [quartznet/quartznet#667]
### .Net Core 2.1

We're experiencing an intermittent issue when running scheduler in k8s.
The following message is seen in logs:
```text
This scheduler instance (sched-566636704296491185520) is still active but was recovered by another instance in the cluster. This may cause inconsistent behavior.
```
Everything is OK on Windows

It seems to be the problem of SqlClient. The [issue 31865](https://github.com/dotnet/corefx/issues/31865) has been created in dotnet/corefx project

**Comment by lahma** [comment]
Seems that the corefx issue has been resolved, closing here and can be reopened if still an issue.
