### ISSUE TITLE
Registering a CalendarInterval trigger with an invalid exclusion calendar does not throw an exception

### ISSUE THREAD

**Issue by moodsman** [quartznet/quartznet#668]
### Expected behavior

1. Create a trigger using the CalendarIntervalScheduleBuilder, for example that will fire every 2 weeks on Monday

2. Modify it with a WeeklyCalendar that excludes Mondays

3. Attempt to register the trigger with Scheduler.ScheduleJob( ITrigger trigger ) - should throw a SchedulerException, stating that the trigger will never fire (as with cron triggers)

### Actual behavior

Nothing happens! The thread seems to just disappear into Scheduler.ScheduleJob( ITrigger trigger ), which never returns. The trigger is not persisted in the store but the calling thread seems to just get stuck awaiting the async Scheduler.ScheduleJob() method to return
### Steps to reproduce

```csharp
// Create a trigger builder
TriggerBuilder newTriggerBuilder = TriggerBuilder.Create().WithIdentity( updateTriggerKey ).WithDescription( updateTriggerDescription ).ForJob( jobKey );

// Set up a weekly calendar interval schedule - startDate should be on a Monday
newTriggerBuilder.StartAt( startDate ).WithSchedule( CalendarIntervalScheduleBuilder.Create().InTimeZone( TimeZoneInfo.Utc ).WithIntervalInWeeks( interval ).WithMisfireHandlingInstructionDoNothing() );

// Create a weekly calendar excluding only Mondays
WeeklyCalendar weeklyCalendar = new WeeklyCalendar();
weeklyCalendar.DaysExcluded = new bool[7];
weeklyCalendar.SetDayExcluded( DayOfWeek.Monday, true );

// Register the calendar and associate with trigger
Scheduler.AddCalendar( "Mondays", weeklyCalendar, true, true );
existingTriggerBuilder.ModifiedByCalendar( "Mondays" );

// Build and schedule the new trigger
jobTrigger = newTriggerBuilder.Build();
Scheduler.ScheduleJob( jobTrigger );
```

**Comment by lahma** [comment]
I'm closing this as reproduction is not full and might be even missing await. A full test case would be great to have and we can reopen if you come up with that.
