### ISSUE TITLE
Give meaningful names to Quartz.Examples folders

### ISSUE THREAD

**Issue by MNF** [quartznet/quartznet#670]
### Expected behavior
The Quartz.Examples. project https://github.com/quartznet/quartznet/tree/master/src/Quartz.Examples
has folders with names Example1 - Example16.

It will be good to rename them to give meaningful names, describing what feature is shown.

Adding of documentation that describe the examples will be also appreciated.

**Comment by lahma** [comment]
Thanks, this is indeed a good idea. Also I hope we can improve the online documentation at some point to have good reference to each example.

**Comment by parrainc** [comment]
FYI, I just forked the project and clone it on my local.
will come up with a PR for this pretty soon.

**Comment by lahma** [comment]
Closing as PR was merged, thanks!
