### ISSUE TITLE
Provide Simplified methods and examples for quick start

### ISSUE THREAD

**Issue by MNF** [quartznet/quartznet#671]
I am a new user and looking for a quick start. From 
https://www.quartz-scheduler.net/documentation/quartz-3.x/quick-start.html in the section “need code just after Start() method“
I see  that to create repeated schedule I need to create job, trigger and schedule job with multiple parameters (15 lines). It will be better if for really **quick** start it will be  a  simplified method with a few parameters to do it .

E.g.[FluentScheduler](https://github.com/fluentscheduler/FluentScheduler)  allows to do it in 1 line
  `Schedule(() => new MyComplexJob("Foo", DateTime.Now)).ToRunNow().AndEvery(2).Seconds();`

I understand, that keep jobs and triggers separate is good for more flexibility and more complex requirements , but many users may be need only simple approach. 

Create a few methods with small number of parameters for typical scenarios and show them in quick start will be attractive for  new users, and your current example will help more advanced users.

**Comment by lahma** [comment]
Updated the sample a bit to be shorter, but not much do otherwise with current API. Probably some extension helpers would help but no-one has offered such a PR. Closing for now.
