### ISSUE TITLE
Trigger job does not update trigger instance data

### ISSUE THREAD

**Issue by disagol** [quartznet/quartznet#673]
Version Quartz 3.0.5
When calling TriggerJob, I'd expect to see the trigger instance updated ( PreviousFireTime, TimesFired count, etc). The job gets triggered and executed but no data on trigger instance is updated.
Thanks

**Comment by lahma** [comment]
TriggerJob creates a temporary trigger that causes execution of the target job. There's no trigger instance that update or reflect to. For consumer this is implementation detail how the job is triggered.
