### ISSUE TITLE
JOB_DATA data type as VARCHAR(MAX)

### ISSUE THREAD

**Issue by troygould** [quartznet/quartznet#676]
Just a question.  
I see that in Quartz.NET version 3.0 that the JOB_DATA column has been changed from IMAGE to VARBINARY(MAX). Is there any issue with me changing this to VARCHAR(MAX) if I'm using the following settings?

            "quartz.jobStore.useProperties" = "true";
            "quartz.serializer.type" = "json";

I've done it, and have been able to successfully add/remove and run jobs with scheduled triggers with no issues so far. I just don't know if there is something lurking in the framework that I'm not aware of that will eventually cause an issue.

We don't store a ton of Jobs. So, space isn't an issue for us. However, readability of the raw data is arguably easier with VARCHAR versus VARBINARY.

Thanks in advance.

**Comment by lahma** [comment]
The VARBINARY comes from the need to serialize binary data, all the way from the beginning of the project. If you never ever need to serialize anything else than JSON, this probbaly works. I'm just not giving any guarantees as tests are run against 'standard' database and if ever needed, migration scripts would not account for your non-standard column type.

So if you have tests in place to validate everything works, I guess it doesn't hurt - just not supported 😃
