### ISSUE TITLE
ISchedulerListener.JobScheduled not called when scheduling multiple jobs (ScheduleJobs)

### ISSUE THREAD

**Issue by arthur-liberman** [quartznet/quartznet#678]
### Version: x.y.z
Version 3.0.6

### Expected behavior

JobScheduled is called for every scheduled job.

### Actual behavior

JobScheduled is not called at all.

### Steps to reproduce

```
Dictionary<IJobDetail, IReadOnlyCollection<ITrigger>> dict = MyJobFactory.CreateJobs();
await _scheduler.ScheduleJobs(dict, false);

```
### Comment

https://github.com/quartznet/quartznet/blob/1f87608466d99f4eb2b95859f72eaa8f203698ee/src/Quartz/Core/QuartzScheduler.cs#L803
Is this call missing?
`await Task.WhenAll(triggersAndJobs.SelectMany(x => x.Value.Select(t => NotifySchedulerListenersScheduled(t, cancellationToken)))).ConfigureAwait(false);`

**Comment by arthur-liberman** [comment]
I added the following call after line #803 and it works correctly now.
`await Task.WhenAll(triggersAndJobs.SelectMany(x => x.Value.Select(t => NotifySchedulerListenersScheduled(t, cancellationToken)))).ConfigureAwait(false);`
When scheduling multiple jobs, the `JobScheduled` function of the listener is called now.

**Comment by lahma** [comment]
Thanks for investigating and creating the PR! Will be part of the next maintenance release.

**Comment by DIEGO32OF** [comment]
Hi Marko, i was reviewing the topic for multiple jobs in asp core with Quartz but i have not found anything about this, do you have any code example or url for this? i can see  in version 3.0.7 of Quartz this is fixed but has support for asp core? if the  answer is yes how can i implement it?  thanks greetings
