### ISSUE TITLE
StoreJobsAndTriggers not **fully** replacing triggers for job

### ISSUE THREAD

**Issue by gtaylor44** [quartznet/quartznet#680]
### Expected behavior
When using StoreJobsAndTriggers with replace set to TRUE, Existing triggers should be **fully** replaced with the new triggers collection.

### Actual behavior
The library is not accounting for triggers that have been removed. It's only updating existing triggers found in the collection and adding ones that don't exist. 

### Steps to reproduce
1. Use ADO data store.
2. Call ScheduleJob method with 2 or more triggers (e.g.  await sched.ScheduleJob(job, triggers, true, cancelToken))
3. Call ScheduleJob method a second time with the same job key. Exclude a trigger from previous trigger collection. 

The code snippet below resolves the issue outlined above. I haven't done a pull request as yet, I would prefer to get your thoughts. Instead of doing a select on every trigger (and update if replace = true), delete all triggers for the job group and re-insert (if replace is set to true). This will cater for triggers that have been removed. 

FYI StoreTrigger method may need to change to prevent double up in logic. 

```csharp
        public async Task StoreJobsAndTriggers(
            IReadOnlyDictionary<IJobDetail, IReadOnlyCollection<ITrigger>> triggersAndJobs,
            bool replace,
            CancellationToken cancellationToken = default)
        {
            await ExecuteInLock(
                LockOnInsert || replace ? LockTriggerAccess : null, async conn =>
                {
                    // TODO: make this more efficient with a true bulk operation...
                    foreach (var pair in triggersAndJobs)
                    {
                        var job = pair.Key;

                        // Get existing triggers for job
                        var existingTriggers = await GetTriggersForJob(job.Key).ConfigureAwait(false);

                        // If replace, delete all existing triggers for job
                        if (replace)
                        {
                            foreach (var trigger in existingTriggers)
                            {
                                var deleteResult = await DeleteTriggerAndChildren(conn, trigger.Key, cancellationToken).ConfigureAwait(false);
                            }
                        }

                        // If NOT replace, validate new triggers with existing triggers to ensure there are no duplicates
                        if (!replace)
                        {
                            var existingTriggerDic = existingTriggers.ToDictionary(t => t.Key);

                            foreach(var jobDetail in triggersAndJobs.Values)
                            {
                                foreach(var trigger in jobDetail)
                                {
                                    IOperableTrigger duplicateTrigger;

                                    if (existingTriggerDic.TryGetValue(trigger.Key, out duplicateTrigger))
                                    {
                                        throw new ObjectAlreadyExistsException(duplicateTrigger);
                                    }
                                }
                            }
                        }

                        var triggers = pair.Value;
                        await StoreJob(conn, job, replace, cancellationToken).ConfigureAwait(false);
                        foreach (var trigger in triggers)
                        {
                            await StoreTrigger(conn, (IOperableTrigger) trigger, job, replace, StateWaiting, false, false, cancellationToken).ConfigureAwait(false);
                        }
                    }
                }, cancellationToken).ConfigureAwait(false);
        }
```

**Comment by gtaylor44** [comment]
And just want to comment on your TODO...
// TODO: make this more efficient with a true bulk operation...

Just curious how you're thinking of approaching this? Are you going to get users to add a stored procedure and a table type? Or dynamically build a VALUES separated INSERT statement? Any other strategies in mind?

**Comment by lahma** [comment]
Sorry for taking quite the time to react to this. I've now been thinking about this and I don't think we can make this change that easily. Imagine a scenario:

* a generic job that handles processing and is parameterized via trigger job data (say a user id is there)
* user can set reminders via UI, these are basically triggers behind the scenes, application uses `ScheduleJobs` to set them

Now if we delete all existing triggers not part of this user's context, we would lose every other trigger (say there's some thousands of them). 

This API promises addition on replacement, not removal. So this logic change would be really breaking and even harmful for existing users that rely that other triggers are kept safe. Thoughts?

**Comment by lahma** [comment]
Closing as there's not much to do here I guess.
