### ISSUE TITLE
ScheduleJob doesnt insert CRON information if a CronTrigger is passed

### ISSUE THREAD

**Issue by Gprsk** [quartznet/quartznet#687]
### Expected behavior
By using ScheduleJob (with the option to send many triggers at once), I can update trigger settings live.
```csharp
await __scheduler__.ScheduleJob(myJobKey, new[] { trigger1 }, true);
```
So, if "trigger1" is built as a simple trigger, it acts like a simple trigger.
After a while, I create a new Trigger, using CRON and call the same method.

Therefore, it should completely replace the old trigger and start acting like a CRON Trigger.

### Actual behavior
Quartz starts throwing all sorts of error, most of them around Foreign Keys not found or failure to read the CRON string.
Also, it throws errors if I try to modify this job further, including trying to remove it by calling **DeleteJob**.

By looking at "QRTZ_TRIGGERS" and "QRTZ_CRON_TRIGGERS", we noticed that it changed the trigger type from "SIMPLE" to "CRON", but QRTZ_CRON_TRIGGERS was never populated

### Steps to reproduce
1 - Create job and attach SIMPLE trigger to it
2 - Update the same job with "replace:true", but now passing a CRON trigger.
3(optional) - Try to remove the job, by calling **DeleteJob**

**Comment by gtaylor44** [comment]
#680 might help here. Waiting for a response from @lahma

**Comment by shweta2089** [comment]
ScheduleJobs(Replace = true) > this method is updating the Qrtz_JOB_DETAILS and QRTZ_TRIGGERS tables only. It NEVER update the table QRTZ_CRON_TRIGGERS or QRTZ_SIMPLE_TRIGGERS with same method.

**Scenario:**
We had a simple trigger and we are converting it to CRON trigger.

**Doubt:**
Why it is not updating the other tables,do we have any limitation with this method or it is a known error from Quartz.
Is there any other way to perform the similar scenario.

**Comment by lahma** [comment]
I think you need to use `RescheduleJob` here which delete the original triggers and inserts new data.

**Comment by lahma** [comment]
Closing as there's not much to do here I guess.
