### ISSUE TITLE
How to identify which trigger is updated and how to incorporate those changes.

### ISSUE THREAD

**Issue by shweta2089** [quartznet/quartznet#691]
In our project, we have multiple jobs and every job has only one trigger with it.
Now I have to update the interval and start time of Job A which is currently active.
I had tried to use Reschedule() method to update the database, but this restart my other jobs and ignores all misfires.
(I don't have any condition which checks that Job A is updated out of all the jobs.)
Does reschedule method identify the updated job and reset specific job only?
What should be the solution to reset the job?

**Comment by lahma** [comment]
Closing for now, if there's better reproduction (sample code) against latest version we can revisit.
