### ISSUE TITLE
JSON serializator is missing

### ISSUE THREAD

**Issue by CassandraDied** [quartznet/quartznet#704]
### Expected behavior

StdSchedulerFactory.GetScheduler() does not throw any exceptions.

### Actual behavior

StdSchedulerFactory.GetScheduler() throws “TypeLoadException: Could not load type 'Quartz.Simpl.JsonObjectSerializer, Quartz.Serialization.Json'”.

### Steps to reproduce
Add to configuration
```csharp
["quartz.serializer.type"] = "json"
```
I've looked into Quartz assembly and didn't find the JsonObjectSerializer class. Is it in another nuget package or what do I miss? Binary works fine. Full net framework 4.7.2.

**Comment by lahma** [comment]
Probably needs a better hint about what to do, but you need https://www.nuget.org/packages/Quartz.Serialization.Json/ for it to work.

**Comment by CassandraDied** [comment]
Did the trick! Thanks.
Would be nice to have this info [here](https://www.quartz-scheduler.net/documentation/quartz-3.x/migration-guide.html).

**Comment by lahma** [comment]
Thanks, added note to the page.
