### ISSUE TITLE
Jobs in ErrorState

### ISSUE THREAD

**Issue by Hahn-Benjamin** [quartznet/quartznet#707]
### Actual behavior

I have got the problem that the job goes into the ErrorState, from time to time.
The log looks like the scheduler tries restarting and running the job during shutdown. The result is a "ThreadPool.RunInThread () returned false!" Error.
Is this a known problem or am I doing something wrong?
The scheduler is hosted in IIS.
Here is the log of Quartz:

21:34:16.1652 INFO "Registering datasource 'default' with db provider: 'Quartz.Impl.AdoJobStore.Common.DbProvider'"
21:34:16.2084 INFO "Using object serializer: Quartz.Simpl.JsonObjectSerializer, Quartz.Serialization.Json"
21:34:16.2377 INFO "Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl"
21:34:16.2377 INFO "Quartz Scheduler v.3.0.5.0 created."
21:34:16.2485 INFO "Detected usage of SqlServerDelegate - defaulting 'selectWithLockSQL' to 'SELECT * FROM [quartz].QRTZ_LOCKS WITH (UPDLOCK,ROWLOCK) WHERE SCHED_NAME = 'Kraken.Jobs.Kafka' AND LOCK_NAME = @lockName'."
21:34:16.2485 INFO "Using db table-based data access locking (synchronization)."
21:34:16.2485 INFO "JobStoreTX initialized."
21:34:16.2485 INFO "Scheduler meta-data: Quartz Scheduler (v3.0.5.0) '{JobAssembly}' with instanceId '{ServerName}'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 5 threads.
  Using job-store 'Quartz.Impl.AdoJobStore.JobStoreTX' - which supports persistence. and is clustered.
"
21:34:16.2485 INFO "Quartz scheduler '{SchedulerAssembly}' initialized"
21:34:16.2485 INFO "Quartz scheduler version: 3.0.5.0"
21:34:17.0969 INFO "JobFactory set to: {JobFactory}"
21:34:17.4886 INFO "Scheduler {SchedulerName} started."
21:34:18.8201 INFO "Scheduler {SchedulerName} shutting down."
21:34:19.7579 INFO "Scheduler {SchedulerName} paused."
21:34:20.0597 ERROR "ThreadPool.RunInThread() returned false!"
21:34:20.1247 INFO "All triggers of Job {JobName} set to ERROR state."
21:34:20.2552 INFO "Scheduler {SchedulerName} Shutdown complete."

```csharp
                ["quartz.serializer.type"] = "json",

                ["quartz.scheduler.instanceName"] = settings.SchedulerName,
                ["quartz.scheduler.instanceId"] = "AUTO",
                ["quartz.jobStore.clustered"] = "true",
                ["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz",
                ["quartz.threadPool.threadCount"] = settings.MaxThreadCount.ToString(),
                ["quartz.jobStore.misfireThreshold"] = "60000",
                ["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz",
                ["quartz.jobStore.useProperties"] = "false",
                ["quartz.jobStore.dataSource"] = "default",
                ["quartz.jobStore.tablePrefix"] = "[quartz].QRTZ_",
                ["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz",
                ["quartz.dataSource.default.provider"] = "SqlServer",
                ["quartz.dataSource.default.connectionString"] = settings.ConnectionString,
                ["org.quartz.jobStore.isClustered"] = "true",
                ["org.quartz.jobStore.clusterCheckinInterval"] = "20000"
```

**Comment by asansona15** [comment]
The quartz doesn't trigger the jobs an error state. this need manual intervention of jobs will auto triggering again as per the schedule. 
Follow below query to run into Quartz database:

-- UPDATE TRIGGER STATE "ERROR" TO "WATING" (IF ERROR STATE EXISTS) 
**UPDATE [dbo].[QRTZ_TRIGGERS] SET TRIGGER_STATE='WAITING' WHERE TRIGGER_STATE='ERROR'**

**Comment by shweta2089** [comment]
I am facing the same issue where Job went to Error State and i received an error log saying " ERROR - ThreadPool.RunInThread() returned false!". I already have a threadpoolcount of 100 and the jobs executing at that time is less than 100, but still this exception occurs. What could be the reason for this ERROR?

**Comment by shweta2089** [comment]
I am facing the same issue where Job went to Error State and i received an error log saying " ERROR - ThreadPool.RunInThread() returned false!".  What could be the reason for this ERROR?

**Comment by lahma** [comment]
Please try with 3.1 beta series (they contain important locking fix) and we can reopen if problems still persist.

**Comment by danports** [comment]
I just ran into what appears to be the same issue today:

```
2024-02-27 14:44:54.659	<6>Quartz.Core.QuartzScheduler[0] Scheduler MassTransit-Scheduler_$_NON_CLUSTERED paused.
2024-02-27 14:44:54.858	<6>Quartz.Core.QuartzScheduler[0] Scheduler MassTransit-Scheduler_$_NON_CLUSTERED shutting down.
2024-02-27 14:44:54.859	<6>Quartz.Core.QuartzScheduler[0] Scheduler MassTransit-Scheduler_$_NON_CLUSTERED paused.
2024-02-27 14:44:54.906	<3>Quartz.Core.QuartzSchedulerThread[0] ThreadPool.RunInThread() returned false!
2024-02-27 14:44:54.951	<6>Quartz.Impl.AdoJobStore.JobStoreTX[0] All triggers of Job DEFAULT.MassTransitScheduleMessageJob set to ERROR state.
2024-02-27 14:44:58.838	<6>Quartz.Core.QuartzScheduler[0] Scheduler MassTransit-Scheduler_$_NON_CLUSTERED Shutdown complete.
```

Looking back, the `ThreadPool.RunInThread() returned false!` error has come up roughly once a quarter on average for the last year, so it is a rare event, which seems consistent with a locking bug. I'm usually tracking pretty closely to the latest Quartz.NET version - right now, I'm on 3.8.0.0.

**Comment by danports** [comment]
If it's difficult to track down the underlying locking bug, can we at least modify this line in `QuartzSchedulerThread` in the meantime so that the scheduler doesn't freak out and set all of the triggers to ERROR when this issue arises? That really makes the whole problem worse, since if the scheduler just ignored the error on shutdown, everything would be fine when it next started up.

https://github.com/quartznet/quartznet/blob/c4d3a0a9233d48078a288691e638505116a74ca9/src/Quartz/Core/QuartzSchedulerThread.cs#L447
