### ISSUE TITLE
quartz 2.2.2 with dotnet framework 4.7.2 issue

### ISSUE THREAD

**Issue by srikanthkadem** [quartznet/quartznet#712]
quartz (2.2.2) not working with dotnet 4.7.2 framework , is this expected.

**Comment by lahma** [comment]
No, it's not expected.

**Comment by srikanthkadem** [comment]
it used work perfectly with 4.5.2 ,may i know how to see quartz logs ..I dont see anything in debug mode as well

**Comment by srikanthkadem** [comment]
just an update, I just tried with 2.6.2 version quartz , it worked perfectly. To migrate to 3.x , we are not ready with async operations. this resolved my issue, still I would like to analyze issue with 2.2.2 if you can provide steps to analyze logs.

**Comment by lahma** [comment]
https://www.quartz-scheduler.net/documentation/quartz-2.x/quick-start.html has logging configuration sample.

**Comment by lahma** [comment]
It's always wise to run the latest version, either 3.x or 2.x, most fixes available.
