### ISSUE TITLE
RAMJobStore: ConcurrentDictionary solely used within lock

### ISSUE THREAD

**Issue by drieseng** [quartznet/quartznet#715]
Upon first look, it appears as if the **ConcurrentDictionary** instance fields in **RAMJobStore** are only used within a synchronized block. As such, there's no reason why **ConcurrentDictionary** should be preferred over a **Dictionary**.

Since **ConcurrentDictionary** incurs quite some overhead and we do not have to worry about concurrency, we could just use a regular **Dictionary** instead.

Would you accept such a PR, or do you plan to remove the instance wide lock?

**Comment by lahma** [comment]
Good observation. Usually locking by single data structure isn't enough as updates need to be made to multiple ones.

And yes, PR would be nice!
