### ISSUE TITLE
asp.net mvc quart  Execute twice at intervals 

### ISSUE THREAD

**Issue by Poolisde** [quartznet/quartznet#716]
### Steps to reproduce
  NameValueCollection config = new NameValueCollection();
            config["quartz.scheduler.instanceName"] = "SchedulerTest_Scheduler";
            config["quartz.scheduler.instanceId"] = "AUTO";
            config["quartz.threadPool.threadCount"] = "2";
            config["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz";
            sched = new StdSchedulerFactory(config).GetScheduler();
            IJobDetail job = JobBuilder.Create()
                                       .OfType<CleanJob>()
                                       .WithIdentity("c1")
                                       .StoreDurably()
                                       .Build();

            string cronExpr = ConfigurationManager.AppSettings["cronExpr"];

            var trigger = (ICronTrigger)TriggerBuilder.Create()
                                 .WithIdentity("c1")
                                 .WithCronSchedule(cronExpr)
                                 .Build();

            sched.ScheduleJob(job, trigger);

            IJobDetail job2 = JobBuilder.Create()
                                       .OfType<HeartJob>()
                                       .WithIdentity("c30")
                                       .StoreDurably()
                                       .Build();

            string hertExpr = ConfigurationManager.AppSettings["heartExpr"];
            var heartTrigger = (ICronTrigger)TriggerBuilder.Create()
                     .WithIdentity("c30")
                     .WithCronSchedule(hertExpr)
                     .Build();
            sched.ScheduleJob(job2, heartTrigger);
            sched.Start();
```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```

**Comment by lahma** [comment]
Please double-check your configuration and maybe enable logging. It's hardly possible that Quartz would double-fire on such simple scenario unless there are two triggers.

**Comment by Poolisde** [comment]
use .WithSimpleSchedule(x => x.WithIntervalInMinutes(30).RepeatForever())
