### ISSUE TITLE
DirtyFlagMap.Put(TKey key, TValue val) returns original value

### ISSUE THREAD

**Issue by drieseng** [quartznet/quartznet#722]
The `DirtyFlagMap.Put(TKey key, TValue val)` method first obtains the current value of the specified key, and returns this value after updating the dictionary.

The return value of this method is never used. This means that you're wasting cycles for looking up the current value for no reason.

**Comment by drieseng** [comment]
Would a PR for this be accepted, or do you consider it a breaking change?

**Comment by lahma** [comment]
Well I think it's a breaking change, so requires a non-minor release to be published. Otherwise I'm happy to have the change.

**Comment by lahma** [comment]
I'm closing this as the perf penalty is quite little and some people might want to get the old value too.
