### ISSUE TITLE
TaskSchedulingThreadPool.RunInThread wraps task

### ISSUE THREAD

**Issue by drieseng** [quartznet/quartznet#724]
In `TaskSchedulingThreadPool.RunInThread(Func<Task> runnable)`, the task returned by the **runnable** delegate is first wrapped into a new **Task<Task>**.

Do you care to explain why is this done?

Thx!

**Comment by lahma** [comment]
I honestly don't have much recollection of the origins of that current form of code. Originall people from Microsoft were helping with .NET Core / Task transition, but I can also have had something to do with it...

**Comment by lahma** [comment]
I'm closing this for now as doesn't seem to be a big issue.
