### ISSUE TITLE
XMLSchedulingDataProcessorPlugin does not support cron expression for a range with increment values for minutes (or hours) 

### ISSUE THREAD

**Issue by velmohan** [quartznet/quartznet#729]
### Expected behavior

The following cron expression used to work in the older version "0 35-55/3 2 * * ?" when added using scheduler config. The trigger will fire every 3 minutes between 2.35 and 2.55.

### Actual behavior

 When scheduler is started I get the error: Quartz.Xml.ValidationException:The 'http://quartznet.sourceforge.net/JobSchedulingData:cron-expression' element is in valid - The value '0 35-55/3 2 * * ?' is invalid according to its datatype 'http://quartznet.sourceforge.net/JobSchedulingData:cron-expressionType' - The Pattern constraint failed.

This cron expression works fine if you use the code to add the trigger as shown below. So, the problem seems to be in XMLSchedulingDataProcessorPlugin. I had a look at the code and I seem to think the XSD schema is the reason for this potentially unintentional restriction.

                        ITrigger trigger2 = TriggerBuilder.Create()
                       .WithIdentity("trigger2", "group1")
                       .WithCronSchedule("0 35-55/3 * * * ?")
                       .ForJob("job1", "group1")
                       .Build();
             

### Steps to reproduce
Just add "0 35-55/3 2 * * ?" using an xml config.  

```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```

**Sample config file used to repro..**

<job-scheduling-data xmlns="http://quartznet.sourceforge.net/JobSchedulingData"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 				version="2.0">

  <processing-directives>
    <overwrite-existing-data>true</overwrite-existing-data>
  </processing-directives>

  <schedule>
    
    <job>
      <name>jobName1</name>
      <group>jobGroup1</group>
      <description>jobDesciption1</description>
      <job-type>QuartzTrial.SimpleJob, QuartzTrial</job-type>
      <durable>true</durable>
      <recover>false</recover>
      <job-data-map>
        <entry>
          <key>key0</key>
          <value>value0</value>
        </entry>
        <entry>
          <key>key1</key>
          <value>value1</value>
        </entry>
        <entry>
          <key>key2</key>
          <value>value2</value>
        </entry>
      </job-data-map>
    </job>
    
    <trigger>
      <simple>
        <name>simpleName</name>
        <group>simpleGroup</group>
        <description>SimpleTriggerDescription</description>
        <job-name>jobName1</job-name>
        <job-group>jobGroup1</job-group>
        <start-time>1982-06-28T18:15:00.0Z</start-time>
        <end-time>2020-05-04T18:13:51.0Z</end-time>
        <misfire-instruction>SmartPolicy</misfire-instruction>
        <repeat-count>1</repeat-count>
        <repeat-interval>3000</repeat-interval>
      </simple>
    </trigger>

    <trigger>
      <cron>
        <name>my-trigger</name>
        <group>simpleGroup</group>
        <job-name>jobName1</job-name>

        <job-group>jobGroup1</job-group>
        
        
        <cron-expression>0 35-55/3 2 * * ?</cron-expression>

      </cron>
    </trigger>

  </schedule>
  
</job-scheduling-data>

**Comment by lahma** [comment]
I'm going to entirely remove the validation from schema and rely that `CronExpression` will error out when it cannot understand the pattern. XML schema is hard.
