### ISSUE TITLE
Dotnet Core log configuration not being honoured

### ISSUE THREAD

**Issue by Soundman32** [quartznet/quartznet#734]
The standard dotnet core logging configuration method is not honoured by the Quartz logger.

For example, log level configuration (usually via `IConfiguration` and `appsettings.json`) doesn't prevent Quartz outputting **Debug** and **Info** level trace messages (whereas other logging is restricted to the configured levels).

  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information",
      "Quartz": "Warning" <-- Has no effect
    }
  }

**Comment by lahma** [comment]
Please see https://www.quartz-scheduler.net/2020/07/08/quartznet-3-1-beta-1-released/ how to configure DI and logging bridge. We can reopen if still an issue.

**Comment by fededim** [comment]
I am using .Net5, latest Quartz.AspNetCore 3.2.4 package and I am experiencing the same issue, my appsettings.json contains

```
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "Quartz": "Warning",
      "Quartz.Core.QuartzSchedulerThread": "Warning",
      "Quartz.Core.JobRunShell": "Warning"
    }
  }
```

but it seems that all Quartz keys are ignored as I always see debug messages in log. @Soundman32 did you manage to solve somehow ?
