### ISSUE TITLE
Quartz cron job set next fire time without executing job

### ISSUE THREAD

**Issue by shahjeet297** [quartznet/quartznet#735]
### Expected behavior
Job should be executed in clustered environment

### Actual behavior

We have scenario where almost max 1400 jobs are running at a time where one of the job is running daily using cron trigger. There are 100 jobs of this type. Around 90 jobs are running correctly but 8 jobs are setting next fire time without running job and updating previous fire time and 2 jobs are setting previous fire time as null and next fire time for next iteration without running job

### Steps to reproduce
Not able to replicate the same on other envoronments but occured on production continously
// scheduler and job configuration, SystemTime prefereably set to fixed point
```

**Comment by lgy2014** [comment]
I also encountered this problem, when using the SQL server database, a job fired six times later, no longer fired, and then the next fire time has been increasing, resulting in no fire.

**Comment by lahma** [comment]
Please try with 3.1 beta 2 or later. This might have been a locking issue. We can reopen if still an issue.
