### ISSUE TITLE
How to fire a job from another appliation

### ISSUE THREAD

**Issue by Ghetti** [quartznet/quartznet#736]
Good morning. Where is a way to fire a jobs from another .net application?
I have quart installed like a Windows service with CrystalQuartz web interface. I need to start a specific job with an external call from a website.
thanks

**Comment by maulik-modi** [comment]
@Ghetti , may be you can have a look at https://github.com/jlucansky/Quartzmin

**Comment by lahma** [comment]
For full framework you can use remoting or for .NET Core some third party solution or wait for the implementation of https://github.com/quartznet/quartznet/issues/511 .
