### ISSUE TITLE
Strange behavior of ScheduleJobs with never fire

### ISSUE THREAD

**Issue by yulObraz** [quartznet/quartznet#738]
I make some calculation on cron string with time shift. So I schedule job based on list of cron strings. Some of them have time in past.

### Expected behavior

Valid triggers are applied.

### Actual behavior

If any of triggers have no fire time then all the job addition fails without information about wrong trigger.

Throws: based on configured schedule, the given trigger '{trigger.Key}' will never fire.

### Steps to reproduce

```csharp
            var sch = factory.Server.Host.Services.GetRequiredService<Quartz.IScheduler>();
            var now = SystemTime.UtcNow();
            var now_2 = SystemTime.UtcNow().AddHours(-1);
            var trigger1 = TriggerBuilder.Create()
                .WithCronSchedule(string.Format("0 {0} {1} {2} {3} ?", now.Minute, now.Hour, now.Day, now.Month), x => x.InTimeZone(TimeZoneInfo.Utc))
                .StartAt(now.AddMinutes(-1)).EndAt(now.AddHours(0.5)).Build();
            var trigger2 = TriggerBuilder.Create()
                .WithCronSchedule(string.Format("0 {0} {1} {2} {3} ?", now_2.Minute, now_2.Hour, now_2.Day, now_2.Month), x => x.InTimeZone(TimeZoneInfo.Utc))
            .StartAt(now.AddMinutes(-1)).EndAt(now.AddHours(0.5)).Build();

            Assert.DoesNotThrowAsync(async () =>
                await sch.ScheduleJob(JobBuilder.Create<Quartz.Job.NoOpJob>().Build(), new List<ITrigger> {
                    trigger1
            }, true), "Throws when first trigger is invalid");

            await sch.ScheduleJob(JobBuilder.Create<Quartz.Job.NoOpJob>().Build(), new List<ITrigger> {
                trigger1, trigger2
            }, true);

**Comment by lahma** [comment]
Even with batch commands you should validate your triggers. I don't think there's much we can do here.

**Comment by yulObraz** [comment]
Can you say how can I check this without implementing half functionality?
This makes useless batch operation. It is not possible to find wrong trigger by error and retry.

**Comment by lahma** [comment]
For your triggers you should call `Validate()` (can throw) and `ComputeFirstFireTimeUtc()` (if returns null it won't be accepted).

**Comment by yulObraz** [comment]
Do something like this?
  var list = new List<ITrigger> { trigger1, trigger2 };
            foreach (var tr in list) {
                ((Quartz.Spi.IOperableTrigger)tr).Validate();
                ((Quartz.Spi.IOperableTrigger)tr).ComputeFirstFireTimeUtc(null);
                Assert.NotNull(tr.GetNextFireTimeUtc(), "trigger should have start time");
            }
I suppose it's private interface.

**Comment by lahma** [comment]
Looks about right, probably need to try-catch the validate. `IOperableTrigger` is a public interface, not just common to use when dealing with triggers, but in this case required.

**Comment by yulObraz** [comment]
Exception that a trigger has no fire time have sence to mark that the job were not added. In this batch operation the exception have sence only if all triggers had no time.
