### ISSUE TITLE
Update dependencies for Quartz.Plugins.TimeZoneConverter

### ISSUE THREAD

**Issue by mj1856** [quartznet/quartznet#739]
Hi, I notice that [Quartz.Plugins.TimeZoneConverter](https://www.nuget.org/packages/Quartz.Plugins.TimeZoneConverter/) takes a dependency on TimeZoneConverter.StrongName, which is a fork of my TimeZoneConverter library.

I added proper strong name signing to TimeZoneConverter as of version 3.0.0.  Can you please update the dependency?

Thanks,
Matt

**Comment by lahma** [comment]
Thanks for the  heads up! I've updated the dependency to point to the official library. Great that it's now strong-signed.
