### ISSUE TITLE
Trigger not fires in v.3.0.7

### ISSUE THREAD

**Issue by marcilioware** [quartznet/quartznet#741]
### Expected behavior

Trigger fires in the scheduled time.

### Actual behavior

Trigger not fires so I have to restart quartz service.

### Steps to reproduce

After start the service and create all jobs and triggers, the service works for a while and then, even with the service running, triggers stop to fires.
I just upgrade to version 3.0.7.

**Comment by ryanlin1986** [comment]
Me too, just dont' work after running for a while( may be days), don't get a clue.

**Comment by flemmingdjensen** [comment]
Same behavior here.... Having 18 jobs configured - suddenly random jobs stops runnning firing....

Have to PauseAll() and ResumeAll() using quartzMin (Web interface)

**Comment by mbtx2** [comment]
Same behavior here.  Also 3.0.7.  Quartz runs fine for days, even weeks and then stops.  In the debug logs, there are no errors at all, and no warnings that aren't normal.  It goes from normal operation to "2019-07-18 09:13:58,728 [7] DEBUG Quartz.Core.QuartzSchedulerThread [(null)] - Batch acquisition of 0 triggers".

This is a production-affecting problem.  I'm not sure how to troubleshoot it, but am willing to try whatever suggestions people might have.  We've used Quartz for many years and become confident in its stability, and it very well may be something in our code.

Is there a way I can have a some code look for this occurrence of "Batch acquisition of 0 triggers"?

**Comment by shahjeet297** [comment]
We have faced the same problem and after investing we have observe that there are jobs which took around 32 seconds and other jobs are taking around 4-5 seconds. There is nothing else which suspecting the cause. We have used the ADO connection delegate with thread count as 50 in clustered environment where two instances are running.

**Comment by lahma** [comment]
This *might* be related to this issue https://github.com/quartz-scheduler/quartz/issues/145 . Probably need to check and port the changes from there if they see, to relate to this issue your are facing.

**Comment by RavindraV07** [comment]
Hi , 

I am scheduling and providing the MySQL connection but I am getting Trigger _Satate ERROR.

Here is my config.


var NameValueCollection = new NameValueCollection();
            NameValueCollection.Add("quartz.scheduler.instanceName", "HomRoverScheduler");
            NameValueCollection.Add("quartz.scheduler.instanceId", "Instance_HomRoverScheduler");
            NameValueCollection.Add("quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz");
            NameValueCollection.Add("quartz.jobStore.useProperties", "false");
            NameValueCollection.Add("quartz.jobStore.dataSource", "Homebuy");
            NameValueCollection.Add("quartz.jobStore.tablePrefix", "QRTZ_");
            NameValueCollection.Add("quartz.dataSource.Homebuy.provider", "MySql");
            NameValueCollection.Add("quartz.dataSource.Homebuy.connectionString", "server=homeroverrds.cvtqawge0hfi.us-east-1.rds.amazonaws.com;database=...;user=...;pwd=...;TreatTinyAsBoolean=false");
            NameValueCollection.Add("quartz.threadPool.threadCount", "50");
            NameValueCollection.Add("quartz.threadPool.threadPriority", "10");
                       NameValueCollection.Add("quartz.serializer.type", "json");
            
            return NameValueCollection;

**Comment by harveynguyen** [comment]
Hi guys,
any updates on this issue ?

**Comment by lahma** [comment]
You should try if Quartz 3.1 beta 1 will fix this issue. We can reopen if issue still persists.
