### ISSUE TITLE
Incorrect examples

### ISSUE THREAD

**Issue by EgoPingvina** [quartznet/quartznet#742]
I started to get acquainted with your library and ran into an amazing problem — the first example the site and here (01_SimpleJobScheduler) can not be builded: errors appear about the lack of methods, unknown interfaces, etc.
![image](https://user-images.githubusercontent.com/9804340/54902210-d3d7ea00-4ee9-11e9-8cb6-9f2519430e96.png)

Please update the block with examples of use.

**Comment by lahma** [comment]
The problem here is that the examples use internal logging functionality. I haven't considered the copy-paste scenario where you would like to use example as-is. Generally Console.WriteLines will work here when you replace log.XXX calls.
