### ISSUE TITLE
Can TriggerJob respect the calendar constraints associated with the scheduled triggers ?

### ISSUE THREAD

**Issue by radu-serbanescu** [quartznet/quartznet#743]
### Expected behavior

When TriggerJob is called for a job with an associated calendar, is there an override that will actually NOT execute the job if the execution time falls withing a restricted window?

### Actual behavior
A job scheduled using a trigger with calendar restrictions should have an option to respect the calendar restrictions when invoked directly using TriggerJob.

### Steps to reproduce
Create a job and schedule it using a trigger with calendar exclusions.
Call TriggerJob at a time within the calendar exclusion window.
The job is executed and there's no option to prevent that.

### Scenario
Create a job that can be executed immediately or at a specific interval but consider calendar constraints for both cases. That is because we cannot determine that a specific time is within the calendar exclusion or not (unless we re-implement the calendar logic outside of Quartz).

**Comment by lahma** [comment]
Unfortunately there's little we can do here. Calendar affects the original trigger, but TriggerJob basically creates one-shot simple trigger without knowledge of any triggers' calendars. There can be multiple triggers with different calendars anyway.

So you would need to retrieve and check against specific calendar in question whether current time is applicable.
