### ISSUE TITLE
Job CancellationToken Not Cancelled When Quartz Loses Track of Job

### ISSUE THREAD

**Issue by Coder3333** [quartznet/quartznet#748]
### Expected behavior

If a clustered scheduler misses its checkin time and has its active jobs cancelled in the Quartz database, I expect the cancellation token on those jobs to be cancelled so that the job can stop itself.

### Actual behavior

If my clustered scheduler ever misses a checkin time, its jobs are abandoned in the Quartz database, removing their instances from Fired_Triggers,  and new jobs are started up to replace them.  The cancellation token on the original jobs is never marked as cancelled.

### Steps to reproduce

Create an IJob that does not allow concurrent execution that runs for 2 hours before completing, unless the cancellation token is cancelled.  Set the chron expression for the job to run every 10 seconds.  Run this on multiple scheduler instances in a cluster.  Eventually, 1 out of 10 times in my case, you will find multiple instances of your job running at the same time, even though it is marked as preventing concurrent execution.  This will be because the entries for the running job will get removed from Fired_Triggers, signifying to Quartz that it is OK to start up another instance of the job.

**Comment by Coder3333** [comment]
I just found this other issue.  I think it explains why Quartz thinks it needs to launch the duplicate jobs, but my request still stands.  If Quartz abandons my job, I want the cancellation token to be flagged as cancelled so I can prevent duplicate operations from taking place.

https://github.com/quartznet/quartznet/issues/703

**Comment by lahma** [comment]
I'm closing old issues which are "stuck", we can reopen if there's still reproducible problems with 3.1 beta series (there's been fixes to locking for example). A pull request fixing unwanted behavior will also be gladly reviewed. Thanks for understanding.
