### ISSUE TITLE
Cache resolved logger in LibLog

### ISSUE THREAD

**Issue by cosminvlad** [quartznet/quartznet#749]
### Expected behavior

The logging system used should be resolved only once.

### Actual behavior

The logging system used is resolved by LibLog at every call to LogProvider.GetLogger

### Steps to reproduce

When the logger is not explicitly set via `LogProvider.SetCurrentLogProvider`, the method `LogProvider.GetLogger` will call `LogProvider.ResolveLogProvider`, which does not cache the result, doing expensive reflection for determining what logging system is available. 
The impact is most noticeable for large numbers of very small jobs, in a clustered environment, since this reflection happens while holding the `TRIGGER_ACCESS` lock.

![image](https://user-images.githubusercontent.com/44359935/55288377-66cbc500-53bf-11e9-80ee-043335425a42.png)

LibLog has this [fixed](https://github.com/damianh/LibLog/blob/master/src/LibLog/LogProvider.cs#L268) already, but I am not sure what is the corresponding release.

**Comment by lahma** [comment]
Thanks for reporting this, I've updated to the latest LibLog package, now in master.
