### ISSUE TITLE
GetTriggerBuilder does not support IgnoreMisfires misfire instruction

### ISSUE THREAD

**Issue by jofortierEaton** [quartznet/quartznet#750]
### Expected behavior
When a Trigger uses IgnoreMisfires instruction, calling GetTriggerBuilder should return a TriggerBuilder set up with IgnoreMisfires instruction.

### Actual behavior
GetTriggerBuilder returns a TriggerBuilder set up with SmartPolicy misfire instruction.

### Steps to reproduce

```csharp
ITrigger trigger1 = TriggerBuilder.Create()
    .WithSimpleSchedule(x => x
        .WithMisfireHandlingInstructionIgnoreMisfires())
    .Build();
ITrigger trigger2 = trigger1.GetTriggerBuilder().Build();
Console.WriteLine("trigger1.MisfireInstruction: {0}", trigger1.MisfireInstruction); // Prints -1
Console.WriteLine("trigger2.MisfireInstruction: {0}", trigger2.MisfireInstruction); // Prints 0
```
Problem seems to be in the implementation of GetScheduleBuilder() for every type of trigger: there is a "switch" that doen't take into account the case "Quartz.MisfireInstruction.IgnoreMisfirePolicy", so the misfire instruction stays to the default one.

**Comment by lahma** [comment]
Thanks for reporting. Will be part of final 3.1 and next 3.1 beta 2.
