### ISSUE TITLE
I reported an error when I generated the solution and could not locate the included directory

### ISSUE THREAD

**Issue by jibp** [quartznet/quartznet#755]
![image](https://user-images.githubusercontent.com/6679245/56781674-874c3b00-6816-11e9-9e83-8e53f4d35b6b.png

**Comment by lahma** [comment]
`build.cmd` should be used and against GitHub repo checked out, there's already an issue about problems with Git versioning task (https://github.com/quartznet/quartznet/issues/763) when using zip file which is missing the .git directory with its information.
