### ISSUE TITLE
Support to Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by taadis** [quartznet/quartznet#756]
RT. suggest use [Microsoft.Extensions.Logging](https://www.nuget.org/packages/Microsoft.Extensions.Logging)

**Comment by lahma** [comment]
The Microsoft Logging seems to happily co-exist with LibLog so Microsoft Logging can now be used through LibLog until LibLog will be removed. [Documentation updated for upcoming 3.1](https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/configuration-resource-usage-and-scheduler-factory.html#logging).

**Comment by jrowe88** [comment]
Hello, it seems like these too happily co-exist.  If I use MIcrosoft.Extensions.Logging with Log4Net as a provider, Quartz seems to be  picking on the configuration of log4net and logging to Log4net directly.  I end up getting double the log entries.  The example below shows on the first line the logging that is formatted and comes through the MS logging provider.  The 2nd lines seems to be generated from within Quartz.  If I am setting the current provider using: Quartz.Logging.LogContext.SetCurrentLogProvider(), can I tell Quartz to stop using LibLog?  Or, is there some other way to configure this?

"
2021-10-01 15:35:23,049| DEBUG | Batch acquisition of 0 triggers
Quartz.Core.QuartzSchedulerThread: Debug: Batch acquisition of 0 triggers
"
