### ISSUE TITLE
Deadlock after postgresql restarted.

### ISSUE THREAD

**Issue by shenzhigang** [quartznet/quartznet#762]
**The following figure shows where deadlock occurs**
![image](https://user-images.githubusercontent.com/8005935/58692694-ba5b8e80-83c1-11e9-9d0e-37157754b5ef.png)

**Comment by lahma** [comment]
This was probably fixed with https://github.com/quartznet/quartznet/pull/879 so upcoming beta 2 / dev feed builds should be used. We can reopen if still an issue.

**Comment by lahma** [comment]
[3.1 beta 2](https://www.quartz-scheduler.net/2020/07/14/quartznet-3-1-beta-2-released/) has been released and hoping this will be also fixed by it.
