### ISSUE TITLE
Download the latest version of the source code, can not be compiled through, what is the reason? 

### ISSUE THREAD

**Issue by liuzhizj** [quartznet/quartznet#763]
The prompt failed to locate the repository containing the directory Local Source Path 

![image](https://user-images.githubusercontent.com/22095210/58763338-f80c1300-858b-11e9-8779-ad201946be9d.png)

**Comment by lahma** [comment]
What are the errors in English?

**Comment by liuzhizj** [comment]
![image](https://user-images.githubusercontent.com/22095210/59100877-e8107c80-8959-11e9-970b-e7184928a4c8.png)

**Comment by lahma** [comment]
Try running build.cmd .

**Comment by liuzhizj** [comment]
Thank you for your reply. The same is true with build. cmd.

**Comment by lahma** [comment]
So far I've determined that this is because the Git version task is expecting to find .git directory with metadata to use, probably needs some workaround.

**Comment by zhoushilei0918** [comment]
Oh,it really made me confused.I met the same problem and took me few days to solve until saw this answer.  I  ( T - T )  cry...  (poor English qwq)

**Comment by zhoushilei0918** [comment]
I tried it and ran build.cmd, but it still didn't work. 
![image](https://user-images.githubusercontent.com/55078024/69768824-28d8a800-11bd-11ea-871c-21c4b774979f.png)
![image](https://user-images.githubusercontent.com/55078024/69768837-39891e00-11bd-11ea-8c32-6f91f5f2a70e.png)
![image](https://user-images.githubusercontent.com/55078024/69769052-20cd3800-11be-11ea-9680-1eb48ed432ac.png)

The text in red shows the same compilation error as above.Is there something wrong during my operations or in my configuration environment？

**Comment by lahma** [comment]
This issue is open and has not been fixed yet.

**Comment by zhoushilei0918** [comment]
OK,thank you for replying.I'm looking forward to the resolution version. (^_^)~

**Comment by zhoushilei0918** [comment]
Cloning programs directly from git and then running build.cmd is sure Ok like this:

`git clone git@github.com:quartznet/quartznet.git`
` .\build.cmd`

But use the code in zip compiles errors.

**Comment by lahma** [comment]
Yes, see https://github.com/quartznet/quartznet/issues/763#issuecomment-517944918

**Comment by zhoushilei0918** [comment]
Thank you. And Quartz.NET is very well written!
