### ISSUE TITLE
Can't start a CLI command

### ISSUE THREAD

**Issue by GerhardKreuzer** [quartznet/quartznet#769]
Hi,
I have to start a command lind program with an Parameter.
The code works when issuied in the 'main' procedure.
Public Sub Print(path As String, fn As String)

        'myDocument.Version = 13
        myDocument.Save(fn)

        'New ProcessStartInfo created
        Dim p As New ProcessStartInfo

        ' Specify the location of the binary
        p.WorkingDirectory = path
        p.FileName = "pdfToPrinter.exe"

        ' Filename contains blanks, so uese double quotes, please
        p.Arguments = """" & fn & """"

        ' Use a hidden window
        p.CreateNoWindow = True

        ' Start the process
        Process.Start(p)

    End Sub

When I use this code in a Job scheduled by Quartz.net it hangs at Process.Start(p)
The file is still correctly printed but afterwards it Fails to return.

Thanks for helping.

With best regards

Gerhard

**Comment by lahma** [comment]
I'm sorry but this does not seem like a Quartz problem. More like a process handling / printer blocking issue. Unfortunately I neither have the resources nor the time to investigate. I hope you find a solution.
