### ISSUE TITLE
Sql Server job store type always returns default for enum values

### ISSUE THREAD

**Issue by timjen3** [quartznet/quartznet#770]
Quartz v3.0.7
Quartz.Serialization.Json v3.0.7

I am working with the dotnetcore variety.

### Expected behavior

IJob properties that are of the enum type should be set to the correct value on the IJob instance when a job is ran by the scheduler when using the SQL Server job store.

### Actual behavior

Job properties that are of the enum type are being set to the default 0 value on the IJob instance when a job is ran by the scheduler when using the SQL Server job store.

From the documentation, it is questionable whether Quartz.NET claims to support enums. But enums do work properly when using the in-memory store with both the default serializer and the json serializer. Also enums are in my opinion a necessary type to support.

### Steps to reproduce

I made a class which can demonstrate the issue by setting a non-default enum value and then checking for that non-default value when it runs and throwing an exception if set to the default value. The job _will_ throw if you use the SqlProperties. it will _not_ throw if you use the InMemory properties whether you are using the json serializer or the default serializer.

```
using Quartz;
using Quartz.Impl;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Threading.Tasks;

namespace SchedulerConsole
{
	public enum MyEnum
	{
		First = 0,
		Second = 1,
	}

	public class ReproduceItJob : IJob
	{
		public MyEnum Order { get; set; }

		public ReproduceItJob()
		{
			
		}

		public Task Execute( IJobExecutionContext context )
		{
			if ( Order == MyEnum.First )
				throw new Exception("Wrong value!");
			return Task.CompletedTask;
		}
	}

	public static class Reproduce
	{
		private static NameValueCollection SqlProperties = new NameValueCollection {
			{  "quartz.serializer.type", "json" },
			{  "quartz.threadPool.threadCount", "2" },
			{ "quartz.jobStore.Type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" },
			{ "quartz.jobStore.tablePrefix", "QRTZ_" },
			{ "quartz.jobStore.dataSource", "local" },
			{ "quartz.dataSource.local.connectionString", "Server=.\\SQLEXPRESS;Database=QuartzTest;Trusted_Connection=true;" },
			{ "quartz.dataSource.local.provider", "SqlServer" },
			{ "quartz.jobStore.driverDelegateType", "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz" }
		};

		private static NameValueCollection InMemoryProperties = new NameValueCollection {
			{ "quartz.serializer", "json" },
			{ "quartz.threadPool.threadCount", "2" },
			{ "quartz.jobStore.Type", "Quartz.Simpl.RAMJobStore, Quartz" }
		};

		public static async Task ReproduceIt()
		{
			var factory = new StdSchedulerFactory( SqlProperties );
			var scheduler = await factory.GetScheduler();
			await scheduler.Start();

			var dataMap = new JobDataMap()
			{
				{ "Order", MyEnum.Second }
			};
			IJobDetail jobDetail = JobBuilder.Create( typeof(ReproduceItJob) )
				.UsingJobData( dataMap )
				.Build();
			ITrigger trigger = TriggerBuilder.Create()
				.StartAt( DateTime.UtcNow )
				.Build();

			await scheduler.ScheduleJob( jobDetail, new List<ITrigger> { trigger }, true );
			await Task.Delay( 20000 );
			await scheduler.Shutdown();
			Console.ReadKey();
		}
	}
}
```

I also want to mention that even when using the Sql Server store, if I retrieve the job manually it will have the correct enum value set:

```
JobKey jobKey = JobKey.Create( identity, group.ToString() );
return await Scheduler.GetJobDetail( jobKey, token );
```

**Comment by VijayakumarNatarajan** [comment]
Did you try saving your data map values as string instead of enums
`var dataMap = new JobDataMap()
{
 { "Order", MyEnum.Second.ToString() }
};`

**Comment by timjen3** [comment]
@VijayakumarNatarajan That's happening lower down in quartz. At this level I just have an enum property on my job class. Quartz should be handling the conversion from my job class into and out of the job data map.

I ended up creating a custom job factory that uses reflection to build my jobs. If the type of the property to be set is an enum it ensures the value from the job data map is a string before setting the property value. Note, this factory uses DI and requires registering jobs with the DI container.

```
using Microsoft.Extensions.DependencyInjection;
using Quartz;
using Quartz.Simpl;
using Quartz.Spi;
using Quartz.Util;
using System;
using System.Linq;

namespace JobScheduling.Implementations
{
	public class BaseJobFactory : SimpleJobFactory
	{
		private readonly IServiceProvider _provider;

		public BaseJobFactory( IServiceProvider provider )
		{
			_provider = provider;
		}

		public override IJob NewJob( TriggerFiredBundle bundle, IScheduler scheduler )
		{
			var job = (IJob) _provider.GetRequiredService( bundle.JobDetail.JobType );
			var jobProperties = job.GetType().GetProperties()
				.ToDictionary( keySelector: kvp => kvp.Name, elementSelector: kvp => kvp.PropertyType );
			foreach ( var prop in bundle.JobDetail.JobDataMap )
			{
				var propType = jobProperties[ prop.Key ];
				if ( propType.IsEnum )
				{
					ObjectUtils.SetPropertyValue( job, prop.Key, Enum.GetName( propType, prop.Value ) );
				}
				else
				{
					ObjectUtils.SetPropertyValue( job, prop.Key, prop.Value );
				}
			}

			return job;
		}
	}
}

```
