### ISSUE TITLE
Install Quartz.NET as a windows service on Windows 10 - ERROR

### ISSUE THREAD

**Issue by Murplatina** [quartznet/quartznet#775]
### Version: 2.6.2
Topshelf v3.1.135.0,
.NET Framework v4.0.30319.42000

### Expected behavior

I'm trying to install Quartz.NET as a windows service on Windows 10. The version of Quartz.NET is v2.6.2 and i have used [this tutorial](http://geekswithblogs.net/TarunArora/archive/2012/11/16/install-quartz.net-as-a-windows-service-and-test-installation.aspx) to do it. In other OS's like Windows 7 and Windows Server 2012 i have installed this version successfully.

### Actual behavior

But when i run the following command (Quartz.Server.exe -i) to see whether my installation has been successful installed, i have the following exception:

> Topshelf.HostFactory Error: 0 : An exception occurred creating the host, Topshelf.HostConfigurationException: The service was not properly configured: [Failure] Command Line An unknown command-line option was found: SWITCH: i (True) [Success] Name QuartzServer [Success] DisplayName Quartz Server [Success] Description Quartz Job Scheduling Server [Success] ServiceName QuartzServer at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumerable1 results)
     at Topshelf.HostFactory.New(Action1 configureCallback) Topshelf.HostFactory Error: 0 : The service terminated abnormally, Topshelf.HostConfigurationException: The service was not properly configured: [Failure] Command Line An unknown command-line option was found: SWITCH: i (True) [Success] Name QuartzServer [Success] DisplayName Quartz Server [Success] Description Quartz Job Scheduling Server [Success] ServiceName QuartzServer at Topshelf.Configurators.ValidateConfigurationResult.CompileResults(IEnumerable1 results)
     at Topshelf.HostFactory.New(Action1 configureCallback) at Topshelf.HostFactory.Run(Action`1 configureCallback)

### Steps to reproduce
1) Copy ...\Downloads\Quartz.NET-2.6.2\server\bin\4.0 to %program files%\Quartz.NET
2) Run Quartz.Server.exe install
3) Run Quartz.Server.exe -i (to see installation status)

I have tried to modify the display name of the Quartz Service to have no spaces or special characters, but the issue still remains. See issue [here](https://github.com/Topshelf/Topshelf/issues/259) in Topshelf issues.

### **EDIT**

If i install Quartz v2.6.2 (with Topshelf v3.1.4.357038) i get the following error:

> Topshelf.HostFactory Error: 0 : An exception occurred creating the host, Topshelf.HostConfigurationException: The service was not properly configured:
[Failure] Command Line An unknown command-line option was found: SWITCH: i (True)

If if install Quartz v3.0.7 (with Topshelf v4.1.0.172) i get the following error:

> Topshelf.HostFactory Error: 0 : An exception occurred creating the host, Topshelf.HostConfigurationException: The service was not properly configured:
[Failure] Command Line An unknown command-line option was found: DEFINE: i =

When i install Quartz Server as a windows service, start and stop button are always disabled whatever the version of the topshelf.
So by this i suspect that the problem should be in Topshelf configuration.

### **EDIT 2**

I have been confirmed that this error is also being fired in Windows Server 2012 R2 Standard production server, when running the command Quartz.Server.exe -i. The difference is that in production environment we have start/stop buttons enabled, but in windows 10 machine i don't have start/stop buttons enabled.

**Comment by lahma** [comment]
I'm not sure where this `-i` parameter comes from, I don't see such parameter supported by [Topshelf command-line](http://docs.topshelf-project.com/en/latest/overview/commandline.html). I'm closing this issue as it seems to be more Topshelf usage related than Quartz problem. We can reopen if there's something actionable.
