### ISSUE TITLE
Documentation about JobDataMap mentions JobFactory injecting JobDataMap-Values

### ISSUE THREAD

**Issue by saxmaster79** [quartznet/quartznet#776]
### Expected behavior

The Documentation under [Lesson 3](https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/more-about-jobs.html) tells what's actually implemented. I suspect a copy/paste error from the Quartz java documentation.

### Actual behavior

The following paragraph may not be accurate:
"If you add properties with set accessor to your job class that correspond to the names of keys in the JobDataMap, then Quartz’s default JobFactory implementation will automatically call those setters when the job is instantiated, thus preventing the need to explicitly get the values out of the map within your execute method."
-> I have not seen anything like that in the SimpleJobFactory class...

**Comment by saxmaster79** [comment]
Ah now I found the [PropertySettingJobFactory](https://github.com/quartznet/quartznet/blob/master/src/Quartz/Simpl/PropertySettingJobFactory.cs) which actually does this. Is the PropertySettingJobFactory the default JobFactory?

**Comment by lahma** [comment]
Yes, it is the default, only overriding the configuration you can get another implementation: https://github.com/quartznet/quartznet/blob/56ff95ea3172504648cd0d02a16f27ab31b89153/src/Quartz/Core/QuartzScheduler.cs#L75 and it's been since 2.0 I believe https://github.com/quartznet/quartznet/commit/ee47ec3d8e85a0e995329a53276fe51b42bca178#diff-3670816342511c486ea84cb94c3ef967 . Hope this clarifies things.

**Comment by matgrioni** [comment]
Perhaps the documentation could be more clear on this. I have a custom factory using CastleWindsor and just didn't think about where the property setting would happen. A note in the documentation in this area would have saved me some time and helped my initial understanding.

**Comment by lahma** [comment]
The documentation can be found in gh-pages branch, can you improve and send a PR?

**Comment by matgrioni** [comment]
Sure I can take a stab at it this week.
