### ISSUE TITLE
Timed tasks trigger repeated executions, 2 times at the same time,why??

### ISSUE THREAD

**Issue by taotao2014** [quartznet/quartznet#778]
Version: 2.3.3.0

Timed tasks trigger repeated executions, 2 times at the same time,why??

**Comment by taotao2014** [comment]
Is it possible to cause this problem if server cluster time synchronization and time rewind?？？？

**Comment by lahma** [comment]
It can be many things, two schedulers running against same database, without clustered configuration, time sync problem. Anything rings a bell?

**Comment by taotao2014** [comment]
no clustered ,no database mode.

**Comment by lahma** [comment]
Can you update to latest 2.x version, 2.6.2 at this time and check if it still reproes?

**Comment by lahma** [comment]
Closing as inactive.
