### ISSUE TITLE
Implement 'processStreamAndScheduleJobs' method

### ISSUE THREAD

**Issue by deimien** [quartznet/quartznet#78]
When working with streams deleting triggers requires a bit of extra work. The pre-processing commands are not executed when only streams are being used. The behavior is a bit different than when working with files. 

Current behavior can be worked around by inheriting the XMLSchedulingDataProcessor and calling the ExecutePreProcessingCommands method for inherited class explicitly.

It would be nice if I could just call a method directly for XMLSchedulingDataProcessor which would execute pre-processing command internally when working with streams. 

Perhaps the 'processStreamAndScheduleJobs' method (or similar functionality), which exists in java source code, could be implemented to achieve the desired behavior.

**Comment by lahma** [comment]
I believe this can be closed as obsolete.
