### ISSUE TITLE
Basic Documentation Needed

### ISSUE THREAD

**Issue by twzero** [quartznet/quartznet#784]
The documentation and downloadable examples give no examples of how jobs are meant to be cancelled, or even how to list scheduled jobs. I really can't believe somebody would go to the trouble of creating something like this and then just forget to explain how to use even basic features. Can jobs even be cancelled?

**Comment by maulik-modi** [comment]
hi @twzero , to know scheduled jobs, please use code from history plugin https://github.com/quartznet/quartznet/tree/master/src/Quartz.Plugins/Plugin/History

Regarding job cancellation, we opt to delete job instead. Alternatively, you may keep "IsCancelled" field in your job configuration table that gets checked before executing any job.

**Comment by lahma** [comment]
@twzero if your refer to stopping running jobs, maybe reading FAQ entry [How do I stop a Job that is currently executing?](https://www.quartz-scheduler.net/documentation/faq.html#how-do-i-stop-a-job-that-is-currently-executing) and the [example 7, InterrupInProgressJobsExample](https://github.com/quartznet/quartznet/blob/master/src/Quartz.Examples/07_InterrupInProgressJobs/InterrupInProgressJobsExample.cs) can help here.

If you are trying to permanently remove triggering of a job, you need to remove the associated triggers. You can either use `IScheduler.UnscheduleJob` to remove specific triggers or if you wan't whole job gone, `IScheduler.DeleteJob` .
