### ISSUE TITLE
Thread Culture is not working

### ISSUE THREAD

**Issue by MHajisoft** [quartznet/quartznet#786]
Hi,
My app is work on "fa-IR" Culture, When the Job Start, the current Culture of host is not appied, and the Method Executed on "en-US" culture.

### Expected behavior
Job run in "fa-IR" Culture Set in web.config

### Actual behavior
Job runs in "en-US" culture

**Comment by lahma** [comment]
Quartz doesn't change culture settings. Have you tried setting thread default culture settings etc? You can always have a helper implementing `IDisposable` with your jobs that ensures proper culture, for example Azure runs on default culture, `en-US`.

**Comment by MHajisoft** [comment]
Thanks for reply.
I call Quartz Schedule by `Spring.Core` dll. It seems that this dll can not get the `Thread.CurrentCulture`.
Finally i solved my issue, by set these lines in code.
`CultureInfo.DefaultThreadCurrentCulture`
`CultureInfo.DefaultThreadCurrentUICulture`
