### ISSUE TITLE
引用版本 不兼容

### ISSUE THREAD

**Issue by xiangxingze** [quartznet/quartznet#792]
项目版本是.NET Core 2.1
引用了 Quartz.net 3.0.7  提示 版本不兼容
![image](https://user-images.githubusercontent.com/13271663/65208853-dc8c3000-dac8-11e9-9410-e738dc20796c.png)

**Comment by Sicos1977** [comment]
?

**Comment by lahma** [comment]
Can understand, we can reopen if there's some more information.

**Comment by Zhang123Ashan** [comment]
> 项目版本是.NET Core 2.1
> 引用了 Quartz.net 3.0.7 提示 版本不兼容
> ![image](https://user-images.githubusercontent.com/13271663/65208853-dc8c3000-dac8-11e9-9410-e738dc20796c.png)


清理本地的nuget缓存后，重新获取包。
工具->nuget包管理器->程序包管理器设置->常规->清理所有的nuget缓存
