### ISSUE TITLE
Deadlock when db not available.

### ISSUE THREAD

**Issue by Voodoolmar** [quartznet/quartznet#794]
Link to code where deadlock happened

https://github.com/quartznet/quartznet/blob/6025454ba072bd8e178ed0e96c44fcf3c4acb509/src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs#L3806

**Comment by Voodoolmar** [comment]
Deadlock after postgresql restarted. #762

**Comment by MustaCrackish** [comment]
Recently I've stumbled upon this problem in the production environment. Two out of three different scheduler instances got deadlocked. Each is an independent scheduler with it's own database, though they share a database server. Database went offline for a brief period, each affected instance logged "Couldn't rollback ADO.NET connection. Transaction not connected, or was disconnected" message and stopped working. I've done some digging and this is what I've found out:

1. `ExecuteInNonManagedTXLock` method of `JobStoreSupport` class takes a lock (TRIGGER_ACCESS in my case) with **random requester id**
2. Error happens during database operation, transaction rolls back
3. `RetryExecuteInNonManagedTXLock` is called 
4. Eventually it calls `ExecuteInNonManagedTXLock` with same parameters
5. `ExecuteInNonManagedTXLock` **generates new random requester id and tries to take the same lock**
6. The lock is already taken by the first run of the `ExecuteInNonManagedTXLock` method but with a different requestor id and scheduler is deadlocked

I hope that this info will help to get a fix out sooner.

**Comment by lahma** [comment]
@MustaCrackish thank you for your analysis and sorry I didn't get back to investigating it sooner. I've prepared a PR https://github.com/quartznet/quartznet/pull/879 to address the issue, now the same requestor id should be used in subsequent call in the logic.
