### ISSUE TITLE
Typo: startTimeOfDay instead of TimeOfDay 

### ISSUE THREAD

**Issue by kellcomnet2** [quartznet/quartznet#795]
In quartznet/src/Quartz/DailyTimeIntervalScheduleBuilder.cs line 338 there is a typo

"the startTimeOfDay for this trigger to end firing each day at the given time."
should be 
"the TimeOfDay for this trigger to end firing each day at the given time."

**Comment by lahma** [comment]
Thanks for reporting, I've fixed the documentation.
