### ISSUE TITLE
update to  net core 3.0

### ISSUE THREAD

**Issue by ghd258** [quartznet/quartznet#796]
update to net core 3.0

**Comment by lahma** [comment]
Quartz.NET 3.0 supports netstandard2.0 which is compatible with .NET Core 3, .NET Core is just a runtime.

**Comment by Zhang123Ashan** [comment]
#792  
found the  same question in netcoreapp3.0

**Comment by pantonis** [comment]
@lahma What about upgrading to netstandard 2.1?

**Comment by lahma** [comment]
Why?
