### ISSUE TITLE
Consider clarifying in the documentation how to create multiple triggers for a job

### ISSUE THREAD

**Issue by lloydjatkinson** [quartznet/quartznet#798]
Hi,

I read the documentation a few times and it took me some time to realise how to register multiple triggers for one job. Perhaps I didn't understand the documentation but it was only when I looked at the overloads of `ScheduleJob` that I noticed it accepts an `IReadOnlyCollection<ITrigger>`.

Would it be possible to update or add a section in one of the relevant chapters with a snippet such as:

```
await scheduler.ScheduleJob(job1, new List<ITrigger>() { job1FooTrigger, job1BarTrigger }, true, cancellationToken);
```

**Comment by lahma** [comment]
Thanks for reporting. I've pushed [a commit](https://github.com/quartznet/quartznet/commit/cc30970341abdff6ca2622cabb5a27c38a3273a0) that adds this info to couple of places.
