### ISSUE TITLE
Enable SQLite for NetStandard?

### ISSUE THREAD

**Issue by aleksey-kuskov** [quartznet/quartznet#801]
I've found out (the hard way) that SQLite is not enabled as a supported provider for NetStandard (besides SQLite-Microsoft) (i.e. `dbproviders.netstandard.properties` file does not contain SQLite provider listed). My guess is that at the time SQLite provider was not available for NetStandard at the time or is there another reason? It looks to work fine with [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core/) package from what I've tested by manually adding SQLite provider properties using `DbProvider.RegisterDbMetadata()` (I've used values as per `dbproviders.properties` file). Can that provider be now added?

**Comment by lahma** [comment]
It seems that they have this now available. A pull request would be appreciated, I think it's just adding the lines to `dbprovider.netstandard.properties` with the name used in full framework `SQLite` and bringing back the tests in [AdoJobStoreSmokeTest](https://github.com/quartznet/quartznet/blob/master/src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs#L155).

**Comment by aleksey-kuskov** [comment]
Will do.

Also, a note to anyone trying to use [Microsoft.Data.Sqlite.Core](https://www.nuget.org/packages/Microsoft.Data.Sqlite.Core/) and getting a `System.NullReferenceException` at `Microsoft.Data.Sqlite.SqliteConnection.Open()` - you need to use the full [Microsoft.Data.Sqlite](https://www.nuget.org/packages/Microsoft.Data.Sqlite/).

**Comment by lahma** [comment]
Great work, thank you for the contribution!
