### ISSUE TITLE
job execute cmd shell can't output result

### ISSUE THREAD

**Issue by bouyeijiang** [quartznet/quartznet#805]
when the job execute cmd shell and that can't return result. stuck waiting.
for example:

ProcessStartInfo info = new ProcessStartInfo();
info.FileName="cmd";
info.Arguments="java -version";

            info.UseShellExecute = false;
            info.StandardErrorEncoding = Encoding.UTF8;
            info.StandardOutputEncoding = Encoding.UTF8;
            info.CreateNoWindow = true;
            info.RedirectStandardOutput = true;
            info.RedirectStandardError = true;

            using (Process process = Process.Start(info))
            {
                string line = string.Empty;
                process.WaitForExit(1000 * 60 * 60 * 24);

                using (StreamReader reader = process.StandardOutput)
                {
                    line = reader.ReadToEnd();
                    if (string.IsNullOrEmpty(line) == false)
                        return line;
                }
                using (StreamReader error = process.StandardError)
                {
                    var str = error.ReadToEnd();
                    if (string.IsNullOrEmpty(str) == false)
                        line = str;
                }

**Comment by lahma** [comment]
Try something like below (works on my machine). Also check the NativeJob as
a reference:
https://github.com/quartznet/quartznet/blob/master/src/Quartz.Jobs/Job/NativeJob.cs

-Marko
<https://github.com/quartznet/quartznet/blob/master/src/Quartz.Jobs/Job/NativeJob.cs>

ProcessStartInfo info = new ProcessStartInfo();
info.FileName = "cmd.exe";
info.Arguments = "/c java -version";

info.UseShellExecute = false;
info.StandardErrorEncoding = Encoding.UTF8;
info.StandardOutputEncoding = Encoding.UTF8;
info.CreateNoWindow = true;
info.RedirectStandardOutput = true;
info.RedirectStandardError = true;

using (Process process = Process.Start(info))
{
    string line = string.Empty;
    process.WaitForExit(1000 * 60 * 60 * 24);

    using (StreamReader reader = process.StandardOutput)
    {
        string str;
        while (string.IsNullOrEmpty(str = reader.ReadLine()) == false)
            line += str;
    }

    if (!string.IsNullOrWhiteSpace(line))
    {
        return line;
    }

    using (StreamReader error = process.StandardError)
    {
        string str;
        while (string.IsNullOrEmpty(str = error.ReadLine()) == false)
            line += str;

        return line;
    }

}
