### ISSUE TITLE
Misfire didn't fired on restart of scheduler sometimes

### ISSUE THREAD

**Issue by shahjeet297** [quartznet/quartznet#808]
**3.0.6**

The jobs should be handled gracefully and misfired should be triggered for them

When we perform the swap it happens that scheduler was down and on restart the misfired are ignored as well as start time is reset to latest one.

We have enabled the useproperties to true, misfire to excute each missed iteration and RequesryRecovery is also on.

**Comment by lahma** [comment]
I'm closing this as there's not much to work with. We can reopen if there's good reproduction with logs etc.
