### ISSUE TITLE
[Start_Time] update in QRTZ_TRIGGERS table | Jobs misfire instruction configured as "WithMisfireHandlingInstructionIgnoreMisfires"

### ISSUE THREAD

**Issue by asansona15** [quartznet/quartznet#811]
**- Quartz Version used: 3.0.7.0**

 
### Expected behavior

- In one of our applications, we have used QUARTZ.net. where few jobs misfire instruction has been configured as "WithMisfireHandlingInstructionIgnoreMisfires"  means it execute misfire event whatever events were missed and accordingly set "Next" and "Prev" fire time" when misfire execution completes and **Start_Time** remain same when the first-time these jobs was started. 

### Actual behavior

- Sometimes we found few of these jobs START_TIME get updated while quartz service is running. Is this suspicious? or expected in any of the conditions . if this is expected, then possible that misfire will get lost?
 
### Steps to reproduce
There are no fixed steps to reproduce these scenarios as it happens intermittently.

It would be great if we know the cause or this is expected behavior.

```csharp
// scheduler and job configuration, SystemTime prefereably set to fixed point
```
properties["quartz.scheduler.instanceName"] = "TestScheduler";
        properties["quartz.scheduler.instanceId"] = "AUTO";
        properties["quartz.threadPool.type"] = "Quartz.Simpl.SimpleThreadPool, Quartz";
        properties["quartz.threadPool.threadCount"] = "50";
        properties["quartz.scheduler.batchTriggerAcquisitionMaxCount"] = "50";
        properties["quartz.jobStore.useProperties"] = "true";
        properties["quartz.jobStore.clustered"] = "true";
        properties["quartz.jobStore.misfireThreshold"] = "60000";
        properties["quartz.jobStore.type"] = "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz";
        properties["quartz.jobStore.tablePrefix"] = "QRTZ_";
        properties["quartz.jobStore.driverDelegateType"] = "Quartz.Impl.AdoJobStore.SqlServerDelegate, Quartz";
        properties["quartz.jobStore.dataSource"] = "default";
        properties["quartz.dataSource.default.connectionString"] = "server=test.database.windows.net;database=QuartzDatabase;persist security info=True;user id=test;password=****;Max Pool Size=53;Pooling=True;Connect Timeout=30;ConnectRetryCount=3; ConnectRetryInterval=10";
        properties["quartz.dataSource.default.provider"] = "SqlServer";
        properties["quartz.jobStore.acquireTriggersWithinLock"] = "true";
        properties["quartz.serializer.type"] = "binary";

**Comment by lahma** [comment]
You are running clustered, are you sure the are no nodes that might replace the triggers? Start time shouldn't be updated in normal conditions at all.

**Comment by shahjeet297** [comment]
No, we have put the logs to check the same and it was not within the code. Is there any scenario in which library reset the start time like cluster recovery?

**Comment by lahma** [comment]
I'm closing this as hard to reproduce. Please test latest 3.1 beta (or when RTM release available) to check if problem still persists after some locking fixes that have been applied.
