### ISSUE TITLE
How to transition from binary to json serialization

### ISSUE THREAD

**Issue by dsedmak** [quartznet/quartznet#813]
The Quartz.NET Version Migration Guide states that binary serialization is not supported when targeting .NET Core.

We are migrating our application from .NET Framework to .NET Core and so far we have used binary as our serialization format.

Is there an official guide on how to transition from binary to json?
Do we have to manually convert the tables columns from varbinary to varchar and if so which ones and how?

Here is our current configuration:
```csharp
new NameValueCollection
{
    { "quartz.jobStore.type", "Quartz.Impl.AdoJobStore.JobStoreTX, Quartz" },
    { "quartz.serializer.type", "binary" },
    { "quartz.jobStore.dataSource", "myDS" },
    { "quartz.dataSource.myDS.connectionString", "xxxx" },
    { "quartz.dataSource.myDS.provider", "SqlServer" },
    { "quartz.scheduler.instanceName", "xxxx scheduler" },
};
```

**Comment by lahma** [comment]
I think that there might be an error in docs. Binary serialization should work with netstandard2.0, JSON just is preferred for new work.

**Comment by dsedmak** [comment]
That is good to know. How about when specifically targeting netcoreapp3.1?

**Comment by lahma** [comment]
It should be backwards compatible. Please try it out and check that everything works as expected.

**Comment by lahma** [comment]
Closing as no new info.

**Comment by peabnuts123** [comment]
@lahma  @dsedmak It looks like this is **100% incompatible** with .NET Standard or .NET Core, as the [NameValueCollection class is no-longer marked as "Serializable"](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections.Specialized/src/System/Collections/Specialized/NameValueCollection.cs). This produces behaviour seen in a few other issues on here (#672, #661) wherein trying to use "binary" serialisation while running in a .NET Core (or, presumably .NET Standard) throws a runtime exception. 
Using the latest version of Quartz running on .NET Framework does not have this issue as the class _is_ Serializable in this runtime. This removes any possible upgrade path for us off .NET Framework, without somehow offline-converting all the data in our database to JSON using .NET Framework - a process which I'm not sure how to achieve (see also: #813) or whether this is even possible. 
What is the course of action here? We have a huge production database filled with serialized NamedValueCollection data. We can read/write it fine running .NET Framework but I don't see any way of migrating to .NET Core or to JSON-serialized data. 

Is it possible to make a change to Quartz that would allow the reading of an old format and writing of a new format (i.e. supporting both formats at the same time while they are migrated). I can't see how else you would achieve this. I'm happy to contribute to this change if there is an appetite for it.

**Comment by lahma** [comment]
> @lahma @dsedmak It looks like this is **100% incompatible** with .NET Standard or .NET Core, as the [NameValueCollection class is no-longer marked as "Serializable"](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Collections.Specialized/src/System/Collections/Specialized/NameValueCollection.cs). This produces behaviour seen in a few other issues on here (#672, #661) wherein trying to use "binary" serialisation while running in a .NET Core (or, presumably .NET Standard) throws a runtime exception.

OK I can understand your pain, that's bad. 

What about creating a composite `IObjectSerializer` that reads using `BinaryObjectSerializer` and writes back using `JsonObjectSerializer` (and configuring that for for the job store)? This would require you to create an app that uses Quartz API to load all relevant entities (triggers, jobs and calendars I guess) and then persist them back to database again effectively transforming the format?

**Comment by peabnuts123** [comment]
Thanks for responding 🙂 We have decided that we will need to do a migration of the data in the production database through the use of a custom serializer. We were able to pretty easily write a serializer that can read both binary and JSON, and writes only JSON. This will slowly migrate the data in our database while maintaining support for existing data. Furthering on this, we are going to write a background task that slowly requests every job key and resaves the job, thus converting our entire database to JSON. 
That said, it would be probably help a lot of people if somewhere in the docs these limitations were mentioned.

**Comment by peabnuts123** [comment]
For reference, here is the serializer we wrote:

```csharp
public class MigratorSerializer : IObjectSerializer
{
    private BinaryObjectSerializer binarySerializer;
    private JsonObjectSerializer jsonSerializer;

    public MigratorSerializer()
    {
        this.binarySerializer = new BinaryObjectSerializer();
        this.jsonSerializer = new JsonObjectSerializer();
    }

    public T DeSerialize<T>(byte[] data) where T : class
    {
        try
        {
            // Attempt to deserialize data as JSON
            var result = this.jsonSerializer.DeSerialize<T>(data);
            return result;
        }
        catch (JsonReaderException)
        {
            // Presumably, the data was not JSON, we instead use the binary serializer
            return this.binarySerializer.DeSerialize<T>(data);
        }
    }

    public void Initialize()
    {
        this.binarySerializer.Initialize();
        this.jsonSerializer.Initialize();
    }

    public byte[] Serialize<T>(T obj) where T : class
    {
        return this.jsonSerializer.Serialize<T>(obj);
    }
}
```

**Comment by lahma** [comment]
Thank you @peabnuts123 for sharing your solution, I've updated the [JSON serialization integration documentation](https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/json-serialization.html#migrating-from-binary-serialization) to include these tips and the sample serializer. I've also linked to this doc from migration guide.

**Comment by ewortzman** [comment]
@peabnuts123 I am in a similar position to you.  We have a production database filled with binary serialized data and cannot deserialize it to convert because in .NET6, NameValueCollection is not serializeable:

```
System.Runtime.Serialization.SerializationException: 'Type 'System.Collections.Specialized.NameValueCollection' in Assembly 'System.Collections.Specialized, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.'
```

This occurs when attempting to deserailize binary data that contains a NameValueCollection in .NET6.  Did you have to run your custom serializer and migrator task on .NET Framework before you were able to permanently migrate?

**Comment by peabnuts123** [comment]
@ewortzman The project to migrate all this stuff got parked, so we never got to run it across the database. The application was being converted from .NET Framework though, so likely we would have been able to work around that issue in our specific instance (and any testing we did back in the day).
