### ISSUE TITLE
When will the RavenDB job store implementation be ready?

### ISSUE THREAD

**Issue by jabellard** [quartznet/quartznet#814]
When will the RavenDB job store implementation be ready?

**Comment by lahma** [comment]
This currently depends on community contributions too. Things don't get ready if nobody is helping.

**Comment by yj7o5** [comment]
@lahma I can take over this if you like? would love to send PR. And I believe you have the initial workings setup here https://github.com/quartznet/quartznet/tree/features/ravendb-jobstore so I think I can just pickup from this branch.

**Comment by yj7o5** [comment]
Also Raven now actually has 5.0 out so do we stick to 4.0 support for now or directly target for 5.0?

**Comment by yj7o5** [comment]
Additionally, does the ravendb-jobstore branch also needs to cover all the changes you're intending as it relates to other infrastructure items #988 (Logging, DI, etc) as well?

**Comment by lahma** [comment]
`features/ravendb-jobstore` contains mostly refactoring needed to get the API "more logical" for document database usage, should improve the ADO.NET usage too (I hope). Unfortunately it's a bit behind the latest in master so a painful rebase required.

I think we should use LTS 4.x client lib as it should also work against 5.x server. This way we can support both usages. I for example haven't upgraded to 5.x series yet in production.

Easier to limit to JobStoreSupport level, not trying to fix all things. DI and logging will be complex changes enough without the RavenDB case.

**Comment by nefarius** [comment]
[I did so for RavenDB 5.x btw.](https://github.com/ravendb/quartznet-RavenDB/pull/14) 😁

**Comment by lahma** [comment]
@nefarius great work! I'm closing this issue as there is now viable solution for this - I'll leave the release and promoting process to the external library authors 🙂
