### ISSUE TITLE
How to not start immediatly the jobs in the scheduler in asp.net core

### ISSUE THREAD

**Issue by blizzger** [quartznet/quartznet#815]
### Version: x.y.z
Quartz 3.0.7

### Expected behavior

I have several jobs what i want to fire manually with the scheduler.

### Actual behavior

If i call the scheduler.Start() it will fire all of my registered jobs. I try to pauseAll() or not to call the Start() method and trigger the jobs with the triggerJob(Jobkey) but when i call this, nothing happened.

### Steps to reproduce
I have a quartzHostedService in my asp.net core application, and it runs when i start my app.
This is the hosted service start method where i create the scheduler and registered all of my jobs.
        public async Task StartAsync(CancellationToken cancellationToken)
        {
            await SchedulerController.InitializeScheduler(_schedulerFactory, _jobFactory);

            foreach (var jobSchedule in _jobSchedules)
            {
                var job = CreateJob(jobSchedule);
                var trigger = CreateTrigger(jobSchedule);
                SchedulerController.JobDetails.Add(job);
                await SchedulerController.Scheduler.ScheduleJob(job, trigger, cancellationToken);
            }
            await SchedulerController.Scheduler.Start();
            var jobDetail = SchedulerController.JobDetails.FirstOrDefault(key => key.Description =="xyJob");
            await SchedulerController.Scheduler.PauseAll(cancellationToken);
            await SchedulerController.Scheduler.TriggerJob(jobDetail.Key);
        }
       private static IJobDetail CreateJob(JobSchedule schedule)
        {
            var jobType = schedule.JobType;
            return JobBuilder
                .Create(jobType)
                .WithIdentity(jobType.FullName)
                .WithDescription(jobType.Name)
                .UsingJobData("Name",jobType.Name)
                .StoreDurably(true)
                .Build();
        }

        private static ITrigger CreateTrigger(JobSchedule schedule)
        {
            return TriggerBuilder
                .Create()
                .WithIdentity($"{schedule.JobType.FullName}.trigger")
                .WithCronSchedule(schedule.CronExpression)
                .WithDescription(schedule.CronExpression)
                .Build();
        }
This is my schedularController class:

 public static class SchedulerController
    {
        public static IScheduler Scheduler { get; set; }

        public static List<IJobDetail> JobDetails { get; set; }

        public static List<ITrigger> Triggers { get; set; }

        public static async Task InitializeScheduler(ISchedulerFactory schedulerFactory, IJobFactory jobFactory)
        {
            Scheduler = await schedulerFactory.GetScheduler();
            JobDetails = new List<IJobDetail>();
            Triggers = new List<ITrigger>();
            Scheduler.JobFactory = jobFactory;
        }
    }

I create my jobs in the startup.cs.

public void ConfigureServices(IServiceCollection services)
        {
            //Add quartz services
            services.AddSingleton<IJobFactory, SingletonJobFactory>();
            services.AddSingleton<ISchedulerFactory, StdSchedulerFactory>();
            //Add our job
            services.AddSingleton<xyJob>();
            services.AddSingleton(new JobSchedule(
                jobType: typeof(xyJob),
                cronExpression: "0/3 * * * * ?"));
}

**Comment by lahma** [comment]
There's now proper support for configuring jobs and triggers from 3.1 beta 1 onwards, https://www.quartz-scheduler.net/2020/07/08/quartznet-3-1-beta-1-released/ . If you don't want your triggers to run, don't add them. You can always trigger manually, but that's a bit odd use case for Quartz.
