### ISSUE TITLE
Sql Server runs with very high CPU and generates massive numbers of query plans

### ISSUE THREAD

**Issue by IDDesigns** [quartznet/quartznet#817]
We are running:

Sql Server 2017 with a single database containing only contents created by the Quartz 3.0.7 sql server script and Quartz 3.0.7.

Running against this database we have about 500 load balanced pairs (so around 250 unique sched_names) running from other servers.

The SQL server is constantly running with very high CPU and the query plan cache is regularly flushed due to so many plans being created, all of which is generated by Quartz traffic.
The load on the scheduler servers running the jobs is what I would expect from the jobs we are running.

Upon further investigation it would appear that the load on the sql server is, in part, due to the fact that the sched_name is hardcoded into the queries so query plans cannot be shared across multiple schedulers.

To help verify that this will help things I have forked the source and created the following branch: https://github.com/IDDesigns/quartznet/tree/features/parameteriseSchedName
which (hopefully) turns all the usages of sched_name into parameters. 
(I'm currently in the fairly early stages of testing this)

Is there any reason why this change wouldn't work?
If not, is this change something that would be considered for inclusion?

Many thanks

Ian

**Comment by lahma** [comment]
This sounds like exactly what is needed. I have some preliminary work related to fixing locking code using regular varchars that causes index scans, but it shouldn't collide with this work.

A pull request would be very welcome 👍

**Comment by lahma** [comment]
Thank you very much, great work!
