### ISSUE TITLE
System.IO.FileNotFoundException in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by blacksnake-rus** [quartznet/quartznet#822]
### Expected behavior
At the time of initialization occurred 38 error "System.IO.FileNotFoundException in System.Private.CoreLib.dll"
This happens when trying to get a type Serilog from an assembly using a reflection: `Type.GetType("Serilog.Log, Serilog")`

If I add a link to the Serilog in the project, no errors occur.

Maybe should add the Serilog as an dependencies to the Nuget?

**Comment by lahma** [comment]
This might be some debugger information. Quartz should work fine without Serilog being present.
