### ISSUE TITLE
LibLog deprecated

### ISSUE THREAD

**Issue by fgsantos89** [quartznet/quartznet#827]
The LibLog are now deprecated as the issue https://github.com/damianh/LibLog/issues/270 says.
Did you will replaced this lib?

**Comment by lahma** [comment]
I think LibLog will be replaced with the MS abstraction in v4, quite breaking change after all.

**Comment by lahma** [comment]
I'm closing this in favor of https://github.com/quartznet/quartznet/issues/756 which was created earlier so we have single issue to follow.
