### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by liangshiw** [quartznet/quartznet#828]
### Version: 3.7.0

I used quartz on the aspnetcore3.0 project, and I found that memory grows and is not recycled after creating a large number of jobs.

Here's a simple example project to duplicate it

https://github.com/liangshiw/MemoryLeakDemo

After running the console application, memory grows dramatically and is not reclaimed

![image](https://user-images.githubusercontent.com/16813853/75415003-41479280-5965-11ea-8e21-258b1b163cd2.png)

This is a great project. Am I using it incorrectly? Thanks for your help.

**Comment by liangshiw** [comment]
I found the reason because the method `DeleteJob` was not called. Should the life cycle of the job be maintained by quartz ?

**Comment by lahma** [comment]
You really don't want to do this on every GET request. Just initialize the scheduler as part of  Startup's ConfigureServices/Configure. As you are always adding 5000 jos on each request it might just create too much backlog and memory grows before Quartz has time to free.

**Comment by liangshiw** [comment]
@lahma 
I updated the sample project. After all jobs are completed, the memory is still not reclaimed.
I read the source code `TriggeredJobComplete` method will delete Trigger and Job.
This is very strange, did I miss something?

![image](https://user-images.githubusercontent.com/16813853/75428683-8c709e00-5983-11ea-9e1e-22c2eee6bc81.png)

**Comment by liangshiw** [comment]
My mistake, this is the design of the dictionary
