### ISSUE TITLE
Exception raised on shutdown with mocked SystemTime

### ISSUE THREAD

**Issue by pierluca** [quartznet/quartznet#829]
### Expected behavior

In a test environment, with SystemTime being mocked, I expect to be able to Shutdown() the Quartz scheduler.

### Actual behavior

An exception is raised and threads are left running, including ClusterManager.

### Steps to reproduce

Move the mocked SystemTime backwards (it happened to us because of a bug...) , the "timeToSleep" (see Analysis) becomes a positive value, above Int32.MaxValue in milliseconds, which causes an exception and prevents the Shutdown from completing. ClusterManager is left running.

### Analysis

In MisfireHandler , Run method:

```csharp
                DateTimeOffset sTime = SystemTime.UtcNow();

                // [...]
                TimeSpan timeToSleep = TimeSpan.FromMilliseconds(50); // At least a short pause to help balance threads
                if (!recoverMisfiredJobsResult.HasMoreMisfiredTriggers)
                {
                    timeToSleep = jobStoreSupport.MisfireHandlerFrequency - (SystemTime.UtcNow() - sTime);
                    if (timeToSleep <= TimeSpan.Zero)
                    {
                        timeToSleep = TimeSpan.FromMilliseconds(50);
                    }

                    if (numFails > 0)
                    {
                        timeToSleep = jobStoreSupport.DbRetryInterval > timeToSleep ? jobStoreSupport.DbRetryInterval : timeToSleep;
                    }
                }

                // when sTime >> UtcNow(), this line raises the following exception:
                // System.ArgumentOutOfRangeException: The value needs to translate in milliseconds to -1 (signifying an infinite timeout), 0 or a positive integer less than or equal to Int32.MaxValue.

                await Task.Delay(timeToSleep, token).ConfigureAwait(false);
```

### Suggested solution

Could we add a sanity check on timeToSleep so that it defaults to jobStoreSupport.MisfireHandlerFrequency if timeToSleep is higher than it ?

**Comment by lahma** [comment]
This is a very specific case that shouldn't happen outside of tests (SystemTime is meant to be used when testing). I will gladly review a pull request, but I'm closing this for now while waiting a PR for review.

**Comment by pierluca** [comment]
@lahma At this point, I am not involved in the Quartz.Net project that identified this issue and I may not be able to contribute a PR.

Nonetheless, should someone have the time to do it, would the solution I suggested above be OK for you?

**Comment by lahma** [comment]
Change is OK as long it just checks the overflow and uses sane value in that case,  sure.
