### ISSUE TITLE
DateTimeOffset stored as ISO 8601 string in JobDataMap is discarded when executing the job

### ISSUE THREAD

**Issue by dmk99** [quartznet/quartznet#834]
### Version: 3.0.7
 
- dotnetcore 3.1.200

### Expected behavior

When storing a `DateTimeOffset` (ISO 8601) string in the `JobDataMap` and having it serialised into a ADO Store. I expect to be able to retrieve the `DateTimeOffset` from the job context when the job executes.

The following config is set (as well as the ADO store details):
- `quartz.jobStore.useProperties = true`
- `quartz.serializer.type = json` 

### Actual behavior

I am unable to get the `DateTimeOffset` (ISO 8601) string from the `MergedJobDataMap` associated with the job execution context. I need to prefix the string value with something else to be able to retrieve it. It is stored in the database, but when pulling it into the executing job it's not there.

My shot in the dark guess is that the deserialiser is picking up that the string is a `DateTimeOffset` 
 and is thus deserialising it into that type whereas JobDataMap is expecting all values to be strings (due to the `useProperties` config) and quietly discards anything which is not.

### Steps to reproduce

1. Set the `quartz.jobStore.useProperties = true` value in config
2. Set the `quartz.serializer.type = json` value in config
3. Create a new job/trigger with at least one `DateTimeOffset` stored as a string using the ISO 8601 format.
```
var job = JobBuilder.Create<ExampleJob>()
			.WithIdentity("Example", group)				
                         .UsingJobData("executed_at", DateTimeOffset.Now.ToString("O"))
                         .Build();

var jobTrigger = TriggerBuilder.Create()
				.WithIdentity("ExampleTrigger", group)
				.StartNow()
				.Build();
```
4. Now schedule the job. When it gets executed the `IJobExecutionContext` will not have the `executed_at` property defined in the `MergedJobDataMap`.

If I store the DateTimeOffset like this, then I can retrieve it as a string and parse it myself:
```
 .UsingJobData("executed_at", $"{nameof(DateTimeOffset)}:{DateTimeOffset.Now:O}")
```

**Comment by olicooper** [comment]
I think this is related to my question? https://github.com/quartznet/quartznet/issues/840

**Comment by dmk99** [comment]
> I think this is related to my question? #840

Yes, this looks like it's the same issue.

**Comment by olicooper** [comment]
Hey @dmk99 If you want to use the fix for this now, you can use the preview/nightly version of the library which can be found at this [MyGet Feed](https://www.myget.org/F/quartznet/api/v3/index.json)

If this doesn't fix your issue then let me know and I'll try to see why if I can 👍

**Comment by dmk99** [comment]
Hi @olicooper,

Thank you for your fix. It works nicely when I set the `quartz.jobStore.useProperties = false` config. So I have changed that in my configuration. Thanks!

Unfortunately the issue described above still occurs when `quartz.jobStore.useProperties = true`. I was following the comment at the bottom of this page: https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/job-stores.html

> **Configuring AdoJobStore to use strings as JobDataMap values (recommended)**
> quartz.jobStore.useProperties = true

Is this still valid?

**Comment by olicooper** [comment]
I believe `quartz.jobStore.useProperties = true` instructs Quartz to store and retrieve all values as strings instead of trying to serialize and deserialize the object (see code below). The reason this is the recommended option is that it is unlikely to break when Quartz knows all values are simple strings, but I think it is also safe to use primitive types and have this option set to `false`. As long as you avoid using classes then you'll probably be safe.

https://github.com/quartznet/quartznet/blob/master/src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs#L3254-L3256
