### ISSUE TITLE
Support NuGet pre-release?

### ISSUE THREAD

**Issue by olicooper** [quartznet/quartznet#836]
I need to be able to test my project against the new features in the upcoming 3.1.0 release but I cannot see any pre-release train to start my testing.. would this be something you'd be able to do?

https://docs.microsoft.com/en-us/nuget/create-packages/prerelease-packages

**Comment by lahma** [comment]
Can you try the [MyGet Feed](https://www.myget.org/F/quartznet/api/v3/index.json), it contains every master build.

**Comment by lahma** [comment]
Circling back there to inform that 3.1 beta 1 is now out!

https://www.quartz-scheduler.net/2020/07/08/quartznet-3-1-beta-1-released/
