### ISSUE TITLE
Switch to Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by tomap** [quartznet/quartznet#839]
Hi,

In our project, we are switching from System.Data.SqlClient to Microsoft.Data.SqlClient
The "migration" is pretty straightforward, but Quartz has a dependency to System.Data.SqlClient

Would it be possible to either:
* switch to Microsoft.Data.SqlClient
* move the SQL related code to another dedicated nuget
* only depend on System.Data interfaces (Idbconnection) and let the "user" choose between Microsoft.Data.SqlClient or System.Data.SqlClient

or maybe you already have a plan of your own?

Best regards,

Thomas

**Comment by lahma** [comment]
This is a great feature request, thank you for bringing this up. I see three usages of the library when removing the dependency:

* catching `SqlException` for connecting/shutdown, might be wrong approach here to be DB agnostic anyway, general exception might be better
* detecting `SqlConnection` being connection type without proper delegate, this probably could be done with string matching using type information
* transient failure detection with `SqlException` and its errors collection

I think only the last point with transient failure detection is more problematic and would require having a different NuGet. However, I would like to avoid adding per-database NuGet if possible. Reflection might be one option here and investigating exceptions/types runtime. Especially the exceptions shouldn't be a problem performance wise as it should be a more rare occasion.

Would you like to make a PR for this?

**Comment by shatl** [comment]
Other option would be to wrap database related exception to Quartz exceptions

**Comment by lahma** [comment]
I'll try what happens if we switch to use the new package altogether...
