### ISSUE TITLE
Could not load file or assembly 'Quartz.XmlSerializers

### ISSUE THREAD

**Issue by pigwing** [quartznet/quartznet#842]
### Expected behavior

when is upgrade .net core 3.1 SDK version 3.1.3 throw this exception

**Comment by pigwing** [comment]
i found a solution XmlSerializer xs = new XmlSerializer(typeof(QuartzXmlConfiguration20), typeof(QuartzXmlConfiguration20).GetNestedTypes());

**Comment by lahma** [comment]
OK seems that this is sorted, though didn't understand how/when this happens as test suite with XML files works as expected.
