### ISSUE TITLE
Quartz.net SQliteJobStore do not support  Cluster

### ISSUE THREAD

**Issue by zaozaoniao** [quartznet/quartznet#845]
###  Quartz -Version 3.0.7
For  Quartz -Version 3.0.7，I use sqliteJobStore to store the job and trigger.
In Stand-only program, everything is good。

But when I add the below code to **support cluster**
```
["quartz.jobStore.clustered"] = "true",
["quartz.scheduler.instanceId"] = "AUTO"
```
An exception is generated： 
```
SQLite cannot be used as clustered mode due to locking problems
```
I have found the  exception sourcec ode in ：
https://github.com/quartznet/quartznet/blob/master/src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs

It seems that the sqlitejobStore could not support quartz.net cluster..
I am very frustrated.

### workarounds 
I do not want to change db for Quartz.net。
I found a  comment show：
> The DriverDelegate is responsible for doing any ADO.NET work that may be needed for your specific database. StdAdoDelegate is a delegate that uses “vanilla” ADO.NET code (and SQL statements) to do its work. If there isn’t another delegate made specifically for your database, try using this delegate - special delegates usually have better performance or workarounds for database specific issues

So I change  the **SQliteAdoDelegate**  to  **StdAdoDelegate**：
```
quartz.jobStore.driverDelegateType = Quartz.Impl.AdoJobStore.StdAdoDelegate, Quartz
```
and  deploy to  quartz cluster, It seems  quartz.net clsuer  worked..

### Question?
- SQLiteJobStore do not  support Quartz.net  cluster? change to StdAdoDelegate is right  ?
- Is success a coincidence?
- Are other components affected?

**Comment by lahma** [comment]
From [Appropriate Uses For SQLite](https://www.sqlite.org/whentouse.html)

> Many concurrent writers? → choose client/server
> 
> If many threads and/or processes need to write the database at the same instant (and they cannot queue up and take turns) then it is best to select a database engine that supports that capability, which always means a client/server database engine.
> 
> SQLite only supports one writer at a time per database file. But in most cases, a write transaction only takes milliseconds and so multiple writers can simply take turns. SQLite will handle more write concurrency that many people suspect. Nevertheless, client/server database systems, because they have a long-running server process at hand to coordinate access, can usually handle far more write concurrency than SQLite ever will.

Cluster will have concurrent writers and thus this setup is not supported. It's intentional to steer away from such configuration that will cause trouble.
