### ISSUE TITLE
DailyTimeIntervalTrigger incorrect next fire time when next fire happens after DST switch

### ISSUE THREAD

**Issue by chrislukkk** [quartznet/quartznet#846]
### Version: x.y.z
2.6.1 and 3.0.7
We are using an older version of quartz(2.6.1) but same issue exists in 3.0.7.

### Expected behavior

I'm using an example of DST in USA this year where Sunday, March 8, 2020, 2:00:00 am clocks were turned forward 1 hour to Sunday, March 8, 2020, 3:00:00 am local daylight time instead.
If I have a **DailyTimeIntervalTrigger created to run every 2 hours between 17:00 and 19:30 every weekday starting 17:00 March 6 EST**, I would expect the next fire times looks like this: 

1) 3/6 10PM UTC (3/6 5PM EST)
2) 3/7 12AM UTC (3/6 7PM EST)
3) **3/9 9PM UTC (3/9 5PM EDT)**
4) 3/9 11PM UTC (3/9 7PM EDT)
....

### Actual behavior

What I got from the schedule is 
1) 3/6 10PM UTC (3/6 5PM EST)
2) 3/7 12AM UTC (3/6 7PM EST)
3) **3/9 10PM UTC (3/9 6PM EDT)**
4) 3/9 11PM UTC (3/9 7PM EDT)
....

The fire time of first execution after DST is late by an hour which is unexpected. It seems the schedule "auto heal" from second execution after DST.

I've also tested when the DST ends in November and the Monday after that the schedule will run 3 times instead which is also incorrect

### Steps to reproduce
The following unit tests will fail

```csharp
       [Test]
        public void TestDayLightSaving3()
        {
	        var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
	        //UTC: 2020/3/7/ 00:00  EST: 2020/3/6 19:00
			var startTime = new DateTimeOffset(2020, 3, 7, 0, 0, 0, TimeSpan.Zero);
	        var trigger = DailyTimeIntervalScheduleBuilder.Create()
		        .StartingDailyAt(TimeOfDay.HourAndMinuteOfDay(17, 00))
		        .EndingDailyAt(TimeOfDay.HourAndMinuteOfDay(19, 30))
		        .OnDaysOfTheWeek(new[] { DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday, DayOfWeek.Thursday, DayOfWeek.Friday })
		        .WithIntervalInHours(2)
		        .InTimeZone(timeZoneInfo)
		        .Build();

	        var first = trigger.GetFireTimeAfter(startTime);
	        //UTC: 2020/3/9/ 21:00  EST: 2020/3/9 17:00
			Assert.That(first, Is.EqualTo(new DateTimeOffset(2020, 3, 9, 21, 0, 0, TimeSpan.Zero)));
        }

        [Test]
        public void TestDayLightSaving4()
        {
	        var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
			//UTC: 2019/11/1/ 23:00  EST: 2019/11/1 19:00
			var startTime = new DateTimeOffset(2019, 11, 1, 23, 0, 0, TimeSpan.Zero);
			var trigger = DailyTimeIntervalScheduleBuilder.Create()
		        .StartingDailyAt(TimeOfDay.HourAndMinuteOfDay(17, 00))
		        .EndingDailyAt(TimeOfDay.HourAndMinuteOfDay(19, 30))
		        .OnDaysOfTheWeek(new[] { DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday, DayOfWeek.Thursday, DayOfWeek.Friday })
		        .WithIntervalInHours(2)
		        .InTimeZone(timeZoneInfo)
		        .Build();

	        var first = trigger.GetFireTimeAfter(startTime);
	        //UTC: 2019/11/4/ 22:00  EST: 2019/11/1 17:00
			Assert.That(first, Is.EqualTo(new DateTimeOffset(2019, 11, 4, 22, 0, 0, TimeSpan.Zero)));
        }
```

**Comment by chrislukkk** [comment]
Checking the code and it seems the AdvanceToNextDayOfWeekIfNecessary in DailyTimeIntervalTriggerImpl use DateTimeOffset.AddDays to advance days but not handle the case if DST happens as part of the advance.
I have a fork branch with some changes in DailyTimeIntervalTriggerImpl and the tests above are passing. Let me know if I should create a pull request for that. Thanks!
https://github.com/quartznet/quartznet/compare/master...chrislukkk:dailytimeintervaltrigger-correct-next-fire-time-across-dst-switch

**Comment by lahma** [comment]
Thank you for reporting and even creating the fix for the issue 👍
