### ISSUE TITLE
FeatureRequest: Enable Lastday Of Month Schedules

### ISSUE THREAD

**Issue by EwaldStricker** [quartznet/quartznet#849]

**Comment by lahma** [comment]
Can you please elaborate.

**Comment by EwaldStricker** [comment]
I need a cron expression like0 0 0 lom 1/1 ? *Starting e.g. 01.01.2020 fires on every last day of the month- 31.01.2020- 29.02.2020- 31.03.2020- 30.04.2020- ...Kr EwaldAm 28.04.20, 20:16 schrieb Marko Lahma <notifications@github.com>:

   
  Can you please elaborate.

**Comment by olicooper** [comment]
I believe Quartz can already do this. I made an example: https://dotnetfiddle.net/ZyKYl3
And you can use this to create cron expressions: https://www.freeformatter.com/cron-expression-generator-quartz.html

**Comment by EwaldStricker** [comment]
Hi Oli,thanks a lot. This is very helpful!!!KR EwaldAm 06.05.20, 15:24 schrieb olicooper <notifications@github.com>:

   
  I believe Quartz can already do this. I made an example: https://dotnetfiddle.net/ZyKYl3 And you can use this to create cron expressions: https://www.freeformatter.com/cron-expression-generator-quartz.html

**Comment by EwaldStricker** [comment]
Mit freundlichen GrüßenEwald StrickerAm 18.05.20, 21:41 schrieb Marko Lahma <notifications@github.com>:

   
  Closed #849.
