### ISSUE TITLE
Old Version Build Request

### ISSUE THREAD

**Issue by steveskalski** [quartznet/quartznet#850]
Hi,
  I am looking for an older build of Quartz.NET, specifically version quartznet-2.3.2 with all DLLs and scheduler built.  I believe these builds use to be available (prebuilt) on your old site but now there is only source code in the release.  Also the release on Githuib does not build (error missing AssemblyInfo.cs).  Is it possible to provide the old build with all dlls?

  Thank you.  I really appreciate the Quartz.Net package.

**Comment by lahma** [comment]
You can build using the `build.cmd` , it also generates the AssemblyInfo.cs that you saw missing. [Here are the older releases](https://sourceforge.net/projects/quartznet/files/quartznet/), they are still on SourceForge platform.

Hope this helps.

**Comment by steveskalski** [comment]
Thank you so much this helped a  ton.
