### ISSUE TITLE
Version 3.1 release date estimate?

### ISSUE THREAD

**Issue by olicooper** [quartznet/quartznet#851]
I see that the 3.1 release is quite close to completion so I was wondering if you had an idea of roughly when this might be released? The nightly release is fine, but for piece of mind its nice to have an official tested version running in production :)

For other peoples reference, there are nightly releases of 3.1.0 built from the master branch (though it is called 3.0.8 currently). You can find it on MyGet https://www.myget.org/F/quartznet/api/v3/index.json.

**Comment by lahma** [comment]
Hopefully soon. I don't see any blockers for the release, mostly QA and documentation. But it's a struggle to find the the to do things properly. I hope you folks can use the MyGet release meanwhile.

**Comment by lahma** [comment]
The 3.1 beta 1 is now out and after some period of kicking the tires it will eventually lead to having the final version out. Please update to beta and give feedback how it works for you!

https://www.quartz-scheduler.net/2020/07/08/quartznet-3-1-beta-1-released/

I'm closing this issue in hopes of actually having the final release out in the near future 😉
