### ISSUE TITLE
Jobs Being Paused and Never Resuming under heavy load

### ISSUE THREAD

**Issue by steveskalski** [quartznet/quartznet#852]
I am using Quartz.NET-2.3.2 with the prebuilt quartz Server service.  I am finding that under heavy load randomly a job will report Paused and the next trigger would be in the past.  I have not been able to catch exactly why this is happening but my guess is the jobs are over running or the system is too busy to run the job.  In either case is there something I can do to make sure the job runs when it can?  

I have RequestRecovery set to false for all my jobs, could this cause the issue?  All my jobs have the following attributes set [PersistJobDataAfterExecution] and [DisallowConcurrentExecution]

Thank you for any help/guidance you can provide.

**Comment by lahma** [comment]
I would strongly suggest upgrading to latest 2.x release and if anyhow possible, even to 3.x series. Usually every release has some sort of bug fixes and it would be painful road trying to troubleshoot such an old version.

There's changes listed for every release in [the change log](https://github.com/quartznet/quartznet/blob/master/changelog.md#release-232-mar-30-2015) (scroll up from your release) and if you migrate to 3.x [there's a migration guide available](https://www.quartz-scheduler.net/documentation/quartz-3.x/migration-guide.html).

**Comment by lahma** [comment]
Closing as no new info.
