### ISSUE TITLE
Full list of configuration settings?

### ISSUE THREAD

**Issue by xKumox** [quartznet/quartznet#855]
Where can I find a full list of configuration settings? 
According to this page : https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/configuration-resource-usage-and-scheduler-factory.html

> There are some sample configurations (including descriptions of the properties) in the “docs/config” directory of the Quartz distribution. You can find complete documentation in the “Configuration” manual under the “Reference” section of the Quartz documentation.

But when I go to what appears to be that page https://www.quartz-scheduler.net/documentation/quartz-3.x/configuration/index.html I get the message: "Sorry not ready"

Ive also found [this ](https://github.com/quartznet/quartznet/blob/67697a1f610911d494808487f3b2af0f5b3724e7/src/Quartz.Server/quartz.config), but I am not sure if that is a complete list?

Is there a full list of configuration settings anywhere? Thanks!

**Comment by lahma** [comment]
There's no complete documentation at the moment, and a PR for such against the gh-pages branch would be very welcome!

There's the base set of configuration that can be obtained from samples and tests but there's also the dynamic behavior part. One can define own job store type and create a property setter `public bool MyAwesomeToggle { get; set; }` which then would be configurable via `"quartz.jobStore.myAwesomeToggle" = "true"`. So reflection allows to inject values too.

[The Java version's configuration guide](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/) is a good start, just mentally remove prefix `org.` and when `.class` is used, it's `.type` in .NET world.
