### ISSUE TITLE
With 3.0.5 you should be able to use new provider with name OracleODPManaged out of the box.

### ISSUE THREAD

**Issue by rsankati** [quartznet/quartznet#857]
With 3.0.5 you should be able to use new provider with name OracleODPManaged out of the box.

_Originally posted by @lahma in https://github.com/quartznet/quartznet/issues/609#issuecomment-392350845_

Hi, I'm migrting quartz func to .net  core, So i've changed respective dll's (Used oracle.managed.dataacess 2.19,Quartz 3.0.5 version) and configured quartz prop correctly. no erros but when i ran it's not scheduling jobs and i'm also not seeing entries in respective tables

**Comment by lahma** [comment]
You should probably enable logging and see what is happening. Issue is way too obscure to understand without details. We can reopen if something tangible is found.
