### ISSUE TITLE
Concurrency Exception with multiple schedulers

### ISSUE THREAD

**Issue by Coder3333** [quartznet/quartznet#860]
### Version: x.y.z
Quartz.Net 3.0.7

### Expected behavior
No error when running more than one instance of scheduler in a process.

### Actual behavior

Quartz.SchedulerException: Could not Initialize DataSource: default
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Quartz.Impl.AdoJobStore.Common.DbProvider.GetDbMetadata(String providerName)
   at Quartz.Impl.AdoJobStore.Common.DbProvider..ctor(String dbProviderName, String connectionString)
   at Quartz.Impl.StdSchedulerFactory.Instantiate()
   --- End of inner exception stack trace ---
   at Quartz.Impl.StdSchedulerFactory.Instantiate()
   at Quartz.Impl.StdSchedulerFactory.GetScheduler(CancellationToken cancellationToken)

### Steps to reproduce
Start multiple schedulers in the same process.

The source code for Quartz.Impl.AdoJobStore.Common.DbProvider establishes dbMetadataLookup as a regular dictionary and maintains the variable as a static, meaning that all instances of DbProvider share the same instance of dbMetadataLookup.  This needs to be changed to a ConcurrentDictionary, so that multiple threads can reference the same variable without the opportunity to throw these types of exceptions as they all insert and try to read values from the Dictionary at the same time.

```csharp
	private static readonly Dictionary<string, DbMetadata> dbMetadataLookup = new Dictionary<string, DbMetadata>();
```

**Comment by lahma** [comment]
Thank you for reporting this! Your investigation result seems quite valid. Could you provide a PR to fix the issue?

**Comment by Coder3333** [comment]
@lahma , I probably did this PR thing wrong.  I have never contributed to this repository before.  I just went for the simple fix.  It could have be done using Lazy to prevent creating the same metadata twice, but this will at least avoid exceptions. https://github.com/quartznet/quartznet/pull/861

**Comment by lahma** [comment]
Thank you for your contribution! Merged to master.

**Comment by Coder3333** [comment]
@lahma , I added another PR with the additional Lazy logic I mentioned, if you are interested.  I did not get to test out the change, but I use this pattern all the time, so I am confident that it will work.  Sorry for not rebasing first, but I think it will merge cleanly.

https://github.com/quartznet/quartznet/pull/862
