### ISSUE TITLE
IIS: job is fired but not started after AppPool recycle

### ISSUE THREAD

**Issue by Bykiev** [quartznet/quartznet#863]
### Version: x.y.z
Quartz.Net: 3.0.7
IIS: 6.2
.NET Framework: 4.6

### Expected behavior

Job should be executed after AppPool recycle with AppPool "Always Running" and enabled Preload

### Actual behavior

After AppPool recycle Quartz job is fired (I'm using quartz.plugin.triggHistory) but isn't executed before the first request to application. When the first request occured the job is successfully executing. I'm using AdoJobStore.

### Steps to reproduce

Global.asax.cs:

```
Scheduler scheduler = new Scheduler();
Task.Run(() => scheduler.StartJob());

public class Scheduler
    {
        public async Task StartJob()
        {
            var config = (NameValueCollection)ConfigurationManager.GetSection("quartz");

            ISchedulerFactory schedFact = new StdSchedulerFactory(config);

            IScheduler sched = await schedFact.GetScheduler();
            await sched.Start();

            IJobDetail job = JobBuilder.Create<TestJob>()
                    .WithIdentity("job", "group1")
                    .Build();

            ITrigger trigger = TriggerBuilder.Create()
                .WithIdentity("jobTrigger", "group1")
                .WithCronSchedule("0 0 0 1/1 * ? *")
                .Build();

           await sched.ScheduleJob(job, trigger);
        }
    }
```

**Comment by lahma** [comment]
I personally haven't been running Quartz under IIS, but have you checked all these https://www.nickedeye.com/iis-keep-website-alive-always-running/ ? Logging probably also helps that you can ensure the preload/initialization is actually calling your global.asax. You could also try doing scheduler.StartJob().GetAwaiter().GetResult(); instead of firing a new task.

**Comment by Bykiev** [comment]
@lahma, hi and thanks for quick resposne!
I've tried all the steps and still have the issue. I'll try use scheduler.StartJob().GetAwaiter().GetResult(); instead of creating a new task, also I'll try to add more logging and then report back.

**Comment by Bykiev** [comment]
@lahma right now I see a lot of message like these (repeating every 10 seconds):

```
Level	Logger	Message
INFO	Quartz.Impl.AdoJobStore.JobStoreTX	Recovering 0 jobs that were in-progress at the time of the last shut-down.
INFO	Quartz.Impl.AdoJobStore.JobStoreTX	Recovery complete.
INFO	Quartz.Impl.AdoJobStore.JobStoreTX	Removed 0 'complete' triggers.
INFO	Quartz.Impl.AdoJobStore.JobStoreTX	Removed 0 stale fired job entries.
INFO	Quartz.Core.QuartzScheduler	Scheduler ToirScheduler_$_ToirSchedulinginstanceId started.
INFO	Quartz.Impl.AdoJobStore.JobStoreTX	Freed 0 triggers from 'acquired' / 'blocked' state.
WARN	Quartz.Impl.AdoJobStore.JobStoreTX	Detected usage of SqlServerDelegate and UpdateLockRowSemaphore, removing 'quartz.jobStore.lockHandler.type' would allow more efficient SQL Server specific (UPDLOCK,ROWLOCK) row access
INFO	Quartz.Impl.AdoJobStore.JobStoreTX	JobStoreTX initialized.
INFO	Quartz.Core.QuartzScheduler	Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'ToirScheduler' with instanceId 'ToirSchedulinginstanceId'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Impl.AdoJobStore.JobStoreTX' - which supports persistence. and is not clustered.

INFO	Quartz.Impl.StdSchedulerFactory	Quartz scheduler 'ToirScheduler' initialized
INFO	Quartz.Impl.StdSchedulerFactory	Quartz scheduler version: 3.0.7.0
INFO	Quartz.Core.QuartzScheduler	Quartz Scheduler v.3.0.7.0 created.
INFO	Quartz.Core.SchedulerSignalerImpl	Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
INFO	Quartz.Impl.StdSchedulerFactory	Using custom data access locking (synchronization): Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore
INFO	Quartz.Impl.StdSchedulerFactory	Using object serializer: Quartz.Simpl.JsonObjectSerializer, Quartz.Serialization.Json
INFO	Quartz.Util.DBConnectionManager	Registering datasource 'default' with db provider: 'Quartz.Impl.AdoJobStore.Common.DbProvider'
```
Is it ok?

**Comment by lahma** [comment]
So if you are on a loop and Quartz restarts every time I guess it's not OK. Is there some sort of timeout for always-on / preload / initialization that is being hit and app pool is being recycled? Maybe something in the event viewer logs about IIS actions?

If you are using persistent job store I don't see reason why you are scheduling the same job and trigger on start, is there an exception from doing that?

**Comment by Bykiev** [comment]
Forgot to say, that most of the jobs are running from database (we're constantly creating jobs) and only this job is always creating on the app start. I don't see any timeout option in IIS. I didn't encounter this issue when I started it via Task.Run(() => scheduler.StartJob());

**Comment by lahma** [comment]
Task.Run probably would hide the timeout and possible restart, but it can also lead to inconsistent state if something happens inside the task that is not observed. I'm still a bit puzzled that you don't get an error if you are creating the same job and trigger (identity) on every start. Maybe try DEBUG level logging and see if something odd is happening.

Please also note (unrelated):

```
Detected usage of SqlServerDelegate and UpdateLockRowSemaphore, removing 'quartz.jobStore.lockHandler.type' would allow more efficient SQL Server specific (UPDLOCK,ROWLOCK) row access
```

**Comment by lahma** [comment]
Also a bit of restructuring might help:

Global.asax

```
private static readonly Scheduler scheduler = new Scheduler();
```

Application_Start:

```
scheduler.Initialize().GetAwaiter().GetResult();
Task.Run(() => scheduler.Start()); // I still see this problematic, might cause loss of exceptions

```

```
public class Scheduler
{
        private IScheduler sched;

        public async Task Initialize()
        {
            var config = (NameValueCollection)ConfigurationManager.GetSection("quartz");

            ISchedulerFactory schedFact = new StdSchedulerFactory(config);

            sched = await schedFact.GetScheduler();

            IJobDetail job = JobBuilder.Create<TestJob>()
                    .WithIdentity("job", "group1")
                    .Build();

            ITrigger trigger = TriggerBuilder.Create()
                .WithIdentity("jobTrigger", "group1")
                .WithCronSchedule("0 0 0 1/1 * ? *")
                .Build();

           await sched.ScheduleJob(job, trigger);
        }

        public Task Start()
        {
           return sched.Start();
       }
    }
```` 

So trying to pin-point the problem, logging might be the key. I'd advice against the Task.Run.

**Comment by Bykiev** [comment]
Same here with a static variable- quartz restarting in the loop. I'll try to add more logging and see what happens...

**Comment by lahma** [comment]
Might be worthwhile to have logging hooks in Application_Error and AppDomain's unhandled exception, event logs might have clues.

**Comment by lahma** [comment]
We can reopen if there's still an issue.
