### ISSUE TITLE
Request for more information on thread pooling

### ISSUE THREAD

**Issue by SH-SierraSierra** [quartznet/quartznet#873]
Hi @lahma,

Congrats on rolling out the website refresh! However, I was hoping that information on thread pooling had been added to  [Lesson 10 of the 3.x tutorial](https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/configuration-resource-usage-and-scheduler-factory.html#stdschedulerfactory). Right now it remains a TODO item. As a newbie trying to implement Quartz.NET as efficiently as possible, this information would be really helpful. Thanks!

**Comment by lahma** [comment]
Hey thanks for raising the issue, I'll see what I can do.

**Comment by lahma** [comment]
The above tutorial has been updated a bit and there's now new [https://www.quartz-scheduler.net/documentation/quartz-3.x/configuration/reference.html](Configuration Reference).
