### ISSUE TITLE
Project logo and graphics

### ISSUE THREAD

**Issue by lahma** [quartznet/quartznet#875]
## Context

This project is over 10 years old, basically founded in 2006. We've never had a logo due to maintainer's bad UX/UI/graphics skills. But such a logo would mean a lot in packaging and web site.

## References

The original Java project has a logo that is based on a clock http://www.quartz-scheduler.org/ , this logo however is not something that we can be directly use just by being a project rooted in this Java version. The Java version's logo is paid done by backing commercial company.

## Requirements

It should be easily applied to modern UIs. SVG/PNG for embeddable graphics and presentation size should be easy to alter just be changing properties when needed (SVG). Ideally the design could work both on dark and light backgrounds. The logo will be used on both web site and NuGet package. Software icon sizes are common requirement.

## Compensation

Quartz.NET is not a commercial project. 

Unfortunately we cannot offer a lot of money for a logo/look, but we can offer a reference for your work. We can show reference to your brand / web site on the home page make it prominent who did the design. A cautious offer would be something like $100 for a logo - if it fulfills the criteria (basically maintainer's and anyone with eye for graphics). All work offered can/should be watermarked so that it can't be used without compensation. We don't want to be the bad guys.

**Comment by Filini** [comment]
First three ideas, let me know if:

- there is already something you like
- you want some changes or a different style
- you're not interested in my work :-)

![Quartz-NET-0001](https://user-images.githubusercontent.com/10072578/87063271-6ea72580-c20e-11ea-9c6c-36119f0189d1.png)
![Quartz-NET-0002](https://user-images.githubusercontent.com/10072578/87063273-6f3fbc00-c20e-11ea-9c1b-a93e7988acf0.png)
![Quartz-NET-0003](https://user-images.githubusercontent.com/10072578/87063275-6f3fbc00-c20e-11ea-8ce9-5fea80bd74af.png)

**Comment by Sicos1977** [comment]
I vote for the middle one

**Comment by lahma** [comment]
Hey thanks for chiming in with the ideas! The second one is something that pleases my eye also the most. Ideally the logo can be standalone (the Q part) and used NuGet package icons etc. I'm also considering trying a platform, [here's some good feedback from twitterverse](https://twitter.com/RyanLNewington/status/1281167762660835328?s=20). What do you think about utilizing such a platform?

**Comment by Filini** [comment]
Using a service like the one suggested on twitter is always a good idea if you have the budget. The big advantage is that you get a lot of proposals from people that are 100% graphic designers.

I am a developer first, and graphic design (especially logo design) is a secondary aspect of my daily work. But this is a good Illustrator exercise fo me, so I'll try to come up with more ideas.

With that said, if you end up liking one of my proposals, I will create all needed formats and variants (white-bordered, icon-only, full-typeface, eps/svg/png/ico, light/dark backgrounds...).

**Comment by drieseng** [comment]
@Filini Any ideas for [SSH.NET](https://github.com/sshnet/SSH.NET)? :p

**Comment by Filini** [comment]
@drieseng I'll think of something!

**Comment by lahma** [comment]
Hey folks, I tried design crowd and got some designs, some were really out of topic even though I described the idea pretty well (I think). These are left from my initial elimination, thoughts? https://www.designcrowd.com/vote/quartz-net-project-logo . I'm leaning towards the rightmost black/white design with clock face like Q.

It's not set in stone to use any of these.

/cc @ryannewington

**Comment by Sicos1977** [comment]
I agree and then the top one

**Comment by lahma** [comment]
@Filini might I request your comments for the designs? You've done some nice work already and I would never want to undermine that.

I most likely will buy the winning design even if it won't be used (they did put an effort). But I should get the files which would be a base for improvement. I'm far from graphics designer, fortunately I can always ask my wife as she's an UX designer by education, though not a graphics designer either 🙂

**Comment by Filini** [comment]
I really like the black/green logo. I gave it 5 stars.
The other logos don't propose a typeface, which for me is a bit limiting. I like to have an option to show the product full name with a styled text.

On a side note, if you decide to buy a logo but then change it, please ask the author if he has any issues about that.
Some designers hate to have their design altered, even if they have been paid for it.
It's probably better to ask for improvement to the original author, if there is something you would like to be changed.

And don't worry about undermining my work, I did it for fun, and I think that if you have the budget you should give some money to designers who do this as their first income source, especially during these times.

**Comment by lahma** [comment]
The Quartz.NET web site has launched with the new logo design, thank you all for your input!

https://www.quartz-scheduler.net/
