### ISSUE TITLE
DI questions relating to the beta

### ISSUE THREAD

**Issue by chadjefferies** [quartznet/quartznet#877]
Congrats on the latest release!

Been playing around with some of the newer DI improvements and after looking at the example [Quartz.Examples.AspNetCore](https://github.com/quartznet/quartznet/blob/master/src/Quartz.Examples.AspNetCore/Startup.cs) I had a few questions.

- Is there a DI friendly way to add Job Listeners? Or is the recommendation still to add them straight to the Scheduler via the `ListenerManager.AddJobListener...`? 

- For configuration options on the scheduler, it would be nice to see an Options pattern adopted, so I could just add a Quartz section to my appsettings file and configure it there.

```
  "Quartz": {
    "quartz.scheduler.idleWaitTime": "1000",
    "quartz.threadPool.threadCount": "2",
    "quartz.jobStore.misfireThreshold": "1000"
  },
```

To work around this, I've adopted code such as...

 
```
var section = config.GetSection("Quartz");
var options = new NameValueCollection();

foreach (var kvp in section.GetChildren())
     options.Set(kvp.Key, kvp.Value);

services.AddQuartz(options, qtz =>....
```

It's possible the [quartz_jobs.config](https://github.com/quartznet/quartznet/blob/master/src/Quartz.Examples.AspNetCore/quartz_jobs.config) solves some of this, I am just not very familiar with that way.

Thanks for your time!

**Comment by lahma** [comment]
First of all, thank you for taking the beta for a spin and providing this valuable feedback! 

> * Is there a DI friendly way to add Job Listeners? Or is the recommendation still to add them straight to the Scheduler via the `ListenerManager.AddJobListener...`?

I had overlooked this. I need to play around with API a bit and see how to fit it to the pattern. The basic addition should probably be there and removal and querying then from the `IListenerManager`.

> * For configuration options on the scheduler, it would be nice to see an Options pattern adopted, so I could just add a Quartz section to my appsettings file and configure it there.
> 
> ```
>   "Quartz": {
>     "quartz.scheduler.idleWaitTime": "1000",
>     "quartz.threadPool.threadCount": "2",
>     "quartz.jobStore.misfireThreshold": "1000"
>   },
> ```

There are myriad of ways to get the properties in for the scheduler, but this use case makes sense when people want to centralize scheduler configuration (excluding triggers and jobs). quartz_jobs.config is for creating the actual schedules and benefits from polling and refresh, the above properties are more set in stone after scheduler is initialized.

I'll try to address these in the near future and will be part of beta2.

Thank you!

**Comment by lahma** [comment]
@chadjefferies I've created a PR https://github.com/quartznet/quartznet/pull/878  and it contains the new API for listener registration:

https://github.com/quartznet/quartznet/pull/878/files#diff-282723427e9068543e72018b5a0cedbcR114

Now also Quartz section is processed as part of initialization and it sets the defaults which code can override.

Please have a look that I've covered your needs before I merge.

**Comment by chadjefferies** [comment]
Wow, thanks for the quick feedback and turnaround! I reviewed the PR and it looks exactly like what I need.

**Comment by lahma** [comment]
This is out as part of the [3.1 beta 2](https://www.quartz-scheduler.net/2020/07/14/quartznet-3-1-beta-2-released/). Please try out the features and keep the feedback coming!
