### ISSUE TITLE
Why the new dependency to SQL-Server Package in V3.1

### ISSUE THREAD

**Issue by DaveLaa** [quartznet/quartznet#903]
### Version: 3.1.0

I don`t have any dependency to SQL-Server in my whole project and don't want to have in future. I don't need DB-Based Quarz-Features.
Now I upgraded the Quartz NuGet package and it installed 50 new dependencies to libraries i will never use... I immediately reverted the update.
Isn't there a way to split the Quartz Lib into a non-DB part, without SQL-Server dependency and the DB dependent part as a sepparate library? Otherwise it will not be possible for me to upgrade Quartz in future...

**Comment by bilbey** [comment]
We also have the same issue after updating 3.1.0. In our project we do not have any dependency on Microsoft.Data.SqlClient and its  additional dependencies. It would be nice to have separate additional packages for DB related implementations.

**Comment by lahma** [comment]
I think it will be doable to change the bits checking against SqlException to use reflection instead. This will transfer dependency handling requirement to library consumer as then there's no out-of the box support for SQL Server anymore as the package isn't pulled automatically.

**Comment by DaveLaa** [comment]
It could work with the System.Data abstraction of the SqlException... System.Data.DataException. I don't know the SqlException good enough though and it might be neccessary to use reflection here, as you mentioned.
I tried to compile the code and the only other thing I found was the SqlParameter which could be handled by a cmd.CreateParameter() statement.

**Comment by mstauber** [comment]
The hard dependency is in the IsTransient method on JobStoreSupport. The IsTransient method as it is now, even changed to use reflection, would not support other clients besides SQL Server.

Detecting transient errors using the MySqlConnector is completely different: 
https://github.com/mysql-net/MySqlConnector/issues/849

[System.Data.Common.DbException](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbexception?view=netcore-3.1) is a better choice., It's getting a new IsTransient property in .NET 5 that will be implemented by the individual ado client libraries, see: https://github.com/dotnet/runtime/issues/34817

**Comment by lahma** [comment]
Unfortunately we cannot rely on having that (method and all). SqlDelegate base protected virtual implementation should probably try to find the property with reflection, otherwise return false. We need to remember that this is currently only for selecting log level on error IIRC.

**Comment by mstauber** [comment]
Checked myself, and yeah, you're right, it's just used as a switch to determine log level. And it seems it's only really needed for azure. 

Original Issue: https://github.com/quartznet/quartznet/issues/470

How about something like this in StdAdoDelegate 

`csharp
protected virtual bool IsExceptionTransient(Exception exception) {
return false;
}
`

and in SqlServerDelegate 

`csharp
protected override bool IsExceptionTransient(Exception exception) {
//logic from IsTransient on JobStoreSupport using reflection
}
`

**Comment by lahma** [comment]
I think we need to start with re-implementing the `JobStoreSupport.IsTransient`, the delegate comes via interface and we cannot add new members before 4.0.
