### ISSUE TITLE
Should services.AddQuartz() register a default ITypeLoadHelper service?

### ISSUE THREAD

**Issue by kevinchalet** [quartznet/quartznet#924]
Currently, if you don't explicitly call `UseSimpleTypeLoader()` when using `services.AddQuartz()`, you get an exception from DI:

```
System.InvalidOperationException : 'No service for type 'Quartz.Spi.ITypeLoadHelper' has been registered.'
```

Assuming the default `SimpleTypeLoadHelper` implementation is appropriate for most use cases, maybe it should be directly registered by `services.AddQuartz()`?

/cc @lahma

**Comment by lahma** [comment]
Yes, that should definitely be the default, few people have created their own AFAIK.
