### ISSUE TITLE
LoggingJobHistoryPlugin.Name and LoggingTriggerHistoryPlugin.Name is null

### ISSUE THREAD

**Issue by sergeyshaykhullin** [quartznet/quartznet#926]
**Describe the bug**
LoggingJobHistoryPlugin.Name and LoggingTriggerHistoryPlugin.Name is null

**Version used**
3.1.0

**To Reproduce**

```
options.AddJobListener<LoggingJobHistoryPlugin>(EverythingMatcher<JobKey>.AllJobs());
options.AddTriggerListener<LoggingTriggerHistoryPlugin>(EverythingMatcher<JobKey>.AllTriggers());
```

**Expected behavior**

LoggingJobHistoryPlugin and LoggingTriggerHistoryPlugin names is set and they is working by default

**Additional context**
Also LoggingJobHistoryPlugin .Name is not virtual and needs interface hacks

**Comment by lahma** [comment]
Thanks for reporting, let's try to get fix in for 3.2.
