### ISSUE TITLE
Migrate SIMPROP_TRIGGERS to simprop_triggers in PostgreSQL schema

### ISSUE THREAD

**Issue by sergeyshaykhullin** [quartznet/quartznet#927]
**Is your feature request related to a problem? Please describe.**
Migrate SIMPROP_TRIGGERS to simprop_triggers in PostgreSQL schema

**Describe the solution you'd like**
Rename table, add migration

**Additional context**
Unify PostgreSQL table naming style

**Comment by lahma** [comment]
Unfortunately I think this is not feasible/worth the effort. Quartz.NET follows the Java version's naming convention and as Postgres is case sensitive, this would be a breaking change with little benefit. All the tables are all uppercase I believe?

**Comment by sergeyshaykhullin** [comment]
No, all tables are in snake_case, but SIMPROP_TRIGGERS
