### ISSUE TITLE
NON_CLUSTERED names in clustered mode

### ISSUE THREAD

**Issue by sergeyshaykhullin** [quartznet/quartznet#929]
**Describe the bug**

- `scheduler_state.instance_name` and `fired_triggers.entry_id` named NON_CLUSTERED..., but UseClustering is set
- Scheduler fires correctly, one time per interval

**Version used**
3.1.0

**To Reproduce**

I'am using this setup:
```cs
services.AddQuartz(options =>
{
        options.SchedulerName = environment.ApplicationName;

	options.UseMicrosoftDependencyInjectionScopedJobFactory(factoryOptions =>
	{
		factoryOptions.AllowDefaultConstructor = false;
	});

	options.UseSimpleTypeLoader();
	options.UseDedicatedThreadPool(poolOptions =>
	{
		poolOptions.MaxConcurrency = 10;
	});
   
        // TODO: https://github.com/quartznet/quartznet/issues/926
	// options.AddJobListener<LoggingJobHistoryPlugin>(EverythingMatcher<JobKey>.AllJobs());
	// options.AddTriggerListener<LoggingTriggerHistoryPlugin>(EverythingMatcher<JobKey>.AllTriggers());

	options.UsePersistentStore(storeOptions =>
	{
		storeOptions.UseProperties = true;
		storeOptions.RetryInterval = TimeSpan.FromSeconds(15);

		storeOptions.UseJsonSerializer();

		storeOptions.UseClustering(clusterOptions =>
		{
			clusterOptions.CheckinMisfireThreshold = TimeSpan.FromSeconds(20);
			clusterOptions.CheckinInterval = TimeSpan.FromSeconds(10);
		});

		storeOptions.UsePostgres(providerOptions =>
		{
			providerOptions.UseDriverDelegate<PostgreSQLDelegate>();
			providerOptions.ConnectionString = connectionString;
			providerOptions.TablePrefix = string.Empty;
		});
	});

        options.AddJob<TestJob>(job =>
		job.StoreDurably()
			.WithIdentity("TestJob")
			.WithDescription("Test"));

	options.AddTrigger(trigger =>
		trigger.WithIdentity("TestJobTrigger")
			.WithDescription("Test trigger")
			.ForJob("TestJob")
			.StartNow()
			.WithSimpleSchedule(x => x.WithInterval(TimeSpan.FromMinutes(5)).RepeatForever()));
});
```

**Expected behavior**

Autogenerated names are respect clustering mode

**Additional context**

Am i doing all right? I have 1 pg cluster with 3 worker quartz server k8s pods.
TestJob fires each 5 minutes, so if 3 workers are set and clustering mode disabled/broken TestJob would fire 3 times each 5 minutes?

**Comment by sergeyshaykhullin** [comment]
I guess that clustering mode is working correct, because job is executing on different quartz servers, so it is just naming problem
![image](https://user-images.githubusercontent.com/46970457/89910628-24dca100-dbf9-11ea-82a2-b98d08996418.png)

**Comment by danvln** [comment]
@sergeyshaykhullin - How do you see this image? Do you use any plugin to see the jobs?

**Comment by sergeyshaykhullin** [comment]
@danvln This is k8s+Grafana+Loki+Promtail. I just logging to stdout and track which pod is executing job
