### ISSUE TITLE
Runtime error occured in main trigger firing loop, when using unit tests.

### ISSUE THREAD

**Issue by guppysb** [quartznet/quartznet#932]
**Describe the bug*
I have upgraded our company's product from Quartz 2.4.1, to 3.1.0. Everything works well with scheduling and firing of IJob.Execute() in the production code.

This is not the case when using the product with unit tests. An error of "Runtime error occurred in main trigger firing loop." is thrown after "Batch acquisition of 1 triggers".

**Version used**

3.1.0

**To Reproduce**

It's a bit difficult to post reproduction code or unit tests because of complex workflow. The unit tests were written for Quartz 2.4.1.0, and have worked well since then, until 3.1.0. I have followed the migration guide [here](https://www.quartz-scheduler.net/documentation/quartz-3.x/migration-guide.html#packaging-changes), and in terms of the regular production code, the jobs are scheduled and IJob.Execute() gets called properly. 

Workflow for production code and unit tests:
1. Setup the scheduler:
```
var props = new NameValueCollection()
            {
                { "quartz.scheduler.instanceName" , name }
            };

var scheduleFactory = new StdSchedulerFactory(props);
_scheduler = scheduleFactory.GetScheduler().GetAwaiter().GetResult();
_scheduler.JobFactory = new ScheduledJobFactory(this);

await _scheduler.Start();
```

2. Build job:
```
IJobDetail job = JobBuilder.Create<IJobScheduledJob>()
                                            .WithIdentity(jobIdString)
                                            .StoreDurably()
                                            .Build();

job.JobDataMap["JobId"] = jobIdString;
```
3. Setup trigger:
```
TriggerBuilder triggerBuilder = TriggerBuilder.Create().WithIdentity(jobIdString);
triggerBuilder = triggerBuilder.StartNow();
ITrigger trigger = triggerBuilder.Build();
```

4. Schedule job:
`await _scheduler.ScheduleJob(job, trigger);`

5. Wait for execution of IJob.Execute():
`public Task Execute(IJobExecutionContext context)
{
  //do something.
}`

However, when using unit tests, the scheduler schedules the job and a successful result is given in step 4 along with the debug logging showing "Batch acquisition of 1 triggers." Immediately right after, an error is thrown "Runtime error occurred in main trigger firing loop.", which can be traced back to QuartzSchedulerThread.cs, line 464. Because of the error, step 5 is never executed.

**Expected behavior**

Step 5 is executed in the above code. 

**Additional context**
N/A

**Comment by lahma** [comment]
The actual runtime error would be critical to know, there should be stack trace and proper error message + exception type.

**Comment by guppysb** [comment]
Hi Lahma. Thank you for your reply. 

This was a very finicky bug to fix, my team mate helped me fix it. It was an issue with assembly version mismatch of System.Diagnostics.DiagnosticSource, between the scheduler project and the unit test project. One was expecting 4.0.4.0, and the other was expecting 4.0.5.0.

The only way I was able to see this was to use Fuslogvw.exe (Assembly Binding Log Viewer), from Visual Studio Command prompt. Look at the loaded dlls and see if there is any runtime exception on assembly loading. 
https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer

Hopefully this helps out someone else in the future. Thanks again for taking a look at the issue.

**Comment by lahma** [comment]
Great that you got that sorted out, probably would be beneficial for Quartz to throw earlier, in this case do some diagnostics source usage before things start up.
