### ISSUE TITLE
NuGet package Quartz.Extensions.Hosting 3.1.0 missing

### ISSUE THREAD

**Issue by Ergamon** [quartznet/quartznet#935]
Seems while updating everything to 3.1.0 you forgot to upload a build of this package.

I tried to build a console application on .NET Framework 4.8 with the generic hosting system.

So I added NuGet packages Quartz 3.1.0 and Quartz.Extensions.DependencyInjection 3.1.0 while following your sample code.

When I tried to add hosting everything went wrong. (There is a package Quartz.Extensions.Hosting 1.0.0, but this is from someone else)

I currently helped myself by copying the 3 classes in this project to my own source code.

**Comment by lahma** [comment]
I think you forgot to read the documentation 😉 https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/hosted-services-integration.html this will be a 3.2 feature and until then you need to use the Quartz.AspNetCore package.

We are trying to get ownership of the package to do the publish but so far with little luck. So you need to wait for 3.2 release to that package (or something similarly named) installed.

**Comment by ipsumcodem** [comment]
Lol looks like you don't read your documentation either... no instructions reference Quartz.AspNetCore: https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/hosted-services-integration.html

Why devs trash their own work with bad documentation is beyond my understanding. 

Thanks for taking the trouble to answer the issue though, it just won't get back the two hours I wasted from trusting your faulty docs.

> 
> 
> I think you forgot to read the documentation 😉 https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/hosted-services-integration.html this will be a 3.2 feature and until then you need to use the Quartz.AspNetCore package.
> 
> We are trying to get ownership of the package to do the publish but so far with little luck. So you need to wait for 3.2 release to that package (or something similarly named) installed.

**Comment by lahma** [comment]
Do you want a refund?

**Comment by lahma** [comment]
The package is now on NuGet.
