### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by ColdFire169** [quartznet/quartznet#958]
The documentation on CronTrigger Tutorial - Examples has a typo. In the example showing 'Fire at 10:15am every day during the year 2005', the 2005 got typed into the Meaning column instead of being on the end of the expression in the Expression column.
https://www.quartz-scheduler.net/documentation/quartz-3.x/tutorial/crontrigger.html#examples

**Comment by lahma** [comment]
Good catch! There's *Help us by improving this page!* link at the bottom of every page if you'd like to provide a PR to fix the issue 🙂

**Comment by ColdFire169** [comment]
I have submitted the Pull Request.

**Comment by lahma** [comment]
Awesome, thank you for taking the initiative and fixing the issue 👍
