### ISSUE TITLE
Add simple mechanism to exchange underlying job storage

### ISSUE THREAD

**Issue by danielmarbach** [quartznet/quartznet#97]
Currently it is pretty complicated to introduce your own persistence mechanism. For example if I want to use RavenDB to store the triggers and jobs I must re-implement almost the whole StdSchedulerFactory. Provide either guidance how to implement persistence on top of the current architecture or simplify the architecture.

**Comment by robertstefan** [comment]
Any additional information regarding this information? :( 👍

**Comment by lahma** [comment]
See [RavenDB](https://github.com/ravendb/quartznet-RavenDB/blob/master/src/Quartz.Impl.RavenDB/RavenJobStore.cs) and [MongoDB](https://github.com/chrisdrobison/mongodb-quartz-net/blob/master/Quartz.Spi.MongoDbJobStore/MongoDbJobStore.cs) as examples, it's enough to build custom IJobStore implementation. I'm closing now, can be reopened if someone wants to chime in with a PR proposal.
