### ISSUE TITLE
Consider making the new internal QuartzOptions properties public

### ISSUE THREAD

**Issue by kevinchalet** [quartznet/quartznet#981]
Hey @lahma,

Would it be possible to make the 3 properties that are currently internal public? It would help a lot with unit tests (to ensure job and trigger details are correctly registered by an `IConfigureOptions<QuartzOptions>` class).

Thanks!

**Comment by lahma** [comment]
There's now public readonly getters for Triggers and Jobs, I've removed the Calendar for now as it wasn't even used.

**Comment by kevinchalet** [comment]
Thanks!

**Comment by kevinchalet** [comment]
Wooops, I suspect you forgot to make the properties "public": https://github.com/quartznet/quartznet/commit/94a4f33968a259f7f2d9f37e62f79ebad58455da#diff-baab1cc10703ed0030c47a179783803aR36 😅

**Comment by lahma** [comment]
Oh dear...

**Comment by lahma** [comment]
Now is should be in master, this time for real... 🤦

**Comment by lahma** [comment]
Hey @kevinchalet I just published 3.2.1 to NuGet and this time I hope I got the visibility modifier correct 😉

**Comment by kevinchalet** [comment]
@lahma awesome, thanks! I can confirm they are now really "public" 😄 
https://github.com/openiddict/openiddict-core/pull/1137
