### ISSUE TITLE
Should ServiceCollectionQuartzConfigurator.UseJobFactory/UseTypeLoader use Replace() instead of TryAddSingleton()?

### ISSUE THREAD

**Issue by kevinchalet** [quartznet/quartznet#982]
I'd expect these methods to replace any existing job factory/type loader, but since it uses `TryAdd`, the new type will be ignored if one is already registered. Would using `services.Replace()` make more sense here?

**Comment by lahma** [comment]
I've changed this the way you suggested, makes sense!

**Comment by kevinchalet** [comment]
Thanks! 👏
