### ISSUE TITLE
Created CronTrigger will be deleted when TriggerName has an underscore

### ISSUE THREAD

**Issue by Maxallica** [quartznet/quartznet#986]
**Describe the bug**
We created a CronTrigger via the TriggerBuilder.
We used our "**CLASSNAME**" + "_" + "TRIGGER" and a simple groupName for the CronTrigger.
After the scheduler was started a second time via IIS. This created CronTrigger was deleted automatically via quartznet.

**Version used**
Recognized in version Quartz.NET 3.0.7 and 3.2.0

**To Reproduce**
```
var groupName = "INTEGRATION";
var trigger = TriggerBuilder.Create()
.WithIdentity(typeof(**CLASSNAME**).Name + "_" + "TRIGGER", groupName)
// Every hour
.WithCronSchedule("0 0 0/1 * * ? *")
.ForJob(job)
.StartNow()
.Build();

await Scheduler.ScheduleJob(trigger);
```

**Expected behavior**
The CronTrigger will not be deleted after restarting the IIS, when a TriggerName has an underscore.

**Additional context**
I checked the quartznet source code and maybe it will caused in the method called "TriggeredJobComplete" at the class "JobStoreSupport.cs".
Also it could be that somewhere in code is a condition with LastIndexOf, IndexOf or CotainsKey('_').

**Frameworks**
ASP.NET (MVC) with .NET Framework 4.6.1
Quartz.NET (quartznet)
Quartzmin with HistoryStorePlugin

**Log**
```
DEBUG  2020-10-07 12:07:35,674  []  Quartz.Core.JobRunShell+<Run>d__10.MoveNext()  Trigger instruction : DeleteTrigger  ǁ
DEBUG  2020-10-07 12:07:35,674  []  Quartz.Impl.AdoJobStore.SimpleSemaphore.ObtainLock()  Lock 'TRIGGER_ACCESS' is desired by: 61add850-4538-4d02-ae40-9af751eb4a2f  ǁ
DEBUG  2020-10-07 12:07:35,677  []  Quartz.Impl.AdoJobStore.SimpleSemaphore.ObtainLock()  Lock 'TRIGGER_ACCESS' is being obtained: 61add850-4538-4d02-ae40-9af751eb4a2f  ǁ
DEBUG  2020-10-07 12:07:35,678  []  Quartz.Impl.AdoJobStore.SimpleSemaphore.ObtainLock()  Lock 'TRIGGER_ACCESS' given to: 61add850-4538-4d02-ae40-9af751eb4a2f  ǁ
DEBUG  2020-10-07 12:07:35,677  []  ?.?()  Batch acquisition of 0 triggers  ǁ
DEBUG  2020-10-07 12:07:35,679  []  ?.?()  Prepared SQL: SELECT TRIGGER_STATE, NEXT_FIRE_TIME, JOB_NAME, JOB_GROUP FROM QRTZ_TRIGGERS WHERE SCHED_NAME = @schedulerName AND TRIGGER_NAME = @triggerName AND TRIGGER_GROUP = @triggerGroup  ǁ
DEBUG  2020-10-07 12:07:35,683  []  ?.?()  Prepared SQL: DELETE FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = @schedulerName AND TRIGGER_NAME = @triggerName AND TRIGGER_GROUP = @triggerGroup  ǁ
DEBUG  2020-10-07 12:07:35,710  []  ?.?()  Prepared SQL: DELETE FROM QRTZ_TRIGGERS WHERE SCHED_NAME = @schedulerName AND TRIGGER_NAME = @triggerName AND TRIGGER_GROUP = @triggerGroup  ǁ
DEBUG  2020-10-07 12:07:35,717  []  ?.?()  Prepared SQL: DELETE FROM QRTZ_FIRED_TRIGGERS WHERE SCHED_NAME = @schedulerName AND ENTRY_ID = @triggerEntryId  ǁ
DEBUG  2020-10-07 12:07:35,721  []  Quartz.Impl.AdoJobStore.SimpleSemaphore.ReleaseLock()  Lock 'TRIGGER_ACCESS' returned by: 61add850-4538-4d02-ae40-9af751eb4a2f  ǁ
```

**Comment by lahma** [comment]
I'll close this for now as there's no additional information that would show that Quartz is deleting the trigger. We can reopen if there's some concrete things to work on.

**Comment by Maxallica** [comment]
Hi lahma. Sorry for the late response (we are very busy currently) and sorry for reopening the ticket.
Maybe you can see the problem more in depth with this two videos I've created for you.
Both recorded with the newest Quartz.NET version 3.2.3.

[JobName_With_Underscore.zip](https://github.com/quartznet/quartznet/files/5476407/JobName_With_Underscore.zip)
[JobName_With_Hyphen.zip](https://github.com/quartznet/quartznet/files/5476429/JobName_With_Hyphen.zip)
